### ISSUE TITLE
I'd like to contribute the Chinese localization language pack. But how?

### ISSUE THREAD

**Issue by fishfree** [SafeExamBrowser/seb-win-refactoring#1]
I also recommend the [Crowdin ](https://crowdin.com) localizaiton service.

**Comment by dbuechel** [comment]
Thanks for your interest in SEB, it would be very welcome if you could contribute the Chinese translation! Unfortunately, the localization mechanism is currently still a scaffolding which defaults to English in all cases. As it is implemented at the moment, all text visible to the user is contained in an XML file: https://github.com/SafeExamBrowser/seb-win-refactoring/blob/master/SafeExamBrowser.I18n/Text.xml.

As the localization mechanism may be subject to change in the ongoing development (the same applies to the text content itself), I'd suggest to notify you once the mechanism is final and ready to be translated into other languages. This can however take until the end of Q2 2020 or later, I'm afraid.

**Comment by fishfree** [comment]
@dbuechel Thank you! Or, can I translate it for v2.3 for Windows on my own computer first?

**Comment by dbuechel** [comment]
That is certainly possible, but I would advise against it. SEB 2.x will be discontinued this year, so you'd be doing the same work twice, first for 2.x and then 3.x. SEB 2.x and 3.x are not exactly the same, so there is text which is unique to both versions respectively...

**Comment by fishfree** [comment]
@dbuechel Thank you for your advice. But it's emergent for me to do the translation for v2.x first. :-) So, would you please tell me the detailed method first?

**Comment by dbuechel** [comment]
As you wish. In SEB 2.x, the localization is done via resource files, see https://docs.microsoft.com/en-us/dotnet/framework/resources/.

**Comment by fishfree** [comment]
@dbuechel Thank you. But I'm not familiar with .NET resource file. Is it possible to add a new localization like poedit into a installed SEB 2.x?

**Comment by dbuechel** [comment]
Unfortunately not. You need to install Visual Studio, edit the source code and compile your changes.

**Comment by dbuechel** [comment]
Actually, it is: https://visualstudio.microsoft.com/free-developer-offers/

**Comment by dbuechel** [comment]
The localization mechanism is now implemented. If you are still interested in providing a Chinese translation, feel free to do so by translating the English text found here:

https://github.com/SafeExamBrowser/seb-win-refactoring/tree/master/SafeExamBrowser.I18n/Data

**Comment by dbuechel** [comment]
I'll close this issue for now, feel free to re-open it or create a new one if you have any further questions.
