### ISSUE TITLE
Unable to access my exams, would say "Modify Setup"

### ISSUE THREAD

**Issue by 22000886-Jana** [SafeExamBrowser/seb-win-refactoring#1004]
**Describe the Bug**
I am able to install the software but when I try to click on the exam file it will say "Modify Setup"
I have tried everything, there is more than 4.5 GB storage on my laptop and I have installed .NetFramework. Still unable to access my exam, i have contacted my school's helpdesk but they cant help me and asked me to contact your team.

**Steps to Reproduce**
1. I went to download the SEB software that was provided by my school
2. It says "Installation Successful"
3. I go and click on the file provided by my school to start my exam
4. I saw the "Modify Setup" prompt, and asked me to uninstall the software.

**Expected Behavior**
The prompt Modify Setup appears when I try to access my exam, and asked me to uninstall the software.

**Screenshots**
<img width="392" alt="installation successful" src="https://github.com/user-attachments/assets/31634fbb-4630-403e-92cc-762c8b577f1b">
^ says installation is successful 

<img width="482" alt="fileclicked" src="https://github.com/user-attachments/assets/833ab96a-7fb8-4b49-898a-f0cf8cb3745a">
^ clicked on this file that was provided by my school to start the exam

<img width="394" alt="modify setup" src="https://github.com/user-attachments/assets/19ca86d3-fcee-4720-a51d-40eb2728ba3f">
^ modify setup

**Version Information**
 - OS:  Windows 10 Education 
 - SEB-Version: 3.4.1.505

**Additional Context**
I have even downloaded the newest version of SEB and it doesn't work. My computer has more than enough storage and I made sure my computer has .NetFramework

**Comment by dbuechel** [comment]
Please update to the latest release version (currently 3.8.0) and try again.

**Comment by 22000886-Jana** [comment]
Hi,
   I've downloaded the latest version but it still says "Modify Setup". The image attached is for your reference. Please advise thank you.

***@***.***

**Comment by dbuechel** [comment]
1. Uninstall Safe Exam Browser via the system control panel.
2. Restart your machine.
3. Install the latest release version by using the setup bundle (.exe).

**Comment by wxnnvs** [comment]
Delete the installer exe file
This might resolve the issue as it opens that as default

**Comment by 22000886-Jana** [comment]
Hi,
   Could you please give me instructions on where to find it? Please advice thanks

**Comment by wxnnvs** [comment]
Check your downloads folder
When you installed safe exam browser u probably used seb_installer_380.exe or something similar

**Comment by wxnnvs** [comment]
Either do what @dbuechel said or go into `c:/program files/Safe Exam Browser/` and look for a file called uninst000.exe rename it
Idk wether this works

**Comment by wxnnvs** [comment]
Im not a smart guy though, so it might just mess it up more

**Comment by dbuechel** [comment]
@22000886-Jana Please try the steps specified above (reinstallation). Should that not fix the issue, please verify in the system settings that the .seb file extension and seb(s)::// URL protocols are linked correctly to the main executable of SEB (SafeExamBrowser.exe).

**Comment by ilomon10** [comment]
Just open the `exam_file.seb` in `SEB Configuration.exe` with `Open Configuration`, then safe to local client configuration, and then open the exam at Start menu `Safe Exam Browser`
