### ISSUE TITLE
Shut down no longer available

### ISSUE THREAD

**Issue by dkummer63** [SafeExamBrowser/seb-win-refactoring#1007]
I had a strange case this week when I installed SEB version 3.8 with 15 female students. After the installation, two students no longer had the option to shut down the computer. Has this happened more often, as I have had several people in recent years who have linked this to the installation of SEB, but I have always denied it. Is this a known problem? 
Thanks for any help. 
![Zwischenablage-1](https://github.com/user-attachments/assets/e3a8e76a-7843-427f-9307-f1e1fd147d38)

**Comment by strau0106** [comment]
When I observe this, it is normally linked to improper shutdown of SEB with the SEB Service enabled. 

It is easily fixed with the SEB Reset Tool.

**Comment by dkummer63** [comment]
Thank you very much, I will test it.

**Comment by dkummer63** [comment]
Unfortunately, it did not help. Do you have another idea?

**Comment by strau0106** [comment]
Then you most likely haven't performed it correctly?

Which option did you choose in the SEB Reset Tool menu?

**Comment by dkummer63** [comment]
The second one: Reset system configuration to default values and the I added the specific user, then restart of the computer. What am I missing.

**Comment by dbuechel** [comment]
@dkummer63 You should first try to restore the configuration using the backup mechanism, and only if that fails reset the values to their default. If this still does not work (make sure to reboot the system if possible, or try hard resetting the machine after saving any open documents or alike), please post the log file of the reset utility.

**Comment by dkummer63** [comment]
Today I have two other students with the same problem. I am worried a bit... : )

**Comment by danschlet** [comment]
That's why we don't recommend to use the SEB Windows Service anymore.

**Comment by dkummer63** [comment]
I do not understand what you mean by that. Not using the SEB Version 3.8 with Windows?

**Comment by dbuechel** [comment]
> Not using the SEB Version 3.8 with Windows?

Not enabling the SEB Service component, see tab [Security](https://safeexambrowser.org/windows/win_usermanual_en.html#SecurityPane) > Ignore SEB Service.

Also, you're using a completely outdated version of SEB for Windows:

```
/* Safe Exam Browser, Version 3.3.1 (x64), Build 3.3.1.388
/* Copyright © 2021 ETH Zürich, Educational Development and Technology (LET)
```

Please update as soon as possible (we strongly recommend to always use the latest release version) and then retry restoring the configuration using the reset utility.

**Comment by strau0106** [comment]
Be aware that disabling the service brings severe security implications with it.

This issue with the shutdown is not something I have ever observed. (that it is not restored after SEB Reset Tool) 

But yes update the SEB Version! Maybe that will resolve this problem (and many other security related things actually...)

**Comment by dkummer63** [comment]
I found a different way to repair it. The recovery-function of windows helped, so that the energy-options are available again. Thank you for your help and I will update the version.
