### ISSUE TITLE
Safe Exam Browser fail to start

### ISSUE THREAD

**Issue by R2D2byBest** [SafeExamBrowser/seb-win-refactoring#1009]
**Describe the Bug**
Safe Exam Browser fail to start.

**Expected Behavior**
After a new installation SEB displays an error. Since SEB does not start, there is no log file.
![Capture d’écran (1228)](https://github.com/user-attachments/assets/af600ce3-6330-4d49-8ee9-8b1eae8d29ff)

**Screenshots**
See screen shot for error

**Version Information**
 - OS: Windows 10 Professional, Version 22H2 
 - SEB-Version SEB 3.8.0 / 3.7.1 / 3.6.0

**Comment by dbuechel** [comment]
Please refer to the already existing issues, e.g. #657 or #746 or #617.
