### ISSUE TITLE
endless password query

### ISSUE THREAD

**Issue by kathrinva** [SafeExamBrowser/seb-win-refactoring#1013]
> - Unfortunately it prouces no Error or log files, so I can't attach it.

**Describe the Bug**
For starting a test with SEB, the password query fails: after filling in the password and pressing enter, the same password query appears. I have this problem with only one student. In week 43 it worked normal, since week 44 it is an endless password query. It appears on different laptops with this student's user interface. No error and no log files appear. On recommendation from bookwidgets support, I also tested it with password "g" that should be the same on any keyboards. Event then it's the same outcome.

**Steps to Reproduce**
1. Go to "Teams Aufgaben"
2. Click on test-Link (from Bookwidgets.com)
3. Enter SEB password and press enter
4. See the infinite password query on and on and on

**Expected Behavior**
Opening the test

**Version Information**
 - After first fail we installed the newest version of the SEB from this fall with the same outcome

**Comment by dbuechel** [comment]
That appears to be an issue with your LMS / web application (i.e. Bookwidgets as you mentioned above). Please contact their support and report the issue with them.
