### ISSUE TITLE
Electron Application Temporarily Disappears and Shows SEB Loader During Exam Session

### ISSUE THREAD

**Issue by ron-tomax** [SafeExamBrowser/seb-win-refactoring#1014]
**Bug Description:**
During an exam session, when running a permitted Electron application within Safe Exam Browser, the application sporadically disappears from view. The SEB loader briefly appears (approximately 1 second) before the Electron application reappears and regains focus. This interrupts the exam flow and causes confusion for users.

**Steps to reproduce the behavior:**
1. Configure SEB with an Electron application as a permitted application
2. Start an exam session with SEB
3. Launch the permitted Electron application
4. Use the application normally for a period of time
5. Observe that the application occasionally disappears
6. Notice the SEB loader appears briefly
7. Wait for application to reappear (approximately 1 second later)

**Expected Behavior:**
The permitted Electron application should remain stable and visible throughout the entire exam session without disappearing or showing the SEB loader.

**Screenshots**
1. Student is performing an exam:
![image](https://github.com/user-attachments/assets/1645e37c-f20a-4c66-8a14-b3435ce5d3ad)
2. The application disappears for 0.5 second:
![image](https://github.com/user-attachments/assets/be608e7f-2e7e-4581-b73d-83459d4a4db6)
3. The application comes back to the front:
![image](https://github.com/user-attachments/assets/6dd90d26-0cc5-4cf2-807d-1e82448c4d38)

**Version Information**
* OS: Windows 10 and Windows 11 (multiple users affected)
* SEB-Version: 3.7

**Additional Context:**
The issue is intermittent and only affects some students, not all users

**Comment by micimh** [comment]
Try deinstalling the programm **OMEN Gaming Hub** which is usually pre-installed on HP-devices.

**Comment by dbuechel** [comment]
Thanks for the detailed report. As suggested by @micimh, this is most likely a third-party application interfering with the kiosk mode of SEB (log messages to that respect should be found in the runtime log of the affected session).

Other applications causing this problem which have been reported to us were ESET AntiVirus as well as Cisco WebEx, you'll find the related issues here on GitHub (e.g. #524).
