### ISSUE TITLE
Version Restrictions are not working

### ISSUE THREAD

**Issue by tr1as3c** [SafeExamBrowser/seb-win-refactoring#1022]
When specifying a new version of Safe Exam Browser as:
Win.3.8.min
and trying the same .seb file with older version like v2.4.1, it opens and runs normally.

**Comment by dbuechel** [comment]
We strongly discourage the usage of the legacy versions (2.x). And the version restriction functionality only works for versions 3.6 upwards, as the previous versions do not have that feature integrated.
