### ISSUE TITLE
How to use the Jitsi meet proctoring feature in the latest version?

### ISSUE THREAD

**Issue by fishfree** [SafeExamBrowser/seb-win-refactoring#104]
In the SEB configuration tool, I found nowhere to config such features. Is there some detailed documentation to follow, please?

**Comment by dbuechel** [comment]
The Jitsi Meet proctoring feature is still very experimental and we frankly do not recommend using it yet. The upcoming version 3.3.0 will provide basic support for remote proctoring with Zoom, and after that we plan to release the same basic functionality with Jitsi Meet.

**Comment by danschlet** [comment]
In addition, in the Windows 3.2 version we intended to use the Jitsi Meet proctoring features mainly together with SEB Server. It also works just with proctoring settings in a SEB config file, but as it's currently an experimental feature, we didn't include it yet in the Configuration Tool. You can nevertheless use the 3.0 iOS version, in its built-in Settings menus, all Jitsi proctoring features can be configured and a shared config file can also be used with SEB 3.2 for Windows. See the 3 Remote Proctoring demo links on our [demo exam portal page](https://demo.safeexambrowser.org/exams/).
I will also update the setting keys for remote proctoring in our [configuration setting key PDF document](https://safeexambrowser.org/developer/documents/SEB-Specification-ConfigKeys.pdf) in the next few weeks.
