### ISSUE TITLE
Issue with SEB 3.8.0.742 x64 and TorTalk 1.5.2.7 - Does not read out loud marked text

### ISSUE THREAD

**Issue by AndreasB-MAU** [SafeExamBrowser/seb-win-refactoring#1041]
**Describe the Bug**
TorTalk 1.5.2.7 does not read out loud marked text within SEB 3.8.0.742 x64

**Steps to Reproduce**
1. Start Edge -> Login to Inspera -> Start exam with SEB
2. Start TorTalk in SEB
3. Mark text and click play in TorTalk
4. Nothing happens, no audio

**Expected Behavior**
TorTalk should read out loud marked text

**Screenshots**

**Version Information**
 - OS: Windows 11 Education 23H2 and 24H2
 - SEB-Version 3.8.0.742 x64
 - TorTalk 1.5.2.7

**Additional Context**
The issue does not exist with TorTalk 1.5.2.7 and SEB 3.5.0.544 x64
The issue only occur when running TorTalk 1.5.2.7 inside of SEB
TorTalk 1.5.2.7 also have OCR read. And that works in both SEB 3.5.0.544 x64 and 3.8.0.742 x64. It reads the text in the OCR-window out loud

**Comment by dbuechel** [comment]
This issue might be related to #889. If so, please consider the limitations mentioned and continue the discussion there.

**Comment by AndreasB-MAU** [comment]
This has been resolved.
