### ISSUE TITLE
SEB 3.8.0.742 takes 30sec-2min to start in Win 11 Education 24H2

### ISSUE THREAD

**Issue by AndreasB-MAU** [SafeExamBrowser/seb-win-refactoring#1043]
**Describe the Bug**
SEB 3.8.0.742 x64 takes 30sec to start. When starting within Edge (Inspera exam) it takes 2min.

**Steps to Reproduce**
1. Go to Start-Menu
2. Click on SEB -> takes 30sec to start
or
3. Start Edge
4. Go to Inspera login -> login
5. Start Exam -> SEB launches -> takes 2min to start

**Expected Behavior**
SEB should start within a couple of secs.

**Screenshots**

**Version Information**
 - OS: Windows 11 Education 24H2
 - SEB-Version 3.8.0.742 x64

**Additional Context**
The issue does not exist with SEB 3.5.0.544 and Win 11 Edu 23H2
The issue does not exist with SEB 3.8.0.742 and Win 11 Edu 23H2
The issue does not exist with SEB 3.9.0.765 x64 BETA and Win 11 Edu 24H2

**Comment by dbuechel** [comment]
Please refer to #1023.
