### ISSUE TITLE
3.8 version crashing instantly. 3.7 and 3.6 does not

### ISSUE THREAD

**Issue by Virvelvind** [SafeExamBrowser/seb-win-refactoring#1045]
2 users are not able to launch the newest version of SEB, and they need it for an exam in 14 days. They both have Elitebook 840 G9
We have ruled out antivirus, webview, runtime etc.

This is the error message they get when trying to open SEB, they also get error when trying to open SEB config

An internal exception occurred ( Address: 0x40463459

The eventlog in Windows shows absolutely nothing related to the app crash, it's just like it never happend. Minidump also shows nothing. The SEB logfile also shows nothing.

**Comment by dbuechel** [comment]
Please do not post the same issue twice. We shall continue under #1044 for the time being.
