### ISSUE TITLE
Setup Failed Safe Exam Browser Version SEB_3.2.0.338

### ISSUE THREAD

**Issue by tommaso-biondi** [SafeExamBrowser/seb-win-refactoring#105]
![image](https://user-images.githubusercontent.com/66788905/125093993-2fd2d680-e0d3-11eb-8e27-f6f568ed3a10.png)
![591ad022d5e1a3d9806db13c6aabe5f7](https://user-images.githubusercontent.com/66788905/125094040-36f9e480-e0d3-11eb-95e3-e8bd18483eab.jpg)
[Safe_Exam_Browser_202107071759527.txt](https://github.com/SafeExamBrowser/seb-win-refactoring/files/6792084/Safe_Exam_Browser_202107071759527.txt)

**Comment by dbuechel** [comment]
SEB 3.1.1 is not supported anymore, please use the latest release version 3.2.0.
