### ISSUE TITLE
It shows ** uses invalid security  certificate

### ISSUE THREAD

**Issue by SRIKAVI2** [SafeExamBrowser/seb-win-refactoring#116]

**Comment by dbuechel** [comment]
Please do provide some minimal explanation of the problem when creating an issue here on GitHub (as is already mentioned in the issue templates). Otherwise, we can't really help you if we don't know the exact nature of the problem nor how to reproduce it.

**Comment by Gomesz785** [comment]
> Please do provide some minimal explanation of the problem when creating an issue here on GitHub (as is already mentioned in the issue templates). Otherwise, we can't really help you if we don't know the exact nature of the problem nor how to reproduce it.

Yeah he is like "not working, anyway what is the fix?"

Lol
