### ISSUE TITLE
AngularJS And CefSharp library crashed SEB

### ISSUE THREAD

**Issue by tommaso-biondi** [SafeExamBrowser/seb-win-refactoring#12]
I have tested the new windows version 3.0.0 .151 with this site https://esercitazione.client.cisiaonline.it/?id=243
SEB browser has closed unexpectedly  …:“ unrecoverable error” with 
[ApplicationMonitor] Process 'CefSharp.BrowserSubprocess.exe' (12788) has been started.
I think that was due interaction from AngularJS And CefSharp library..
The https://esercitazione.client.cisiaonline.it/?id=243 is fully compatible with Chromium.

**Comment by danschlet** [comment]
This looks like a bug in the Chromium browser engine version used in SEB 3.0. Maybe an update of the browser engine will solve the issue. Or there is some helpful information in the SEB log files, could you send us these please?

Our main Windows developer will have a look at this when he's back from a leave next week.

**Comment by tommaso-biondi** [comment]
I tried and successfully tested this link  https://esercitazione.client.cisiaonline.it/?id=243    with chromium.
Are you using a custom version of Chromium in seb 3.0?

**Comment by danschlet** [comment]
Well, we are not building our own Chromium from its source code. But as we need an embeddable version, we are using CEF 3 (Chromium Embed Framework) and the CefSharp C#/.NET wrapper. I don't know if and how much they change in their Chromium builds (maybe @dbuechel knows that). In the release notes I see that SEB 3.0 is using Chromium Version 79.0.3945.130. Which version did you use to try the link?

**Comment by tommaso-biondi** [comment]
Chromium
Versione 85.0.4168.0 (Build) (a 64 bit)

**Comment by danschlet** [comment]
That's of course significantly newer than the version 79 used in SEB 3.0.0. You could try to download a Chromium 79 version and verify if the link crashes in there as well.

Currently there seems to be a CefSharp stable build with Chromium 81 and a preview version with 83. Maybe it will work with one of these. When @dbuechel is back, we anyways need to release at least a minor update because of some issues (VM detection false positives and antivirus false positive detections/Registry power options reset issue).

**Comment by tommaso-biondi** [comment]
I just tried with 79.0.3945.130 version and  It's working correctly (https://esercitazione.client.cisiaonline.it/?id=243)....

**Comment by dbuechel** [comment]
The browser crashes because you're trying to load a data-URI for the favicon: data:;base64,iVBORw0KGgo=

Is this intended? Either way, I'll implement a fix which ensures that the browser does not crash if something is wrong with the favicon.

**Comment by dbuechel** [comment]
This issue should be fixed with the new version 3.0.1.
