### ISSUE TITLE
Setup failed for SEB 3.2.0.338 for Windows

### ISSUE THREAD

**Issue by dino1966** [SafeExamBrowser/seb-win-refactoring#120]
Hello
I'm trying to install SEB 3.2.0.338 on 3 different pc (Windows 10 Version 20h2) but I get always the same error described in the attached log
[Safe_Exam_Browser_20210718230305.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/6836974/Safe_Exam_Browser_20210718230305.log)
.NET 4.8 is already installed 
Can you please help to fix? Thanks a lot

**Comment by dbuechel** [comment]
Please try to install the Microsoft Edge WebView2 Runtime manually, and then retry installing SEB: https://go.microsoft.com/fwlink/p/?LinkId=2124703

**Comment by dino1966** [comment]
Hello.

I just tried to run the executable downloaded from your link, and I get the following error:

 



 

Any suggestion?

Thanks a lot

 

 

 

Da: Damian Büchel ***@***.***> 
Inviato: lunedì 19 luglio 2021 12:43
A: SafeExamBrowser/seb-win-refactoring ***@***.***>
Cc: dino1966 ***@***.***>; Author ***@***.***>
Oggetto: Re: [SafeExamBrowser/seb-win-refactoring] Setup failed for SEB 3.2.0.338 for Windows (#120)

 

Please try to install the Microsoft Edge WebView2 Runtime manually, and then retry installing SEB: https://go.microsoft.com/fwlink/p/?LinkId=2124703

**Comment by dbuechel** [comment]
The image isn't visible in your comment...

**Comment by dino1966** [comment]
![image](https://user-images.githubusercontent.com/87620727/126192397-ebc88fa2-8198-4ca1-828c-1c1f435a7600.png)

The text says, "a problem occurred while downloading the necessary files.  Error 0x80042194

**Comment by danschlet** [comment]
This doesn't look like an original Safe Exam Browser downloaded from https://safeexambrowser.org.

**Comment by dino1966** [comment]
Hello

The screen is from installation of Microsoft Edge WebView2 Runtime, suggested above.

https://go.microsoft.com/fwlink/p/?LinkId=2124703

 

 

it is not from the SEB installation.

 

Da: Daniel R. Schneider ***@***.***> 
Inviato: lunedì 19 luglio 2021 18:40
A: SafeExamBrowser/seb-win-refactoring ***@***.***>
Cc: dino1966 ***@***.***>; Author ***@***.***>
Oggetto: Re: [SafeExamBrowser/seb-win-refactoring] Setup failed for SEB 3.2.0.338 for Windows (#120)

 

This doesn't look like an original Safe Exam Browser downloaded from https://safeexambrowser.org.

**Comment by danschlet** [comment]
Try to deactivate anti-malware software, especially if it has a feature to scan internet traffic for malware.

**Comment by dino1966** [comment]
Hello

I tried to do that on 2 different pc (both Windows 10 21H1) , disabling Symantec and McAfee antivirus.

Unfortunately in both cases I get the same error installing the MicrosoftEdgeWebview2 , error 0x80042194

 

Da: Daniel R. Schneider ***@***.***> 
Inviato: lunedì 19 luglio 2021 18:52
A: SafeExamBrowser/seb-win-refactoring ***@***.***>
Cc: dino1966 ***@***.***>; Author ***@***.***>
Oggetto: Re: [SafeExamBrowser/seb-win-refactoring] Setup failed for SEB 3.2.0.338 for Windows (#120)

 

Try to deactivate anti-malware software, especially if it has a feature to scan internet traffic for malware.

**Comment by dino1966** [comment]
I also tried to use a Windows 10 VM (version 2004  build SO 19041.685) without antivirus and I get the error 0x80042194 when I try to install MicrosoftEdgeWebview2 
When I try to install SEB_3.2.0.338_SetupBundle I get the already reported error 0x80070490

**Comment by dino1966** [comment]
Hello
I finally found the issue. It was an update of the router which changed the security settings on the firewall 
I succeded to complete the installation

**Comment by danschlet** [comment]
Great that you found the reason for the error. I guess the installer for the Microsoft Edge WebView2 Runtime still connects to a Microsoft server to download the latest runtime binary and your router firewall security settings prevented that connection.

This could confirm our suspicion that often some network security related issues prevent the SEB installer bundle to run correctly. I also guess that Microsoft uses certificate pinning for the servers which provide those system dependency binaries. Then the connection could fail if people use an anti-malware tool which replaces system root certificates to be able to decrypt and scan https internet traffic (that is in fact a man-in-the-middle MITM attack).
