### ISSUE TITLE
Safe Exam browser taskbar displaces to up and right; cannot click Quit Button

### ISSUE THREAD

**Issue by Gomesz785** [SafeExamBrowser/seb-win-refactoring#121]
**Describe the Bug**
Once a file has been loaded. seb, the exam loads, but the task bar is in the middle and up and slightly to the right on the screen. So the quit button is vanished.

**Steps to Reproduce**
1.load a .seb file
2. The issue
**Expected Behavior**
The Taskbar is at the bottom of the screen and the quit button is visible. 
**Screenshots**
kind of blurry
![20210719_184926](https://user-images.githubusercontent.com/87658122/126178334-e9f78abb-978f-4c93-b4f9-e6b75196a5e1.jpg)
very clear
![20210719_184942](https://user-images.githubusercontent.com/87658122/126178377-c7dc313f-a83b-4fbb-b6ae-b0ba3606f142.jpg)

**Version Information**
 - OS: windows 7
 - SEB-Version 3.1.1 or 3.1.0

**Additional Context**
Do graphics driver updates have something to do here?

**Comment by Gomesz785** [comment]
Oh and if Devs need log files i will post....

**Comment by Gomesz785** [comment]
Now i can't quit the browser.
I am trying CRTL+Q.
But if above doesn't work I have to get the battery out of my laptop shutdown?

**Comment by Gomesz785** [comment]
OK...
My father came and clicked `CTRL+DEL` 
Went to a screen, clicked log out!!!
TADA
Then it restarted or shutted down.
My father also happened to be a C peogrammer, ubuntu king, and the cheatlcheat list of windows.

**Comment by Gomesz785** [comment]
So now my query is; how to get the taskbar to the bottom?

**Comment by dbuechel** [comment]
Thanks for your report. Please do note that we don't support Windows 7 anymore, as it has reached its end of life. Notwithstanding, have you tried the latest release version 3.2.0?

**Comment by Gomesz785** [comment]
Not really tried the 3.2.0 version. So logically you don't support 3.1.0?

But my educational institution said that I can use 3.1.0. The files were also given by them. So do you think it is a graphics driver issue?

Any way will the 3.2.0 work on Win 7?

**Comment by Gomesz785** [comment]
@dbuechel There is a problem with laptop ordering; effectively making buying a windows laptop just can't. 

Just wanted to note you...

**Comment by Gomesz785** [comment]
>problem with laptop ordering; 
All laptop stocks are over and importers have not ordered new stocks. Only one laptop is available for pre ordering but it delivers August 1st. But my exam is in July.

**Comment by dbuechel** [comment]
> Not really tried the 3.2.0 version. So logically you don't support 3.1.0?

That is correct, we always only support the latest release version.

> So do you think it is a graphics driver issue?

You'd need to try that yourself, as with Windows, it can be a myriad of issues due to the different possible hardware & software combinations.

> Any way will the 3.2.0 work on Win 7?

You'd need to try that. We do recommend either way to update your OS to Windows 10, as Windows 7 isn't officially supported by MSFT anymore.

**Comment by Gomesz785** [comment]
I will do the exam with the bug. Certainly will install 3.2.0 and try it.

**Comment by Gomesz785** [comment]
Ok. I have good news....
It worked this time.
![DSC01234](https://user-images.githubusercontent.com/87658122/126593727-23661fa9-9f5d-4dcb-b4b7-65117b6c8ef4.JPG)
![DSC01240](https://user-images.githubusercontent.com/87658122/126593778-dd7e8470-8f31-429c-82d2-3afb2086cae8.JPG)
So can you put that my `CTRL+DEL` shortcut into the wiki or user guide as some kind of notes? Just to help users like me?
If you are on to this I will give you the .txt or .md file... :)

**Comment by Gomesz785** [comment]
![image](https://user-images.githubusercontent.com/87658122/126599449-86307c5c-8f75-47ef-b092-51ac0a9e5a66.png)
![image](https://user-images.githubusercontent.com/87658122/126599551-09ea04f5-2121-45b3-99ec-0cbb60fc88fe.png)

**Comment by danschlet** [comment]
Are you kidding me? EVERY WINDOWS USER KNOWS THIS SHORTCUT! Or is this a problem of the millennials?

**Comment by Gomesz785** [comment]
lOL

**Comment by Gomesz785** [comment]
Anyway now it is not a issue.... lol this is the funniest issue on github
