### ISSUE TITLE
can.t install ù

### ISSUE THREAD

**Issue by cristianlr99** [SafeExamBrowser/seb-win-refactoring#126]
i can't complete the installation of seb browser because it says that i may don't have the privileges to start the system services.
i'll leave the log report and a screen of the error
[Safe_Exam_Browser_20210723150812.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/6869081/Safe_Exam_Browser_20210723150812.log)
![Cattura](https://user-images.githubusercontent.com/87863952/126789025-104586cf-6abb-4fc6-8aaa-20a9fff5ea21.PNG)

**Comment by dbuechel** [comment]
You need to run the setup with elevated privileges. If there is an issue on your system related to the starting of Windows services, then you'll need to solve that yourself, we can't provide support for that. Making sure that Windows is up-to-date and regularly restarting the OS always is a good idea, so you might start there if you haven't done so already.
