### ISSUE TITLE
Using ZOOM with SEB

### ISSUE THREAD

**Issue by vanie76** [SafeExamBrowser/seb-win-refactoring#131]
### Discussed in https://github.com/SafeExamBrowser/seb-win-refactoring/discussions/130

<div type='discussions-op-text'>

<sup>Originally posted by **vanie76** July 27, 2021</sup>
I integrated ZOOM with SEB version 3.1.0 . Run 40 over e-assessment last semester via MOODLE.
When I downloaded the new version and ran the same config file this semester, the ZOOM is not launching. Please help

</div>

**Comment by dbuechel** [comment]
Please do not post the same issue twice.
