### ISSUE TITLE
0x80070490 Элемент не найден

### ISSUE THREAD

**Issue by marat123456** [SafeExamBrowser/seb-win-refactoring#138]
При установке SEB выходит ошибка: 0x80070490 Элемент не найден
Лог фаил прикрепляю.
[Safe_Exam_Browser_20210802145528.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/6916122/Safe_Exam_Browser_20210802145528.log)

**Comment by dbuechel** [comment]
Duplicate, please see the steps for manually installation in #139.
