### ISSUE TITLE
Virtual Machine Error on Windows

### ISSUE THREAD

**Issue by chuck2098** [SafeExamBrowser/seb-win-refactoring#14]
Hi, Good Morning Everybody,
Today, I tried to install your software but when I try to run it, I get the follow error:
![IMG-20200626-WA0002](https://user-images.githubusercontent.com/51959518/85840115-3af2e700-b79c-11ea-9d46-7621289e7d53.jpg)

 I have no Virtual Machine on my pc but I get this error. Why?

P.s. the pc is just recoverd and no particular softwsre installed.

Thank you!

**Comment by dbuechel** [comment]
Are you using SEB 3.0.0 or SEB 3.0.1?

**Comment by chuck2098** [comment]
The last, I downloaded it from here: https://safeexambrowser.org/download_en.html
I think 3.0.1.
When I open the file that the teacher provided me, I get this error.
But, if I open the application without open the file provided by the teacher, I get this screen:
![image](https://user-images.githubusercontent.com/51959518/85847491-c1f98c80-b7a7-11ea-95ad-681ace00eaf0.png)

**Comment by dbuechel** [comment]
The version information can be found on the splash screens as well as when pressing WIN+A and then selecting "Information about SEB" in the Action Center. If you are using 3.0.0, then try to update to 3.0.1 and see whether the problem persists.

**Comment by dbuechel** [comment]
It is also written to the application logs, see `%LocalAppData%\SafeExamBrowser\Logs\[...]_Runtime.log`

**Comment by SebastianZiegler** [comment]
We have the same problem with one of our students

Here is the log File:
[2020-06-30_11h31m27s_Runtime.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/4877231/2020-06-30_11h31m27s_Runtime.log)

**Comment by dbuechel** [comment]
@diegoara96: It appears that the issue with false positive detection of VMs is still not fixed. This user is using the new version and still triggers the detection with a normal laptop:

`Computer 'NEKOII-PC' is a LIFEBOOK-FTS LIFEBOOK A556 manufactured by FUJITSU`

**Comment by diegoara96** [comment]
@SebastianZiegler  @chuck2098 I need the output of these 2 commands  that are executed on a powershell console
`Get-WmiObject Win32_pnpEntity ` 
` Get-WmiObject Win32_NetworkAdapterConfiguration`

you can run them this way to create text files with the output

Get-WmiObject Win32_pnpEntity | Out-File path\filename.txt
Get-WmiObject Win32_NetworkAdapterConfiguration | Out-File path\filename.txt

**Comment by diegoara96** [comment]
I accept suggestions on how to improve these methods or add new ones.

@dbuechel if you see that the new methods cause many problems you can remove them but think that the manufacturers' method is not enough.

**Comment by dbuechel** [comment]
@diegoara96: Yes, I think I'll need to remove your code with version 3.1 if you can't find a solution for the issues by then. But let's first see what the problem here is, maybe there is a way to prevent the false positives.

**Comment by SebastianZiegler** [comment]
do you have a release date for 3.1?

**Comment by dbuechel** [comment]
@SebastianZiegler: No, for now it is scheduled for Q3 2020. But it would be great if you could help out in locating the issue, namely by executing the commands @diegoara96 has listed above.

**Comment by SebastianZiegler** [comment]
Here the output:

[filename.txt](https://github.com/SafeExamBrowser/seb-win-refactoring/files/4894830/filename.txt)
[filename2.txt](https://github.com/SafeExamBrowser/seb-win-refactoring/files/4894831/filename2.txt)

**Comment by diegoara96** [comment]
Thanks @SebastianZiegler . I think I have the bug located but I need one more command to be sure

`Get-WmiObject Win32_NetworkAdapterConfiguration | Format-List * | Out-File path\filename.txt`

**Comment by SebastianZiegler** [comment]
No problem

[filename3.txt](https://github.com/SafeExamBrowser/seb-win-refactoring/files/4904749/filename3.txt)

**Comment by diegoara96** [comment]
The problem was that the student's Mac was madly assigned and SEB detected it as a possible virtual machine. To avoid this, this generic check has been changed to a more specific check using prefixes.

I created a new PR #17  that corrects this problem and prevents similar things from happening in the future. Sorry for the inconvenience

**Comment by dbuechel** [comment]
Thanks @diegoara96 for the fix! @chuck2098 and @SebastianZiegler, could you please test whether this fixes your issue? You can download a beta build with the changes here: https://sebdev-let.ethz.ch/api/buildjobs/1g36ch0lweb79h48/artifacts/SEB_3.1.0.174_SetupBundle.exe

**Comment by SebastianZiegler** [comment]
I got the first feedback, from one of our students and it seems to work now. Thx.

**Comment by ndum** [comment]
Any News to SEB 3.1.0? The issue still exists...

Thanks!

**Comment by dbuechel** [comment]
Should be fixed with release version 3.1.0.

**Comment by thehowl** [comment]
For anyone that stumbles upon this issue on google in look for a solution:

Short answer: uninstall VirtualBox.

Long answer: [this is the VirtualMachineDetector code.](https://github.com/SafeExamBrowser/seb-win-refactoring/blob/master/SafeExamBrowser.SystemComponents/VirtualMachineDetector.cs) To determine if it is being ran inside a virtual machine, it looks through the devices of the computer to see if there are virtualbox drivers (typically installed using virtualbox guest additions). However, also when installing VirtualBox as a host some devices are added to the machine in order for all virtualization features to work. Uninstalling virtualbox removes the drivers and passes the VirtualMachineDetector checks.

**Comment by dbuechel** [comment]
@diegoara96 Could you please verify the statement of @thehowl above? If this in fact is the case, then the respective code needs to be removed in order to avoid false positives. I do have VirtualBox installed on my machine, and I do not get any false positives however...

**Comment by diegoara96** [comment]
@dbuechel I just tested it on 2 different computers with virtualbox installed and SEB works fine. Anyway if you want to remove that code to avoid problems I'm fine with that.

**Comment by dbuechel** [comment]
Excellent, thanks for verifying it. No, I think it indeed improves the VM check, we just need to make sure that there are no false positives. I also don't get any issues with my installation of VirtualBox.

**Comment by thehowl** [comment]
I suspect this could possibly be a Windows 7 issue? As especially Windows 10 has HyperV and a bunch of virtualisation features which I suspect make the virtualbox drivers obsolete. In any case can probably do some debugging and pinpoint the exact driver names if necessary.

**Comment by dbuechel** [comment]
Aha. Well, we don't officially support Windows 7 anymore for SEB version 3.x. But yes, if you could do some debugging and report the exact issue, then we might be able to make it work for Windows 7 as well.
