### ISSUE TITLE
Unable to download the Safe Exam Browser for Windows version 3.3.0

### ISSUE THREAD

**Issue by ankitada** [SafeExamBrowser/seb-win-refactoring#146]
**IMPORTANT**
Please _always_ consult the documentation first before creating a bug report!
https://safeexambrowser.org/windows/win_usermanual_en.html

**Describe the Bug**
Unable to download the Safe Exam Browser for Windows version 3.3.0. It is showing network error. 

**Steps to Reproduce**
1. Go to 'https://safeexambrowser.org/download_en.html'
2. Click on 'Download'

**Expected Behavior**
I expect the setup file to download in less than 5 mins.

**Screenshots**
Screenshot Attached

**Version Information**
 - OS: [Windows 10 ]
 - SEB-Version [[SEB](![1331_257_1](https://user-images.githubusercontent.com/88391165/128134801-a02cabcb-d651-49f4-9a5c-f2fac05f6544.png)) 3.3.0]

**Comment by dbuechel** [comment]
The download works just fine, there must be a network or infrastructure issue on your side.

**Comment by ankitada** [comment]
We have tried the download on multiple laptops across different networks and it still doesn't work.

**Comment by danschlet** [comment]
Didn't you try the alternative download link (two lines below the blue button, "[Download](https://github.com/SafeExamBrowser/seb-win-refactoring/releases/download/3.3.0/SEB_3.3.0.354_SetupBundle.exe) from GitHub project site."?

Maybe you have some anti-malware tools installed on all those laptops which somehow doesn't like the sourceforge site?

**Comment by ankitada** [comment]
The Alternate GitHub download works. Thank you
