### ISSUE TITLE
Unable to connect with Jitsi server in SEB windows

### ISSUE THREAD

**Issue by ganeshkumar-sr** [SafeExamBrowser/seb-win-refactoring#154]
### Discussed in https://github.com/SafeExamBrowser/seb-win-refactoring/discussions/149

<div type='discussions-op-text'>

<sup>Originally posted by **ganeshkumar-sr** August  5, 2021</sup>
I have created a configuration file with Jitsi features in ios SEB browser, We can't proctor the students in Jitsi meet(https://meet.jit.si/), when that configuration file opened in Windows SEB(3.2.0). The student can access the starturl and camera also turned on, but the student not joined in the Jitsi room.The same configuration works when we open it ios mobile, we can see the students in Jitsi meet room.

</div>

I've gone through the code of seb browser and found that "prejoinPageEnabled: false" is missing in index.html which is needed to join the Jitsi room automatically.Please analyze this issue and provide fix.

**Ref :** https://community.jitsi.org/t/join-meeting-button-on-meet-jit-si-workaround/69788

**Comment by dbuechel** [comment]
Thanks, we'll see that we integrate this when we revisit the Jitsi Meet implementation.

**Comment by dbuechel** [comment]
A fix for the issue is now available in version 3.4.0.
