### ISSUE TITLE
I have some problem please suggest me for solve it

### ISSUE THREAD

**Issue by Neronis** [SafeExamBrowser/seb-win-refactoring#159]
After updating win 10 it shown as link >> https://www.mediafire.com/file/01hpdjuszmwhqqj/262684.jpg/file

**Comment by dbuechel** [comment]
Please follow the issue template when reporting a new bug. According to your error message, the WMI repository on your machine is most likely corrupted and you'll need to repair it, see e.g. https://techcommunity.microsoft.com/t5/ask-the-performance-team/wmi-repository-corruption-or-not/ba-p/375484.
