### ISSUE TITLE
No Input possible

### ISSUE THREAD

**Issue by SebastianZiegler** [SafeExamBrowser/seb-win-refactoring#16]
One student reports that she cannot login into moodle with SEB, she could click in the fields but cannot write anything.

Any ideas?

She uses Win 10 Home and SEB 3.0.1

**Comment by dbuechel** [comment]
How can we reproduce the issue?

**Comment by SebastianZiegler** [comment]
I have no idea, the students are at home, I cannot access the device. Should I ask her anything?

**Comment by dbuechel** [comment]
Yes, namely how to reproduce the issue.

**Comment by dbuechel** [comment]
Any updates here?

**Comment by SebastianZiegler** [comment]
seems to work, don't know where the problem is.
