### ISSUE TITLE
Not found /theme/boost_ethz/sebuser.php

### ISSUE THREAD

**Issue by vinaora** [SafeExamBrowser/seb-win-refactoring#160]
https://github.com/SafeExamBrowser/seb-win-refactoring/blob/a33c7c0ff9a14db4f9cc9684ad5d365c1588768c/SafeExamBrowser.Browser/Handlers/ResourceHandler.cs#L367

GET /theme/boost_ethz/sebuser.php HTTP/1.1" 404

**Comment by dbuechel** [comment]
Please follow the templates when creating a new issue. Either describe a bug or a feature request with sufficient information for us to understand the issue.
