### ISSUE TITLE
Invalid Class Error

### ISSUE THREAD

**Issue by HannaStudent** [SafeExamBrowser/seb-win-refactoring#176]
**IMPORTANT**
Please _always_ consult the documentation first before creating a bug report!
https://safeexambrowser.org/windows/win_usermanual_en.html

**Describe the Bug**
THere was a fatal error of an Invalid Class

**Expected Behavior**

**Screenshots**
![Fatal Error](https://user-images.githubusercontent.com/89732353/131249690-2d35745e-2ef5-4fd7-b197-a6daf5dd55ac.png)

**Comment by dbuechel** [comment]
Please always search whether there already are issues about your problem, which in your case there are, e.g. #33. According to your error message, the WMI repository on your machine is most likely corrupted and you'll need to repair it, see e.g. https://techcommunity.microsoft.com/t5/ask-the-performance-team/wmi-repository-corruption-or-not/ba-p/375484 or https://www.thewindowsclub.com/how-to-repair-or-rebuild-the-wmi-repository-on-windows-10/.
