### ISSUE TITLE
download safe exam browser

### ISSUE THREAD

**Issue by alrightyaphrodit** [SafeExamBrowser/seb-win-refactoring#183]
hi, I'm an university student and i want to ask if I can download and if seb workshop well on a computer with windows 10 home s mode, I'm asking this because in the site there is write that seb is supporter only on windows 10 and 8.1 but I don't understand if for windows 10 it refers also for windows 10 home s mode edition. Thanks for the help I really don't know what to do :)

**Comment by dbuechel** [comment]
No, Windows 10 Home S Mode allows only UWP applications / applications from the Microsoft store, thus you can't use that edition with SEB for Windows.

**Comment by alrightyaphrodit** [comment]
can I use seb with windows 10 home 64 bit o I need another version of windows 10?
