### ISSUE TITLE
Warning if the user is trying to open a file with an incopatible version

### ISSUE THREAD

**Issue by lorenzorutayisire** [SafeExamBrowser/seb-win-refactoring#19]
**Is your feature request related to a problem? Please describe.**
It would be helpful if SEB warns you if you're trying to open a .seb file with a version lower than 3.0.1.

**Describe the solution you'd like**
Just open a popup window telling the two versions are different when I try to open the .seb file.

**Additional context**
Today I had to do an university exam with SEB, when I clicked on the file SEB opened up fine, I could even insert the password and navigate in the exam's website. However, when it came to actually start the exam, the website complained telling me that I wasn't using SEB. I temporarily couldn't understand the reason and thanks to the experience of my course mates I understood that I was using a wrong version of the .seb file (I had SEB 3.0.1 installed and the file was 2.4.1).

**Comment by dbuechel** [comment]
SEB configuration files are backwards- as well as forwards-compatible, a configuration can't be incompatible with a SEB version. Your issue appears to be that you either used the wrong SEB version (e.g. your university expects you to use SEB 2.4.1, but you used 3.0.1) or the wrong configuration file (e.g. your university provides a configuration file for SEB 2.4.1 and another for SEB 3.0.1, and you used the wrong one).

**Comment by dbuechel** [comment]
I'll thus close this for now. If I understood your issue wrong or you have further questions, feel free to re-open it.

**Comment by danschlet** [comment]
I guess the idea is that we provide a new setting in future for the minimal SEB version a config file is supposed to be used with. That would be possible, but it doesn't make much sense now that we don't have unified versions for all platforms (Windows, Mac, iOS) or it would make this setting complicated to use. So at the moment the minimal supported SEB version needs to be checked by the exam web application (some do this, for example Inspera Assessment or Dugga).

@lorenzorutayisire  I guess the error message that your exam system displays is not correct. Moodle for example says "You must use **an approved version** of Safe Exam Browser ...". You're right, the exam application probably is checking for the Browser Exam Key, which is different if using SEB 2.4.1 or 3.0.1.
