### ISSUE TITLE
Accept-language in HTTP header is set to en-US,en and cannot be changed, despite SEB being in a different language

### ISSUE THREAD

**Issue by Sturek** [SafeExamBrowser/seb-win-refactoring#194]
**Describe the Bug**
While the SEB interface is localized, "accept-language" in the HTTP header is set to "en-US, en" and websites are, thus, defaulting to English.

**Steps to Reproduce**
1. Set your system to a language other than English.
2. Configure the SEB to go to a page displaying the HTTP header, such as: [https://manytools.org/http-html-text/http-request-headers/](https://manytools.org/http-html-text/http-request-headers/)
3. Start the SEB
4. Compare the language of the interface to the accept-language value in the HTTP header.

**Expected Behavior**
Expected behavior would be that the language passed to the website in the HTTP header is the same as the language of the SEB interface.

**Screenshots**
![Screenshot 2021-09-09 155237](https://user-images.githubusercontent.com/6900803/132698675-c9f6832b-bc6a-4833-a7c6-bb2fe3c14717.png)

**Version Information**
 - OS: Windows 10 Pro, 21H1
 - SEB-Version 3.3.0

**Additional Context**
This may be due to CefSettings.AcceptLanguageList not being set in [BrowserApplication.cs](https://github.com/SafeExamBrowser/seb-win-refactoring/blob/a791d49c1ba0bd2342203a67a17662794b97a315/SafeExamBrowser.Browser/BrowserApplication.cs#L285) and defaulting to en-US,en, as per [https://cefsharp.github.io/api/83.4.x/html/P_CefSharp_CefSettingsBase_AcceptLanguageList.htm](https://cefsharp.github.io/api/83.4.x/html/P_CefSharp_CefSettingsBase_AcceptLanguageList.htm) . May be related to this [unresolved, closed issue](https://github.com/SafeExamBrowser/seb-win-refactoring/issues/27).

**Comment by dbuechel** [comment]
Thanks for your report. We'll see that we can fix this with the next version.

**Comment by dbuechel** [comment]
The issue should be fixed and works according to our testing. You can review the change in the latest beta build if you wish.
