### ISSUE TITLE
SEB BLACK SCREEN

### ISSUE THREAD

**Issue by zelwyns27** [SafeExamBrowser/seb-win-refactoring#195]
after launching seb, screen turns black and then fails to continue

https://user-images.githubusercontent.com/90400766/132702319-a8ddde40-d41c-411a-8d4a-4604f968158b.mp4

**Comment by dbuechel** [comment]
Could you please provide the log files for the affected session, to be found under `%LocalAppData%\SafeExamBrowser\Logs`.

**Comment by dbuechel** [comment]
Closed due to lack of feedback.
