### ISSUE TITLE
Application could not be found error

### ISSUE THREAD

**Issue by dahansen** [SafeExamBrowser/seb-win-refactoring#196]
![SEB error 2021-09-07](https://user-images.githubusercontent.com/1844555/133009944-b7a3f7f5-96cd-4aab-ad56-ac4875db925b.png)

This error displayed for several students using SEB on 2021-09-07. They all had the latest version of SEB downloaded 1 week prior. The error appeared after entering the student SEB password. Students could click “OK” and proceed without any problem, but it could be confusing/stressful. Any ideas what this is about?

I see someone else posted a similar question over at https://sourceforge.net/p/seb/discussion/844844/thread/bde4939054/#b34d but without a screenshot to clarify. Hopefully the above screenshot will help identify the problem. 

We did not get a copy of the log files as the students were trying to complete an exam on their own devices at the time.

Thanks!

**Comment by dbuechel** [comment]
Please check the configuration in the configuration tool under "Applications" -> "Permitted Processes". I reckon you have an empty entry in that table, so you'd need to remove that entry in order to get rid of that error message.

**Comment by dahansen** [comment]
> Please check the configuration in the configuration tool under "Applications" -> "Permitted Processes". I reckon you have an empty entry in that table, so you'd need to remove that entry in order to get rid of that error message.

Thanks for your response. I cannot check the file you mention because it did not occur on my computer. This occurred on several students' computers in an exam. They'd just downloaded SEB from https://support.inspera.com/hc/en-us/articles/360018691091-Is-your-Safe-Exam-Browser-Up-To-Date- -- is there a reason why the "Permitted Processes" would contain an "empty entry" by default?

**Comment by danschlet** [comment]
Please report this issue to Inspera. They created the settings, so they have to find out what's wrong with it.

**You should always first contact the provider of your exam system.** They are responsible for solving issues with their exam system and they can contact us if they trace the problem back to SEB.
