### ISSUE TITLE
Unable to Paste

### ISSUE THREAD

**Issue by LucaTomei** [SafeExamBrowser/seb-win-refactoring#20]
**IMPORTANT**
I'm unable to paste text inside SEB

<img width="1440" alt="Schermata 2020-07-16 alle 14 09 36" src="https://user-images.githubusercontent.com/46397302/87669472-5c793a00-c76e-11ea-85d8-9a47a4fb04d1.png">

**Comment by dbuechel** [comment]
Bug reports have a template for a reason. One important aspect of the template is the information about how to reproduce the issue. If we don't know how to reproduce a problem we can't help you nor fix the issue.

**Comment by danschlet** [comment]
SEB 2.x for Windows, macOS and iOS has a feature called "private clipboard", which prevents text from the outside being pasted into the SEB browser (or text from the exam being pasted to other applications or cloud clipboard tools etc.). You can disable this feature in the Security pane "Use private clipboard" (settings key: enablePrivateClipboard = false).

PS: We do **not** appreciate issue reports with phrases like "IMPORTANT" or "ASAP!!!!". SEB is open source freeware and we do best-effort support. We appreciate friendly, polite support request.
