### ISSUE TITLE
SEB (with CefSharp) cant play MP4-Files

### ISSUE THREAD

**Issue by ndum** [SafeExamBrowser/seb-win-refactoring#202]
Hi,

Currently no MP4 files (e.g. from Ilias) can be played from the SEB, because the CefSharp engine cannot play H264 / AAC formats (for licensing reasons).

Source: https://github.com/cefsharp/CefSharp/issues/3301

Is there a solution for this? Could the SEB project possibly compile CefSharp itself with the audio/video formats?

Thanks for the help.

![codexs](https://user-images.githubusercontent.com/18392323/134126435-83f88f7f-f3b7-4045-8085-f9d76e850882.PNG)

**Comment by dbuechel** [comment]
No, that is not possible for various reasons, first and foremost due to licensing issues.

**Comment by fishfree** [comment]
@dbuechel Do you think these workarounds can be used? https://stackoverflow.com/questions/34182394/mp4-codec-support-in-chromium https://superuser.com/questions/1533485/chromium-wont-play-mp4

**Comment by dbuechel** [comment]
> Do you think these workarounds can be used?

No, in order to use proprietary codecs with SEB, you'd first need to compile CEF with support for proprietary codecs, then build CefSharp with that custom CEF build, and then integrate the custom CefSharp binaries into SEB.

> Or give some detailed instructions for us to compile with the feature personnally please?

We don't have such instructions, apart from the above mentioned. We thoroughly investigated what would be needed in order to do the custom builds ourselves, and it turned out that all of this is *way* out of scope even for us, alone the licensing issues appear to be a nightmare. There indeed is a reason why Chromium as big and well-known open source project does not come with these proprietary codecs...

**Comment by danschlet** [comment]
Some additional information:

- We are keeping an eye on Microsofts .NET WebView2 API, which also uses the Chromium browser engine and can be used to embed web browser views into applications. We are even already using it for the optional Zoom and Jitsi Meet proctoring features in SEB for Windows. But this API is not yet providing all functionality that we need for the SEB browser, so we cannot use it (yet) to replace CefSharp. But WebView2 provides support for MP4, as Microsoft (similar to Apple) licenses these "proprietary" codecs. So sometimes in future we might switch to WebView2 and then SEB also on Windows would be able to also provide support for the most commonly used video codec MP4 with H.264 and AAC.
- For now you need to convert your videos to a format supported by SEB for Windows. If you also support students with Mac and iOS devices, you would need to use a web player, which supports multiple formats, [see this discussion](https://github.com/SafeExamBrowser/seb-win-refactoring/discussions/362#discussioncomment-2206112).

**Comment by fishfree** [comment]
@danschlet  I just test the latest release Safe Exam Browser 3.4.1, it still does not support playing MP4. However, in [this thread](https://learn.microsoft.com/en-us/answers/questions/666056/how-to-automatically-play-a-local-mp4-file-using-w), it seems WebView2 has supported MP4 file playing.

Or, can we use replace the chromium in seb-win with our own built exe file?
