### ISSUE TITLE
Prevent student-generated Config files from launching SEB.

### ISSUE THREAD

**Issue by kstarzecki** [SafeExamBrowser/seb-win-refactoring#210]
How does one go about that?
Our LMS does not support HTML header feature. 
Is there a way to prevent SEB from loading other configurations? 
(not re-configuring, launching from the 'start-exam-type *.seb file")

**Comment by danschlet** [comment]
Generally speaking I think you should convince the vendor of your LMS to provide an SEB integration in the future (or maybe there's a way to develop a plugin to achieve that).

But I would recommend to [read this page](https://safeexambrowser.org/developer/seb-integration.html), there are some ideas about this subject.
