### ISSUE TITLE
Windows 11 not supported

### ISSUE THREAD

**Issue by Rupesh-rkgit** [SafeExamBrowser/seb-win-refactoring#216]
Many people have moved to windows 11 so kindly make it available for windows 11 also.

**Comment by dbuechel** [comment]
Windows 11 isn't released yet, if my memory serves me right it'll be released tomorrow, October 5th 2021. Could you elaborate on "Windows 11 not supported": Did you encounter an error when running SEB 3.x under Windows 11? According to some preliminary tests on our side, SEB 3.x works just fine under Windows 11.

**Comment by Rupesh-rkgit** [comment]
Actually when I tried to run it for Accenture test, it didn't started so I had to re install windows 10 , losing all my files/apps. It worked fine for windows 10 btw.

**Comment by dbuechel** [comment]
Can you share the log file(s) for the affected session? They can be found under `%LocalAppData%\SafeExamBrowser\Logs`.

**Comment by Rupesh-rkgit** [comment]
Sorry, all the files and installed apps got deleted when when I downgraded the windows version.

**Comment by dbuechel** [comment]
Do you recall what exactly happened? Did SEB start at all and then hang on the splash screen, did it crash or something alike?

**Comment by Rupesh-rkgit** [comment]
![image](https://user-images.githubusercontent.com/57684533/135819654-5d26fd98-78cc-4b38-9798-ed6160939f48.png)

I downloaded secure exam browser as instructed and it got installed easily. Also System Configuration link said that system is compatible for test But when I tried to click on "Proceed to test" as mentioned screenshot, it didn't responded at all. I installed-uninstalled 2-3 times to check if there was any problem in installation but It didn't worked. Lastly when I installed windows 10 and clicked the same button, it worked.

**Comment by dbuechel** [comment]
Secure Exam Browser isn't the product we develop and maintain, our software is called Safe Exam Browser. You'd need to contact Accenture and report your issues to them.

**Comment by NextThread** [comment]
secure exam browser is shit!
it **doesn't** even work on **Windows** not even in **Mac** too.

I know this repo is of another one, but I am leaving my comment, if by any chance any Accenture guy looks into it! 
Even I tried contacting them, their support team **not** even **able** to fix that!!
