### ISSUE TITLE
MSI extraction

### ISSUE THREAD

**Issue by IanCundall** [SafeExamBrowser/seb-win-refactoring#217]
The instructions on extracting the MSI on this page: https://safeexambrowser.org/windows/win_usermanual_en.html#download result in **NO** MSI extraction and an unannounced reboot of the workstation! That's not polite at all!

The EXE is compiled by Wix so you need to direct people to use the Wix toolset utility DARK.EXE to get the MSI:

"[path_to_Wix_Tools]\dark.exe" "[path_to_your_EXE]\SetupBundle.exe" -x "[target_path_for_the_extracted_files]"

The MSI is then extracted to "[target_path_for_the_extracted_files]\AttachedContainer".

**Comment by dbuechel** [comment]
You're correct, those are old instructions referring to SEB 2.x, we'll see that we can update resp. remove them, as the MSIs already are available for download alongside the setup bundle of SEB 3.x.

**Comment by dbuechel** [comment]
The documentation has been updated and published.
