### ISSUE TITLE
SEB Closing Runtime

### ISSUE THREAD

**Issue by SebastianZiegler** [SafeExamBrowser/seb-win-refactoring#22]
Hello,

today we had a test and one of our students reported the this issue. Some day before she did a pre test and everything was fine. Some ideas. She tried to reinstall but noting changed. All other students didn't had the issue.

![71449aec-a283-488f-a792-19a321fe55c5](https://user-images.githubusercontent.com/2564530/88380842-95846080-cda5-11ea-99a7-f1968a755f39.jpg)

[2020-07-24_09h43m29s_Client.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/4971315/2020-07-24_09h43m29s_Client.log)
[2020-07-24_09h43m29s_Runtime.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/4971316/2020-07-24_09h43m29s_Runtime.log)

Best regards
Sebastian

**Comment by dbuechel** [comment]
It looks like there was a problem with WCF on that machine, is there any more information available in the Windows event logs ("Application")? Your student could try to repair or re-install the .NET framework, maybe the WCF components are corrupted...?

**Comment by dbuechel** [comment]
I'll fix the hang on termination if this error occurs, obviously SEB shouldn't crash if no WCF communication can be established.

**Comment by dbuechel** [comment]
Should be fixed with release version 3.1.0.
