### ISSUE TITLE
Erasing clipboard history upon exiting SEB

### ISSUE THREAD

**Issue by DaredevilFD** [SafeExamBrowser/seb-win-refactoring#220]
Upon exiting SEB the active text in the clipboard is deleted. However, the text is not removed from the clipboard history (accessible through the shortcut Win+V).

I would like it if the clipboard history also was deleted upon exiting SEB. Ideally just the history created while inside SEB.

Alternatively/additionally adding an option to completely disable use of copy/paste while inside SEB would also solve our issue.

Background: We're attempting to create a setup for High-stakes testing where participants are allowed to bring and use their own personal computers. The clipboard history allows the participants to extract questions form the test. Which is...undesirable.

Edit: I apologize if any of the features I'm asking for already exist.

**Comment by dbuechel** [comment]
Thanks for your report. We had this on the radar once but then had to tackle other priorities. Back then it also appeared to not work as it does now, as we weren't able to access the history if I recall it correctly. We'll see whether we can add this to an upcoming version, but I must advert that we already have a full backlog.

As a general note: High-stakes exams with BYOD always carry a higher risk of manipulation / cheating, as most of the students have full control over their devices. This also applies to your use case, so even if we will be able to improve SEB as you suggested, students could simply use another application which records the clipboard history (or even quickly write one themselves, if they're capable of doing so).

**Comment by DaredevilFD** [comment]
We've been testing and trying a few things in order to find a workaround regarding this copy/paste issue. Though with very little success in terms of what currently lies within our own power to fix.

However,
I did come across a forum post which mentioned disabling the clipboard history function using a .reg file.
Would it not be possible for you guys to run some sort of script that would be able to disable clipboard history upon launching SEB? Maybe even enabling it again upon exit?
What do you think?

I do fully acknowledge that running high-stakes exams with BYOD setup, is not an easy thing. We are however, intent on giving it a proper shot.

**Comment by dbuechel** [comment]
We'll see whether we can implement this in an upcoming version, given that the mechanism via registry is reliable and doesn't have any side effects on a user's system.

However, quite a while ago we changed the default behavior of SEB to not use its service component (which is responsible for such registry changes) unless explicitly enabled in the configuration (under tab "Security"). We do not recommend using the service with BYOD, thus integrating a registry change to suppress the clipboard history might introduce new, different issues for you.

**Comment by johnny986y** [comment]
why isnt there an English TPLC-F  section on the seb application yet?

**Comment by danschlet** [comment]
Can you please use terms which anybody understands or add a link which explains what "TPLC-F" is?

**Comment by johnny986y** [comment]
ENGLISH TOLC-F is a type of test taken in italy for university entrance of medical related students. and it is taken at home through the seb application. but at the moment i cant find it on the seb app, i have already paid and registered for the exam tho
Get BlueMail <https://bluemail.me> for Desktop
Daniel R. Schneider wrote:
Can you please use terms which anybody understands or add a link which explains what "TPLC-F" is?

**Comment by dbuechel** [comment]
This issue should potentially become obsolete with the new clipboard policy settings available already in the beta version of the upcoming release version 3.6.0 (see also #625). Thus, I'll allow myself to close this issue for the time being, but please do feel free to reopen it in case there comes new information to light.
