### ISSUE TITLE
Error Fatal al abrir un examen

### ISSUE THREAD

**Issue by DelfinaPons** [SafeExamBrowser/seb-win-refactoring#230]
Al momento de hacer un examen y abrir seb me salta este error y ya no se de que forma solucionarlo
![seb](https://user-images.githubusercontent.com/84234575/138790451-eeffcde6-727c-4ce8-9481-c90e6682d980.jpg)

**Comment by dbuechel** [comment]
@DelfinaPons I'll allow myself to close this issue. If you have any further input or issues, please feel free to reopen this issue or create a new one.
