### ISSUE TITLE
Can't open seb(s):// link

### ISSUE THREAD

**Issue by MoodLB** [SafeExamBrowser/seb-win-refactoring#231]
**Description**
Opening a seb(s):// link occurs to en error message "Configuration resource "sebs://(...)" is not supported" from Safe Exam Browser client.

**Steps to Reproduce**
1. Go to 'sebs://0680015x.moodle.monbureaunumerique.fr/mod/quiz/accessrule/seb/config.php?cmid=64312' with a Firefox browser
2. The Safe Exam Browser client is launched automatically and an error message "Configuration resource "sebs://(...)" is not supported" occurs.

**Expected Behavior**
The Safe Exam Browser client is supposed to reach the exam.

**Screenshots**
![sebs_failure](https://user-images.githubusercontent.com/93208888/138910380-19a09e30-c9e3-44b7-9507-99c85ca73ae3.JPG)

**Version Information**
 - **OS: Windows 10 Professional, Version 2004**
 - **SEB-Version: SEB 3.3.1 388**
 - **Firefox 93.0 (64 bits)**
 - **Moodle 3.9.9**

**Notes**

- The Moodle portal is using a **Single Sign On authentication server** (CAS server from Apereo version 5.x).

**What I checked?**

- **"quizaccess_seb | showseblinks"** option is enabled in Moodle,

-  The link "https://0680015x.moodle.monbureaunumerique.fr/mod/quiz/accessrule/seb/config.php?cmid=64312" is working (after passing the authentication step) when applied on a browser as a result of a "config.seb" file correctly downloaded,

- The error occurs when the client executes the HTTP request as the logs underline it. The client doesn't get any response from the server (the variable **isAvalaible** from _SafeExamBrowser.Configuration/DataResources/NetworkResourceLoader.cs_ didn't get any value),
[2021-10-26_17h10m39s_Runtime.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/7419494/2021-10-26_17h10m39s_Runtime.log)

- Surprisingly, after installing a Fiddle or mitmproxy (HTTPS proxy) instance on my local PC, the client manages to work correctly. Here is the network dump of the transaction :
[fiddler_session.txt](https://github.com/SafeExamBrowser/seb-win-refactoring/files/7419657/fiddler_session.txt)

**Comment by dbuechel** [comment]
Any updates here?

**Comment by MoodLB** [comment]
I've progressed a little bit on this issue.

**What did I do?**

- I checked the HTTP response sent by our Moodle server (which is lying behind an haproxy server) and after multiple 302 redirections due to CAS workflow, the final code I got is a 200 HTTP code.
So, the SEB client doesn't achieve to retrieve this status code and I can't figure why my server commits a violation protocol.

- I recompiled the last version of SEB code and changed the HEAD Method by a GET Method in the _NetworkResourceLoader.cs_ file (line 160 - _var request = new HttpRequestMessage(**HttpMethod.Get**, uri);_ instead of _var request = new HttpRequestMessage(**HttpMethod.Head**, uri);_) and here, no error from the SEB client.
That's pretty weird because there is no special treatment for HEAD requests by our haproxy.

- After checking some documentation on the Internet, it could be the HTTP parser from dotnet which is very strict on its controls. I managed to use another HTTP handler to test if the error occurs :  **WinHTTP handler**.

So I created a custom class Http2CustomHandler.cs :
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace SafeExamBrowser.Configuration.DataResources
{
	public class Http2CustomHandler : WinHttpHandler
	{
		protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, System.Threading.CancellationToken cancellationToken)
		{
			return base.SendAsync(request, cancellationToken);
		}
	}
}
```

And I managed to use this class in the _Execute_ method of _NetworkResourceLoader.cs_ file :

```
private HttpResponseMessage Execute(HttpRequestMessage request)
		{
				var task = Task.Run(async () =>
					{
						using (var client = new HttpClient(new Http2CustomHandler()))
						//using (var client = new HttpClient())
						{
							return await client.SendAsync(request);
						}
					});
				return task.GetAwaiter().GetResult();
		}
```
And it works perfectly well with this HTTP handler. It makes me conclude that there is something too strict on the dotnet HTTP handler to accept this 200 status code but I didn't manage to know what.

So, I'm trying to debug the code but as I'm not a developer and not very familiar with C#/.Net, I struggled a little bit.

**Comment by dbuechel** [comment]
Excellent, thanks for the update. We're using HEAD in that method for performance reasons, as at this point we don't really need to load the entire configuration file (yet), we simply want to check whether it's available and ready to be loaded later on.

> It makes me conclude that there is something too strict on the dotnet HTTP handler to accept this 200 status code but I didn't manage to know what.

I unfortunately don't know the exact details of the implementation in the .NET Framework, but I reckon a component that widely used should be working according to common standards. But please let us know if there's anything we could do that would help you with your investigations.

**Comment by MoodLB** [comment]
Thanks for your answer. I'll do my best to advance on this issue.

I've got just a question concerning the conception of your code. 

Regarding your code below, we depend of the HEAD method request return (either it should return a 200 SuccessStatusCode or an 401 Unauthorized status code) to pass through the GET method in order to check the URL availability.

**Wouldn't it be more convenient to pass through the GET method no matter the failure reason?**

```
		private bool IsAvailable(Uri resource)
		{
			try
			{
				var uri = BuildUriFor(resource);

				logger.Debug($"Sending HEAD request for '{uri}'...");

				var request = new HttpRequestMessage(HttpMethod.Head, uri);
				var response = Execute(request);
				var isAvailable = response.IsSuccessStatusCode || IsUnauthorized(response);

				logger.Debug($"Received response '{ToString(response)}'.");

				if (!isAvailable)
				{
					logger.Debug($"HEAD request was not successful, trying GET request for '{uri}'...");

					request = new HttpRequestMessage(HttpMethod.Get, uri);
					response = Execute(request);
					**isAvailable = response.IsSuccessStatusCode || IsUnauthorized(response);**

					logger.Debug($"Received response '{ToString(response)}'.");
				}

				return isAvailable;
```
I mean, in my case, I could have pass through the GET method test (which is working) but as the code breaks earlier with the HEAD method test, I didn't have the chance to use this option.

**Comment by dbuechel** [comment]
I think we could indeed improve this code so that the GET request is executed in case the HEAD request results in an exception. I'll add this for the upcoming version. Thanks again for the great input!

**Comment by dbuechel** [comment]
I have improved the implementation as you've suggested, feel free to test it in the latest beta build for version 3.3.2.

**Comment by MoodLB** [comment]
I confirm the GET check passes after the failure of the HEAD check with this version. Thanks a lot for your work and merry Christmas!

**Comment by dbuechel** [comment]
Excellent, thanks for your feedback. Happy holidays to you as well!
