### ISSUE TITLE
Missing additional recources in version Safe Exam Browser 3.3.1

### ISSUE THREAD

**Issue by redegelde** [SafeExamBrowser/seb-win-refactoring#234]
**IMPORTANT**
Please _always_ consult the documentation first before creating a bug report!
https://safeexambrowser.org/windows/win_usermanual_en.html

**Describe the Bug**
with version 3.3 there is now "additional resources anymore
We have an URL and in the new version, we can we put this?

**Steps to Reproduce**
open The program, and add the url in tab addintional resources

**Expected Behavior**
add the URL and go

**Screenshots**
![seb2 2](https://user-images.githubusercontent.com/93261079/140291046-888dd443-b8be-427a-b3c1-ad0840c997cf.png)

**Version Information**
 - OS: [e.g. Windows 11 Professional,]
 - SEB-Version [e.g. SEB 3.0.1]

**Additional Context**

**Comment by dbuechel** [comment]
The additional resource feature isn't yet contained in SEB 3.x. As the [roadmap](https://safeexambrowser.org/about_roadmap_en.html) reveals, we plan to add it in one of the upcoming feature updates in 2022 or 2023 at the latest. If you'd like to be notified when a new SEB release happened, you can subscribe to the [SEB RSS feed](https://sourceforge.net/p/seb/news/feed.rss). Thus I'll allow myself to mark this issue as closed for the meanwhile.
