### ISSUE TITLE
Can't open URI schema link.

### ISSUE THREAD

**Issue by Gendie** [SafeExamBrowser/seb-win-refactoring#24]
## Description
After upgrading to v3.0.1 Opening URI schema is not working. 
In my demonstration, I will use the URI Schema of Zoom application because it is popular.

**Steps to Reproduce**
The simplest way to produce the issue is
- Upgrade from version 2.3 to version 3.0.1.
- Add Zoom to Permitted Processes and remove Zoom from Prohibited Processes.
- Open a page that contains a link with custom URI Schema inside the "Safe Exam Browser".
   Example: `<a href="https://us04web.zoom.us/j/00000000000?pwd=00000">Click me</a>`
- Click on the link.

**Expected Behavior**
Show popup says 'Open Zoom meeting'
![image](https://user-images.githubusercontent.com/28968965/88479172-7d4f4580-cf4d-11ea-8b32-a15b150fcc8f.png)

**Actual Behaviour**
Displays an error
![20200726_144347](https://user-images.githubusercontent.com/28968965/88479355-d53a7c00-cf4e-11ea-93a8-71170b0d97cc.jpg)

**Version Information**
 - OS: Windows 10 Professional
 - SEB-Version 3.0.1

**Additional Context**
- I tried other URI Schemas but it didn't work.
- At SEB config at Network tab Active URL filtering is not selected.

**Comment by dbuechel** [comment]
Should be fixed with release version 3.1.0.
