### ISSUE TITLE
Popup Creation Fails

### ISSUE THREAD

**Issue by dbuechel** [SafeExamBrowser/seb-win-refactoring#240]
When opening a new window/tab with JavaScript, unlike all other browsers, SEB returns null in method `window.open(...)'`. As a result, setting the URL in the second statement does not work.

```
var targetWindow = window.open("","_blank");
...
targetWindow.location.href = '<the real url>';
```

_Originally posted by @uhensler in https://github.com/SafeExamBrowser/seb-win-refactoring/discussions/228#discussioncomment-1604061_

**Comment by dbuechel** [comment]
Turns out this (still) is a limitation of the browser engine: https://github.com/cefsharp/CefSharp/wiki/General-Usage#popups. There are experimental approaches to make the parent-child relationship for popups work, but for now we can't integrate them in a release as they'd most likely cause other issues.

**Comment by wolfgang-pfalzgraf** [comment]
Does this mean that we have to go back to SEB 2.4 to be albel to open a ms-Word Window in an OpenOlat Task (Aufgabenbaustein)?
Is there a timelien to solve this problem?

**Comment by danschlet** [comment]
Maybe the OpenOLAT guys can solve this issue, I would at least try to ask in their forums.

**Comment by amaitland** [comment]
> Turns out this (still) is a limitation of the browser engine: https://github.com/cefsharp/CefSharp/wiki/General-Usage#popups. There are experimental approaches to make the parent-child relationship for popups work, but for now we can't integrate them in a release as they'd most likely cause other issues.

The Wiki is actually outdated and is on my list of things to update. If you are using WinForms then hosting a popup as a tab is relatively simple starting in version 96.0.142

See https://github.com/cefsharp/CefSharp/blob/cefsharp/96/CefSharp.WinForms.Example/BrowserTabUserControl.cs#L72 for example.

**Comment by dbuechel** [comment]
Thanks for the info, @amaitland. I'll definitely keep this in mind as we have planned to integrate tabs in an upcoming release version, so I think we can at least fix it that way once we add tabs as a feature.

**Comment by dbuechel** [comment]
@wolfgang-pfalzgraf I don't think so, but you might need to change your implementation to work around the popup problem or not use popups if possible. As far as I know, there appears to be no timeline for fixing the issue in the browser engine.

**Comment by amaitland** [comment]
> once we add tabs as a feature.

@dbuechel You're not limited to using tabs, was just an example.

**Comment by dbuechel** [comment]
> You're not limited to using tabs, was just an example.

Oh, okay, in that case I misunderstood the example, sorry. I'm however a bit confused now regarding the possible solution(s) to this issue: Do you see a solution that we could implement, given our [current implementation of ILifeSpanHandler](https://github.com/SafeExamBrowser/seb-win-refactoring/blob/master/SafeExamBrowser.Browser/Handlers/LifeSpanHandler.cs#L31)? I have tried various attempts of assigning a new instance of our [BrowserControl](https://github.com/SafeExamBrowser/seb-win-refactoring/blob/master/SafeExamBrowser.Browser/BrowserControl.cs) implementation to the `newBrowser` parameter, but all lead to an application crash.

**Comment by amaitland** [comment]
> I'm however a bit confused now regarding the possible solution(s) to this issue

Please start from the beginning, what are you trying to do with the popup? 

> Do you see a solution that we could implement, given our current implementation of ILifeSpanHandler?

Your implementation cancels popup creation, so the behaviour you are seeing is expected. CefSharp now includes a ILifeSpanHandler implementation that handles the plumbing of hosting the popup in a ChromiumHostControl instance. 

For reference see https://github.com/cefsharp/CefSharp/blob/master/CefSharp.WinForms/Handler/LifeSpanHandler.cs

You can download the project source and debug the WinForms example to get a better understanding.

**Comment by uhensler** [comment]
@dbuechel We cannot solve this issue in OpenOlat (at least not with reasonable effort). We assume that you will try again to solve this SEB issue, especially since it should be possible according to @amaitland 's statements. What are your further plans?

**Comment by dbuechel** [comment]
> Please start from the beginning, what are you trying to do with the popup?

We had a report where a popup window reference in JavaScript (`targetWindow` below) would be null when created as follows :

```
var targetWindow = window.open("","_blank");
...
targetWindow.location.href = '<the real url>';
```

Up to now, the handling of popups that we currently have appeared to be sufficient for most use cases. We namely cancel the popup creation and fire an event where we open a new browser window with a new instance of our [browser control implementation](https://github.com/SafeExamBrowser/seb-win-refactoring/blob/master/SafeExamBrowser.Browser/BrowserControl.cs) which loads the originally intended URL for the popup:

https://github.com/SafeExamBrowser/seb-win-refactoring/blob/master/SafeExamBrowser.Browser/Handlers/LifeSpanHandler.cs#L36
https://github.com/SafeExamBrowser/seb-win-refactoring/blob/master/SafeExamBrowser.Browser/BrowserApplication.cs#L415

But it appears to be the case that canceling the popup creation as we do at the moment breaks the parent-child relationship normally available for popup windows. Thus the solution would require to make this parent-child relationship work so that the above code does not return `null` when calling `window.open(...)`.

Do I understand you correctly in that we can make this relationship work if we'd use your LifeSpanHandler implementation linked above as a basis and then extend it so that we still are able to suppress popups in case we need to do so? And if so, will we be able to host the child browser control in our own browser window implementation and not the popup window CEF automatically generates?

Thanks again for your help, @amaitland. It really means a lot, as I am not very familiar with the inner workings of CEF.

**Comment by amaitland** [comment]
> Do I understand you correctly in that we can make this relationship work if we'd use your LifeSpanHandler implementation linked above as a basis and then extend it so that we still are able to suppress popups in case we need to do so?

@dbuechel Yes, use the provided `LifeSpanHandler` implementation. In version `97` (which should be out shortly) I've added the ability to cancel popup creation. So you shouldn't need to use a custom implementation. 

Relevant commit https://github.com/cefsharp/CefSharp/commit/02438767953692e5c66443546adcedc728cc113a

> And if so, will we be able to host the child browser control in our own browser window implementation and not the popup window CEF automatically generates?

Correct. You can Add the [ChromiumHostControl](https://cefsharp.github.io/api/96.0.x/html/T_CefSharp_WinForms_Host_ChromiumHostControl.htm) instance to your own `Form`/Window. The example uses tabs, you can use whatever you like.

**Comment by dbuechel** [comment]
Okay, I have been able to integrate the new API but it unfortunately doesn't entirely work: Given the testing page listed below, the browser namely crashes when a popup itself intends to create another popup or when a page tries to close its popup programmatically and the popups furthermore do not navigate as they should.

```
<html>
    <head>
        <title>JavaScript Popup Test</title>
    </head>
    <body>
        <script type="text/javascript">
            var targetWindow = window.open('', '_blank');

            if (targetWindow == null)
            {
                document.getElementsByTagName('body')[0].style['background'] = 'red';
                alert('window.open returned null!');
            }
            else
            {
                document.getElementsByTagName('body')[0].style['background'] = 'green';
                targetWindow.location.href = 'https://www.duckduckgo.com';
                setTimeout(() => targetWindow.close(), 10000);
            }
        </script>
    </body>
</html>
```

I have replaced our own custom implementation of `ILifeSpanHandler` with the new builder API, I don't know whether there is an error in how I am using the API @amaitland?

```
var lifeSpanHandler = LifeSpanHandler
	.Create(() => LifeSpanHandler_CreatePopup(args))
	.OnBeforePopupCreated(LifeSpanHandler_PopupRequested)
	.OnPopupCreated((control, url) => LifeSpanHandler_PopupControlCreated(control, args, url))
	.OnPopupDestroyed(LifeSpanHandler_PopupDestroyed)
	.Build();

private ChromiumHostControl LifeSpanHandler_CreatePopup(PopupRequestedEventArgs args)
{
	PopupRequested?.Invoke(args);

	return args.Instance.Control as ChromiumHostControl;
}

private void LifeSpanHandler_PopupControlCreated(ChromiumHostControl control, PopupRequestedEventArgs args, string url)
{
	args.Instance.InitializeWindow();
}

private void LifeSpanHandler_PopupDestroyed(ChromiumHostControl control, IBrowser browser)
{
	if (!control.IsDisposed && control.IsHandleCreated)
	{
		control.Dispose();
	}
}

private PopupCreation LifeSpanHandler_PopupRequested(IWebBrowser chromiumWebBrowser, IBrowser browser, IFrame frame, string targetUrl, string targetFrameName, WindowOpenDisposition targetDisposition, bool userGesture, IBrowserSettings browserSettings)
{
	var creation = PopupCreation.Cancel;
	...

	switch (settings.PopupPolicy)
	{
		case PopupPolicy.Allow:
		case PopupPolicy.AllowSameHost when sameHost:
			...
			creation = PopupCreation.Continue;
			break;
		case PopupPolicy.AllowSameWindow:
		case PopupPolicy.AllowSameHostAndWindow when sameHost:
			...
			break;
		case PopupPolicy.AllowSameHost when !sameHost:
		case PopupPolicy.AllowSameHostAndWindow when !sameHost:
			...
			break;
		default:
			...
			break;
	}

	return creation;
}
```

**Comment by dbuechel** [comment]
I was able to fix the crash and bring it to work correctly when attempting to programmatically close a popup via `targetWindow.close()` by using the following handler for `OnPopupDestroyed`:

```
private void LifeSpanHandler_PopupDestroyed(IBrowser browser, ChromiumHostControl control, PopupRequestedEventArgs args)
{
	args.Instance.Terminate();

	if (!control.IsDisposed && control.IsHandleCreated)
	{
		control.Dispose();
	}
}
```

The other two issues however remain. Furthermore, I have noted that even merely opening a popup can lead to an application crash.

Given these issues, I will attempt to make things work (at least without crashing), but if I won't manage to do so until the feature freeze for the next release version (which starts Monday, January 24th) then I'm afraid that we'll have to move this issue to version 3.4.

**Comment by amaitland** [comment]
@dbuechel What version are you using? 

Unfortunately your code example is incomplete so I'm not sure where the problem lies. The LifespanHandler.Create delegate should only be used if you are creating a custom implementation of ChromiumHostControl, if you are not then don't pass in a delegate. 

 If you require further assistance then please fork https://github.com/cefsharp/CefSharp.MinimalExample and provide an example that reproduces the problem, push changes to GitHub (squash into a single commit). Keep the changes to the absolute minimum required to reproduce the problem. 

If you can provide an example I can have a look when time permits.

**Comment by dbuechel** [comment]
> What version are you using?

We're currently using 97.1.11, but I plan to update to the latest version before release (I think that'd be 97.1.12).

> The LifespanHandler.Create delegate should only be used if you are creating a custom implementation of ChromiumHostControl, if you are not then don't pass in a delegate.

We do [inherit from `ChromiumWebBrowser`](https://github.com/SafeExamBrowser/seb-win-refactoring/blob/master/SafeExamBrowser.Browser/BrowserControl.cs) as we require quite a bit of plumbing and custom behavior for our browser implementation, see also [BrowserApplicationInstance.cs#L128](https://github.com/SafeExamBrowser/seb-win-refactoring/blob/master/SafeExamBrowser.Browser/BrowserApplicationInstance.cs#L128).

> If you can provide an example I can have a look when time permits.

Thanks a lot @amaitland, that would be a huge help; I'll try to provide a minimal example at once.

**Comment by dbuechel** [comment]
Okay, I have been able to somewhat reproduce the problem: [Minimal Changeset](https://github.com/dbuechel/CefSharp.MinimalExample/commit/641e15a45877bd6ab3fad091f195079645296838#diff-dac9058532c52f8d4e693bcc0df10c98f8a15740a43a8c2f341a524ac826a27b). With this change, when you open 3-4 popups consecutively (i.e. open [Popup Test.html](https://github.com/SafeExamBrowser/seb-win-refactoring/files/7905034/Popup.Test.html.txt) in the main window, then again in the popup, then again in the 2nd popup etc.) you should be able to reproduce the crash (normally happens after 10s when the popups are about to be closed).

The Windows event viewer reports the following for the crash:

```
CefSharp.MinimalExample.WinForms.exe, Version: 1.0.0.0, Zeitstempel: 0x61e94d27
Module: libcef.dll, Version: 97.1.1.0, Zeitstempel: 0x61cbb337
Exceptioncode: 0xc0000005
Offset: 0x000000000399a52b
C:\Workspaces\Experiments\CefSharp.MinimalExample\CefSharp.MinimalExample.WinForms\bin\AnyCPU\Debug\net452\CefSharp.MinimalExample.WinForms.exe
C:\Workspaces\Experiments\CefSharp.MinimalExample\CefSharp.MinimalExample.WinForms\bin\AnyCPU\Debug\net452\x64\libcef.dll
```

However, I think I already detected the mistake: We are inheriting our [`BrowserControl`](https://github.com/SafeExamBrowser/seb-win-refactoring/blob/master/SafeExamBrowser.Browser/BrowserControl.cs#L21) from `ChromiumWebBrowser`, but the `LifeSpanHandler.Create()` handler wants a `ChromiumHostControl`. I did simply cast the browser control as seen above as I thought that `ChromiumWebBrowser` inherits from `ChromiumHostControl` (see e.g. the inheritance hierarchy in the [documentation](https://cefsharp.github.io/api/93.1.x/html/T_CefSharp_WinForms_ChromiumWebBrowser.htm)). This appears not to be the case, because I was unable to compile a direct cast in the minimal example and had to first save the reference as `object`:

```
LifeSpanHandler.Create(() =>
{
	// Produces compiler error CS0039: "Cannot convert type ..."
	return new ChromiumWebBrowser("about:blank") as ChromiumHostControl;
})

LifeSpanHandler.Create(() =>
{
	object browser = new ChromiumWebBrowser("about:blank");

	return browser as ChromiumHostControl;
})
```

Could this be the issue @amaitland, or am I completely mistaken here? And if this indeed is the issue, do we need to inherit our custom browser control from `ChromiumHostControl` or what is the difference between those two?

**Comment by amaitland** [comment]
> I did simply cast the browser control as seen above as I thought that ChromiumWebBrowser inherits from ChromiumHostControl (see e.g. the inheritance hierarchy in the documentation). 

You are referencing an old version of the documentation. I haven't released a 97 version yet. The 96 documentation should be correct. 

http://cefsharp.github.io/api/96.0.x/html/T_CefSharp_WinForms_ChromiumWebBrowser.htm

> Could this be the issue @amaitland, or am I completely mistaken here?

This would be an issue. 

They share a common base control of http://cefsharp.github.io/api/96.0.x/html/T_CefSharp_WinForms_Host_ChromiumHostControlBase.htm

They onky share a subset of features so you'll most likely need to do some refactoring.

**Comment by dbuechel** [comment]
Thanks again for your feedback and help, @amaitland. I tried the default control creation handler (i.e. `LifeSpanHandler.Create()`) with the minimal example as well as our official code and am unfortunately still able to reproduce the issue, so I'm not sure if this is the only reason for the crashes.

Since `ChromiumHostControl` lacks a lot of functionality we need in a browser instance, I definitely won't be able to make this functionality work in the time I have left before feature freeze. So I'll have to move this to version 3.4, and even then I'm not sure if and how we'll be able to consolidate the functionality, given that we need quite a few of the handlers `ChromiumWebControl` provides but `ChromiumHostControl` apparently lacks:

```
DialogHandler
DisplayHandler
DownloadHandler
KeyboardHandler
LifeSpanHandler
MenuHandler
RequestHandler
```

**Comment by amaitland** [comment]
> with the minimal example as well as our official code and am unfortunately still able to reproduce the issue, so I'm not sure if this is the only reason for the crashes.

Please push your code to GitHub so I can see what's going on.

> given that we need quite a few of the handlers ChromiumWebBrowser provides but ChromiumHostControl apparently lacks:

ChromiumHostControl is a **host control**, a control that hosts the popup browser. The parent ChromiumWebBrowser handlers will fire for the parent and it's popups. Check IBrowser.IsPopup see https://github.com/cefsharp/CefSharp/blob/cefsharp/97/CefSharp.WinForms/Handler/LoadHandler.cs#L21 for an example that hopefully gives some clarity. 

It's possible I'll add some more events to simplify things, you can very easily add your own.

> and even then I'm not sure if and how we'll be able to consolidate the functionality

Some of the handlers will likely require no modification. Little planning and the rest should be quite trivial to add support for popups.

**Comment by dbuechel** [comment]
> Please push your code to GitHub so I can see what's going on.

I've created a new, temporary branch called [SEBWIN-531](https://github.com/SafeExamBrowser/seb-win-refactoring/tree/SEBWIN-531), the changes are contained in the following commit: https://github.com/SafeExamBrowser/seb-win-refactoring/commit/0cb14d33182272e820c18e70f073a1d30328254f

> The parent ChromiumWebBrowser handlers will fire for the parent and it's popups.

Okay, that's pretty crucial and I wasn't aware of this at all. The implementation we currently have always creates a new `BrowserApplicationInstance` for popups et al. which then has its own dedicated `BrowserControl`. So this means that in our code, a `BrowserApplicationInstance` will need to handle all events for itself as well as all of its popup windows? And does this also apply for new browser windows opened e.g. via a link with `target="_blank"`?

**Comment by amaitland** [comment]
> I've created a new, temporary branch called SEBWIN-531, the changes are contained in the following commit: 0cb14d3

Can you provide a fork of the minimum example that reproduces the problem 

> The implementation we currently have always creates a new BrowserApplicationInstance for popups et al.

You currently cancel popup creation, so effectively you aren't using popups at all.

> via a link with target="_blank"?

This would by default open a popup. You are canceling popup creation currently.

**Comment by dbuechel** [comment]
> Can you provide a fork of the minimum example that reproduces the problem

https://github.com/dbuechel/CefSharp.MinimalExample as specified in https://github.com/SafeExamBrowser/seb-win-refactoring/issues/240#issuecomment-1017456640

> This would by default open a popup. You are canceling popup creation currently.

We'd definitely need to keep the current behavior for new windows / popups when they're opened by e.g. `target="_blank"`. All we're trying to achieve is to make the JavaScript code listed below work correctly whilst maintaining all of our custom browser behavior like URL filtering etc.:

```
var targetWindow = window.open("","_blank");
...
targetWindow.location.href = '<the real url>';
```

**Comment by amaitland** [comment]
> https://github.com/dbuechel/CefSharp.MinimalExample as specified in [#240 (comment)](https://github.com/SafeExamBrowser/seb-win-refactoring/issues/240#issuecomment-1017456640)

See https://github.com/cefsharp/CefSharp.MinimalExample/tree/chromiumhostcontrol for an updated example.

- I've rebased and squashed your branch (best to keep upgrade commits separate, so code is easier to review)
- Refactored winforms example to provide a more complete demo
- Your example `html` above was turned into https://cefsharp.github.io/demo/openpopup.html to simplify testing.
- Added a custom LoadingProgressChanged property to demo one option for creating common event.

For common events I'm open to adding them directly in `CefSharp` (they'll need to be added to all the `WinForms`, `WPF`, `WPF.HwndHost` and `OffScreen` implementations, so there's a bit of work there.

> We'd definitely need to keep the current behavior for new windows / popups when they're opened by e.g. `target="_blank"`

Not sure why you'd want the extra complexity, would it actually be necessary to create an extra code path?. If the answer is yes then that's totally upto to you (simple enough to do).

**Comment by dbuechel** [comment]
Thanks a lot for the updated example, @amaitland! I think I understand now what's to be done to integrate the popup functionality in our context.

> Not sure why you'd want the extra complexity, would it actually be necessary to create an extra code path?

I do still think so, this due to the fact that we induce a kiosk mode without the Windows shell (explorer.exe) running. Thus our custom shell needs to handle application instances and their window(s) itself, that's why I need to correctly register every new browser window (even if it's "just" a popup) with the browser application.

**Comment by dbuechel** [comment]
I just had to realize that we most likely won't be able to consolidate our browser functionality requirements with the functionality of the API as it currently presents itself. I am aware of the fact that CefSharp is only a wrapper around CEF, so I reckon the underlying issue really pertains to CEF or even Chromium itself.

I still encounter some difficulty in understanding the difference between or why it even would be necessary to have a `ChromiumWebBrowser` control and a `ChromiumHostControl` with different functionality instead of just being able to use the same control for all types of windows (popup or not); this appears to me, as an average user of the API, somewhat like a design flaw, though I am conscious that it may be due to technical limitations or intentional design patterns of which I am not aware.

> `ChromiumHostControl` is a host control, a control that hosts the popup browser. The parent `ChromiumWebBrowser` handlers will fire for the parent and its popups.

This really appears to be the root of the issue: We allow our users to define different settings for the main and additional browser windows (i.e. popups), see https://safeexambrowser.org/windows/win_usermanual_en.html#BrowserPane. However, if we now switch to the new API, all the subsequently opened windows launched from the main (i.e. the first opened) browser window will be popups, and as the `ChromiumHostControl` uses the handlers of its parent window, the settings defined for additional windows will effectively be ignored. That's also why I initially intended to create a new `ChromiumWebBrowser` for popups, as we'd need at least a separate set of handlers for popups, so that the main window and additional windows can have different functionality.

@amaitland Thanks again for all the help and support with this issue, it really is highly appreciated. It bothers me quite a bit that it appears that we won't be able to make this work, but as far as I can judge we'd really need a popup with its own, full `ChromiumWebBrowser` control and dedicated set of handlers.

@danschlet I do judge the possibility to distinguish between main and additional browser windows to be more important than a working parent-child relationship for popups opened with JavaScript, or what do you think? If you agree, I'd suggest to set this issue as "won't fix" for the time being, but keep it open and re-evaluate the situation at a later point in time.

**Comment by amaitland** [comment]
> this appears to me, as an average user of the API, somewhat like a design flaw

It could be rewritten, it could potentially take weeks, someone would need to pay me (just the reality of it).

> It bothers me quite a bit that it appears that we won't be able to make this work, but as far as I can judge we'd really need a popup with its own, full ChromiumWebBrowser control and dedicated set of handlers.

You absolutely can make it work. You just need to create events for all the handler methods you are after. Take you a few hours, mostly just plumbing code, nothing complex. Each handler method becomes an event.

**Comment by dbuechel** [comment]
> You just need to create events for all the handler methods you are after. Take you a few hours, mostly just plumbing code, nothing complex. Each handler method becomes an event.

Okay, that's excellent news, thanks for the input @amaitland! I had implemented the control extensions like you've demonstrated in the host control branch of the minimal example, but once I reached the handlers I wasn't aware that I could replace resp. re-implement them as events for the `ChromiumHostControl`. I assumed that there is some internal plumbing and functionality in the `ChromiumWebBrowser` control which I won't be able to replicate for the `ChromiumHostControl` so that it can have its own, dedicated set of handlers / events.

I'll thus attempt to continue with this issue by trying to implement all the handlers we are currently using in our specialization of `ChromiumWebBrowser` as events for the newly added specialization of `ChromiumHostControl`.

**Comment by dbuechel** [comment]
I'm terribly sorry, @amaitland, I'd kindly need to ask for your input yet another time. After a bit of trial and error, I think I finally was able to define the interfaces how I'd like to be using them, more or less a copy of your minimal example:

```
// IChromiumWebBrowserEx in your example
interface ICefSharpControl : IChromiumWebBrowserBase, IWin32Window, IComponent, ISynchronizeInvoke
{
	event EventHandler<AddressChangedEventArgs> AddressChanged;
	event EventHandler IsBrowserInitializedChanged;
	event EventHandler<TitleChangedEventArgs> TitleChanged;
}

// ChromiumWebBrowserEx in your example
class CefSharpBrowserControl : ChromiumWebBrowser, ICefSharpControl
{
	public CefSharpBrowserControl(string url) : base(url)
	{
	}
}

// ChromiumHostControlEx in your example
class CefSharpHostControl : ChromiumHostControl, ICefSharpControl
{
	public CefSharpHostControl(string url)
	{
	}
}

// This is our custom implementation / wrapper of the CefSharp browser control
internal class BrowserControl : ...
{
	...

	public ICefSharpControl Control { get; set; }

	public string Address => Control.Address;
	public bool CanNavigateBackwards => Control.BrowserCore.CanGoBack;
	public bool CanNavigateForwards => Control.BrowserCore.CanGoForward;

	...

	public void Initialize()
	{
		Control.AddressChanged += (o, args) => addressChanged?.Invoke(args.Address);
		Control.FrameLoadStart += BrowserControl_FrameLoadStart;
		Control.IsBrowserInitializedChanged += BrowserControl_IsBrowserInitializedChanged;
		Control.LoadError += BrowserControl_LoadError;
		Control.LoadingStateChanged += (o, args) => loadingStateChanged?.Invoke(args.IsLoading);
		Control.TitleChanged += (o, args) => titleChanged?.Invoke(args.Title);
	}

	...

	public void Find(string term, bool isInitial, bool caseSensitive, bool forward = true)
	{
		Control.Find(0, term, forward, caseSensitive, !isInitial);
	}

	public void NavigateBackwards()
	{
		Control.BrowserCore.GoBack();
	}

	...

	private void BrowserControl_IsBrowserInitializedChanged(object sender, EventArgs e)
	{
		if (Control.IsBrowserInitialized)
		{
			Control.BrowserCore.GetHost().SetFocus(true);
		}
	}

	private void BrowserControl_LoadError(object sender, LoadErrorEventArgs e)
	{
		loadFailed?.Invoke((int) e.ErrorCode, e.ErrorText, e.FailedUrl);
	}
}
```
Now regarding the handlers which don't exist for `ChromiumHostControl`: How exactly do I need to turn the handler methods into events? It turned out that I can't quite get my head around it unfortunately. So we need e.g. that the `CefSharpHostControl` is able to handle dialogs. Do I thus need to add the API of `IDialogHandler` to our `ICefSharpControl` like shown below? And how will our custom `ChromiumHostControl` know that it shouldn't forward the events to its parent `CefSharpBrowserControl`?

```
// IChromiumWebBrowserEx in your example
interface ICefSharpControl : IChromiumWebBrowserBase, IWin32Window, IComponent, ISynchronizeInvoke
{
	...

	bool OnFileDialog(IWebBrowser chromiumWebBrowser, IBrowser browser, CefFileDialogMode mode, CefFileDialogFlags flags, string title, string defaultFilePath, List<string> acceptFilters, int selectedAcceptFilter, IFileDialogCallback callback);
}

// ChromiumWebBrowserEx in your example
class CefSharpBrowserControl : ChromiumWebBrowser, ICefSharpControl
{
	public CefSharpBrowserControl(string url) : base(url)
	{
	}
}

// ChromiumHostControlEx in your example
class CefSharpHostControl : ChromiumHostControl, ICefSharpControl
{
	public bool OnFileDialog(IWebBrowser chromiumWebBrowser, IBrowser browser, CefFileDialogMode mode, CefFileDialogFlags flags, string title, string defaultFilePath, List<string> acceptFilters, int selectedAcceptFilter, IFileDialogCallback callback)
	{
		// What to do here?
	}

	public CefSharpHostControl(string url)
	{
	}
}
```

**Comment by amaitland** [comment]
> Now regarding the handlers which don't exist for `ChromiumHostControl`: How exactly do I need to turn the handler methods into events?

Commit https://github.com/cefsharp/CefSharp.MinimalExample/commit/34650112db2f7f1a6e030e0c4b2846cf331630ae added a basic example to the `MinimalExample`.

The key parts

- https://github.com/cefsharp/CefSharp.MinimalExample/commit/34650112db2f7f1a6e030e0c4b2846cf331630ae#diff-4eddd5e55540eaade9e3ffa46785402306a9eb4a98c46baaf71904a87ae56d33
- https://github.com/cefsharp/CefSharp.MinimalExample/commit/34650112db2f7f1a6e030e0c4b2846cf331630ae#diff-54294c2b4baac358617c5fa47fb27319d0a9819798c301f51823f81f711db2c0
- https://github.com/cefsharp/CefSharp.MinimalExample/commit/34650112db2f7f1a6e030e0c4b2846cf331630ae#diff-6e4d5ea533ed7108e6bb21e0fde5a0d7816987945c557900904aaedf05ab6864


It's basically:

- Add event args class
- Add the event to the common interface
- Add the event and a method to your `ChromiumHostControl` and `ChromiumWebBrowser` instances (copy and paste stuff)
  - The method simply fires the event
- Add a handler implementation that gets the relevant control instance and calls the method.

Starting at  https://github.com/cefsharp/CefSharp.MinimalExample/commit/34650112db2f7f1a6e030e0c4b2846cf331630ae#diff-6e4d5ea533ed7108e6bb21e0fde5a0d7816987945c557900904aaedf05ab6864  is an actual example.

**Comment by amaitland** [comment]
A `PR` adding some more events to the actual `CefSharp` implementation would be welcome.

**Comment by dbuechel** [comment]
Excellent, thanks a lot for the instructions @amaitland, it's now clear to me what I need to do.

>A PR adding some more events to the actual CefSharp implementation would be welcome.

I hope very much that I can collaborate with that once I've terminated the work on this issue, though I'd first need to attempt to clone and build CefSharp locally.

**Comment by dbuechel** [comment]
Okay, I've made some progress and was able to successfully change the implementation for a few handlers thus far. I however just realized that I haven't yet implemented the following three events which `ChromiumWebBrowser` provides but `ChromiumHostControl` doesn't:

```
interface ICefSharpControl : IChromiumWebBrowserBase, IWin32Window, IComponent, ISynchronizeInvoke
{
	event EventHandler<AddressChangedEventArgs> AddressChanged;
	event EventHandler IsBrowserInitializedChanged;
	event EventHandler<TitleChangedEventArgs> TitleChanged;
}
```

@amaitland How would I go about implementing these (and potentially other) events for our specialization of `ChromiumHostControl`?

**Comment by amaitland** [comment]
> I however just realized that I haven't yet implemented the following three events which ChromiumWebBrowser provides but ChromiumHostControl doesn't:

Both ChromiumWebBrowser and ChromiumHostControl implement those events in version 97.

In version 98 a new interface has been added 
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.WinForms/IWinFormsChromiumWebBrowser.cs

**Comment by dbuechel** [comment]
> Both ChromiumWebBrowser and ChromiumHostControl implement those events in version 97.

Yes, you're absolutely right, I didn't realize that even though I already was using version 97.1.1. The events didn't fire for the specialization of `ChromiumHostControl` and thus I thought there might be something missing.

> In version 98 a new interface has been added
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.WinForms/IWinFormsChromiumWebBrowser.cs

Perfect, thanks a lot, I updated to version 98, got rid of the three events in `ICefSharpControl` and am now using the new interface. But unfortunately the problem remains that the three events don't fire for popups using the `ChromiumHostControl` specialization, they fire only for the first (main) window with the `ChromiumWebBrowser` specialization. Could it be that these events aren't correctly triggered for `ChromiumHostControl` instances within CefSharp?

**Comment by amaitland** [comment]
> Could it be that these events aren't correctly triggered for `ChromiumHostControl` instances within CefSharp?

If you are using a custom `LoadHandler` or ``DisplayHandler` then make sure you use the `WinForms` specific implementations as a base and make sure to call the base methods if you override any of them. The events won't be called  otherwise.

https://github.com/cefsharp/CefSharp/blob/cefsharp/98/CefSharp.WinForms/Handler/LoadHandler.cs
https://github.com/cefsharp/CefSharp/blob/cefsharp/98/CefSharp.WinForms/Handler/DisplayHandler.cs

**Comment by dbuechel** [comment]
The parent-child relationship for popups should now work as expected. @wolfgang-pfalzgraf @uhensler The new functionality can be tested in the latest beta build: https://sebdev-let.ethz.ch/api/buildjobs/8tkr1xr5rh1fjmhf/artifacts/SEB_3.4.0.420_SetupBundle.exe

**Comment by mbaddar** [comment]
Do you happen to have a Mac build for 3.4.0 Beta? Thanks a lot

**Comment by dbuechel** [comment]
Mac builds etc. are over at the macOS / iOS repository, see https://github.com/SafeExamBrowser/seb-mac

**Comment by danschlet** [comment]
There is no version 3.4 for Mac yet, the latest stable version 3.1 will be released later this week. On the above mentioned link, you can get a release candidate version.

**Comment by mbaddar** [comment]
Great. Thanks a lot

**Comment by wolfgang-pfalzgraf** [comment]
That's gerat. Thank you.

**Comment by dbuechel** [comment]
A fix for the issue is now available in version 3.4.0.

**Comment by uhensler** [comment]
We have added the mentioned code of the University of Zurich to the public release of OpenOlat. This allows the use of the SEB JavaScript API.

This code does not solve the problem of opening a new window/tab on SEB for macOS. The JavaScript variable `window` is always `null`, so there is an exception. This seems to be and bug in the SEB. Can you please look into this?

In the GUI this leads to a popup with the message "Quit Safe Exam Browser: Are you sure you want to quit Safe Exam Browser?".

**Comment by dbuechel** [comment]
> This code does not solve the problem of opening a new window/tab on SEB for macOS. The JavaScript variable window is always null, so there is an exception. This seems to be and bug in the SEB. Can you please look into this?

If this is solely a macOS / iOS issue, then you'd need to create a new issue in the respective repository: https://github.com/SafeExamBrowser/seb-mac

**Comment by uhensler** [comment]
see https://github.com/SafeExamBrowser/seb-mac/issues/230
