### ISSUE TITLE
[Help] Student not able to use SEB, log included

### ISSUE THREAD

**Issue by jeroenhens** [SafeExamBrowser/seb-win-refactoring#245]
[2021-11-12_10h08m25s_Runtime.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/7538581/2021-11-12_10h08m25s_Runtime.log)

I have a student who can't use SEB. SEB is properly installed, but it keeps giving errors. I have the log included, she is using a laptop with no external screen, but it seems like SEB doesn't like the monitor configuration?

Anybody with a solution? Thx in advance!

**Comment by dbuechel** [comment]
There seems to be an issue on their system which, in case that they are not attempting to cheat, might be resolved by repairing or rebuilding the WMI repository: https://www.thewindowsclub.com/how-to-repair-or-rebuild-the-wmi-repository-on-windows-10

To workaround this issue, you could enable the setting "Ignore errors when validating display configuration" in your configuration: https://safeexambrowser.org/windows/win_usermanual_en.html#SecurityPane. This however will have the side effect that the display check doesn't help anymore with suppressing the usage of VMs.
