### ISSUE TITLE
Environment Variable Expansion for Permitted Processes

### ISSUE THREAD

**Issue by simonrentzke** [SafeExamBrowser/seb-win-refactoring#25]
From: https://github.com/SafeExamBrowser/seb-win/issues/88

> **Is your feature request related to a problem? Please describe.**
> 
> Currently, permitted applications that are not installed in the system path must be specified with a full path, but for some of them (those installed in AppData, such as Zoom, Microsoft Teams, Webex and similar) the path changes according to the user who installed them.
> 
> However, the path could be specified using environment variables (such as %AppData% or %USERPROFILE%) that would allow to identify exactly that application that has permitted access.
> 

I can't seem to get this to work correctly and was wondering if version 3 should work similarly to version 2?

Thank you.

**Comment by dbuechel** [comment]
Might well be that I missed that one. I'll have a look at it and implement it for version 3.1, in case it is indeed missing.

**Comment by simonrentzke** [comment]
Apologies. It looks like it does work as expected.

I used the `%username%` env variable with path `c:\users\%username%\appdata` and it works as expected. 

Thank you!
