### ISSUE TITLE
Cannot type @ in login dialog

### ISSUE THREAD

**Issue by SebastianZiegler** [SafeExamBrowser/seb-win-refactoring#26]
Hello,

some of our students reported, that after starting SEB and login into moodle, they cannot login, if they password contains the '@'.

Greetings

**Comment by dbuechel** [comment]
I can't reproduce your issue, I can enter `@` without any issues (e.g. here [https://www.w3schools.com/Tags/att_input_type_password.asp](https://www.w3schools.com/Tags/att_input_type_password.asp)).

**Comment by danschlet** [comment]
That's likely some keyboard layout issue. Try to type @ into the username login field, what happens? Make sure the correct keyboard layout is selected. I hope those users are not using Windows 7? There we had some keyboard layout selection issues in the past (SEB 2.x), if I remember right selecting the correct keyboard layout in the Windows Control Panel helped (not only in the Windows Task Bar).

**Comment by dbuechel** [comment]
Any updates here?

**Comment by dbuechel** [comment]
Closed due to lack of feedback.
