### ISSUE TITLE
Predefined or Unantended Browser exam key and config key

### ISSUE THREAD

**Issue by smasaae** [SafeExamBrowser/seb-win-refactoring#264]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when my student use different OS like Windows and Mac, the browser exam key and config key always changing when i run *.seb from windows to mac os,  

**Describe the solution you'd like**
Predefined or Unantended Browser exam key and config key in exam menu, we choose it generated automaticly or manually (eg. we put some string and then there button to generate both key)

**Describe alternatives you've considered**
A Patch for windows or mac to use Predefined or Unantended browser exam key and config key and exported as *.seb.

**Comment by dbuechel** [comment]
The browser exam key indeed is specific to each operating system and SEB version. The configuration key however should be equal on all operating systems and SEB versions, as long as you use the same configuration. So what you're requesting actually already exists, i.e. with the functionality of the configuration key, only that you can't choose the actual value of the configuration key.

Further details and the exact specification of BEK and CK can be found on our website: https://safeexambrowser.org/developer/seb-config-key.html

**Comment by smasaae** [comment]
its hard to comply, cause our student have to various OS version both windows (from win 7 to 10) and Mac, each install seb on them sometimes need extra skill, cause facing different difficulties, its quite time consuming for our team to solve, may be patch injection for  fixed BEK and CK is best solution.

**Comment by dbuechel** [comment]
@smasaae But again, if you use the CK then it doesn't matter which operating system nor which SEB version your students are using, the only thing which will be verified is whether they're using the correct SEB configuration.

**Comment by danschlet** [comment]
@smasaae The Config Key was designed with the intension that the exam system automatically calculates it together with the according SEB settings it would generate automatically server-side. An example is the SEB-Moodle deeper integration available in Moodle 3.9 or newer.

If I understood your post correctly, if you have students with special needs and you need a modified configuration for them, ideally the exam system would offer such an option to use individual settings for specific students. It's planed that we will provide that with SEB Server sometimes in the future. Moodle doesn't have such an option yet, but one solution would be if Moodle would accept additional, manually generated Config Keys for a specific quiz (similar as it currently accepts multiple BEKs). You should forward such feature requests to the providers of your exam solution.

**Comment by RahulKrishna05** [comment]
Does anyone know how to extract the Browser Exam Key? Only the SEB 3.10.2 patch will work for my setup, so I would really appreciate any help with this specific version.
