### ISSUE TITLE
SEB overrides "Accept-Language" header for all requests

### ISSUE THREAD

**Issue by Gendie** [SafeExamBrowser/seb-win-refactoring#27]
**Describe the Bug**
When a website is running inside SEB. Foreach xhr request. Header "Accept-Language" is overridden to "en-US,en;q=0.9", Even if I set this header using javascript to another value like "ar-EG" 

**Steps to Reproduce**
1. Create a simple app that sends xhr request.
2. Set "Accept-Language" header to "ar-EG" for the request. `XMLHttpRequest.setRequestHeader(header, value)`
3. Inspect the sent request headers

**Actual Behaviour**
The "Accept-Language" header is "en-US,en;q=0.9"

**Expected Behavior**
The "Accept-Language" header should be "ar-EG"

**Version Information**
 - OS: Windows 10 Professional
 - SEB-Version 3.0.1

**Comment by dbuechel** [comment]
Could you please verify whether the issue also happens in the CEF sample application? You can find the binaries here: http://opensource.spotify.com/cefbuilds/index.html

**Comment by dbuechel** [comment]
Any updates here? If CEF overrides the header, there's not much we can do...

**Comment by dbuechel** [comment]
@Gendie: Could you verify the issue raised above?

**Comment by dbuechel** [comment]
Closed due to lack of feedback.
