### ISSUE TITLE
SEB (Moodle manual configuration) doesn't block ctrl alt del in windows to prevent user logout

### ISSUE THREAD

**Issue by nicolasflasque** [SafeExamBrowser/seb-win-refactoring#282]
**IMPORTANT**
Please _always_ consult the documentation first before creating a bug report!
https://safeexambrowser.org/windows/win_usermanual_en.html

**Describe the Bug**
From a moodle quiz (moodle 3.9), configured to force SEB, with manual configuration : during the test under the SEB environment, the user can logout using ctrl+alt+del and choose 'logout' (disconnect from user session'), then do what he wants, then go back to the Quiz with SEB with no penalty, apart from the countdown still running.

**Steps to Reproduce**
1. Configure a quiz with SEB, manual settings
2. start the test
3. press ctrl alt del and logout
4. login to user account
5. continue the test with seb

**Expected Behavior**
Ctrl alt del should not allow that, as stated in the documentation

**Screenshots**

**Version Information**
 - OS: Windows 10 Enterprise 2016 LTSB
 - SEB-Version 3.3.1

**Additional Context**

**Comment by dbuechel** [comment]
There should be a red lock screen once SEB detects that the user intended to change the user account. If you want to suppress the options invoked by CTRL+ALT+DEL, then you'd need to use the SEB Service (which we do not recommend for BYOD): https://safeexambrowser.org/windows/win_usermanual_en.html#SecurityPane.
