### ISSUE TITLE
SEB with Moodle in LTI-mode

### ISSUE THREAD

**Issue by Cordina90** [SafeExamBrowser/seb-win-refactoring#285]
I have set up an Moodle environment which my student can access through our internal learning environment using LTI (both LTI 1.1 and 2.0 are available).
This way my students can access Moodle courses, assignments and tests, which work perfectly, until I set using SEB as a requirement for attempting a test.
From Moodle the Safe Exam Browser loads fine, but then requires student to login using a username and password for Moodle, which they don't have.
This issue was presented before: [https://sourceforge.net/p/seb/discussion/844844/thread/3a2516dc14/?limit=25](url), but I cannot find if this was actually solved.

**Comment by danschlet** [comment]
The current SEB integration in Moodle is not compatible with Moodle being embedded in LTI. We'll have a look if we can make this work with the improvement being currently implemented, see [this Moodle tracker issue](https://tracker.moodle.org/browse/MDL-72188). As this is a Moodle issue, it should be discussed there.
