### ISSUE TITLE
Unable to Open Office Documents due to Protected View

### ISSUE THREAD

**Issue by UncleRaymondo** [SafeExamBrowser/seb-win-refactoring#30]
Unable to Open Office Documents due to Protected View

**IMPORTANT**
Please _always_ consult the documentation first before creating an issue!
https://safeexambrowser.org/windows/win_usermanual_en.html

### Description

Although the SEB 3.0.1 Utility opens the Office Applications fine, it cannot open the documents due to what our testing shows as Protected View enabled.

When you try to open a file (a PowerPoint slide deck in this case), you receive the following similar error:

![image](https://user-images.githubusercontent.com/5147133/93053902-d6b13680-f6ab-11ea-80ad-d33091ac8a29.png)

Our testing shows that if Protected View is disabled, then this seems to work, however this is a very bad workaround and counter-productive, especially to a Cyber Security unit.

Can you please advise of a better workaround to resolve this issue rather than telling 200 students to disable Protected View during their weekly quizzes and exams?

Cheers,
Ray

### Environment & Version

~Computer description, e.g. manufacturer, device name, hardware specs etc.~

- [ ] Mac
- [x] Windows

OS-Version: Windows 10 Build 2004, Office 2019
SEB-Version: 3.0.1 for Windows

### Steps to Reproduce

1. Have office default with Protected View on which is by default
2. Inside SEB, click on a link to download a PowerPoint file from a URL that is permitted within SEB as an authorised URL
3. Get the above error

> ***Information:** 
Please replace all placeholders (~PLACEHOLDER~) and version numbers according to your situation. The more detailed information you provide, the easier it will be for us to detect and reliably fix the issue. Feel free to delete this comment before submitting the issue report...*

**Comment by dbuechel** [comment]
I am able to reproduce the issue, I however doubt that there is much we can do to resolve it. There seems to be an incompatibility with the kiosk mode Create New Desktop of SEB. I was however able to open documents with Protected View when using kiosk mode Disable Explorer Shell, so you could try that as a workaround: https://safeexambrowser.org/windows/win_usermanual_en.html#SecurityPane

**Comment by dbuechel** [comment]
@UncleRaymondo Any further help needed on this issue?

**Comment by UncleRaymondo** [comment]
Hi @dbuechel, apologies I'm planning on testing this in the coming days. Will report back soon :)

**Comment by dbuechel** [comment]
Closed due to lack of feedback.
