### ISSUE TITLE
SEB3 fails to start if user's profile path contains Cyrillic characters 

### ISSUE THREAD

**Issue by PKGeorgiev** [SafeExamBrowser/seb-win-refactoring#31]
**IMPORTANT**
Please _always_ consult the documentation first before creating a bug report!
https://safeexambrowser.org/windows/win_usermanual_en.html

**Describe the Bug**
If user's profile path contains Cyrillic characters and Windows' system locale is set to "English" (windows-1252), SEB fails to start with an error: "Illegal characters in path".

**Steps to Reproduce**
1. Create a user account with Cyrillic name, for example Тест
2. Change your system locale in Windows to "English - United states" (windows 1252)
3. Restart the computer
4. Login again and try to start SEB

**Expected Behavior**
SEB3 should start regardless of language and system's locale.

**Screenshots**
![image](https://user-images.githubusercontent.com/9254467/93919069-e9fc7b80-fd15-11ea-9c76-4723a82169ee.png)

**Version Information**
 - OS: Windows 10 Professional, Version 1809, x64
 - SEB-Version SEB 3.0.1.163, x64

**Additional Context**
When I go to %appdata%\SafeExamBrowser\logs, only the runtime log gets created.

If I change system's locale to "Bulgarian" (windows-1251), SEB starts normally. But this is inconvenient since there are more than 200 PCs to configure, not including student's home computers.

**Comment by dbuechel** [comment]
Thanks for your detailed report. I am however unsure whether we can do anything to fix the issue, it appears like Windows / .NET require the system locale to be one that contains Cyrillic characters in order to allow those characters in a path:

`Directory.CreateDirectory(directory);`

This is the statement which fails, and there isn't much we can change here, we need to create the directory for log files if it doesn't exist. It really appears to be the case that .NET doesn't allow Cyrillic characters in the path if the system locale is e.g. English.

**Comment by PKGeorgiev** [comment]
That's strange. .NET is unicode compliant and therefore should not rely on system's locale (system locale affects only non-unicode aware programs). I suppose a conversion from ASCII to Unicode occurs that causes the problem. I remember that at least one log file was created. So the locale should not be a problem.
Give me some time to get used to SEB's code and perform some tests if that helps. I'll give you feedback soon.

**Comment by dbuechel** [comment]
Of course, that would be great. Let me know if I can help in any way.

**Comment by PKGeorgiev** [comment]
I've tested SEB with a a user that was typed in Cyrillic on my laptop. I can confirm SEB fails to start.
I've managed to clone latest source and compile SEB project. Interestingly with compiled version it works with paths that contain Cyrillic chars. 
It seems the issue is related only to version 3.0.1.163.

**Comment by dbuechel** [comment]
That would be very strange, as there haven't been any changes in that part of the code. Are you sure that the log directory did not exist when running the local build?

**Comment by PKGeorgiev** [comment]
Let me perform the test again. I'll post the results here.

**Comment by dbuechel** [comment]
Any updates here?

**Comment by dbuechel** [comment]
Closed due to lack of feedback.
