### ISSUE TITLE
Windows Configuration Editor contains outdated MacOS list (Unhandled exception...Value of '9' is not valid for 'SelectedIndex') 

### ISSUE THREAD

**Issue by jeroenhabets** [SafeExamBrowser/seb-win-refactoring#310]
**Unhandled exception error when opening .seb file with MacOS > 10.14 Mojave**

<img width="741" alt="image" src="https://user-images.githubusercontent.com/1929535/147461421-798b94c4-e624-4dff-933a-3af498e6319a.png">

I believe it's caused by Windows Configuration Editor containing outdated MacOS list as it stops at 10.14 Mojave while the MacOS goes all the way to 12 Monterey.

- Open .seb file on MacOS and select "11 Big Sur" as minimum version
- Save .seb file
- Open .seb file on Windows (tested using beta)

Expected: open without error
Actual: Unhandled exception...Value of '9' is not valid for 'SelectedIndex'

P.S. The code reports the exception on line 809 while I believe [SebWindowsConfigForm.cs line 808](https://github.com/SafeExamBrowser/seb-win-refactoring/blob/0abbef749e42d474be96ba4f2c860c47d7614c63/SebWindowsConfig/SebWindowsConfigForm.cs#L808) throws it.

And [SebWindowsConfigGUIManagement.cs](https://github.com/SafeExamBrowser/seb-win-refactoring/blob/0abbef749e42d474be96ba4f2c860c47d7614c63/SebWindowsConfig/SebWindowsConfigGUIManagement.cs#L381) does indeed stop at Mojave.

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/1929535/147461235-da33f337-209b-4184-981e-b1086018b395.png">

**Version Information**
- MacOS: 12 Monterey, SEB-Version: mac3.2pre5_3632
 - Windows: Win10 - SEB-Version: the last one shared in [#84](https://github.com/SafeExamBrowser/seb-win-refactoring/issues/84#issuecomment-997813289)

**Comment by dbuechel** [comment]
Thanks for the report, we'll see that we can fix this for the upcoming version 3.3.2.

**Comment by dbuechel** [comment]
@danschlet Which values would I need to add to that dropdown in the configuration tool?

**Comment by jeroenhabets** [comment]
@dbuechel (@danschlet) I couldn't find the values on seb-mac `master` but `3.2` branch has (hope that helps):

[SEBUIUserDefaultsController.m line 211](https://github.com/SafeExamBrowser/seb-mac/blob/91b8bd5be5060cd91ce0da414bdd676637bbad0f/Classes/Preferences/SEBUIUserDefaultsController.m#L211) 

```    return [NSArray arrayWithObjects:
            NSLocalizedString(@"10.7 (this SEB: 10.11)", nil),
            NSLocalizedString(@"10.8 (this SEB: 10.11)", nil),
            NSLocalizedString(@"10.9 (this SEB: 10.11)", nil),
            NSLocalizedString(@"10.10 (this SEB: 10.11)", nil),
            NSLocalizedString(@"10.11 El Capitan", nil),
            NSLocalizedString(@"10.12 Sierra", nil),
            NSLocalizedString(@"10.13 High Sierra", nil),
            NSLocalizedString(@"10.14 Mojave", nil),
            NSLocalizedString(@"10.15 Catalina", nil),
            NSLocalizedString(@"11 Big Sur", nil),
            NSLocalizedString(@"12 Monterey", nil),
            nil];

**Comment by dbuechel** [comment]
Ah great, that appears to be what I need, yes. Thanks for the help, @jeroenhabets.

**Comment by dbuechel** [comment]
Okay, I have updated the list in the configuration tool. @jeroenhabets You can test the change in the latest beta build if you wish: https://sebdev-let.ethz.ch/project/AppVeyor/seb-win-refactoring/builds/435

**Comment by jeroenhabets** [comment]
@dbuechel Thanks! I no longer get the error I reported :).
