### ISSUE TITLE
SafeBrowser OS - builtin on live-Linux OS

### ISSUE THREAD

**Issue by danielpm307** [SafeExamBrowser/seb-win-refactoring#312]
**Is your feature request related to a problem? Please describe.**
yes, the system conflict problem or addition driver and windows variables that users have
**Describe the solution you'd like**
the safe browser needs to be independent user settings of OS.

**Describe alternatives you've considered**
SafeBrowser is builtin on live-Linux OS.basic desktop with auto-update in the primary and stable workspace for users.

**Additional context**
- I see other tools like mining software or recovery or system repair software use Linux base OS to perform tasks. 
- Using lightweight Linux is a good solution for schools or universities to write it to a pen drive, and students use it as a key to entering the exams.
- There is no conflict with windows update or package or setting that occurs error. 
- Safe browser has high access to users' activity.

**Comment by dbuechel** [comment]
Thanks for your feature request. I'm however afraid I don't quite understand the core intention of the request: Would you like to suggest a Linux version of SEB or that SEB itself comes with a Linux distribution which users could install on a memory stick?

**Comment by danielpm307** [comment]
Thanks for the answer. 
My goal is to live OS using SEB.
 In my experience, Windows has the license for use and uses many resources (not recommended for some students ). Mac OS needs apple hardware. Installing SEB on Linux may have problems. For example, students can manipulate Linux for Backdoor security. But my idea is about a Linux version without superuser access and configuring it by the SEB team to change usage just for the SEB browser. It's like a student OS for the exam. For ease of use, there is no need to install it on a PC, and it can boot on live. It's like a keycard for students.
Manipulating Linux kernel and files by the SEB team is necessary because students have full access to backdoor security without that. 

advantage of this idea :

- Linux uses low resource
- there is no conflict with OS (The Linux OS prepared for stable using SEB)
- universities can use that for studentID or ExamID for online exams. (it can change to protocol)
-  its plug and play method and students can use that on any computer. 
- some online exams like Duolingo or other certificates can use that with their options
- You isolate the OS, and you can verify that OS is valid for using SEB. 
- in the future can develop it to Be a Student OS. 
- you can access more than the windows in it to check security. 
- its independent of hardware students use. its compatibility with all computers. (some scripts do not work in windows 7 )
-students no need to install or anything. Just plug a pen drive and click on SEBburner.exe to write on Pendrive.

I hope to explain it in detail, but I am glad to answer if you have other questions about this idea. 

Have a good year. 🎄

**Comment by michaelhq** [comment]
Hello dany

If I may make a recommendation on this. There is already a system, but without SEB.

Have a look here: https://www.digitale-nachhaltigkeit.unibe.ch/services_and_support/lernstick/index_eng.html

Best regards
Michael

**Comment by dbuechel** [comment]
Thanks for the clarification, @danielpm307. In that case I'd need to close this issue for now, as it definitely is out of scope for us and as @michaelhq (who I think is part of the Lernstick /  Campla team?) mentioned there already is a product which more or less delivers what you're looking for.

**Comment by ashwai6998** [comment]
> Thanks for your feature request. I'm however afraid I don't quite understand the core intention of the request: Would you like to suggest a Linux version of SEB or that SEB itself comes with a Linux distribution which users could install on a memory stick?

SEB in linux

**Comment by nimizu** [comment]
@DanialPahlavan  I wish for it happen. Instead of installing bloatware in system we can just use the live usb to give the exam so simple.
