### ISSUE TITLE
Microsoft SSO window opens empty

### ISSUE THREAD

**Issue by AnjanaSenanayake** [SafeExamBrowser/seb-win-refactoring#316]
**Describe the Bug**
The Microsoft SSO window for login opens as an empty window in the Single Page Application I am trying to login using SEB.

**Steps to Reproduce**
1. Set the start URL in SEB configuration tool to the following: https://oat-candidate-tool-qa.azureedge.net/
2. Save configuration
3. Launch SEB
4. Click login with Microsoft SSO
5. Opens an empty window

**Expected Behavior**
The Microsoft SSO window should be opened where we can provide the credentials for a user.

**Version Information**
 - OS: Windows 10 Professional
 - SEB-Version 3.3.1.388

**Comment by dbuechel** [comment]
Thanks for your report, we'll have a look at it.

**Comment by dbuechel** [comment]
The underlying issue appears to be #240. I'll thus close this for now, please subscribe to #240 and report further findings or questions there.
