### ISSUE TITLE
SEB Browser does not start on Kiosk Laptop

### ISSUE THREAD

**Issue by Anmthr** [SafeExamBrowser/seb-win-refactoring#328]
**IMPORTANT**
Please _always_ consult the documentation first before creating a bug report!
https://safeexambrowser.org/windows/win_usermanual_en.html

**Describe the Bug**
We have managed devices that are being used by the people of this city. This managed device has a Kiosk profile managed by Intune. This is for security reasons. Now it's needed to make sure SEB is also available on these devices. The install process happends with no issues. When we start the SEB application everything seems to be working untill the loading screen reaches the start of "Initializing Browser". This crashes the application. We see the following error on screen "SEB failed to start a new session! Please consult the log files for more information". When I change the configuration too start SEB without browser everything starts up normal. Issue seems to be starting the browser. The Browser log file gives the following error "[0113/091828.594:FATAL:gpu_data_manager_impl_private.cc(414)] GPU process isn't usable. Goodbye.". We have tried many different configurations for the SEB application, but nothing seems to be working. What is the best solution in this case?

**Steps to Reproduce**
1. Go to 'I explained it in the description'

**Expected Behavior**
We want the application to start the browser, because people have to go to a certain website.

**Screenshots**

**Version Information**
 - OS: Windows 10 21H1
 - SEB-Version [3.3.1]

**Additional Context**

**Comment by Anmthr** [comment]
Is there a possibilty to turn of hardware acceleration? Maybe this is causing the issue.

**Comment by dbuechel** [comment]
This looks like a configuration issue with your devices, e.g. did you make sure that you have all the required graphics-related drivers installed an up to date?

**Comment by Anmthr** [comment]
I don't it's related because when I log in outside of the kiosk mode the application seems te working fine. Is it possible to turn off hardware acceleration?

**Comment by dbuechel** [comment]
No, there are no such configuration options at the moment, at least within / for SEB. You could try the CEF sample application in your kiosk profile and see whether you can get it to work: https://cef-builds.spotifycdn.com/index.html#windows64

As it appears to be an issue with the browser engine, you might be able to get a solution in the CEF forum: https://magpcss.org/ceforum/

**Comment by dbuechel** [comment]
You don't need to install the CEF sample application, you can simply attempt to run it in your kiosk profile to check whether the same issue arises there as well. Do you happen to have a stack trace for the error in the Event Viewer?

I assume you made sure to install the required runtime dependencies as specified in the release notes or the [readme](https://github.com/SafeExamBrowser/seb-win-refactoring#readme)? Without them, the browser won't work and crash, though it normally isn't with that exception if I remember correctly.

**Comment by Anmthr** [comment]
I fixed the issue. Thanks for the advice!

**Comment by Mitchelrsd88** [comment]
Hi,

Can you please share what you did to solve this?
I am facing the exact same issue!

Thanks in advance.

**Comment by Anmthr** [comment]
I found that applocker was blocking a few processes. I whitelisted the following processes:
RTKAUDUSERVICE64.EXE
SAFEEXAMBROWSER.CLIENT.EXE
CEFSHARP.BROWSERSUBPROCESS.EXE

**Comment by Mitchelrsd88** [comment]
Thanks!
I'll look into it.

**Comment by dbuechel** [comment]
These two processes are indeed part of SEB and need to be able to run without interference:
```
SAFEEXAMBROWSER.CLIENT.EXE
CEFSHARP.BROWSERSUBPROCESS.EXE
```
The following process appears to belong to some audio functionality from Realtek and is not part of SEB (though it certainly may be that the process is required for audio reproduction):
```
RTKAUDUSERVICE64.EXE
```

**Comment by Mitchelrsd88** [comment]
I can confirm that is indeed the solution to this problem.
Thanks!

**Comment by Anmthr** [comment]
I deleted my previous comment because it had some incorrect information in it.  The following information is correct:
Another note, you also have to add the following files tot he Intune Kiosk Profile:
C:\Program Files\SafeExamBrowser\Application\CefSharp.BrowserSubprocess.exe

C:\Program Files\SafeExamBrowser\Application\libcef.dll

I attach these files to the following AUMID:
{6D809377-6AF0-444B-8957-A3773F02200E}\SafeExamBrowser\Application\SafeExamBrowser.exe"

The GUID might be different in your situation.
