### ISSUE TITLE
Navigation buttons for web pages

### ISSUE THREAD

**Issue by mattimagg** [SafeExamBrowser/seb-win-refactoring#329]
**The feature request**
I would like to suggest that SEB provides a way to navigate back to previous page and forward to next page within a browser window that has been opened as a URL resource.

**An example**
Let‘s say that a test includes a URL resource for cnn.com. What the candidates should be able to do is click any article and then use some sort of a back key or button to go back to the original page.

**Why is this important?**
Being able to navigate back and forth saves a great deal of time, because if candidates need to go to a previous page, they now have to close the browser window and open it again. This can become very tedious and time-consuming.

**Implementation**
To implement this, SEB could add navigation buttons at the top of the web page.

**Comment by dbuechel** [comment]
This feature already exists, but it unfortunately is (at the moment) a bit tricky to activate: You'll first have to enable the browser window toolbar (see https://safeexambrowser.org/windows/win_usermanual_en.html#AppearancePane), then you'll need to allow navigating in the main and / or additional window (see https://safeexambrowser.org/windows/win_usermanual_en.html#BrowserPane).

**Comment by mattimagg** [comment]
Hi
Thanks for the swift response. Can we configure settings automatically for
all candidates? Are there instructions for that on your website?

fim., 13. jan. 2022 kl. 10:52 skrifaði Damian Büchel <
***@***.***>:

**Comment by dbuechel** [comment]
Yes, there is information on our website, e.g. https://safeexambrowser.org/developer/seb-integration.html. You'd normally place a configuration file on a web server or distribute it directly to the candidates. You could also use SEB-Server which allows not only to change the configuration for an exam dynamically but also to monitor an exam in real time, given you're using Moodle or EdX as LMS.

**Comment by mattimagg** [comment]
Since we (University of Iceland) are using Inspera, wouldn't it be proper
to ask the people at Inspera to change the config file according to our
wishes?

fim., 13. jan. 2022 kl. 14:14 skrifaði Damian Büchel <
***@***.***>:

**Comment by dbuechel** [comment]
Yes absolutely, that is correct. Sorry, I wasn't aware that you're using Inspera.

**Comment by mattimagg** [comment]
But what about trying out settings on my own computer for testing? Can I do
that? I tried changing the items you discussed:

[image: image.png]
[image: image.png]

But I don't get Back/Forward buttons.


fös., 14. jan. 2022 kl. 09:02 skrifaði Damian Büchel <
***@***.***>:

**Comment by dbuechel** [comment]
Yes, you should be able to test these settings locally. Just be aware of the configuration mechanisms of SEB as described in the documentation: https://safeexambrowser.org/windows/win_usermanual_en.html#ConfigFilePane

**Comment by dbuechel** [comment]
Also, if you are using Inspera SEB, then I cannot say whether they have changed or restricted the configuration possibilities.

**Comment by mattimagg** [comment]
It seems that my settings are not used. Is it possible that the config file
from Inspera has priority?

My settings file is located here. Where can I find the SEB file that
Inspera manages?

[image: image.png]

fös., 14. jan. 2022 kl. 10:33 skrifaði Damian Büchel <
***@***.***>:

**Comment by mattimagg** [comment]
I see. Thank you very much, I will try that.

fös., 14. jan. 2022 kl. 11:32 skrifaði Daniel R. Schneider <
***@***.***>:

**Comment by mattimagg** [comment]
One last thing: Is there a potential security risk in using back/forward
navigation for external resources?

fös., 14. jan. 2022 kl. 11:32 skrifaði Daniel R. Schneider <
***@***.***>:

**Comment by mattimagg** [comment]
Many thanks, gentlemen, for your excellent responses.

fös., 14. jan. 2022 kl. 12:25 skrifaði Damian Büchel <
***@***.***>:
