### ISSUE TITLE
Invalid class error while starting SEB

### ISSUE THREAD

**Issue by ramonavic** [SafeExamBrowser/seb-win-refactoring#33]
**Describe the Bug**
Invalid class error 

![2020-09-24T12_03_14 443Z-support-attachment-3185f9f030a94e6a4054ef0785006f5fded502eed5066d45a2afdb7b84d1e7e5](https://user-images.githubusercontent.com/18659991/94167728-230b2c00-fe8d-11ea-97a6-78b864369c4e.png)

**Expected Behavior**
It should open the exam and lock the student. I can share our config if necessary.

**Version Information**
 - OS: Windows 10
 - SEB-Version: Unknown, I have asked the student this

**Additional Context**
Hi guys, 

A student has reported the following error while using SEB on Windows 10. We are not a school, but a platform so therefore we are still in contact with the student in order to understand what happened. So far only one student has reported this.

I have asked if the student has the most recent version of SEB, and can ask to fetch the logs, although that will take time. Let me know if I can gather any additional information for you!

Kind regards, 

Ramon

**Comment by dbuechel** [comment]
Your WMI repository is most likely corrupted. Try repairing it like described here: https://www.thewindowsclub.com/how-to-repair-or-rebuild-the-wmi-repository-on-windows-10/

**Comment by ramonavic** [comment]
Thanks for your help Damian! I will let the student know

**Comment by dbuechel** [comment]
@ramonavic were you able to resolve the issue?

**Comment by ramonavic** [comment]
@dbuechel, we have given the advice to the student but haven't heard back from him. We have also suggested to use an alternative device in case of any short term exams. I think we can close the issue here now. Thank you for your help! I will get back to the issue if the problem has persisted after fixing the WMI repo.

**Comment by heartar2** [comment]
i got the same fatal error but it's not invalid class. i was gonna take an exam as a student. they provided links to download safe exam browser and the config file (.seb file extension). after installing, i should be able to start the exam by opening the .seb file with safeexambrowser.exe (just as they told me to). but this error window appeared instead.
![image](https://user-images.githubusercontent.com/79237890/108298678-eccda080-71cf-11eb-8c2e-408846251961.png)

**Comment by asdfzxc3** [comment]
this is my first time installing safe exam browser and I got this fatal error, please help me solve this error, why did this happen?
![image](https://user-images.githubusercontent.com/79786998/109413871-3abd8200-79e2-11eb-81ba-3c5208660d02.png)

**Comment by dbuechel** [comment]
Please always open a new issue and don't post on an already closed one. Did you try the provided solution attempt from above? I haven't seen these particular error messages before, you might have some bigger issues on your machines, thus try to e.g. repair the .NET framework or install the latest Windows Updates.

**Comment by dii18** [comment]
it's my first time installing SEB but i got this kind of fatal error, please help me solve this problem
![error](https://user-images.githubusercontent.com/91555160/135121837-a2bface1-47f4-4c1f-8d89-42643845846e.png)

**Comment by matthiasgoossens** [comment]
> @ramonavic were you able to resolve the issue?

Not the original poster, but I had the exact same error and repairing the repository did fix it.

When verifying the repository it said "repository is consistent". Despite this message I still did the reset of the repository and that fixed the error.

When trying to reset I got an error about services blocking the reset but following these steps (https://visualplanet.org/blog/?p=274) I could perform the reset.

**Comment by dbuechel** [comment]
Excellent, thanks for the info, that is good to know!
