### ISSUE TITLE
SEB Browser JavaScript Error

### ISSUE THREAD

**Issue by Anmthr** [SafeExamBrowser/seb-win-refactoring#337]
**IMPORTANT**
Please _always_ consult the documentation first before creating a bug report!
https://safeexambrowser.org/windows/win_usermanual_en.html

**Describe the Bug**
The following website "https://minerva.optimumassessment.com/spa/assessment-login/#/SXD9 " works in Edge Chromium, however inside the SEB Browser it gives an Javascript error.

**Steps to Reproduce**
1. Go to 'the website mentoined above'
2. Click on 'Start Examen' in the Bottom right corner.
3. See error

**Expected Behavior**
The error should not come, a video should be playing. 

**Screenshots**
See attachments.

**Version Information**
 - OS: [e.g. Windows 10 Enterprise 21h1
 - SEB-Version. SEB 3.3.1

**Additional Context**
![error](https://user-images.githubusercontent.com/97663096/149928690-40ef86e9-d4d4-4748-b969-9afa7004b0a3.png)
[2022-01-18_12h16m51s_Browser.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/7888625/2022-01-18_12h16m51s_Browser.log)

**Comment by dbuechel** [comment]
As far as I can see, this is an video with a proprietary video codec. SEB 3.x does not support proprietary video codecs, you'd thus need to encode your video with a free, open-source codec like e.g. [WebM](https://en.wikipedia.org/wiki/WebM).

**Comment by Anmthr** [comment]
Thanks for the quick response. I know enough!

Van: Damian Büchel ***@***.***>
Verzonden: dinsdag 18 januari 2022 12:35
Aan: SafeExamBrowser/seb-win-refactoring ***@***.***>
CC: Mathoera, Arnold ***@***.***>; Manual ***@***.***>
Onderwerp: Re: [SafeExamBrowser/seb-win-refactoring] SEB Browser JavaScript Error (Issue #337)


As far as I can see, this is a video with a proprietary video codec. SEB 3.x does not support proprietary video codecs, you'd thus need to encode your video with a free, open-source codec like e.g. WebM<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FWebM&data=04%7C01%7Ca.mathoera%40utrecht.nl%7C477a89563b8a488f9d1508d9da768ba1%7Cb9ea87f7a2634e6898e15fad3547a805%7C0%7C0%7C637781024954654580%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Hpt1S4Fd4pnaBEaYvx6PU9IUuwthQWwvFOYgeNXh8h8%3D&reserved=0>.

-
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSafeExamBrowser%2Fseb-win-refactoring%2Fissues%2F337%23issuecomment-1015326021&data=04%7C01%7Ca.mathoera%40utrecht.nl%7C477a89563b8a488f9d1508d9da768ba1%7Cb9ea87f7a2634e6898e15fad3547a805%7C0%7C0%7C637781024954654580%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=sw6TY2PUJin8sfNwk0038l0gZWphpMP8NHHmK9k98iY%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXJDQ6HNVKD7WXU57I5GYSDUWVF5ZANCNFSM5MG5KQBQ&data=04%7C01%7Ca.mathoera%40utrecht.nl%7C477a89563b8a488f9d1508d9da768ba1%7Cb9ea87f7a2634e6898e15fad3547a805%7C0%7C0%7C637781024954654580%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=AzFfI3%2BN1rzTCO4cjkXExCJbLt6ki7jw%2F7Q7w9Kuvj8%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ca.mathoera%40utrecht.nl%7C477a89563b8a488f9d1508d9da768ba1%7Cb9ea87f7a2634e6898e15fad3547a805%7C0%7C0%7C637781024954654580%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=AmcNI35bXVp9XqOlIWx473CzuC1S0K1%2Fk54ES4X86U0%3D&reserved=0> or Android<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ca.mathoera%40utrecht.nl%7C477a89563b8a488f9d1508d9da768ba1%7Cb9ea87f7a2634e6898e15fad3547a805%7C0%7C0%7C637781024954654580%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=FcuK0uOZ3sxB6uJVoFORCqkHR1MZWOzm7wImZPjD%2FN8%3D&reserved=0>.
