### ISSUE TITLE
Safe Exam Browser detects a dual boot as a virtual machine

### ISSUE THREAD

**Issue by MindSwipe** [SafeExamBrowser/seb-win-refactoring#34]
**Describe the Bug**
When starting up the Safe Exam Browser with a configuration that disallows virtual machines on a machine that has more than 1 operating system installed (in my case Windows 10 and Debian 9) it detects as running in a virtual machine and does not allow to be started.

**Steps to Reproduce**
1. Install a version of Windows
2. Install a Linux distribution
3. Try and run a configuration that disallows running in a virtual machine

**Expected Behavior**
I expect the safe exam browser to start up and allow me to do the test.

**Version Information**
 - OS: Windows 10 Pro Version 2004 build 19041.423 as well as Debian 9
 - SEB-Version: SEB 3.0.1

**Additional Context**
This issue would also be fixed by supporting a Linux version of SEB, as it would allow me to purge Windows.

**Comment by dbuechel** [comment]
@diegoara96 I think this is another false positive...

**Comment by diegoara96** [comment]
Try running this beta with some bugs fixed https://sebdev-let.ethz.ch/api/buildjobs/1g36ch0lweb79h48/artifacts/SEB_3.1.0.174_SetupBundle.exe

if the fault continues I will need the output of these 2 powershell commands
```
Get-WmiObject Win32_pnpEntity | Out-File path\filename.txt
Get-WmiObject Win32_NetworkAdapterConfiguration | Format-List * | Out-File path\filename.txt
```

the Out-File path\filename.txt is only for save the output as a file in the path you want

**Comment by MindSwipe** [comment]
Sorry for the delayed response.

Version 3.1.0.174 seems to have fixed the problem.

**Comment by MindSwipe** [comment]
Can confirm Version 3.1.0.174 has fixed the problem.

Interestingly I talked with a friend today who has Manjaro alongside Windows installed and he never had any problems
