### ISSUE TITLE
SEB Keyboard layout selection does not display all available Keyboards in Windows 

### ISSUE THREAD

**Issue by nvarghese-rm** [SafeExamBrowser/seb-win-refactoring#349]
With SEB Windows v3.3.1, we have noticed a different behaviour when compared to SEB Win v2.3, in that not all available language and keyboard options setup in Windows are now available for selection in SEB.

As an example, we have English (United States) with US keyboard and English (United States) with International keyboard in Windows.
![WInKeyboard](https://user-images.githubusercontent.com/87759879/151450727-bf17dca3-e42e-42ba-b8f1-e9338d5513ca.png)

But when we are in SEB, only one of these is displayed and it is not clear which is which.
![SEBKeyboard](https://user-images.githubusercontent.com/87759879/151450850-4057f67e-9760-4bbf-96ea-a47e2648acda.png)

Similar was also observed when we had English (Australia) with US keyboard and English (Australia) with International keyboard. 

**Expected Behavior**
User/student should be able to see all language keyboards added on their device while clicking language layout icon on SEB taskbar.

**Version Information**
 - OS: Windows 10 Professional and Home
 - SEB-Version : SEB for Windows v3.3.1

**Additional Context**
I raised something related previously (https://sourceforge.net/p/seb/bugs/156/) that showed that both keyboards used to be displayed in SEB v2.3. In that issue, it was mentioned that a fix was on v3.2 roadmap to display both the language and keyboard in the SEB keyboard selection.
So is this new behaviour in v3.3.1 intended?

**Comment by dbuechel** [comment]
Thanks for the detailed report. We will investigate this issue and intend to resolve it for version 3.4.

**Comment by nvarghese-rm** [comment]
@dbuechel  - Do we have an indication when v3.4 may be released?

**Comment by dbuechel** [comment]
We are aiming for Q2 2022, i.e. no later than end of June.

**Comment by dbuechel** [comment]
We were able to fix the issue, please check out the latest beta build to test the changes: https://sebdev-let.ethz.ch/api/buildjobs/v9bd4vfqsnp25ffa/artifacts/SEB_3.4.0.430_SetupBundle.exe.

For the record: The underlying .NET Framework (specifically Windows Forms, which we now use to implement this functionality) appears to have quite some trouble itself in getting the keyboard layout information (see e.g. [https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/InputLanguage.cs,138](https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/InputLanguage.cs,138)). So the reliability of the new implementation unfortunately still largely depends on the reliability of the framework itself.

**Comment by dbuechel** [comment]
A fix for the issue is now available in version 3.4.0.
