### ISSUE TITLE
[Question] Checking Authenticity of Third Party Applications in Unmanaged PCs

### ISSUE THREAD

**Issue by cemonem** [SafeExamBrowser/seb-win-refactoring#35]
# Checking Authenticity of Third Party Applications in Unmanaged PCs

### Description

Hello,
Is it possible to check the authenticity of the allowed third party applications within Safe Exam Browser (by checking if the md5sum of the executable matches the one in the configuration file etc.)? Although the configuration of the browser is enforced with the browser exam keys and the moodle plugin, it seems that one can cheat in BYOD cases by replacing the allowed executable with another application with the same name, even though that application may not be permitted during the exam.

### Environment & Version

Windows 10

- [ ] Mac
- [x] Windows

SEB-Version: 3.0.1

**Comment by dbuechel** [comment]
You can use the original name check for applications (see https://safeexambrowser.org/windows/win_usermanual_en.html#PermittedProcessesSection), but the reality is that BYOD exams, where users have full control over their computers, will never be as secure as a controlled environment with managed computers. A checksum may well be a feature we'll consider for an upcoming version, thanks for the input.
