### ISSUE TITLE
0 internal screen and 1 external screen detected, can't use SEB (Student)

### ISSUE THREAD

**Issue by bobdewston** [SafeExamBrowser/seb-win-refactoring#350]
**IMPORTANT**
Please _always_ consult the documentation first before creating a bug report!
https://safeexambrowser.org/windows/win_usermanual_en.html

**Describe the Bug**
I can't use SEB because it says that I have 0 internal screen and 1 external screen. I am on PC and using 1 monitor connected via HDMI

**Steps to Reproduce**
1. Open SEB
2. Go to an assignment
3. Try to do assignment

**Expected Behavior**
I could do the assignment

**Screenshots**
![WhatsApp Image 2022-01-28 at 08 14 37](https://user-images.githubusercontent.com/98566893/151472271-41720432-9eb5-4fbe-a6d5-5db02c05e6b0.jpeg)

**Version Information**
 - OS: Windows 10 Home
 - SEB-Version SEB 3.1.1

**Additional Context**

**Comment by dbuechel** [comment]
As the error message already indicates, the configuration you're using only permits to use an internal display. If you received that configuration from your institution, then you'd need to report the issue to them. If you have control over the configuration, then you can change the value in the configuration tool: https://safeexambrowser.org/windows/win_usermanual_en.html#SecurityPane
