### ISSUE TITLE
Multilingual support

### ISSUE THREAD

**Issue by Fredrik-OnlinePartner** [SafeExamBrowser/seb-win-refactoring#353]
We are using SEB to load our web app Trelson Assessment to lock down both Windows and macOS. 

We would like a solution where there is a possibility to use several different languages, preferably following the system locale but also being able to manually switch languages for SEB.

**Comment by dbuechel** [comment]
SEB already has a few localizations, at the moment English, German, French, Italian and Chinese. The UI of SEB is automatically loaded with the system locale or English as fallback in case the OS language does not (yet) exist for SEB.

If you'd like to contribute a language, please feel free to take the English reference and provide a pull request here on GitHub: https://github.com/SafeExamBrowser/seb-win-refactoring/blob/master/SafeExamBrowser.I18n/Data/en.xml

**Comment by Fredrik-OnlinePartner** [comment]
Thank you for your email.

We will of course contribute to your excellent service and help you with
translations as our app now supports nine languages. @Daniel Liljeström
***@***.***> will be handling it from our side.

Best regards
[image: Company logo]
Fredrik Hedström
Head of development
***@***.***
[image: -] +46842000408
Online Partner AB | www.onlinepartner.se
Mejerivägen 3,
117 43 Stockholm
<https://mail.google.com/mail/u/0/#SignatureSanitizer_SafeHtmlFilter_>
Book a meeting! <https://app.hubspot.com/meetings/hedstrom>
[image: Twitter] <https://twitter.com/onlinepartnerab>  [image: Facebook]
<https://sv-se.facebook.com/Online.Partner.se>  [image: Instagram]
<https://www.instagram.com/onlinepartnerab>  [image: Youtube]
<https://www.youtube.com/onlinepartnerse>  [image: Linkedin]
<https://www.linkedin.com/company/online-partner>



Den fre 11 feb. 2022 kl 14:06 skrev Damian Büchel ***@***.***
