### ISSUE TITLE
Error lauching SEB

### ISSUE THREAD

**Issue by vanie76** [SafeExamBrowser/seb-win-refactoring#354]
![image](https://user-images.githubusercontent.com/87995554/153370454-80ea9b18-3cd2-41cf-b0db-804fe6e78cec.png)
Got the above error when lauching SEB
Please help

**Comment by dbuechel** [comment]
Please refer to the already existing issues and discussions regarding this topic, e.g. #176, #33. As far as we were able to determine, this issue is caused by an issue with the configuration of the operating system.
