### ISSUE TITLE
SEB & Word - Only open certain files / files in directory

### ISSUE THREAD

**Issue by jellevandewalle** [SafeExamBrowser/seb-win-refactoring#355]
We use SEB in combination with Bookwidgets.
We can push manual configuration files from Bookwidgets, but we are missing some features in the seb configuration tool to properly close off the exam.

You can enable the use of Word (winword.exe) in the application section. **Great!**
When using the right arguments (f.e. "-t c:\seb\doc2.docx"), you can even open the correct document. Again, **Great!**

![app_seb](https://user-images.githubusercontent.com/99411461/153428659-8de35be0-5d4d-47f4-9e40-d89f88cb0b75.jpg)

But you can't deny the user / student from opening another file in Word. **Bad!**

They can see all the directory's even when setting up a down/up folder in the down/ uploads section.
![updown_seb](https://user-images.githubusercontent.com/99411461/153428664-55aaf0a5-070d-4e72-a27b-bd10b5367428.jpg)

How can I, as a teacher, prevent my students from opening any other file in Word except the ones I put in the seb folder?

**Comment by danschlet** [comment]
You need to use SEB in conjunction with a virtual desktop environment, because SEB on its own cannot secure a highly complex operating system like Windows. [Just read the SEB manual for more information](https://safeexambrowser.org/windows/win_usermanual_en.html#ApplicationsPane).

**Comment by dbuechel** [comment]
> They can see all the directory's even when setting up a down/up folder in the down/ uploads section.

These configuration values only apply for the internal browser of SEB. As a matter of fact, most configuration values available in the configuration tool only apply to SEB's internal functionality and don't control aspects and functionality of third-party applications.
