### ISSUE TITLE
"Invalid Class" Runtime Issue

### ISSUE THREAD

**Issue by froschy** [SafeExamBrowser/seb-win-refactoring#363]
At Freie Universität Berlin we have several students who report "invalid class" popups after trying to install Safe Exam Browser.

### Steps to Reproduce
1) Download Safe Exam Browser via [our wiki website]([https://wikis.fu-berlin.de/x/Mol2QQ]())
2) Open Setup Bundle
3) Open Safe Exam Browser

### What we tried to fix this issue
- Analog to [this sorceforge thread]([https://sourceforge.net/p/seb/discussion/844844/thread/20ad0ed0f3/]()) we tested whether the WMI repo is consistent (which it was).
- We checked for .NET and Visual C++ Redistributable updates, everything was fine.

### OS:
- Windows 10 Pro (Vers. 21H1)
- SEB: 3.1.0.228 and 3.3.2.413

We cannot figure out how to fix this. Do you have any suggestions how to fix this? We appreciate any hints.
Thank you!

![Screenshot](https://user-images.githubusercontent.com/69001402/155160590-93e6463e-1d42-48a6-bc57-e77a8ece68c1.png)

**Comment by dbuechel** [comment]
Please try to execute the following command in an instance of Windows PowerShell and post the result back here: `Get-WmiObject -Class Win32_ComputerSystem`

**Comment by dbuechel** [comment]
Regarding the version information: Are you sure that the error also happened with SEB 3.3.2.413? We introduced a fix with version 3.1.1 which should prevent this error in case the system information is missing on a machine (though it really shouldn't be missing on a properly configured system).

**Comment by froschy** [comment]
Thank you, Damian!

This is the output we got from a student:
![Screenshot 2022-03-01 174944](https://user-images.githubusercontent.com/69001402/156341020-3e6d040e-da58-44d6-8a2e-fb4cdca12673.jpg)

Looks like the system information is missing as you stated. The check if the repository was corrupted came out clear though.

Regarding your second question: yes, we also installed and tested the latest SEB Version from SourceForge.

What can we do now?

Thanksk again for your help!

**Comment by dbuechel** [comment]
> Looks like the system information is missing as you stated. [...] What can we do now?

This is something that would need to be fixed on the student's system. That WMI class should be present on all properly configured systems since Windows Vista, see https://docs.microsoft.com/en-us/windows/win32/cimwin32prov/win32-computersystem.

> Yes, we also installed and tested the latest SEB Version from SourceForge.

Could you please post the exact error message and log files from SEB version 3.3.2.413?

**Comment by dbuechel** [comment]
Closed due to lack of feedback.

**Comment by Swaussie01** [comment]
Okay I've figured it out: I simply had to convert the command to a powershell syntax:

cd C:\Windows\System32\wbem
for /f %s in ('dir /b *.mof') do mofcomp %s
