### ISSUE TITLE
zoom with ctrl + mouse wheel does not work

### ISSUE THREAD

**Issue by jp-weber** [SafeExamBrowser/seb-win-refactoring#37]
**Describe the Bug**
zoom with ctrl + mouse wheel does not work and setting the option for zooming with the mouse wheel has no effect, even a standard configuration with active option has no effect.

**Steps to Reproduce**
1. use a standard configuration
2. open the safe exam browser
3. try to zomm via ctrl + mouse

**Expected Behavior**
zoom with ctrl + mouse wheel should work, when the option is on.

**Version Information**
 - OS: Windows 10 Enterprise LTSC, Version 1809
 - SEB-Version 3.0, 3.0.1 and preview 3.1

**Comment by dbuechel** [comment]
This isn't possible due to a restriction in the browser engine. Zooming via the browser menu or keyboard shortcuts should however work as expected. The option is still there for users who have SEB 2.x and 3.x in usage.

**Comment by jp-weber** [comment]
@dbuechel  Oh well, thanks, I didn't know that. But maybe we could solve this in the meantime as a workaround, where the brower window recognizes ctrl + mouse wheel and then executes the logic behind the zoom in/outbutton? 


```csharp
private void Window_ZoomMouseWheel(object sender, MouseWheelEventArgs e)
{
    if (Keyboard.Modifiers == ModifierKeys.Control)
    {
       if (e.Delta > 0)
          ZoomInRequested?.Invoke();

       else if (e.Delta < 0)
          ZoomOutRequested?.Invoke();
    }
}
```

**Comment by dbuechel** [comment]
This unfortunately doesn't work, as the browser engine is embedding its own window structure within the browser window. The event handler you're using will only catch events which are anywhere over the window except the browser control (i.e. browser content) itself.

**Comment by danschlet** [comment]
I honestly wonder why you would like to use ctrl + mouse wheel for zooming web pages. That sounds like a very non-standard, outdated way (I think besides old Windows Firefox versions and therefore SEB 2.x, no other browser supports that, mostly they would use keyboard shortcuts, or am I wrong?).

**Comment by jp-weber** [comment]
It is difficult to see how the browser control is embedded. But as I have seen, there are functions and solutions for zooming from the browser control, also for the mouse wheel.
https://github.com/cefsharp/CefSharp/blob/master/CefSharp.Wpf/ChromiumWebBrowser.cs#L262
https://stackoverflow.com/a/39220412


@danschlet some students have complained to us that their normal way of zooming no longer works.  But for me this is also a normal way to zoom, which to my knowledge works in all browsers (e.g. Edge Chromium) and other applications.

**Comment by dbuechel** [comment]
Yes, that is correct, CTRL+mouse wheel is a standard way to zoom (at least on Windows). But we're using the Windows Forms version of the CefSharp browser control and the last time I checked, it unfortunately wasn't possible to implement zooming via CTRL+mouse wheel for it. If you have news that this changed, please point me to them and I'll of course implement the functionality for an upcoming version.
