### ISSUE TITLE
Turn spell check on and off client-side

### ISSUE THREAD

**Issue by NOTE-HBL** [SafeExamBrowser/seb-win-refactoring#371]
My school switched from SEB 2.4.1 to SEB 3.3.2 this week because of various problems with the new Moodle 3.11. Teachers were frustrated to discover that only English spell checking is supported now, because we let students write essays with the Safe Exam Browser and they need spell checking for that. But we altered assignments in order to deal with this issue so we can manage that they don't have spell checking. 

However, the red dotted lines under words in other languages makes it hard to read the essays for the students while they are writing. 

Of course I could turn that off using the configuration tool, but I would like the students to be able to use the spell check for their English essays. 

It would already be a big improvement if the spell check could be turned off by the students so that it makes texts in other languages more easily readable. (Of course it would ultimately be great if other languages be supported in the spell checker but I understand that takes time and is not a priority, in the meantime this would be a nice temporary solution).

**Comment by dbuechel** [comment]
Thanks for your input. The spell checking feature will most likely remain to be configured via configuration tool, as there are many situations where the students should not be able to enable the feature on their own (e.g. in a grammar exam or a high-stakes assessment which also verifies that a student is able to write a text properly without assistance).

Regarding your specific use case, I'd recommend you to use two different configurations, one with the spell checking enabled and another one which has it disabled. The support of different languages is on our roadmap, but not a priority at the moment.
