### ISSUE TITLE
Similar to issue #283: Open an Excel-sheet in Moodle-Test

### ISSUE THREAD

**Issue by awaelde** [SafeExamBrowser/seb-win-refactoring#372]
We would like to use Excel in some e-exams in Moodle and 'give' an Excel sheet for it. This works quite well so far (embedded file linked in test question), but not with the SEB (latest version). When using the SEB, Excel does not open when double-clicking on it, although I have allowed Excel.exe in the Applications tab in the SEB configuration file. The file is only downloaded. Is there a way to configure the SEB in such a way that double-clicking  on an Excel sheet opens Excel directly (this used to work for us with Lplus and an older version of the SEB a few years ago)?

**Comment by dbuechel** [comment]
At the moment not, we plan to add this functionality as described in #283.
