### ISSUE TITLE
Add integrity check for .dll files

### ISSUE THREAD

**Issue by Filocava99** [SafeExamBrowser/seb-win-refactoring#373]
Wouldn't be better if there was an integrity check on every dll of SEB? Like computing the hash of a dll and then send it to the server for approval. I know it can by bypassed by simply sending the hash that the server would expect, but casual devs wouldn't  be so smart to do so imho.

**Comment by dbuechel** [comment]
We are planning various improvements for the verification of a SEB installation integrity, all of which we'll track under #336. The first step will be a standalone tool which will verify an entire SEB installation which we plan to release with version 3.4.
