### ISSUE TITLE
On-Screen Keyboard not showing up when running SEB

### ISSUE THREAD

**Issue by Iscle** [SafeExamBrowser/seb-win-refactoring#38]
**Describe the Bug**
On touchscreen devices, such as the Surface Pro 2, the On-Screen Keyboard from Windows 10 won't show up after running SEB. Normally the user can force it to appear by tapping the keyboard icon in the task bar, but not when SEB replaces it with it's own.

**Steps to Reproduce**
1. Go to a site with text input
2. Click on the text input box
3. Nothing appears

**Expected Behavior**
1. Go to a site with text input
2. Click on the text input box
3. The keyboard pops up

Alternatively:
1. Have a keyboard icon on the task bar
2. Tap the keyboard icon
3. The keyboard pops up

**Version Information**
 - OS: Windows 10 Pro
 - SEB-Version: SEB 3.0.1

**Comment by dbuechel** [comment]
The on-screen keyboard will only work after re-activating the old, non-UWP implementation via the registry:

1. Navigate to `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\TabletTip\1.7`.
2. Right-click and choose "New" → "DWORD (32 bit) value" with name `DisableNewKeyboardExperience` and value `1` .
3. Restart your computer.

After that, you need to activate the tablet mode in Windows before starting SEB. It might be that the keyboard only works in kiosk mode Disable Explorer Shell, though.
