### ISSUE TITLE
Inserting images in the exam document

### ISSUE THREAD

**Issue by lsigalini** [SafeExamBrowser/seb-win-refactoring#381]
It is not possible to insert images into the document by performing the drag & drop operation. When the image is dragged into the document and dropped onto the document, it "returns" to the left column and is not shown in the document.

1. Create an image with the "Drawing tool"
2. Go to the list of created images
3. Drag the image on the document and drop it
4. See error: the image return on the left column

**Expected Behavior**
The image should remain in the document at the cursor position.

**Version Information**
 - OS: Windows 10 or Windows 11
 - SEB-Version: the last version

**Comment by dbuechel** [comment]
We'd need a bit more information about your issue: Are you referring to an exam system (e.g. Moodle), or what do you mean by "exam document"?

**Comment by dbuechel** [comment]
Closed due to lack of feedback.
