### ISSUE TITLE
Software version number in cutom user agent string

### ISSUE THREAD

**Issue by randy-knapp** [SafeExamBrowser/seb-win-refactoring#39]
I created a custom user agent string in the SEB configuration application. When the string is passed to server, the version number is appended as 1.0.0.0, even though technically it's version 3.0 of the Safe Exam Browser.  Is there a reason for this?  3.X vs. 1.0.0.0

**Comment by dbuechel** [comment]
Are you using a local development build? The build number is always 1.0.0.0 for those, as versioning is handled by our CI system.

**Comment by dbuechel** [comment]
Closed due to lack of feedback.
