### ISSUE TITLE
Does SEB support on windows 11 ?

### ISSUE THREAD

**Issue by ari1101** [SafeExamBrowser/seb-win-refactoring#391]
### Discussed in https://github.com/SafeExamBrowser/seb-win-refactoring/discussions/223

<div type='discussions-op-text'>

<sup>Originally posted by **loctran7777** October  9, 2021</sup>
I just upgraded to win 11 and now I'm confused because my school is about to apply the exam on SEB. I looked it up, it seems that seb only supports win 10. Will there be SEB on win 11?</div>

**Comment by dbuechel** [comment]
Yes, see https://safeexambrowser.org/download_en.html.
