### ISSUE TITLE
Configuration file not loading via seb://

### ISSUE THREAD

**Issue by ramonavic** [SafeExamBrowser/seb-win-refactoring#4]
Hi!

After testing the SEB 3.0.0 Beta, we ran into an issue when opening the configuration file through a seb:// url.

After clicking the sebs:// link, SEB does open, but it does not load the configuration file. Instead, SEB displays the text of the configuration file.
We use document.location to redirect to the seb:// url. 

When saving the same configuration to a .seb file and then opening it, the configuration loads without problems.
 
The log files are attached. Is there something we should change on our end, or is this an issue in the SEB application?

[seb-logs.zip](https://github.com/SafeExamBrowser/seb-win-refactoring/files/4407472/seb-logs.zip)

Thanks in advance!

**Comment by dbuechel** [comment]
Thanks for your feedback. Are you clicking on a seb(s)-link inside SEB, or outside in a normal browser? Also, would you have a test page where I can debug the issue?

SEB should correctly recognize configuration files as long as reconfiguring is allowed in the currently active configuration.

**Comment by ramonavic** [comment]
Thanks for you quick response!
We're clicking the seb:// url in a regular browser (tested in Firefox and Edge).
We've set up an account for you to try it out yourself. After logging in you should immediately see the SEB start button.

I've emailed the credentials to you.

**Comment by dbuechel** [comment]
Excellent, I have received them, thanks. I will have a look at the problem first thing tomorrow.

**Comment by dbuechel** [comment]
Okay, I was able to reproduce the issue. Can you elaborate on your comment below, is it that the seb-URL you use leads to an HTML page which then redirects to the actual configuration file?

> We use document.location to redirect to the seb:// url.

In the log file, SEB detects that the resource under the given seb-URL is HTML and thus attempts to load it with the browser. As to why it renders the configuration file instead of loading it I will try to find out now...

**Comment by dbuechel** [comment]
I think I found the root cause: You are returning "text/html" as content-type in the response for the configuration file request. Thus the browser simply renders the content instead of initiating a file download...

**Comment by ramonavic** [comment]
Makes sense! We're going to check if this helps. I'll get back to you after :)

**Comment by ramonavic** [comment]
@dbuechel we have changed our headers and it works now! We'll be deploying it to production soon. Thanks for you help!

**Comment by dbuechel** [comment]
Great! Thanks for helping out with the beta testing.
