### ISSUE TITLE
Missing URL in alert message

### ISSUE THREAD

**Issue by GregMorel** [SafeExamBrowser/seb-win-refactoring#40]
I just discovered SEF. Thank you for this amazing product!

It seems that a regression has been introduced in version 3.1.0 for Windows: when we attempt to access a filtered URL, a popup displays the message _Access to "" is not allowed according to the current configuration_. In version 3.0.1, the same message correctly provides the forbidden URL / domain.

Regards
Greg

**Comment by dbuechel** [comment]
There is a new feature in SEB 3.1 which controls the visibility of URLs for the browser. It can be controlled in the configuration tool under "Browser" -> "Restrictions in Exam / Additional Window" -> "Show URL". The default value is the most restrictive, i.e. never show any URLs.
