### ISSUE TITLE
Pressing Ctrl + Alt + Del the default menu is not disabled as expected by use of SEB

### ISSUE THREAD

**Issue by AnuragTripti** [SafeExamBrowser/seb-win-refactoring#405]
SEB Version 3.3.2.413

**Comment by dbuechel** [comment]
The default behavior has been changed as of SEB 3.0.1 (if I recall correctly). To use the SEB Service, you'll have to activate it in the configuration: https://safeexambrowser.org/windows/win_usermanual_en.html#SecurityPane
