### ISSUE TITLE
French translation?

### ISSUE THREAD

**Issue by GregMorel** [SafeExamBrowser/seb-win-refactoring#42]
Hi SEB Team,

is there a French translation project?
I would be delighted to offer my help in for such a translation.

Regards,
Greg

**Comment by dbuechel** [comment]
There isn't yet, if you'd like to contribute you're most welcome to do so. The easiest way would be if you translate the raw data from one of the existing languages: https://github.com/SafeExamBrowser/seb-win-refactoring/tree/master/SafeExamBrowser.I18n/Data

**Comment by dbuechel** [comment]
@GregMorel If you'd like to have the French translation included in the upcoming version 3.1.1 which we plan to release end of this year, then I'd need the translation until December 16th. Otherwise, we'll certainly include it in the next feature update version 3.2.

**Comment by dbuechel** [comment]
Another contributor meanwhile translated all text data into French, so I'll allow myself to close this issue. You can find the translation here: https://github.com/SafeExamBrowser/seb-win-refactoring/blob/master/SafeExamBrowser.I18n/Data/fr.xml
