### ISSUE TITLE
illegal character in path when windows user name is in hebrew

### ISSUE THREAD

**Issue by guysiTomax** [SafeExamBrowser/seb-win-refactoring#421]
On windows when the username is in Hebrew or the date is in Hebrew format we are getting an "illegal character in path" exception

[**Screenshots**]
![image](https://user-images.githubusercontent.com/94598094/171123478-55b746d0-5835-4054-abd5-be6dde850692.png)

**Version Information**
 - OS: win 10 
 - SEB-Version - 3.3.1

**Comment by dbuechel** [comment]
Thanks for the report, we'll try to fix that.

**Comment by guysiTomax** [comment]
Hello, any update or ETA on this one ?

**Comment by dbuechel** [comment]
Unfortunately, we did not have the time yet to investigate the issue due to other priorities. But we'll certainly try to fix it for one of the upcoming versions.

**Comment by dbuechel** [comment]
Would you mind translating the error message? That would help us greatly in determining the underlying issue.

**Comment by guysiTomax** [comment]
Hi,

 

The translation of the error is” illegal character in the path”

It happens when the user name  or the OS is using Hebrew as the default language.

 

Guy

**Comment by dbuechel** [comment]
Excellent, thanks a lot. Yes, I realized it after writing the comment, sorry for the inconvenience.

**Comment by dbuechel** [comment]
The issue should be fixed now. @guysiTomax It would help us greatly if you could install the latest beta build and verify that the issue indeed is resolved: https://sebdev-let.ethz.ch/api/buildjobs/pejp7x8iie1ug85v/artifacts/SEB_3.5.0.486_SetupBundle.exe

**Comment by dbuechel** [comment]
The issue seems to be reliably fixed according to our internal testing.

**Comment by guysiTomax** [comment]
Thanks much,
when will 3.5.0 be released ?

**Comment by dbuechel** [comment]
We're targeting Q1 2023, but that's still a rough estimate (at the time of writing).
