### ISSUE TITLE
Handle Exit Codes for WebView2 Bootstrapper

### ISSUE THREAD

**Issue by dbuechel** [SafeExamBrowser/seb-win-refactoring#429]
Error 0x8004090d means, "there is already a newer version of WV2 installed"
@dbuechel: WV2 installers are... (not easy going). You have to check for things like this, if you bundle it with SEB.

_Originally posted by @NickETH in https://github.com/SafeExamBrowser/seb-win-refactoring/discussions/424#discussioncomment-3029818_

**Comment by dbuechel** [comment]
https://wixtoolset.org/documentation/manual/v3/xsd/wix/exitcode.html

**Comment by dbuechel** [comment]
https://github.com/SafeExamBrowser/seb-win-refactoring/discussions/424#discussioncomment-3030452

**Comment by dbuechel** [comment]
WIX appears to not allow exit codes bigger than an integer.

**Comment by dbuechel** [comment]
https://github.com/wixtoolset/issues/discussions/6851

**Comment by dbuechel** [comment]
Will be fixed with WiX version 4.0.

**Comment by dbuechel** [comment]
Keeping this open in order to fix the issue once WiX version 4.0 is released.

**Comment by dbuechel** [comment]
Turns out this was already fixed for WiX version 3.9, the hex code simply needs to be converted to a signed integer.

**Comment by NickETH** [comment]
Very good to know!
Where did you find that info?
That means 0x8004090d converts to 2147748109

**Comment by dbuechel** [comment]
> Where did you find that info?

I received the input from the official WiX repository here on GitHub, see https://github.com/wixtoolset/issues/discussions/6851

> That means 0x8004090d converts to 2147748109

No, I first also made the mistake to convert it to an unsigned integer, but it turns out that the exit code is a signed integer (i.e. `-2147219187`). I am now in the course of adding this to the setup bundle and do hope that it works as intended, as the unsigned integer resulted in a compilation error.

**Comment by dbuechel** [comment]
Yes, same for me 😁 It appears that everything works as expected with a signed integer, the build passed correctly as well.
