### ISSUE TITLE
Can S.E.B run without Administrator privileges on Windows

### ISSUE THREAD

**Issue by sskras** [SafeExamBrowser/seb-win-refactoring#43]
**Is your feature request related to a problem? Please describe.**
I tried installing Safe Exam Browser on Windows. The installer requires Administrator privileges. Which I didn't had.

**Describe the solution you'd like**
Is this done on purpose (Admin is needed for some functionality) or is it just an unintentional side effect?
I would like to run it using unprivileged account.

**Describe alternatives you've considered**
It has neither Linux binaries nor Chrome OS extension, nor a Progressive Web Application I could run.

**Additional context**
I installed it in a VM where it didn't run. But it opened me a possibility to copy out the binaries. Which I copied to my physical machine (notebook). Where it did run. Only that my exam was over already.

**Comment by dbuechel** [comment]
SEB requires administrator privileges when installing due to its Windows service component as well as file and protocol associations. For now, we won't be providing a portable solution, but that might be something we'll offer in the future.

**Comment by DegrangeM** [comment]
It would be very nice if there was an non admin version, even if it was a light version with some functionnality removed.

**Comment by sskras** [comment]
@dbuechel commented [on Nov 16, 2020](#issuecomment-728238677):

> SEB requires administrator privileges when installing due to its Windows service component 

Still it ran for me without the admin privileges **after I copied the files** from `%ProgramFiles%\SafeExamBrowser` dir to my `%USERPROFILE%\Downloads`.  And I was able to complete the exam.

Thus I am interested in what does that Windows service component do (ie. what functionality/security measure I was missing, if any).

> [...] as well as file and protocol associations. 

This works per-user just fine.

> For now, we won't be providing a portable solution, but that might be something we'll offer in the future.

Yes, having portable solution would be nice.  But it's quite orthogonal to being included into the Administrator group, IMO.

Both installable and portable versions of an app can require Admin account (eg. Notepad saving the hosts file).

**Comment by dbuechel** [comment]
> Thus I am interested in what does that Windows service component do (ie. what functionality/security measure I was missing, if any).

The SEB service component performs all operations which require elevated user privileges, see e.g. https://safeexambrowser.org/windows/win_usermanual_en.html#SecurityPane.

**Comment by DegrangeM** [comment]
> > Thus I am interested in what does that Windows service component do (ie. what functionality/security measure I was missing, if any).
> 
> The SEB service component performs all operations which require elevated user privileges, see e.g. https://safeexambrowser.org/windows/win_usermanual_en.html#SecurityPane.

Couldn't all these operations requiring elevated user privilege being disabled with non admin installation ?
