### ISSUE TITLE
URL path visible in SEB filebrowser

### ISSUE THREAD

**Issue by johan-werk** [SafeExamBrowser/seb-win-refactoring#431]
**Describe the solution you'd like**
I want that our students don't see the URL path in the SEB filebrowser.
Now can students find files with the showed URL path and that is not allowed in case of privacy.

Can you make an option that the URL path isn't visible in SEB filebrowser?

![WhatsApp Image 2022-06-27 at 2 18 53 PM](https://user-images.githubusercontent.com/108275705/175946844-42e6bf8b-cb36-4f1a-96ad-3f7967091102.jpeg)

**Comment by dbuechel** [comment]
@danschlet I think we'd need a new configuration key to control this aspect?

**Comment by danschlet** [comment]
I guess so. To better understand, @johan-werk, are you using the setting to preset a specific directory which is accessible in the file browser? (what does UNC mean?)
Maybe the path should never be displayed when using a preset directory (maybe only the directory name)? If navigation in the file system is not allowed in the file browser, it seems unnecessary for the user to see the path.

**Comment by johan-werk** [comment]
@danschlet I had make a mistake. I mean te URL to a local server. This is a secret adres for our students. 
In the example picture you see \\sv-dcfs-01\personeel.
We don't want to see that. Do you understand me now?

**Comment by dbuechel** [comment]
This will be included in the upcoming release version 3.5.0 and can now be tested in the latest beta build: https://sebdev-let.ethz.ch/api/buildjobs/1gj1bw2t06de5co5/artifacts/SEB_3.5.0.533_SetupBundle.exe.
