### ISSUE TITLE
Back to Start Button: Start URL sometimes not working

### ISSUE THREAD

**Issue by AntonT76** [SafeExamBrowser/seb-win-refactoring#437]
Hi,

I'm using SEB 3.3.2 on Windows 10 and Moodle 3.9.
In SEB Configuration Tool I use the option "Back to Start Button" - "Use Start ULR (see General tab)", save as seb file and upload it to Moodle quiz. The URL of the Start Button does not work under certain conditions.
eg: Start URL in general tab is = https://mymoodle.com

After finishing a quiz:
- if I activate "Use Start ULR (see General tab)", _URL will not work_ (browser only reloads the current web page, but doesn't load the Start URL)
- if I insert custom URL (eg. https://mymoodle.com), URL will work.
- if I insert an other custom URL (eg. https://safeexambrowser.org), ULR will work.

br, Anton

**Comment by dbuechel** [comment]
Thanks for the report, we'll have a look at it.

**Comment by dbuechel** [comment]
I just tested the functionality and it appears to work perfectly fine when using a valid URL. The URL you specified does not exist, thus SEB automatically navigates backwards to the previous page so that a user does not get stuck on an empty page.

**Comment by AntonT76** [comment]
Dear @dbuechel 

thank you for your reply. I testet it again and the problem still exists - also with valid URLs. I will describe you two settings:

Setting 1: NOT OK
- Tab "General" - "Start URL": type in some valid URL (eg https://safeexambrowser.org)
- Tab "Exam" - "Back to Start Button": activate "Use Start URL (see General tab)
- save and upload seb-file in Moodle quiz
- start a quiz, press "Back to Start" - the browser still reloads but will NOT open the Start URL

Setting 2: OK
- Tab "General" - "Start URL": no entry
- Tab "Exam" - "Back to Start Button": type in some valid URL (eg https://safeexambrowser.org)
- Tab "Network" - "Filter": type in the valid URL and activate filtering (if you don't do this, SEB will not allow to change to the valid URL, if you press "Back to the Start Button" 
- save and upload seb-file in Moodle quiz
- start a quiz, press "Back to Start" - the browser will load the valid URL

It seems to be that any valid URL in "General" - "Start URL" will be ignored. Maybe this will help:
- in Setting 2 if I deactivate network filtering, a pop up window will appear that the URL is not allowed to open
- in Setting 1 it doesn't matter if network filtering is activated/deactivated - even the network filtering is deactivated, no pop up window appears

br, Anton

**Comment by dbuechel** [comment]
I think the issues you're experiencing stem from Moodle. I tried the scenarios you described above without uploading the SEB configuration to Moodle and they both worked without any issues. If you can confirm this, then it definitely is an issue in the SEB integration in Moodle.

**Comment by dbuechel** [comment]
> What's the best next step? Should I open a Moodle Tracker Issue?

Yes exactly, I think that would be the correct thing to do.

**Comment by AntonT76** [comment]
done: https://tracker.moodle.org/browse/MDL-75574
br Anton
