### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by RiedleroD** [SafeExamBrowser/seb-win-refactoring#44]
I'm sure you have your reasons not to support Linux, but I wanted at least an issue regarding that.

So I do still have a windows machine, but my main workstation runs on Linux. It'd really make my day if I don't have to hope that windows takes too long to update for me to do the exam.

If there is no other way, at least providing a tutorial of how to compile it would be nice.

**Comment by dbuechel** [comment]
The main reason why we don't support Linux is because we currently don't have the resources to develop and maintain a Linux version. In Windows 10, you have the option to pause updates for I think a maximum of 7 days in case you don't have time to update your system before an exam.

**Comment by RiedleroD** [comment]
Yeah but if windows downloaded an update silently *again*, you're basically fucked. Happened to a friend of mine today, that's why I mentioned it. I do understand the resources problem though, so I won't press you with this issue.

**Comment by danschlet** [comment]
If we find some organization which would finance it, we will be happy to provide an SEB version for Linux. They can join the [SEB Consortium](https://safeexambrowser.org/consortium/fees.html) and contribute money, then we might be able to work on a Linux version (as that requires hiring at least one additional develper).

As you know, there is not one Linux, there are thousands of technologically very different distributions and several Linux desktop environments. SEB usually needs to work very closely with an operating system to lock it down securely for an exam. Therefore it will probably never be possible to provide a SEB version similar to Mac, iOS, Windows which just runs on any Linux distribution. If we create a Ubuntu compatible version, then all users of other distributions will diss us for not supporting their preferred version. To be honest, I don't think a Linux version is realistic at all, unless it contains its own bootable Linux distribution (which was already supported with the seb2 browser engine used in SEB for Windows 2.x, see https://github.com/eqsoft/seb2 and https://github.com/eqsoft/sebian).
