### ISSUE TITLE
Automatically block other language keyboard inputs except for a chosen default

### ISSUE THREAD

**Issue by bradcarmichael1** [SafeExamBrowser/seb-win-refactoring#452]
Hi team, a bit of a strange one. 

Would it be possible to add a feature to automatically block all other languages as a keyboard input except for a chosen default in SEB's settings?

EG: We have an English unit that is focused on teaching students simplified Chinese. If they have the Chinese Simplified language pack installed in Windows and set as the keyboard input option, it will popup with suggested words which can potentially by used by students to easily answer quiz questions.

Ideally it would be good to be able to "lock" down only one usable keyboard option as set by the lecturer/teacher of the unit within the SEB configuration such as English in this scenario or whatever language is relevant to other localised use cases.

**Comment by dbuechel** [comment]
There currently is no such option to suppress an input language within SEB. But you can disable the keyboard layout button in the configuration: https://safeexambrowser.org/windows/win_usermanual_en.html#AppearancePane. However, this does not disable the keyboard shortcuts of Windows itself to change the input language. Another option would be to make sure that the particular input language is not installed on the student's system.
