### ISSUE TITLE
CORS issues in SEB 3.1.0

### ISSUE THREAD

**Issue by Krisell** [SafeExamBrowser/seb-win-refactoring#46]
**Describe the Bug**
Many sites don't work in SEB 3.1.0 due to issues with CORS headers. This is caused by the extra headers for the browser exam key (BEK) and config key, perhaps in combination with cross-domain policy changes in CEF 85

**Steps to Reproduce**
1. Install SEB 3.1.0
2. Activate the Browser Exam Key and Config Key in the settings, either by configuring the client or by creating an exam settings file.
3. Configure SEB to load https://twitter.com, or any other site that loads content cross-domains (see below for more examples).
4. Activate developer tools to see the actual errors. Common visible errors are icons missing, fonts missing, or never-ending loading spinners.

**Expected Behavior**
It loads as in a normal browser and as in SEB 3.0.1.

**Screenshots**
![image](https://user-images.githubusercontent.com/25909128/99818617-bc358680-2b4e-11eb-8ea6-ba6237dadb2c.png)

![image](https://user-images.githubusercontent.com/25909128/99816558-200a8000-2b4c-11eb-9ede-2197ece8e0eb.png)

An example from GeoGebra.org (this is where I discovered the issue): http://dev.geogebra.org/examples/html/example-graphing.html
![image](https://user-images.githubusercontent.com/25909128/99816356-dc177b00-2b4b-11eb-88c9-f8a3287246ca.png)

Errors on https://google.com
![image](https://user-images.githubusercontent.com/25909128/99816379-e33e8900-2b4b-11eb-8e73-bc6dfe508b8b.png)

**Version Information**
 - OS: Windows Professional 1903
 - SEB-Version: 3.1.0 (verified in both 64 bit and x86).

**Additional Context**
The problem only happens when activating the BEK and config key, and is very likely caused by the extra headers appended to each request with the browser exam key and config key. Were these always added to all requests and all domains, not just navigation and non-cross-domain-requests?

Dynamically loaded cross-domain content should definitely respond with CORS headers and complete lack of those would not work in a normal browser. However the extra headers cause the requests to no longer be classified as "simple requests" which should trigger a preflight, and perhaps some domains are not expecting those for these simple GET-requests, but that sounds weird as well. Could it be that preflights are made, but that they don't include the extra headers, such that the browser interprets the response as not allowing the request (with those headers)?

**Comment by Krisell** [comment]
Twitter.com does indeed try to perform a preflight before loading assets via GET and the response is 400, either because GET requests should really not trigger preflights, or because these special headers are unrecognized:

![image](https://user-images.githubusercontent.com/25909128/99818068-0b2eec00-2b4e-11eb-9fe6-765d8c8ccefc.png)

I'm not sure if it's a good solution, but skipping the BEK and config-key for any cross-domain requests would solve the issue I think, but I don't know if any exam systems rely on those being included cross-domain.

**Comment by dbuechel** [comment]
Thanks for the detailed report! To be honest, I never had to dig that deep with CefSharp / CEF until now and my web development knowledge is a bit old, I need to first catch up on a few things here (e.g. preflights)...

I can reproduce the issue but I am not sure whether there is much I can do: I am using [IResourceRequestHandler.OnBeforeResourceLoad](https://cefsharp.github.io/api/85.3.x/html/M_CefSharp_IResourceRequestHandler_OnBeforeResourceLoad.htm) to append the custom headers, and looking at the API, I couldn't right away find an indicator via which I could identify those preflight / cross-domain requests (if I understood your solution proposal correctly it would be the idea to omit the BEK / CK headers on those requests). Or am I misunderstanding or missing something?

**Comment by Krisell** [comment]
Thanks for acknowledging the issue. I'm afraid I don't have any knowledge of the inner workings of SEB or of CefSharp, and my suggestion was just a quick thought. If you have access to the current website domain (via the IWebBrowser object) and the domain of the request (via the IRequest object), you could perhaps try to skip the custom headers if they don't match?

**Comment by Krisell** [comment]
And to be clear, `preflight` requests are made automatically due to the extra headers. Omitting the custom headers will automatically get rid of the preflights.

You can read more at https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS, but in short – a `preflight` (the HTTP verb OPTIONS) is a small request performed before another to ask for "permission" to perform the actual request. It is very common for POST requests cross-domain, but GET-requests with non-standard headers will also trigger preflights.

**Comment by danschlet** [comment]
But it seems to work on Mac and iOS, although those versions also add the same headers to all HTTP requests...

Theoretically we wouldn't have to add those headers to requests to other domains, as long as the exam web application isn't affected. All requests from the exam applications should contain the custom header, as otherwise (depending on how they check for BEK/CK) they might trigger an access error.

**Comment by Krisell** [comment]
There are definitely browser discrepancies at play here, and Google has made quite a lot of changes to cross-domain policies this year (for instance the default value for the SameSite cookie setting). Since this problem is not present in SEB 3.0.1, it seems like the update of Chrome has affected this. Other browser's may follow in future updates.

Here's some references to CORS-changes in Chrome 85, although I'm not sure this is the exact change that is causing these issues: https://www.chromium.org/Home/chromium-security/extension-content-script-fetches

**Comment by dbuechel** [comment]
Excellent, thanks for the further information and explications. I'll study the issue closer and will see whether I can find a solution.

**Comment by Krisell** [comment]
This may be the same issue, and if that is the case it is probably caused by upstream changes in CEF. It is probably not a bug but rather a policy change, and if so, the solution is for apps to avoid custom headers, and for servers to allow preflights (as it looks like that might be more common in the future, even for GET-requests).

https://github.com/cefsharp/CefSharp/issues/3277

**Comment by Krisell** [comment]
An update was made to https://github.com/cefsharp/CefSharp/issues/3277#issuecomment-734112224 with a confirmation that the issue is caused by updated CORS policies in recent chrome versions, and the suggestion to remove custom headers to external domains.

**Comment by dbuechel** [comment]
Okay, thanks for the update. So this means that I will need to filter the requests and only add our custom headers to requests which target the same domain as the currently loaded page. Do you know whether I need to filter by domain or even by subdomain (e.g. `test.org` or even `subdomain.test.org`)?

**Comment by Krisell** [comment]
Yes precisely, and CORS do apply to subdomains as well (and even to the protocol and port, but that might not be an issue here).

So yes, comparing the complete domain of the loaded page with the complete domain of the request and only including the custom headers should they match.

**Comment by dbuechel** [comment]
Ah, I see. Excellent, thanks for the help. I will introduce the filter with version 3.1.1, which we plan to release end of this year.

**Comment by dbuechel** [comment]
Okay, I think I fixed the issue. @Krisell Could you please test the build linked below and verify that it now works as it should?

https://sebdev-let.ethz.ch/project/AppVeyor/seb-win-refactoring/builds/261

**Comment by Krisell** [comment]
@dbuechel I have tested now and all of the previous issues have been resolved. I also checked in the developer tools and verified that the BEK and CK are sent for on-domain requests but not for cross-domain. Great work!

**Comment by dbuechel** [comment]
Excellent, thanks for the quick response and your help in general. In that case the issue will be resolved with the upcoming version 3.1.1.

**Comment by jeroenhabets** [comment]
@dbuechel our customers have been impacted by this so I wonder if you can share the planned 3.1.1 release data?

**Comment by dbuechel** [comment]
@jeroenhabets We will release 3.1.1 before december the 24th, for sure.
