### ISSUE TITLE
Merge my contributed zh-CN Chinese translation file.

### ISSUE THREAD

**Issue by fishfree** [SafeExamBrowser/seb-win-refactoring#47]
[zh_CN.zip](https://github.com/SafeExamBrowser/seb-win-refactoring/files/5581369/zh_CN.zip)

**Comment by dbuechel** [comment]
Excellent, thanks a lot! I will integrate your translation in SEB, would you be willing to keep translating or at least reviewing text for SEB? I unfortunately do not speak Chinese, so I would need to use Google Translate to handle new text and at times, those translations are horribly wrong...

Regarding the file: SEB selects the language according to the system's two letter language code. Would this be "zh" or "cn" for Chinese?

**Comment by dbuechel** [comment]
@fishfree I'd need to know whether I should use "zh" or "cn", it won't be loaded correctly if I use the wrong language code...

**Comment by dbuechel** [comment]
@fishfree I'd need a response until end of this week, otherwise we'll have to postpone this for version 3.2.

**Comment by dbuechel** [comment]
I have added the text data. Could you please install the beta version and verify that it works?

https://sebdev-let.ethz.ch/api/buildjobs/dvl7q3d88i3ot2n3/artifacts/SEB_3.1.1.236_SetupBundle.exe

**Comment by fishfree** [comment]
@dbuechel Very sorry for replying late. I installed the application in a Chinese Windows, unfortunately it still starts up in English.

Chinese has 2 types: Simplified Chinese and Traditional Chinese, the former is usually zh-CN/zh_CN, the latter is usually zh-TW/zh_TW.  Language code is sometimes different from country code.

If you can only support country code, I think CN/cn is more possible.

Thank you very much!

**Comment by dbuechel** [comment]
I had it as "cn", but that didn't work as you said. I just changed it to "zh", let's see whether that works. Could you try the latest build again?

https://sebdev-let.ethz.ch/api/buildjobs/gkfoo3kra94eekid/artifacts/SEB_3.1.1.248_SetupBundle.exe

**Comment by fishfree** [comment]
@dbuechel It works now! Great work!
