### ISSUE TITLE
SEB+Moodle on Windows: Embedded videos do not play

### ISSUE THREAD

**Issue by FloMiLe** [SafeExamBrowser/seb-win-refactoring#475]
**Describe the Bug**
An embedded video in Moodle's quiz questions does not play inside SEB on Windows. The video does play under macOS (Safari/SEB) and a regular Browser on Windows.

It has been mentioned on SourceForge that only open-source video codecs are supported, e.g. [here](https://sourceforge.net/p/seb/support-requests/115/). However, I have encoded the video with all codecs available in [Handbrake](https://handbrake.fr), and none seemed to work. That is despite x264 should be open source according to [Wikipedia](https://en.wikipedia.org/wiki/List_of_open-source_codecs).

**Steps to Reproduce**
1. Create Moodle quiz to be used with SEB
2. Add question that contains an embedded video in the question text.
3. Open quiz in SEB on Windows.
4. See that the video does not play and only a small black frame is shown.

**Expected Behavior**
The video should play or be playable, as is the case in regular browsers, and in SEB on macOS.

**Screenshots**

**Version Information**
 - OS: Windows 10 Enterprise
 - SEB-Version 3.3.4

**Comment by dbuechel** [comment]
x264 is just an encoder (as Wikipedia already correctly states). Thus, to be able to play such a video within SEB, you'd still need a proprietary decoder for the H.264/MPEG-4 AVC format. One alternative which seems to have worked for other users in the past is [WebM](https://en.wikipedia.org/wiki/WebM), see also #362 or #102.

**Comment by danschlet** [comment]
For example this page gives some information about video codecs and their compatibility with different browsers: https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers

Note that according to the page above, WebM is only supported starting Safari 14.1 on Mac, which would mean in SEB running on macOS Big Sur 11.x (probably from 11.1) and Safari 15 for iOS/iPadOS, which means SEB running on iOS/iPadOS 15. If you need compatibility with older macOS/iOS versions, you need to provide MP4 movies for these platforms.

We are no web developers, but in the past an option was to use a Javascript movie player like flowplayer, JW Player or to embed videos from Vimeo or YouTube, as these video players provide videos in different formats for different web browsers. 

We asked our Moodle team if they have some best practices for using videos with Moodle and SEB and I will post the answer here. You can also search the forums on moodle.org as they are the primary source for information relating to Moodle and many there also use SEB.

Maybe some other SEB-Moodle users reading this can provide some hints.

**Comment by FloMiLe** [comment]
@dbuechel and @danschlet, thanks a lot for you quick and detailed replies!

I must admit beyond the obvious that I am not an expert on video formats. But I am glad your suggestion to use WebM does seem to work for me as well. It requiring recent OS and browsers is not going to be problem...
