### ISSUE TITLE
Problems displaying formulars in math mode 

### ISSUE THREAD

**Issue by rlamprecht** [SafeExamBrowser/seb-win-refactoring#48]
The SEB doesn't display formulas in the math mode. It either display the raw input or the error 'Math Mode not working'.

**Comment by Krisell** [comment]
@rlamprecht I think you need to provide a lot more detail about the issue, for instance what site is loaded. 

It sounds like the issue may be related to https://github.com/SafeExamBrowser/seb-win-refactoring/issues/46, and if it works in SEB 3.0.1 that is probably the case.

**Comment by dbuechel** [comment]
Yes, @rlamprecht please provide all the information required as specified in the issue template.

**Comment by dbuechel** [comment]
Please test the latest dev build, most likely the issue should be resolved due to the changes related with #46: https://sebdev-let.ethz.ch/project/AppVeyor/seb-win-refactoring/builds/261
