### ISSUE TITLE
Fatal Error on Opening (Windows)

### ISSUE THREAD

**Issue by hsinger12** [SafeExamBrowser/seb-win-refactoring#49]
Hello,

Just a bit of an issue, I have a student who has downloaded the Safe Exam Browser, and when he tries to open it we get a Fatal error message. I will be attaching an image. I am kind of clueless about what the issue is, and if you are able to help with it, it would be appreciated. Windows 10 Professional 1903.
![Error](https://user-images.githubusercontent.com/74926487/99996402-ae1f7a00-2d89-11eb-804c-45d82cbaad30.png)

**Comment by dbuechel** [comment]
Please refer to the solution provided in #33.
