### ISSUE TITLE
Can you compile SEB for Ubuntu?

### ISSUE THREAD

**Issue by Akaj-lab** [SafeExamBrowser/seb-win-refactoring#50]
### **Is your feature request related to a problem? Please describe.**
I'm so frustrated when I want to use SEB on my computer that runs Ubuntu. I have to use my brothers computer.

**Describe the solution you'd like**
Can you make .deb file that I can use on Ubuntu?

**Describe alternatives you've considered**
I have to use brothers computer since my teacher doesn't wat to change from SEB

**Comment by dbuechel** [comment]
Unfortunately not, we currently don't have the capacity to create and maintain a version for Ubuntu.
