### ISSUE TITLE
Does SEB support Grammarly ? Grammarly is working in SEB Win 3x and Mac 3x 

### ISSUE THREAD

**Issue by SACESEB** [SafeExamBrowser/seb-win-refactoring#508]
**IMPORTANT**
Please _always_ consult the documentation first before creating a bug report!
https://safeexambrowser.org/windows/win_usermanual_en.html

**Describe the Bug**
User is able to use the Grammarly application running in background while using SEB.

**Steps to Reproduce**
1. Install Grammarly desktop application into your machine (Win10)
2. Run the desktop application and keep it running in background.
3. Launch the Safe Exam browser and start typing some text inside the text box present in the exam.
4. Observe a small icon on top of the safe exam browser just besides the area where you are typing.
5. 5. Click on the Grammarly icon to get the text suggestions.

**Expected Behavior**
After step 4 & 5, User can see a small icon and get the text suggestions on top of the safe exam browser.

**Screenshots**
After step 4 & 5, Safe exam browser should not allow the Grammarly app to work on top of it.

**Version Information**
 - SEB-Windows Version [SEB 3.3.2]
 - OS Tested On: Windows 10 Home, Version 21H1
                          Windows 11 Home Version 21H2

 - SEB Mac Version [3.0]
 - OS Tested on: Mac Monterey v12.2.1 (MacBook Pro)
 
**Additional Context**
This issue is not reproducible on the version we were using earlier.
-SEB Windows Version [SEB 2.3]
 - OS Tested On: Windows 10 Home, Version 21H1

Can someone please confirm if SEB supports Grammarly? It was not working with the previous versions we used.

Thanks heaps.

Cheers,
DB

**Comment by dbuechel** [comment]
You can simply add Grammarly to the list of prohibited applications in your configuration, then SEB should terminate it during startup, see https://safeexambrowser.org/windows/win_usermanual_en.html#ProhibitedProcessesSection.

**Comment by danschlet** [comment]
I created a [separate discussion for the macOS version](https://github.com/SafeExamBrowser/seb-mac/discussions/247) (if you have an issue affecting both the Mac and Windows versions of SEB, please create separate issues in both repositories). I cannot reproduce the issue with SEB 3.1.1 for macOS.

Please note that we don't support any older SEB versions, always try to reproduce issues with the latest SEB version before reporting a bug.

**Comment by dbuechel** [comment]
> Have there been major changes to SEB, resulting in this change?

When comparing SEB 3.x with SEB 2.x, then yes indeed, there have been major changes (the application has basically been rewritten, though based on the functionality and mechanisms of the older version). See also https://github.com/SafeExamBrowser/seb-win-refactoring/discussions/507#discussioncomment-4116916.

> There will be lot of similar applications and we may not have the details of all such applications. How shall we go about it as if the applications will be accessible via SEB then it totally defeat the purpose of a controlled exam browser.

We simply can't test and manually add all the tens of thousands of applications there are in the world ourselves, there is some effort which the users resp. exam administrators intending to use SEB will have to put in when configuring and testing their exam setup.

Regarding this specific use case: SEB 3.x has a live application log where you can detect information about changes in the active foreground window as well as the application monitoring. Using the live log should help you resolve the issue fairly quickly.
