### ISSUE TITLE
issue with installation of safe exam browser

### ISSUE THREAD

**Issue by tohee** [SafeExamBrowser/seb-win-refactoring#51]
![Screenshot (39)](https://user-images.githubusercontent.com/70477206/91661831-50ef9180-ead6-11ea-8333-35b7b87d4098.png)
![Screenshot (39)](https://user-images.githubusercontent.com/70477206/91661834-52b95500-ead6-11ea-8e26-0d127e8147aa.png)
windows version 10
64-bit processor
safe exam browser version 3.0.1.163
[Safe_Exam_Browser_20200830151744 log file.txt](https://github.com/SafeExamBrowser/SafeExamBrowser-Website/files/5146970/Safe_Exam_Browser_20200830151744.log.file.txt)

**Comment by dbuechel** [comment]
It seems like the .NET Framework failed to install. Please make sure you have enough free disk space available (at least 4.5 GB) and try again or try to install it manually before installing SEB: https://dotnet.microsoft.com/download/dotnet-framework/net472
