### ISSUE TITLE
Windows remote desktop connection is allowed in the SEB 3.1.0 version

### ISSUE THREAD

**Issue by alizdd** [SafeExamBrowser/seb-win-refactoring#52]
We have faced in our latest tests that after we connect a device via windows remote connection service than we can enter an exam without any block. As I read in the forums Safe exam browser should filter the undesired services like remote connection but we can enter an exam with the remote connection well,

This is a big issue because of we can't block windows remote connection in the prohibited processes list

I think this is a bug since developers mentioned that SEB should filter the services
https://sourceforge.net/p/seb/discussion/3704033/thread/2aa02d90/

And we tested with 2.4.1 version of seb, it works as expected, I think it is about the latest update

Any help is appreciated,

1. Connect to a device via windows remote desktop connection
2. Start a safe exam inside of remote desktop
3. There will be no error thrown about remote connection
4. We can take the exam succesfully inside of remote connection

Expected Behavior:
An error must be occured when we try to start an exam inside of remote connection

 - OS: Windows 10 professional
 - SEB-Version 3.1.0

**Comment by dbuechel** [comment]
Thanks for the report. I think you might be unaware of an important change we had to introduce with version 3.0.1: Starting with this version, the SEB service functionality (which, among other things, prevents remote connections) is now bypassed by default. This means that you need to enable it again in your configuration, namely under Security > SEB Service (Win) > uncheck "Ignore SEB Service".
