### ISSUE TITLE
Managed personal and Managed shared Devices

### ISSUE THREAD

**Issue by KaanOezsoy** [SafeExamBrowser/seb-win-refactoring#525]
Hallo Zusammen

Wir haben das Problem mit dem SEB:
Bei einem Enrollment mittels MS Autopilot wird ja Teams mit diesem Machine-Wide Installiert. Dies passiert bei Managed personal und Managed shared Devices. Beim Managed Personal haben wir keine Probleme aber mit dem Shared.
Die MS Teams Prozesse beim Shared Device werden in einem anderen (System?) Kontext gestartet, so dass der User diese nicht beenden kann. In Zusammenhang mit der Safe Exam Browser SW ein Problem, denn damit diese läuft, müssen die MS Teams Prozesse beendet werden.

Sämtliche Unterlagen sowie Fehlermeldungen sind im Anhang. 

Freundliche Grüsse
Kaan Özsoy
[SEB.zip](https://github.com/SafeExamBrowser/seb-win-refactoring/files/10114852/SEB.zip)

**Comment by dbuechel** [comment]
Da können wir leider nichts direkt dazu beitragen, das ist eher ein SysAdmin- resp. Depoyment-Problem. Vielleicht kann MSFT resp. deren Support-Foren da weiterhelfen, wäre etwas eigenartig, wenn man Teams nicht ausschliessen könnte.
