### ISSUE TITLE
Install error (Path cannot be found)

### ISSUE THREAD

**Issue by mrtruebeliever** [SafeExamBrowser/seb-win-refactoring#537]
**Describe the Bug**
When installing I get the message "The feature you are trying to use is on a network resource that is unavailable. Click OK to try again, or enter an alternat path to a folder containing the installation package 'SafeExamBrowser.msi' in the box below."

**Steps to Reproduce**
1. Go to 'SEB_3.4.1.505_SetupBundle.exe'
2. Click on 'Install'
3. See error

**Expected Behavior**
Program installs without error

**Screenshots**
<img width="821" alt="SEB install error" src="https://user-images.githubusercontent.com/11655167/205610180-0cef942e-95e3-4b33-80dc-63d7fafef5cb.png">

**Version Information**
 - OS: Windows 10 Education, Version 21H2]
 - SEB-Version SEB 3.4.1.505

**Comment by dbuechel** [comment]
Am I correct in assuming that you still have the legacy version (SEB 2.x) installed and are now trying to update to SEB 3.x? If yes, then it looks like you're missing the cached setup package of SEB 2.x, which is required to properly uninstall the old version.

**Comment by dbuechel** [comment]
This utility from MSFT might help resolving your issue: https://support.microsoft.com/en-us/topic/fix-problems-that-block-programs-from-being-installed-or-removed-cca7d1b6-65a9-3d98-426b-e9f927e1eb4d.

**Comment by dbuechel** [comment]
Closed due to lack of feedback.
