### ISSUE TITLE
Blank page displayed by SEB during Remindo digital exam

### ISSUE THREAD

**Issue by sabaird** [SafeExamBrowser/seb-win-refactoring#538]
**Describe the Bug**
We are using SEB in combination with Remindo for digital exams. Recently the following has been happening: midway through the Remindo digital exam, SEB will not display the page. There is no error shown, the page just remains blank. This is not happening for all students taking the exam. All the students in a particular exam location are using the same hardware with the same OS, build, local installed software, so are, for all intents and purposed, identical. The PCs are HP EliteOne 800 G5 with Intel Core i7-9700, 8GB DDR4 RAM, 512 GB SSD.
Paragin, the supplier of Remindo, have indicated that there was no issue with Remindo in the time window of the digital exams affected by this issue.
When examining the Event Viewer on the PCs affected, we encounter 2 errors that are occurring close to one another (< 30 seconds apart).

.NET runtime error
```
Application: CefSharp.BrowserSubprocess.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.SEHException
   at <Module>.CefExecuteProcess(CefMainArgs*, scoped_refptr<CefApp>*, Void*)
   at CefSharp.BrowserSubprocess.SubProcess.Run()
   at CefSharp.BrowserSubprocess.BrowserSubprocessExecutable.Main(System.Collections.Generic.IEnumerable`1<System.String>, CefSharp.RenderProcess.IRenderProcessHandler)
   at CefSharp.BrowserSubprocess.Program.Main(System.String[])
```
Application Error 
```
Faulting application name: CefSharp.BrowserSubprocess.exe, version: 103.0.120.0, time stamp: 0xbbfc65c4
Faulting module name: KERNELBASE.dll, version: 10.0.18362.2274, time stamp: 0x7c302d74
Exception code: 0xe0000008
Fault offset: 0x0000000000043fa9
Faulting process id: 0x337c
Faulting application start time: 0x01d903dde6830a15
Faulting application path: C:\Program Files\SafeExamBrowser\Application\CefSharp.BrowserSubprocess.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 02a8c52c-9361-4225-8c25-87d7f74c9c63
Faulting package full name: 
Faulting package-relative application ID: 
```

**Steps to Reproduce**
So far, we have been unable to forcibly reproduce the issue. The issue doesn't occur during every Remindo digital exam, nor does it affect all workstations. It is also not the case that a specific workstation exhibiting the issue will consistently exhibit the issue during every Remindo digital exam taken on that workstation.

**Expected Behavior**
Simply for the page to be displayed.

**Screenshots**
![SEB_white_screen](https://user-images.githubusercontent.com/120112958/206473939-65318ebe-1209-4619-a728-3c5cb96a4570.jpg)

**Version Information**
 - OS: Windows 10 Professional, version 1909
 - SEB-Version 3.4.0

**Additional Context**
We were experiencing this issue with SEB-version 3.1.1. We upgraded all workstations to SEB-3.4.0, but we are still experiencing the issue.

**Comment by dbuechel** [comment]
This looks like an issue in the browser engine. You might find more information in the application log of the browser component, to be found under `%LocalAppData%\SafeExamBrowser\Logs`.

**Comment by sabaird** [comment]
Thanks for your response. As they are shared workstations we perform a daily clean-up of all local profiles on the workstation. We will therefore have to wait until the issue reoccurs and secure the logs immediately following this.

**Comment by sabaird** [comment]
We have secured logs from several workstations that exhibited the issue. While the logs are quite diverse in warnings and errors logged, there is one error that occurred on 5 of the 6 workstations from which we secured the logs:
`ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is disabled, ANGLE is `

We found an article online on this error ([https://stackoverflow.com/questions/67501093/passthrough-is-not-supported-gl-is-disabled]). We have attempted to apply the following switches on the SafeExamBrowser executable:

`--headless`
`--disable-gpu`
`--disable-software-rasterizer`

However, our impression is that they are not being applied. As you can't immediately see the result of these switches, we tested using the `--show-fps-counter` switch, which should display an FPS counter and GPU activity. However, these weren't displayed. When we tested this on Edge, it worked as expected. Hence our conclusion that the switches aren't being applied using SafeExamBrowser.

Perhaps we are barking up the wrong tree. 

Attached is an Excel containing the content from each of the Browser.log files from the path you indicated: [Browser.log.xlsx](https://github.com/SafeExamBrowser/seb-win-refactoring/files/10390775/Browser.log.xlsx)

We appreciate any guidance that can be offered. Thanks!

**Comment by danschlet** [comment]
See my answer in https://github.com/SafeExamBrowser/seb-win-refactoring/issues/551

**Comment by dbuechel** [comment]
I'd say we track the work for custom command line arguments under #551 as remarked by @danschlet. Please feel free to extend or post your findings there, @sabaird .
