### ISSUE TITLE
Confusing label text and lack of focus in restart dialog

### ISSUE THREAD

**Issue by VirtualRusty** [SafeExamBrowser/seb-win-refactoring#548]
**Is your feature request related to a problem? Please describe.**
This dialog comes up during an SEB browser restart (when a problem forces a shutdown)
1. It doesn't describe what is required which is enter the exam access code
3. I recall there may be not be focus in the PIN entry field (need to manually click in field)

**Describe the solution you'd like**
1. The text should match the Mac version of SEB which uses plain English in this dialog
2. Ensure the cursor is in the dialog box when it appears and that it responds to the enter key

**Describe alternatives you've considered**
No alternatives

**Additional context**
![IMG_046387](https://user-images.githubusercontent.com/120538228/207743198-61892b42-10bf-44b9-a3d4-252adff7687b.jpg)

**Comment by dbuechel** [comment]
Could you elaborate which text you'd be expecting? This is the dialog asking the user for the settings password in order to decrypt the SEB configuration, and that's also what the message indicates.

**Comment by VirtualRusty** [comment]
The existing dialog text has no context and the text would only make sense to a developer anyway. In the real world environment of the exam room, running Inspera exams as is the case for us, an invigilator needs to know what is required to be done here. When you do this on a Mac it states "Enter Exam Password" (see image) which is staightforward and explains what is required at this point. The student entered this shared password at the start of the exam. (We also have an Administrators override/restart password for Inspera we enter later on in the restart sequence, so we and the student need to know what password to enter at this point). 
![start exam](https://user-images.githubusercontent.com/120538228/208012557-0718316b-419a-4f74-baf6-1669a99205b9.png)

**Comment by dbuechel** [comment]
@danschlet What do you opine regarding the naming? I don't quite see the need for change, as until now, everything related to the settings password in SEB for Windows is named "settings password" accordingly, see e.g. also in the configuration tool:

![grafik](https://user-images.githubusercontent.com/28347927/208155216-31b25c5d-e794-4ae8-b844-9bbce189a5ed.png)

**Comment by danschlet** [comment]
@dbuechel Yes, the password is officially called "settings password", but I think we have to see this from the end user (exam candidate) perspective. They try to start an exam, usually by clicking a link on a web page or after selecting an exam in the SEB Server exam list. They most likely don't know, that action loaded some configuration file containing SEB settings, they just expect an exam to start. Therefore it is surely less confusing for them, if they are queried for an "exam password" and not a "settings password". The term "settings password" makes total sense when a config file is opened from disk in the Configuration Tool, but less in an exam context. I think that was the reason that I changed the title of the password dialog a long time ago in the Mac/iOS versions, maybe there was even an according feature request. It's even possible that SEB 2.x had the same terminology, although I'm not sure about that.

Therefore I think this is a valid request, maybe you could change it for the next release at your convenience.

**Comment by VirtualRusty** [comment]
I don't have access to the exam environment at the moment, and I'm wondering if the initial dialog to enter the exam password to start the exam is different to the one that appears on a reboot of the SEB that I mention here. I want to emphasise that post-COVID a lot of larger institutions like universities are starting the use the SEB environment and that there are a lot of people exposed to this app for the first time in the exam room as the exam starts, both students and invigilators, the majority of whom are non-technical. No one in the exam environment looks at the settings, SEB just launches during login to the exam. I had to learn SEB on the run at the very first exam and even when I show new invigilators at the next exam session the reboot process, this dialog has caught me out as it has no context and I've put in the wrong code. Instead I just tell them "the first dialog is the exam code, the second dialog is the administrator's override code" due to poor labelling. I hope it can be changed as suggested so this is no longer an issue for us.

**Comment by dbuechel** [comment]
> [...] there are a lot of people exposed to this app for the first time in the exam room as the exam starts, both students and invigilators, the majority of whom are non-technical. No one in the exam environment looks at the settings, SEB just launches during login to the exam. I had to learn SEB on the run at the very first exam [...]

Well, that's definitely not good at all and also not the way things are intended to be. SEB for Windows is a complex application within the equally complex SEB ecosystem with a myriad of different use cases and configuration options. It requires a minimal level of introduction and familiarity in order to be used meaningfully, there's just simply no way around it.

I think I more or less copied the terminology from the legacy version, it appears it was even more technical there: https://github.com/SafeExamBrowser/seb-win/blob/master/SebWindowsClient/SebWindowsClient/SEBUIStrings.resx#L178

@danschlet Sure, I can change the text for version 3.5.0. Which instances would you like to change? There's also the use case with the local configuration, where "exam password" doesn't seem to quite fit, or what do you think (see https://github.com/SafeExamBrowser/seb-win-refactoring/blob/master/SafeExamBrowser.I18n/Data/en.xml#L582)?

**Comment by VirtualRusty** [comment]
That's great. I know one of the dialogs in the SEB reboot on Windows lacks focus (cursor in field) and I think it was this one, if that can be checked as part of the investigation.

**Comment by danschlet** [comment]
@dbuechel, yes, the use case with the local client configuration should show a different error message. In the macOS/iOS version, the settings password is only queried when opening a client config (not afterwards when starting SEB, while this config is loaded from the persisted system settings store). I think this is different in the Windows version (probably those latter two cases need different messages). The one in the macOS/iOS version when opening a client config is:

Title: Configuring Client
Message: Enter the password used to encrypt these settings:

I'm not sure if this message (for this use case) is actually better than the current Windows message "Please enter the settings password for the selected configuration:", maybe in this case the Windows message makes more sense.

When starting SEB with local client settings which are encrypted, I think a message like 

Title: "Starting Session" 
Message: "Enter session password:" 

would make sense.

What do you think, @VirtualRusty ?

**Comment by VirtualRusty** [comment]
@danschlet I didn't see this last post until the last few days ago...

I'm not sure what this last comment refers to as I've not seen this dialog on the Mac version as below. What conditions invoke this dialog?

> The one in the macOS/iOS version when opening a client config is:
> 
> Title: Configuring Client Message: Enter the password used to encrypt these settings:

Also, is this referring to my initial posting or something else?

When starting SEB with local client settings which are encrypted, I think a message like

Title: "Starting Session"
Message: "Enter session password:"

In any case, to return to the original proposal I made which may address the above as well, I've just done a local config test file in the Mac to get a better idea of how it works and run it locally on the PC, so I can see at least a few ways it might be implemented. I’ve worked out which setting does what and I must say, as an invigilator of now 50 separate SEB based exams, I had no idea how all this stuff worked from the admin/config side of things. And realistically I shouldn’t need to. So my issue with the arcane labelling on the Windows client holds true that its wording bears no relation that I can see to how the end user, the exam candidate or assisting invigilator, actually use the SEB in an exam environment.

I think when addressing dialog word choice, use as much as possible the common language of the exam candidate, and the invigilator who may need to reboot the SEB, and their understanding of what they are doing in the exam room and/or electronic exams.

For example we as exam staff communicate to the student they are sitting an exam at a particular date and time, and they enter the room understanding they are sitting an exam. We mention the SEB which they need to pre-install before entering the room, and that app has the word exam in its name – safe exam browser. We also give them an exam password, a code, so they can enter or initiate the exam they are sitting. This idea remains true regardless of whether they access the exam via an enterprise level signon (such as universities), a URL or a locally launched .seb file delivered via other means. They are still sitting an exam in the broadest sense. (The word exam is universally understood and can cover assessments or quizzes etc). I’m not sure what other use cases there are, but if they are to access an exam then the dialog should reflect that in the words it displays. So I still think the Mac dialogs should be replicated on the PC, as illustrated above – “Starting exam – enter exam password” explains exactly what is happening. As an invigilator in a 250+ seat room, I do about 20 SEB reboots a day on BYODs often moving from one to the other in succession. I don’t want to have to think about which OS I’m attending to at any moment (its hard to tell from the screen side as they look alike nowadays), and not have to click in dialog boxes to enter the admin code, which is the case with Win SEB at the moment. If a small number of candidates have different use cases to the university enterprise level rollout, where for some reason ‘exams’ is not the right label, then the person sending them details can easily explain it to them in instructions, and any admin people should have enough knowledge to know what it means if they are doing a configuration setup or change. Administrators are the smallest of all the user cohorts and the most technical so they should be able to figure out what is what.

**Comment by VirtualRusty** [comment]
The issue with the dialog at SEB Win launch and during SEB reboots is the window itself has lost focus. The cursor is present in the field, the dialog is just not 'selected/active' or whatever the term is [start SEB no focus](https://user-images.githubusercontent.com/120538228/212655105-6fca107e-6a15-46a6-849d-a7cbb978fa32.png)

**Comment by VirtualRusty** [comment]
And if the dialogs are being changed, the quit SEB dialog could also be simplified to match the Mac one, which simply says enter quit password. I'm all for the Win and Mac apps to have universal interfaces:-)

![win quit password](https://user-images.githubusercontent.com/120538228/212656123-88476437-0126-446a-9cfd-9bf18c5d276b.png)

![mac quit password](https://user-images.githubusercontent.com/120538228/212656542-173a2bd6-ca04-4c90-8dfe-c392263f02e9.png)

**Comment by VirtualRusty** [comment]
While this isn't critical it would be good for the dialog text to be brief like on the Mac SEB

![quit screens](https://user-images.githubusercontent.com/120538228/213055695-d0cf73c4-a92b-489c-ab6e-d17a4efabc72.png)

**Comment by danschlet** [comment]
Yes, I totally agree with what you wrote. I have to admit that we should have spend more time on making sure the dialogs match in all SEB versions. It's one of these things which make a difference in everyday use of the software. They may seem less critical than fixing crashes or adding new features which stakeholders demand. But even such seemingly small usability improvements can make a big difference. I'd wish we'd have a dedicated staffer who we could task with going through all the UI text and suggest improvements or point out where it needs to be unified. As we don't have that resource, it's very helpful to get such feedback from the community, thank you!

It's good to hear that you feel like the word "exam" is suitable. Somehow I had the impression that in the US usually "test" is used and "exam" may have a slightly different meaning (more like the whole process of doing tests/quizzes/assessments and getting grades for it).

The focus issue we should definitely look into. I remember when I was helping out with programming in previous SEB versions (2.x) that it wasn't so straight forward on Windows to always make sure that the correct window and text field gets focused. But we'll try to fix it.

**Comment by VirtualRusty** [comment]
thanks @danschlet for the positive response, I didn't expect to be spending so much time on this!

As to the differences between exam and test, most US universities use the term exam on their web sites. I'm unsure if US students colloquially call them tests, but formally they are exams. I'm not an academic but a test is usually a small or incremental mid-term assessment to either test knowledge gained so far or to consolidate knowledge learned to date, whereas an exam is the formal assessment at the end of session or the completion of the course being undertaking, the results of which end up on the student's academic transcript. So when I work at scale in the auditoriums students are sitting the formal exams. 

On the topic of universal interface, there seems to be forum here that would cover the SEB in general, as they seem to be specific to Mac or PC, but its likely more practical that way. I will be working again in April and will see if there are still any interface differences that cause issue when working rapidly from one device to another.

**Comment by dbuechel** [comment]
@VirtualRusty Could you please elaborate when you encounter the focus issue resp. how exactly you're starting SEB when it occurs?

**Comment by VirtualRusty** [comment]
@dbuechel 

- The first dialog "Settings Password Required" is not in focus on initial launch of SEB (eg via the .seb config file loading), - "Settings Password Required" dialog also lacks focus on a restart of SEB during exam. 
- However, the "Quit Password Required" dialog, when you click the Quit/Terminate Session icon, lower right on the screen, does have focus.

**Comment by dbuechel** [comment]
> The first dialog "Settings Password Required" is not in focus on initial launch of SEB (eg via the .seb config file loading), - "Settings Password Required" dialog also lacks focus on a restart of SEB during exam.

We already have investigated this issue, and if I remember correctly, the root cause was the fact that in Windows, an application cannot steal or force the input focus from another resp. the currently active application (for obvious security reasons). If an attempt to do so happens, then the respective application icon will be highlighted with an orange flashing color in the taskbar.

I'll try to have another look at it, but there is, as explained above, most likely nothing we can do about the initial focus issue.
