### ISSUE TITLE
Failed to Start a New Session

### ISSUE THREAD

**Issue by aamfirdaus** [SafeExamBrowser/seb-win-refactoring#55]
I installed SEB 3.0.1 and created a config file. I asked clients to install the same file version and they can run the config file. However, some of my clients installed the latest version 3.1.0, and some of them succeeded, but some failed to start a new session. 

I thought this happened because the different version of the creator's SEB and the clients. However, some of them succeeded. It is now narrowed down to the case when the Windows 8/10 is not updated to the latest. 

However, after the Windows is updated, the issue remains. It failed to start a new session.

**Comment by dbuechel** [comment]
Could you please provide the log files of the affected machines? They can be found under `%LocalAppData%\SafeExamBrowser\Logs`.

**Comment by aamfirdaus** [comment]
Thank you for your response. Here are some of the log files.

[2020-11-26_17h10m21s_Client.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/5620578/2020-11-26_17h10m21s_Client.log)
[2020-11-26_17h10m21s_Runtime.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/5620579/2020-11-26_17h10m21s_Runtime.log)

**Comment by dbuechel** [comment]
It appears that there is some issue with the WCF communication between the application components of SEB. Are there any related messages in the Windows event log of these machines?

**Comment by aamfirdaus** [comment]
There is no log regarding this issue. The case was found on a device whose Windows was not up to date, and I thought there is no need to update since the bundle already contains Net Framework.

**Comment by dbuechel** [comment]
Updates should always be installed in a timely fashion, not only because of security concerns, but also because Windows and the .NET framework themselves can contain bugs or other issues which may be resolved in an update.

**Comment by aamfirdaus** [comment]
All right. Thank you so much,
