### ISSUE TITLE
Trust centre office 365 and function popup

### ISSUE THREAD

**Issue by rmjonkeredu** [SafeExamBrowser/seb-win-refactoring#554]
**IMPORTANT**
Please _always_ consult the documentation first before creating a bug report!
https://safeexambrowser.org/windows/win_usermanual_en.html

**Describe the Bug**
When Excel (versie O365) is permitted two errors emerge which I suspect are related (hence my combination in 1 report). 
1) When in the trust centre in Excel the option that files that are downloaded from the internet are only availabe in secure view is ticked (our laptop install restores this with every startup) SEB blocks the popup that normally appears. What happens next is that the student gets a message that the file is corrupted and cannot be viewed. When the teacher than changes the settings with that student, the file can be opened normally. This is not fun when you have 100+ students. 
2) When a student enters a function in excel e.g. =average and then clicks the function in the upper bar to launch the function menu, excel shuts down. Normally there is a popup with the function menu.

**Steps to Reproduce**
as above

**Expected Behavior**
Files should be opened normally, and if the trust centre function is on, the popup should appear where the student should be able to click 'edit'. 
Function menu should appear, or not appear, but for sure excel should not shut down.

**Screenshots**

**Version Information**
 - OS: [Windows 10 professional
 - SEB-Version [e.g. SEB 3.4.0

**Additional Context**

**Comment by dbuechel** [comment]
Closed due to lack of feedback.
