### ISSUE TITLE
SEB is running keeps flashing in the screen and prevents student from starting test

### ISSUE THREAD

**Issue by youphorst** [SafeExamBrowser/seb-win-refactoring#556]
**Describe the Bug**
Multiple users of our assessment platform reported a problem with SEB. After pressing start in the assessment platform, the expected result would be that SEB is launched and the right configuration tool is started. This was the case for most students of this exam, but for a few a strange error occurred.
After pressing start, the screen with the message 'SEB is running' was flashing continuously. I expect that not all checks were done properly, as the student receives the message that they didn't have access to the assignment. This is only happening if the SEB isn't used (properly).

**Steps to Reproduce**
We haven't been able to completely reproduce it, so we expect is is caused by something in the hardware used by the students.
The steps that the students took:
1. Navigate to the exam
2. Click on start
3. Our assessment platform automatically loads the SEB Config file and opens it in SEB.
4. Our assessment platform handles the login automatically.
5. The student clicks 'start' again, now in SEB
6. SEB is (semi) started and starts flashing. A video is added.

**Expected Behavior**
The expected behavior is that after step 5 of the steps to reproduce the student is able to start the exam without any problems.

**Screenshots**
I've added a video which we received from the users.

https://user-images.githubusercontent.com/123061996/213392069-e35d44d6-049e-4924-9821-2aead824276a.mov

**Version Information**
- OS: Windows 11
- SEB: version 3.4.1
I've added screenshots of the hardware and drivers of the student's device.
![IMG_8829](https://user-images.githubusercontent.com/123061996/213391947-f5d3f9d3-173f-46da-a8b5-d6e4016cf58f.jpg)

**Additional Context**
The user indicated that the virusscanners and firewall were deactivated, the latest version of SEB was downloaded and the operating system was updated to the latest version.

If you want I can give you access to a test environment of our assessment platform.

**Comment by dbuechel** [comment]
This looks like an issue with ESET anti-virus or Cisco's WebEx meeting tool, please refer to #520 or #333.
