### ISSUE TITLE
[Math Error] in expression after approx. 30 s.

### ISSUE THREAD

**Issue by lucaboesch** [SafeExamBrowser/seb-win-refactoring#56]
Hi,

Has that happened to you?
If you have MathJax in a question or answer option, after the initial correct display, once approximately 30 seconds passed, the formula is replaces by [Math Error].

**Steps to Reproduce**
1. Create a quiz with a question including MathJax
2. Attempt the quiz
3. On the page displaying that question, wait for approximately 30 seconds

**Screenshots**

![IMG_5712](https://user-images.githubusercontent.com/377279/100631294-d9770b80-332b-11eb-8b8d-2fcf35872ba7.JPG)
![IMG_5713](https://user-images.githubusercontent.com/377279/100631275-d4b25780-332b-11eb-93f8-61bbca4444b0.JPG)

**Version Information**
 - Microsoft Windows 10 Famille, Version 10.0.19041
 - SEB 3.1.0.228

**Additional Context**
It seems not theme related. That happens in our theme as well as in Boost.

**Comment by dbuechel** [comment]
I do not have any experience with MathJax. Did you check the developer console, there might be some info logged when the error happens. There is an issue with CORS requests (#46) which will be solved with the upcoming patch version 3.1.1, you could try the beta build to see whether this also resolves your problem:

https://sebdev-let.ethz.ch/project/AppVeyor/seb-win-refactoring/builds/261

**Comment by jgilevich** [comment]
We have a same error in with the STACK (Maxima) plugin.

**Comment by dbuechel** [comment]
Did you try the beta build linked above which contains a fix for the CORS issue?

**Comment by jgilevich** [comment]
Hi, I tried the beta build and it works! When it is due to be released?
Thank you.

**Comment by dbuechel** [comment]
No later than end of this year, probably next or the week after next week.
