### ISSUE TITLE
Unable to install the SEB

### ISSUE THREAD

**Issue by deepakbanwala0001** [SafeExamBrowser/seb-win-refactoring#562]
I am not able to install the SEB in Windows 10. Please find the attached screenshot and SEB logs. Please suggest what could be the reason. 

![86145946-2f71-4201-b9e0-b160225ad914](https://user-images.githubusercontent.com/96123516/216246227-9f8b976b-07c6-4bd6-ac02-d2021ddbac84.jpg)
[Safe_Exam_Browser_20230124163459 (1).log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/10565662/Safe_Exam_Browser_20230124163459.1.log)

**Comment by dbuechel** [comment]
The WebView2 component fails to install. You can try to install it manually and then retry the setup bundle, or install all required dependencies manually and then install the MSI setup of SEB:

https://github.com/SafeExamBrowser/seb-win-refactoring#requirements
https://github.com/SafeExamBrowser/seb-win-refactoring/releases
