### ISSUE TITLE
SEB doesn't force close Chrome Remote Desktop

### ISSUE THREAD

**Issue by stignarnia** [SafeExamBrowser/seb-win-refactoring#575]
**Describe the Bug**
SEB forces the user to close things like Teamviewer and most other remote desktop applications, but fails to do so with Chrome Remote Desktop.

This app uses the `remoting_host.exe` executable file.

I know these can be added manually in the configuration but I feel like its absence is a bug because so many similar software are already blocked.

**Steps to Reproduce**
Open SEB from inside a Chrome Remote Desktop session and see that it lets you continue

**Comment by dbuechel** [comment]
Thanks for reporting the issue to us, we'll see that we can add Chrome Remote Desktop to the default list of prohibited applications for the upcoming release version 3.5.0.

**Comment by dbuechel** [comment]
The change can now be tested in the latest beta build for version 3.5.0: https://sebdev-let.ethz.ch/api/buildjobs/91lrp0snq6av4g1x/artifacts/SEB_3.5.0.530_SetupBundle.exe.
