### ISSUE TITLE
Lenovo Yoga 6 

### ISSUE THREAD

**Issue by dkummer63** [SafeExamBrowser/seb-win-refactoring#586]
A student was in an exam with the SEB, was able to pass it, but then the computer got stuck and displayed a blocked, black screen. ctrl-alt-del only shows a button 'Cancel', but it doesn't go any further. 45 seconds on the off button doesn't help, neither does the reset button. I'm frankly at a loss as to what else to do.

**Comment by dbuechel** [comment]
Then there either is a hardware malfunction or another particular issue with that device. According to a quick internet research, most Lenovo devices should perform a hard shutdown when pressing the power button for more than 10 seconds.

We can't really do much more from afar, but if you should find any useful information in the SEB or system logs that would indicate an issue with SEB itself, please feel free to post them here.
