### ISSUE TITLE
SEB_3.1.0.228_x86_Setup.msi will not install on Windows 7.

### ISSUE THREAD

**Issue by Cad1mus** [SafeExamBrowser/seb-win-refactoring#59]
When you run the MSI it fails looking for an alternate path for SEB_3.0.1.163_x86_Setup.msi

![image](https://user-images.githubusercontent.com/43783077/101933051-a1808b80-3ba9-11eb-90c8-dc55053e0ecc.png)

**Comment by dbuechel** [comment]
How are you trying to install the setup? According to the error message, you're trying something with a network resource?

**Comment by Cad1mus** [comment]
I’ve tried from both a network share and from C:.  But I was just running SEB_3.1.0.228_x86_Setup.msi


[cid:image001.png@01D6D1F3.9ADD70B0]<https://can01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.hwcdsb.ca%2F&data=02%7C01%7Cr.raaymakers%40tvdsb.ca%7Cc82a8c2ffaf042ade83808d74db7e963%7C2024c5d6bed5470598acf83e64a78e99%7C0%7C0%7C637063324620675199&sdata=OzeesfdwURg0VohJ9sMH4Nxrwjyu4oyXodOqsCkkogs%3D&reserved=0>
Chris Cornish
Senior Client System Support Analyst – Technology Lead
Information and Communication Technology
Hamilton Wentworth Catholic District School Board
Tel: 905.525.2930 x 2972
Fax: 905.528.9448
Email: cornishc@hwcdsb.ca<mailto:cornishc@hwcdsb.ca>

**Comment by dbuechel** [comment]
Hm, that is odd indeed. I don't quite understand your use case, to be honest. What are you exactly trying to do?

**Comment by dbuechel** [comment]
If you're a student, you should anyways use the setup bundle, as it also installs all required dependencies to run SEB.

**Comment by Cad1mus** [comment]
> Hm, that is odd indeed. I don't quite understand your use case, to be honest. What are you exactly trying to do?

I was preparing deployment packages for SCCM so I was using the MSI's.  When the Windows 7 deployment wasn't working I ran the MSI manually and that was the error I got.

**Comment by dbuechel** [comment]
Windows 7 isn't officially supported anymore. Could be that this is the issue, but you might also have a network issue here. I personally have never encountered this error message when installing SEB 3.x.

**Comment by Cad1mus** [comment]
> Windows 7 isn't officially supported anymore. Could be that this is the issue, but you might also have a network issue here. I personally have never encountered this error message when installing SEB 3.x.

I totally understand the Windows 7 not being supported.  

163 still works on Windows 7 so hopefully there isn't anything in the new configuration file that will not work on the older version.

**Comment by dbuechel** [comment]
There shouldn't be any such thing. SEB 3.x isn't officially supported, but should still work on Windows 7, though I haven't tested it myself since a long time. And we always recommend to use the latest release version, as we are constantly improving and updating SEB.
