### ISSUE TITLE
Some students cannot take exam because of "Wrong Browser Exam Key"

### ISSUE THREAD

**Issue by tavaba** [SafeExamBrowser/seb-win-refactoring#595]
I'm coducting exams for a university. The students bring their own devices to take the exams. I prepared 2 SEB configuration files (1 for Windows, 1 for Mac) with proper instruction for the students.
This last for 1 year.
During the process, a small amount (less then 1%) of students cannot take exams on their own devices because of "Wrong Browser Exam Key", although the students exactly follow my instruction. I assumed that some security softwares on student's computers might filter SEB requests, but I was wrong. The problem occurs even on a computer with fresh installed Windows.

**Comment by dbuechel** [comment]
Could you share the log files for the session of an affected computer? We'd definitely need more information or better yet a way to reproduce the problem in order to be able to investigate the issue further. Also, how or where did you get the message that the browser exam key is wrong?

**Comment by dbuechel** [comment]
Are there any updates on this issue? Otherwise, we'd need to close it due to lack of feedback.

**Comment by dbuechel** [comment]
Closed due to lack of feedback.
