### ISSUE TITLE
SEB gesperrt

### ISSUE THREAD

**Issue by SebastianZiegler** [SafeExamBrowser/seb-win-refactoring#60]
Version 3.1

What could be the reason?

![IMG-20201214-WA0024](https://user-images.githubusercontent.com/2564530/102080779-5071d100-3e0f-11eb-85ac-969430045e62.jpeg)

**Comment by dbuechel** [comment]
As the error message already says, a user switch or system lock has been performed. The exact reason can be found in the client log.

**Comment by SebastianZiegler** [comment]
Hello,

we have lots of these problems again, where the location of the client log?

Thx
Sebastian

**Comment by danschlet** [comment]
We found out this problem also happens if users close the lid of their PC laptop while SEB is still running. Quit SEB before closing the lid of your laptop.

**Comment by dbuechel** [comment]
> we have lots of these problems again, where the location of the client log?

`%LocalAppData%\SafeExamBrowser\Logs`
