### ISSUE TITLE
Error : "This computer appears to be a virtual machine"

### ISSUE THREAD

**Issue by Plekke** [SafeExamBrowser/seb-win-refactoring#604]
Hi,

When starting SEB from Bookwidgets we get the error "This computer appears to be a virtual machine"
The issue is since the latest upgrade to 3.5.0.

we have several computers that hasn't upgraded yet. (which run on the 3.4.1) these work fine.

![afbeelding](https://user-images.githubusercontent.com/131015455/233988569-4ee1ff0a-5742-48a4-a790-8b74536c4e4a.png)

 - OS: Win 10
 - SEB-Version: 3.5.0

**Comment by dbuechel** [comment]
Could you please specify what computers you are using? And please also post the log files of the affected SEB session(s), they can be found under `%LocalAppData%\SafeExamBrowser\Logs`.

**Comment by Plekke** [comment]
We are using Dell Latitude 3420 

[2023-04-24_14h51m31s_Runtime.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/11310612/2023-04-24_14h51m31s_Runtime.log)

**Comment by dbuechel** [comment]
Thanks for the information. This could indeed be a false positive, which would be most unfortunate. Are you using any virtualization solutions resp. are there any installed on your systems (e.g. VMware, VirtualBox, Hyper-V etc.)?

**Comment by Plekke** [comment]
No we aren't using any of virtualization solutions on our computers.

**Comment by dbuechel** [comment]
Could you please execute the following line in the command prompt of Windows and post the results here: `WMIC /namespace:\\root\cimv2 PATH Win32_PnPEntity GET DeviceID`

**Comment by Plekke** [comment]
Here you go.

[output.txt](https://github.com/SafeExamBrowser/seb-win-refactoring/files/11340113/output.txt)

**Comment by dbuechel** [comment]
Thanks a lot, we will analyze the output and report back our findings.

**Comment by Tim455** [comment]
I had the same issue and was able to get past incorrect detection by removing the device named "Microsoft Virtual Disk" device in device manager. After the exam was over I had the students press the "Scan for hardware changes" button to make the device reappear in device manager. 
This removed the following device PnP device list: `SCSI\DISK&VEN_MSFT&PROD_VIRTUAL_DISK\2&1F4ADFFE&0&000003`

**Comment by dbuechel** [comment]
Thanks a lot for the input @Tim455. That is indeed a false positive then, as we assume that to be part of a Hyper-V machine, see https://github.com/SafeExamBrowser/seb-win-refactoring/blob/master/SafeExamBrowser.SystemComponents/VirtualMachineDetector.cs#L20. We'll definitely need to fix that for the next release version.

**Comment by dbuechel** [comment]
The issue should now be fixed and can be tested in the latest beta version of SEB 3.6.0: https://sebdev-let.ethz.ch/api/buildjobs/ah1rr6cvqsd5yhaa/artifacts/SEB_3.6.0.558_SetupBundle.exe.

**Comment by Plekke** [comment]
The beta version seems to work!

**Comment by rensgri** [comment]
I use version 3.7 and I have same problem on my pc, could you help me. This test just allow using version 3.7, so i can't use vesion 3.9. I want to use SEB on monday
