### ISSUE TITLE
Change mouse cursor to picture

### ISSUE THREAD

**Issue by LazerK3** [SafeExamBrowser/seb-win-refactoring#606]
It's possible to change mouse cursor to picture. Then when inside exam you can view the picture as it is your mouse cursor.

1. Get a .ico picture and change file ending to .cur
2. Open mouse properties and change one of the cursors to the new .cur file
3. Save
4. When in exam the new pointer is visable.

 - OS: Windows 10 Education, Version 10.0.19044
 - SEB-Version 3.5.0

**Comment by dbuechel** [comment]
Thanks for your report. I'm not quite certain though whether I understand it correctly: Is this a feature request or a vulnerability report?

If the former, then I'm afraid that we won't be able to implement such a feature any time soon. If the latter, then I'm not quite sure about its impact, as one would assume that it is not possible to meaningfully cheat with a mouse cursor (or do you have the opposite experience from e.g. an exam?).

**Comment by LazerK3** [comment]
Well i guess it’s a feature request. You can in windows make your cursor quite big so there can be a lot of information visable.

**Comment by dbuechel** [comment]
Thanks for the clarification. As already stated, we'd then need to close this for now, as we already have a completely full backlog for resp. until the next year.
