### ISSUE TITLE
Start of Safe Exam Browser causes fatal Error

### ISSUE THREAD

**Issue by user230521** [SafeExamBrowser/seb-win-refactoring#615]
**Describe the Bug**
Installation went smooth but when running the application its shows a fatal error.

**Expected Behavior**
safe exam should start.

**Screenshots**
![image](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/134216555/de1dc3da-40dc-4637-a784-533fb3700dcd)

![image](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/134216555/1cf65e82-c07d-49ef-b720-e2dfb6762908)

![image](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/134216555/0f39da00-bd68-46fc-b95b-d51060683304)

**Version Information**
 - OS: Windows 10 Professional, [Version 10.0.19045.2251]
 - SEB-Version  3.5.0.544

**Additional Context**
I read the documentation and the hinds and solultions on #33 but still not working. I have further done all crosschecks to verify the Problem on my side, but wasn't able to find the problem. Its only Safe exam who causes trouble at the moment. Maybe you have an alternative way of solving the problem. I would need the Safe exam latest by wednesday. Thanks for your effort.

**Comment by dbuechel** [comment]
Please execute the following statement on the command prompt of Windows and post the output below: `WMIC /namespace:\\root\cimv2 PATH Win32_PnPEntity GET DeviceID`.

**Comment by dbuechel** [comment]
Thanks for the update. The command returned a plausible list of devices, so I can't really warp my head around why the same command would fail when executed from within SEB. But as you appear to have been able to solve the issue, I'd suggest to close it for now. But please feel free to reopen it or add new information in case the issue should reappear.
