### ISSUE TITLE
Screen Reader

### ISSUE THREAD

**Issue by AMcMichan** [SafeExamBrowser/seb-win-refactoring#616]
Hi,
We are using the latest version of SEB in a Bring Your Own Device School and have a combination of windows and mac laptops.

Would it be possible to have an in-built screen reader function within SEB that reads the text as it is written on the screen?  We are wanting this for a couple of our students with imparied vision.

Usually, they use a screen-reader within their usual browser, but this isn't available within SEB.

**Comment by dbuechel** [comment]
Thanks for your input. We unfortunately will not be able to implement a custom screen reader for SEB, that's quite definitely out of scope for us for the upcoming years, even if we'd get another full-time developer.

We however are working constantly on improving the accessibility of SEB, and with respect to it, the latest release version 3.5.0 brings a great many improvements and should work well with the two most common ones (NVDA and Jaws). Please do note (as stated in the release notes) that you'll need to use kiosk mode Disable Explorer Shell at the moment when using a screen reader with SEB: https://safeexambrowser.org/windows/win_release_notes_en.html.
