### ISSUE TITLE
Closing browser window  : ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer

### ISSUE THREAD

**Issue by abowman-unige** [SafeExamBrowser/seb-win-refactoring#620]
We had this error today when an user closed an browser window on an permitted external link.

SEB 3.5
Windows 10
Link used: [https://www.larousse.fr/dictionnaires/anglais-francais](https://www.larousse.fr/dictionnaires/anglais-francais )

ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer

[bug-closing-browser.zip](https://github.com/SafeExamBrowser/seb-win-refactoring/files/11611387/bug-closing-browser.zip)

**Comment by dbuechel** [comment]
Thanks for the report, we'll have a look at it as soon as possible.

**Comment by dbuechel** [comment]
I was able to have a look and tried to open the specified website in an additional browser window, but could not reproduce the issue. The page opened as expected and furthermore did not cause any unexpected behavior on closing.

There however appears to have been a security issue resp. an issue with the certificate validation on this site, looking at the client log you've posted:

```
2023-05-31 10:52:25.080 [22] - WARNING: [Browser Window #2] Request failed: ERR_CERT_AUTHORITY_INVALID (-202, resource request).
2023-05-31 10:52:25.295 [22] - WARNING: [Browser Window #2] Request failed: ERR_SOCKET_NOT_CONNECTED (-15, resource request).
```

There furthermore are a lot of related errors in the browser log. @abowman-unige  Are you able to reproduce the issue, and if yes, how?

**Comment by dbuechel** [comment]
@abowman-unige Are there any updates on this issue? Otherwise, we'd need to close it for now.

**Comment by abowman-unige** [comment]
No update from last time, i'll close it for now
