### ISSUE TITLE
Problem with Windows 11 Taskbar

### ISSUE THREAD

**Issue by jduminy** [SafeExamBrowser/seb-win-refactoring#622]
It appears that SEB overlays a taskbar on top of the Windows  taskbar.

On Windows 11, the taskbar is slightly bigger than on Windows 10, with the result that it peeps out over the top of the SEB taskbar. It is then possible to click on the Windows taskbar, with the result that it comes to the foreground, and then the full functionality of Windows is available to the user.

![image](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/4047646/2743b738-fa66-4c7c-aa00-0cc3c41d9633)

**Comment by dbuechel** [comment]
That is highly unlikely, I'd assume that is part of the webpage itself? Could you please post the entire image / screen shot in used in your use case, as well as the log files for the affected session (to be found under `%LocalAppData%\SafeExamBrowser\Logs`?

**Comment by jduminy** [comment]
OK, I have established that this behaviour is only when 'Kiosk Mode' is set to 'None' in the config. It is fine when the Kiosk Mode is set to 'Create new desktop' so will not affect live deploymemts.

**Comment by dbuechel** [comment]
Yes, obviously when not using a kiosk mode, SEB's UI is displayed on the default Windows desktop, possibly overlapping the Windows taskbar etc.
