### ISSUE TITLE
Private clipboard on Windows

### ISSUE THREAD

**Issue by 1TheITCrowd** [SafeExamBrowser/seb-win-refactoring#625]
**Is your feature request related to a problem? Please describe.**
Using Windows 11 - SEB Version 3.5.0
When taking a test in SEB it's possible to cut and paste text. In the background you could have a script running (10 lines of code) to replace certain text on the clipboard with other text. So when you paste the text again, your chosen text shows up.

For example: 
A script that listens to the clipboard for the string "1". When within SEB I cut the number 1 to the clipboard. The script sees number 1 on the clipboard and replaces the text on the clipboard to something predefined. Then when I paste the text in SEB I get my new text that the script put on the clipboard.

**Describe the solution you'd like**
Block the use of the clipboard all together or use a clipboard that is not accessible with third party apps.

**Describe alternatives you've considered**
Blocking CTRL+X, CTRL+C or CTRL+V  won't be enough because the hotkeys could be other key combinations

**Additional context**
It's better that I'm not publishing the code on here. This cheat has been actively used by our students

**Comment by dbuechel** [comment]
Thanks a lot for your report. This is a vulnerability which we're actually already aware of, and for which we've planned to implement a mitigation for the upcoming version 3.6.0.

**Comment by dbuechel** [comment]
We have implemented a first version of the functionality. It'd be great if you could have a look at the latest beta build and test it yourself: https://sebdev-let.ethz.ch/api/buildjobs/ds6r2vjrmd9vh9ra/artifacts/SEB_3.6.0.589_SetupBundle.exe. The different settings regarding the clipboard can be found under tab "Security" in the configuration tool.
