### ISSUE TITLE
Anydesk all versions accessible in SEB 3.4.1

### ISSUE THREAD

**Issue by FickelPaper** [SafeExamBrowser/seb-win-refactoring#627]
**IMPORTANT**
Please _always_ consult the documentation first before creating a bug report!
https://safeexambrowser.org/windows/win_usermanual_en.html

**Describe the Bug**
SEB 3.4.1 can be accessed via anydesk all version. Add any desk to blacklist. 

**Steps to Reproduce**
1. Go to '.Anydesk..'
2. Click on '..Share screen..'
3. Scroll down to '..accept..'
4. See error - Full SEB available for cheating

**Expected Behavior**
Need to blacklist it A$ap

**Screenshots**
NA

**Version Information**
 - OS: Windows 10 Professional, Version 1803, MacOS
 - SEB-Version SEB 3.4.1

**Additional Context**
Need to implement before 7th Jul'23 before PG exam starts

**Comment by dbuechel** [comment]
You can add any application (thus also AnyDesk) to the list of prohibited applications in a SEB configuration file: https://safeexambrowser.org/windows/win_usermanual_en.html#ProhibitedProcessesSection.
