### ISSUE TITLE
File System Access discontinues listing abruptly if a folder name contains the letter "ı"

### ISSUE THREAD

**Issue by bali-ibrahim** [SafeExamBrowser/seb-win-refactoring#63]
**Describe the Bug**

I think the file browser fails to pass the [_Turkey test_](https://stackoverflow.com/q/796986/7032856) as I failed to see the contents of a folder if it contained a folder named including the character `ı`.

**Steps to Reproduce**
1. Create a folder that includes `ı` in their name, such as `C:\Users\username\ı`
2. Browse the folder with File System Access in the client

**Expected Behavior**
I expect to see the content of the folder in the File System Access even if there are folders of which their name include the character `ı` or any unforeseen bug for that matter.

**Screenshots**
The client: ![Client](https://user-images.githubusercontent.com/40886141/102687684-d754ee00-4201-11eb-9e41-da77b939a766.jpg)
OS File Browser: ![OS](https://user-images.githubusercontent.com/40886141/102687715-feabbb00-4201-11eb-8645-e0e5ffd9d35e.png)

**Version Information**
 - OS: [Windows 10 Pro N, Version: 20H2, OS Build: 19042.685]
 - SEB-Version [SEB 3.1.1](https://sourceforge.net/projects/seb/files/seb/SEB_3.1.1/SEB_3.1.1.250_SetupBundle.exe/download)]

**Comment by dbuechel** [comment]
Thanks for your report. I am able to reproduce the issue, I'll see what might be the issue here.
