### ISSUE TITLE
Application Error After Sleep Mode

### ISSUE THREAD

**Issue by dbuechel** [SafeExamBrowser/seb-win-refactoring#631]
### Discussed in https://github.com/SafeExamBrowser/seb-win-refactoring/discussions/630

<div type='discussions-op-text'>

<sup>Originally posted by **Tompa83** July 10, 2023</sup>
Hello, we use SEB at location for our students. We have a strict policy that requires our Windows 10 PC computers to go into sleep mode when inactive (ie power saving mode or however it is called). If the computer is in sleep mode for about 10 minutes or more SEB crashes after about another minute once you end sleep mode.
It says "Application error - An unrecoverable error has occured! Please consult the log files for more information. SEB will now shut down...." and there's only the OK button. 

Here's how we get the error:

1. Start SEB, our homepage loads up in the browser
2. Shut the laptop lid (or whichever way you want to enter sleep mode)
3. 10 minutes later start it up again and wait another minute (it really needs to be 10 minutes minimum)
4. The error message pop up and SEB closes

I have attached the log files. I opened SEB at 17:17, entered sleep mode and started it again at 17.29, and the crash came at 17.30.

If you want to see for yourself here's a video (note, not the same attempt as the logs):
https://www.youtube.com/shorts/ybtqeh7SAOY

I am very grateful for any help, it is currently a big inconvenience for our invigilators. Thank you!

[2023-07-10_17h17m23s_Browser.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/12003736/2023-07-10_17h17m23s_Browser.log)
[2023-07-10_17h17m23s_Client.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/12003737/2023-07-10_17h17m23s_Client.log)
[2023-07-10_17h17m23s_Runtime.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/12003738/2023-07-10_17h17m23s_Runtime.log)
</div>

**Comment by dbuechel** [comment]
@Tompa83 I've been able to reproduce the issue, however upon further looking into it, I am uncertain whether this is an issue on our side or whether there is an issue in Windows resp. the .NET Framework itself upon resuming a session after sleep mode. The IPC mechanisms used between the SEB application components seems to fail resp. end up in a faulted state, which in turn leads SEB to terminate the running session. As to why exactly that would happen is unclear to me, I would expect the IPC to continue its functionalities after resuming the system normally. I furthermore have detected other abnormal behavior (e.g. the currently active display also could not be retrieved anymore) which leads me to think that this might indeed be an issue of the latter mentioned (i.e. OS or framework) parts.

Thus, most unfortunately, we'd need to mark this issue as won't fix for the moment, as we're already very busy with other priorities and hence do not have much time left to keep digging into this problem further. To my knowledge, SEB furthermore never was intended to support or never actually supported sleep mode at all in the first place, though I'd need to clarify this with a more senior team member first.

**Comment by Tompa83** [comment]
I very much appreciate you taking the time to investigate the issue. It is understandable that it is not a priority to fix as the problem is quite niche and might not be entirely in your control. At least now we know that fiddling with SEB settings won't solve the issue and we can start disussing what we need to do to move forward. Thanks again!

**Comment by dbuechel** [comment]
I'll close this issue for now, but please do feel free to reopen it in case new insights should arise.
