### ISSUE TITLE
Undocumented feature? Top menu bar disappears in quiz activity that requires SEB

### ISSUE THREAD

**Issue by pdorok** [SafeExamBrowser/seb-win-refactoring#639]
**Is your feature request related to a problem? Please describe.**
We use Safe Exam Browser for e-assessments. In a quiz activity that requires SEB, the top menu bar disappears.
As far as we know, this feature is undocumented and can't be activated/deactivated in the settings.
Most examiners/supervisors need to see the students' name in the top menu bar in e-assessments on campus in order to authenticate the students in the exam by comparing the displayed name in our exam Moodle system and the name on the student's ID card.

For e-assessments on campus, the top menu bar (or an alternative means of displaying the students' names) is crucial, as the supervisors are required to check the students' identities before or during the exam.

**Describe the solution you'd like**
An option to disable the top menu bar during a quiz activity with Safe Exam Browser in the **SebClientSettings.seb** and within the Moodle quiz settings would be best, in our humble opinion. In our view, the default option should be to display the top menu bar.
A documentation of this feature would be great, as well.

**Describe alternatives you've considered**
Our workaround so far was to add the block "Logged in user" to each and every exam course and to check the following option in the quiz settings:

**Edit settings / Appearance**
Show blocks during quiz attempts: Yes

We have configured the block "Logged in user" to just display the name of the students (no user pic, e-mail address, location etc.).
It is displayed right below the quiz navigation, which is very convenient.

The required setting for the block "Logged in user" to display correctly during the quiz activity is:

**Configuring a Logged in user block / Where this block appears**
Display on page types: Any page

**Additional context**

Screenshot:
![SEB_no_top_menu_bar](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/126562975/19c2af1b-848f-4f88-a7e7-50d2be7644ea)

**Comment by dbuechel** [comment]
I think this is a feature request which would need to be placed in a Moodle forum. SEB itself does not control the content rendered in the Browser Engine, thus in case some part of Moodle (I guess that is what you refer by "top menu bar") is not visible when inside a quiz, then that's because Moodle does not render it accordingly.

**Comment by pdorok** [comment]
Dear Damian,
thank you very much for your quick reply.
In each and every quiz that does not require Safe Exam Browser the top menu bar is rendered and displayed normally.
Only when the Safe Exam Browser is set as required the top menu bar disappears.

The following screenshot illustrates, what I refer to as the "top menu bar":

![top menu bar](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/126562975/485a7046-d04d-4b57-8888-cd4d218f2d69)

I'm not quite sure, in which Moodle forum to post this issue as a feature request, because it seems very likely to be a SEB-specific issue... Do you have any recommendations?

Thank you very much and best regards,
Philipp

**Comment by danschlet** [comment]
As @dbuechel mentioned, this is a Moodle and not SEB issue. Looks like you're using a custom Moodle theme. It's up to the developers of that theme to decide which Moodle UI elements to display in the secure quiz mode, which is used for the SEB quiz access restriction (and other possible quiz access restrictions). Try if the default Moodle theme displays the user name when using the SEB quiz restriction. I think our Moodle theme developer modified our (ETH Zurich) custom Moodle theme to display the Moodle user name during quizzes as well.
