### ISSUE TITLE
WebDriver support for Safe Exam Browser (Web Driver / Selenium)

### ISSUE THREAD

**Issue by jeroenhabets** [SafeExamBrowser/seb-win-refactoring#64]
First of all: Thanks for all the good work :)

Our customers have been hit by issues in SafeExamBrowser and our platform therefore we'd like to add a couple of SEB configurations to our end-to-end tests.

I couldn't find anything on WebDriver support for Safe Exam Browser / Selenium, except an [old request](https://sourceforge.net/p/seb/support-requests/34/). 

a) Please confirm there is no WebDriver support yet.
b) If added, I believe it should be a SEB Config setting

As you are probably aware Chromium/Chrome has WebDriver support so it's probably more introducing a setting and enabling it than having to do all the heavy lifting

References:
- W3C Webdriver spec: https://www.w3.org/TR/webdriver/
- Chromium Webdriver page: https://chromedriver.chromium.org/

**Comment by danschlet** [comment]
There is no Selenium support for SEB and I don't know how WebDriver could be supported in the embedded CEF3/CefSharp browser engine. As none of our (contributing funds) SEB Consortium members requested such a support, it is a low priority feature request, which probably could be considered for the 2022 roadmap.

In case you want to invest some resources in this feature, you could study the documentation for CefSharp/CEF3 and find out if/how this could be activated in SEB. We usually accept pull requests if it doesn't tamper with SEB security and doesn't require a lot of work on our side.

**Comment by jeroenhabets** [comment]
Thanks! Looks like we need to investigate CEF3/CefSharp pages then, like 

- https://bitbucket.org/chromiumembedded/cef/wiki/UsingChromeDriver.md
- https://stackoverflow.com/questions/64233124/how-to-attach-a-selenium-chromedriver-to-an-embedded-cefsharp-browser-in-a-wpf-a

**Comment by jeroenhabets** [comment]
Since SEB stays much more up-to-date the risk from an outdated browser engine has been drastically reduced so we do not plan to pursuit an automated end-to-end test for the foreseeable future.

This feature request may be closed, or kept open for future reference, I leave that up to you.

**Comment by dbuechel** [comment]
Thanks for the update. Then I'd suggest that we close it for now, but please feel free to reopen the issue at any time. We do have quite a lot in our backlog already, so everything that we can take off from it helps us moving forward.

We do have an internal issue where we'd like to look at automatic UI testing in general (not only for the browser engine), but since that has no priority at the moment, we like won't be able to have a look at it any time soon.
