### ISSUE TITLE
Ease of Access / Magnifier not usable in SEB

### ISSUE THREAD

**Issue by senapetschnig** [SafeExamBrowser/seb-win-refactoring#640]
**Describe the Bug**
The Windows build in Magnifier / Ease of Access Feature can not be used

**Steps to Reproduce**
1. Enable ease of Access in a Exam Config in the registry tab of the config tool
2. Start SEB with this config
3. press ctrl+alt+del the blue screen is shown
4. on the bottom right click on ease of access and enable the magnifier
5. the only option to get back to SEB window is to press the cancel button
6. when cancel is pressed the magnifier is gone
7. as alternative start the magnifier before starting seb, than the magnifier quits also and is not available in the SEB Window

**Expected Behavior**
When the magnifier is enabled it should stay enabled in the SEB Window so that impaired people can use it during an exam

**Version Information**
 - Window 3.5+

Kind Regards
              Sebastian

**Comment by dbuechel** [comment]
Were you able to try to add the system utilities as permitted applications to your configuration?

**Comment by senapetschnig** [comment]
Yes we tried, but the magnifier seems to be a "special" application, after starting SEB and adding the magnifier in autostart there is still no magnifier activated in SEB.
In our case we now try to come along with the Textzoom function in SEB itself, which is not ideal but definitely better than nothing ;-)

**Comment by dbuechel** [comment]
It might be necessary to start it manually, but if you're having a workaround, then I'd unfortunately need to close this issue for the moment, as we're completely booked with other priorities. But please do feel free to reopen or comment in case new insights are available.
