### ISSUE TITLE
Certificate problem on Windows 11

### ISSUE THREAD

**Issue by Tweak-NL** [SafeExamBrowser/seb-win-refactoring#641]
**Describe the Bug**
We are trying to test SEB on Windows 11 but we have a weird problem using a "encrypted seb config" when we import a PFX with:

certutil.exe -f -user -p "" -importPFX "C:\temp\testcert.pfx" 

Open the SEB Config tool and on general tab fill in a random website and go to config file tab
select the cert on "choose identity" and save the settings, after that it is NOT possible to open the .seb file.

The error "Error decrypting settings" will popup. 

This above works fine on Windows 10 but not on Windows 11.

What i found out: When you import the PFX with the wizard from Windows (Cert store) there is no problem.

So i tried with powershell to import the PFX but same problem "error decrypting" we are using a logonscript to import the certificate and fire up SEB. So we are kinda stuck now. Is there a solution?

![Schermafbeelding 2023-08-05 000023](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/67078330/5108f8de-8c1c-49cb-adc5-f579b8687ece)

![Schermafbeelding 2023-08-05 000112](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/67078330/8d0e20fb-1af8-4769-93aa-aa2705c0a785)

**Comment by dbuechel** [comment]
To be frank I do not have too much experience regarding certificates and find everything related to them extremely cumbersome. But if I understand your case correctly, it actually does work when using the system wizard, but when using the command-line tool `certutil.exe` there is a problem? And if so, could it not be that you might not be using the command correctly or that there has been a change to the utility under Windows 11? Does `certutil.exe` provide any feedback when executing the command?

**Comment by Tweak-NL** [comment]
it is a very weird problem, when using the certutil.exe there is no error and you will even see the imported certificate in the "store"
I tried to compare them when imported with the wizard or with using the certutil.exe but i dont see any difference. On the internet i cant find any changes, and when using powershell (Import-PfxCertificate) there are not much options/parameters to give. Powershell also gives no errors and shows the certificate in the store.

**Comment by dbuechel** [comment]
Yes, this indeed seems very strange, particularly since it appears to work fine under Windows 10 as you've stated. We haven't changed anything in that particular part of the code, thus it would seem quite unlikely that it is a (new) bug in SEB, but rather an issue in Windows 11.

In case you're familiar with source code, you might find any insights in the related code section decrypting the settings with a certificate: https://github.com/SafeExamBrowser/seb-win-refactoring/blob/master/SebWindowsConfig/Utilities/SEBProtectionController.cs#L440.

**Comment by Tweak-NL** [comment]
Sorry for creating this post/question here. Because i found the solution.. I really dont know why certutil works different under Windows 11 compared to Windows 10. 

When i imported the PFX with certutil.exe i did an export with also certutil.exe and i noticed the Provider = Microsoft Software Key Storage Provider

So i removed the certificate from the store and did a import with the wizard and again export with certutil. Now the Provider = Microsoft Enhanced Cryptographic Provider v1.0

Then we already know what is wrong.. So now removed the certificate again and used the command:

certutil.exe -f -user -p "" -csp "Microsoft Enhanced Cryptographic Provider v1.0" -importPFX "C:\temp.pfx" NoRoot,NoExport

Not it seems to work fine! So with Windows 11 we need to specify the CSP when importing. Maybe it helps someone else.

**Comment by dbuechel** [comment]
Excellent, that's great to know and yes indeed, this might just help someone with the same problem.
