### ISSUE TITLE
SEB RED SCREEN SHOWING LOCKED

### ISSUE THREAD

**Issue by Manoj-Kande** [SafeExamBrowser/seb-win-refactoring#643]
**IMPORTANT**
Please _always_ consult the documentation first before creating a bug report!
https://safeexambrowser.org/windows/win_usermanual_en.html

**Describe the Bug**
Seb is locked during installation and it asks me to enter the password(In Red Screen) .But i dint start any exam or any session.And i tried many ways to unlock it but i cant resolve the prbml.coz i dont know th epassword.And even i dindnt write  one exam.

**Steps to Reproduce**

**Expected Behavior**

**Screenshots**
![image](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/142070527/e1deb617-f8d9-4724-bdde-eaa04254f7f4)

**Version Information**
 - OS: Windows 11.
 - SEB-Version SEB 3.5.0.544

**Additional Context**
I Request  the team Seb to resolve the prbml  as soon as possible.And my exams are going on...

**Comment by dbuechel** [comment]
This happens since you've started SEB, but then didn't terminate it properly. You'd need to resolve this with the teacher in charge who instructed you to use SEB and who should now the correct password to unlock SEB.
