### ISSUE TITLE
Is it possible to use PO or other plugable i18n solution instead?

### ISSUE THREAD

**Issue by fishfree** [SafeExamBrowser/seb-win-refactoring#65]
Because I need to translate some of the interface language strings into my university-specific strings. So if the App can dynamically load i18n file on starting-up will be more flexible than currently compiled-in i18n solution.
I know many web-based apps use PO-based solution. It seems .Net also support this, see [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/portable-object-localization?view=aspnetcore-5.0).

**Comment by danschlet** [comment]
I don’t think we will support this, as 
a) none of the SEB Consortium members who are contributing funding requested this
b) it would create confusion if the strings are not clear or differ from the SEB standard version. We would then get unnecessary support questions and couldn’t answer those not knowing the modified strings.

Just use your exam solution for individual guidance. What would you anyways want to change?

If you really think you need your custom UI, then create your own customized SEB version (but name it differently), following our MPL license.
