### ISSUE TITLE
SEB works fine in Virtual Machine

### ISSUE THREAD

**Issue by emilmueller** [SafeExamBrowser/seb-win-refactoring#651]
With very few manipulations, it is possible to bypass the VM-check in SEB.

**Describe the Bug**
With https://github.com/dotfornet/dnSPy you can edit and recompile the following dll:
- SafeExamBrowser.Monitoring.dll
- SafeExamBrowser.SystemComponents.dll 

**Expected Behavior**
Whith these small changes I am able to run SEB in a virtual machine. I have full access to my host computer an can use alle the programs.

**Version Information**
 - OS: Windows 11 (Host), Windows 10 (VM)
 - SEB-Version: SEB 3.5.0

**Additional Context**
If you need further information, you can contact me (emil.mueller@kantiwattwil.ch)

Best.
emil

**Comment by dbuechel** [comment]
Safe Exam Browser itself can only be a part of a secure exam environment, especially with regard to Bring Your Own Device (BYOD) scenarios. Other (possibly even more important aspects) are good invigilation, meaningful and well-designed exams, integrity verification of SEB installations before an exam using the SEB Verificator etc.
 
Notwithstanding, SEB already comes with various additional security measures like the Browser Exam Key (BEK), the App Signature Key (ASK) as well as an integrated integrity verification, which actually will detect your manipulation. We would suggest a Zoom call where you may show us the manipulations you applied and we can discuss how SEB mitigates this. Would you be interested in such a call?

**Comment by moxxxer** [comment]
Seems to me you dont know too much about IT/CyberSec.. 
Why would you touch their files? Just stealth your VM took me 20 Minutes and I can run all Proctoring software SEB, PearsonVue, Proctorio etc. 
Tbh proctoring is just making money for these companies like its way to easy to bypass and I cant believe people complain about stuff.. No offence to you SEB team but what you did here is garbage if someone knows how a computer works they can just run your stuff on a VM just like any other proctor.. and no you will never be able to fix it because: Yes you can update to detect smth no matter what you update its literally 1 line of code and Im back undetected..

**Comment by moxxxer** [comment]
Also Emil als normalo IT Typ  versuche gar nicht erst DLL etc. zu ändern ist viel zu komplex alles in so einem Fall bau lieber die VM um und du sparst dir Zeit und Arbeit und es funktioniert auch wenn du nur Basiswissen hast! 
Und wenn du rausgefunden hast wie und verstehst wieso es auf der VM läuft dann wirst du merken das hier was zu schreiben nichts bringt weil die Leute die sowas zusammenbasteln meistens irgendwelche Ethical IT studenten sind wenn man keinen IT-Greyhead an Bord hat wird sowas nie funktionieren.

**Comment by danschlet** [comment]
Please note that we don't accept comments containing verbal abuse. Mind your language when posting comments here, this is no toxic social media app. We attempt to behave like professionals and expect the same from the community.

**Comment by dbuechel** [comment]
I second the above, though am generally not in favor of censoring people as long as they manage to retain some basic decency. We're always open for constructive criticism, or rather we're actually welcoming and depending on it, as it helps us to provide a better product.

**Comment by HunAbdla** [comment]
Any way to bypass SEB lite exam tool on windows 11 Ivan VMware on apple silicon Mac
