### ISSUE TITLE
Safe exam browser is not installing in my PC

### ISSUE THREAD

**Issue by ashishpaymode** [SafeExamBrowser/seb-win-refactoring#655]
Hello Team,
 I have an Accenture exam on Safe Exam Browser and I installed SEB a few days ago on my PC and mistakenly I Uninstalled it. After that I tried to install it but it did not install and gave Error 1001. I have attached screenshot of it with this mail. Please solve the problem as I have an Accenture Test on it. Note - I have all its requirements on my PC.
![Screenshot (272)](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/94953945/65cd9b98-c1d1-4e5a-beff-2b57655a91df)
![Screenshot (271)](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/94953945/5428277e-bf53-4fdb-b722-5d8d4077ecde)

**Comment by dbuechel** [comment]
The software you're trying to install is **Secure** Exam Browser (not **Safe** Exam Browser). That product is not developed by us, though it appears to be a clone of SEB 2.x (which is not supported by us anymore).
