### ISSUE TITLE
Safe-Exam-Browser hängt sich beim Initialisieren auf

### ISSUE THREAD

**Issue by ITNKSA** [SafeExamBrowser/seb-win-refactoring#659]
**Expected Behavior**
Der SEB bricht beim starten bei der Initialisierung mit einer Fehlermeldung ab

**Steps to Reproduce**
1. Eingabe Testschlüssel auf exam.net in Browser (Chrome) 
2. SEB wird vom Browser geöffnet
3. Initialisierung läuft sehr langsam und bricht bei ca. 50% ab
4. Fehlermeldung mit Verweis auf Log-Files

**Log-Files**
[2023-09-07_08h49m05s_Service.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/12545997/2023-09-07_08h49m05s_Service.log)

[2023-09-07_08h53m33s_Runtime.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/12545998/2023-09-07_08h53m33s_Runtime.log)

**Version Information**
 - Windows 10 Professional
 - SEB-Version SEB 3.5.0.544

**Comment by dbuechel** [comment]
Sie scheinen den SEB-Service zu benutzen, wobei eine der Operationen zum Absichern des System des SEB-Services fehlzuschlägen scheint. Es ist leider sehr schwierig wenn nicht unmöglich, dies von der Ferne aus beheben zu versuchen. Für was ein Anwendungsszenario benutzen Sie SEB?

Allenfalls können Sie den SEB-Service schlicht ignorieren (wie dies in den Standardeinstellungen auch der Fall ist). Falls nicht, bräuchten wir sicher mehr Informationen (z.B. allfällige Fehler oder Warnungen aus der Windows-Ereignisanzeige).

**Comment by dbuechel** [comment]
Closed due to lack of feedback.
