### ISSUE TITLE
https://safeexambrowser.org/ site is down

### ISSUE THREAD

**Issue by meyyappanv** [SafeExamBrowser/seb-win-refactoring#662]
**IMPORTANT**

I wanted to consult the documentation on SEB, but looks like the site is down.

**Describe the Bug**

This URL: https://safeexambrowser.org/windows/win_usermanual_en.html doesn't work any more. 

**Steps to Reproduce**
1. Go to https://safeexambrowser.org/windows/win_usermanual_en.html
2. See error site doesn't load.

**Expected Behavior**
Site loads with user manual

**Screenshots**
<img width="574" alt="image" src="https://github.com/SafeExamBrowser/seb-win-refactoring/assets/17023819/149e9a3b-3290-4c6f-9cff-1e1a988d19df">

**Version Information**
 - OS: Windows 10 Professional, Version 1803
 - SEB-Version SEB 3.0.1

**Additional Context**
None

**Comment by dbuechel** [comment]
This must have been a temporary issue, I can reach the page without any issues.
