### ISSUE TITLE
SEB wrongfully detects virtual machine environment

### ISSUE THREAD

**Issue by mbalous** [SafeExamBrowser/seb-win-refactoring#669]
**Describe the Bug**
SEB tells me it's running inside a Virtual Environment, when it's not.

**Steps to Reproduce**
Start SEB from start menu.

**Expected Behavior**
I expect no errors.

**Screenshots**
![image](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/10358985/074c60a9-044b-4f10-9d18-3e51da048fd0)

**Version Information**
- OS Name:                   Microsoft Windows 10 Enterprise
- OS Version:                10.0.19045 N/A Build 19045
- SEB 3.5.0.544

**Comment by dbuechel** [comment]
Can you please post the log files for the affected session(s)? They can be found under `%LocalAppData%\SafeExamBrowser\Logs`.

**Comment by tkbstudios** [comment]
@mbalous can you please send the log files from the sessions like @dbuechel asked?

**Comment by dbuechel** [comment]
Yes, otherwise we'd need to close the issue due to lack of feedback.

**Comment by tkbstudios** [comment]
I can confirm it happened to us too, next time I get that, I'll send my logs because it's also an issue to be investigated.

**Comment by ellchr00** [comment]
I can confirm the issue here too ..... 
to reproduce I tested with exam.net/seb/test

[2023-11-14_23h18m58s_Runtime.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/13358281/2023-11-14_23h18m58s_Runtime.log)

I also add the same Information as requested in #14 .... and her on this machine VirtualBox is installed and some Networkadapters although not in use ....

[NetworkAdapter.txt](https://github.com/SafeExamBrowser/seb-win-refactoring/files/13358351/NetworkAdapter.txt)
[NetworkAdapter_FormatList.txt](https://github.com/SafeExamBrowser/seb-win-refactoring/files/13358352/NetworkAdapter_FormatList.txt)
[pnpEntity.txt](https://github.com/SafeExamBrowser/seb-win-refactoring/files/13358353/pnpEntity.txt)

**Comment by dbuechel** [comment]
Thanks for the update. We'll again have a look at the issue and report back here.

**Comment by dbuechel** [comment]
@diegoara96 It does appear that the "vbox" check you've originally added for PCI devices (see https://github.com/SafeExamBrowser/seb-win-refactoring/blob/master/SafeExamBrowser.SystemComponents/VirtualMachineDetector.cs#L29) triggers for the network adapters of a host operating system as well (see e.g. "VirtualBox Host-Only Ethernet Adapter"). Would you happen to know a way to differentiate between host and client network adapters, or is this a known limitation?

**Comment by diegoara96** [comment]
The way to differentiate it is that in the host should not appear references to Vbox in the deviceID.

### **My PC**
``````
Caption                     : VirtualBox Host-Only Ethernet Adapter #2
ClassGuid                   : {4d36e972-e325-11ce-bfc1-08002be10318}
CompatibleID                : 
ConfigManagerErrorCode      : 0
ConfigManagerUserConfig     : False
CreationClassName           : Win32_PnPEntity
Description                 : VirtualBox Host-Only Ethernet Adapter
DeviceID                    : ROOT\NET\0000
ErrorCleared                : 
ErrorDescription            : 
HardwareID                  : {sun_vboxnetadp}
InstallDate                 : 
LastErrorCode               : 
Manufacturer                : Oracle Corporation
Name                        : VirtualBox Host-Only Ethernet Adapter #2
PNPClass                    : Net
PNPDeviceID                 : ROOT\NET\0000
``````

Anyway I just created a new VM and I think we can change vbox to VEN_VBOX and it should fix the problem.
### **My VM**
``````
Caption                     : VBOX HARDDISK
ClassGuid                   : {4d36e967-e325-11ce-bfc1-08002be10318}
CompatibleID                : {SCSI\Disk, SCSI\RAW}
ConfigManagerErrorCode      : 0
ConfigManagerUserConfig     : False
CreationClassName           : Win32_PnPEntity
Description                 : Unidad de disco
DeviceID                    : SCSI\DISK&VEN_VBOX&PROD_HARDDISK\4&2617AEAE&0&000000
``````

**Comment by dbuechel** [comment]
Excellent, then I shall change the string respectively!

**Comment by ellchr00** [comment]
I can confirm for me that on this computer this works fine now. Thanks for the fast response!
