### ISSUE TITLE
Unauthorized Access to Social Media Platforms via External Links on Moodle within SEB

### ISSUE THREAD

**Issue by ormoon-ll** [SafeExamBrowser/seb-win-refactoring#673]
When using Safe Exam Browser in conjunction with Moodle, a vulnerability has been discovered that allows users to gain unauthorized access to social media platforms. This deviates from the expected behavior where such platforms should be inaccessible to maintain the integrity of the online examination environment.

Steps to Reproduce:

Launch SEB and log in to Moodle.
![387327724_3494347877546383_1115170513625979743_n](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/72150728/40fef109-bad7-466a-9489-dcca153aa25c)

Locate and click on any external link provided within Moodle course materials or pages.
![387331201_1070355697239393_7602685126386082699_n](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/72150728/b824d361-9804-484d-85df-bc5cde8c233c)

Once on the external website, navigate to the bottom (or any section) where social media links are typically provided.

![387463559_1752845665155093_6726343780625554699_n](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/72150728/d661cfd0-1660-4f46-98ff-2d1daa40c15a)

![387455755_1759080337863522_5151250378602029994_n](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/72150728/b051eb0e-386d-4b22-99f0-5ef048545800)

Click on any of these social media links, which leads to the respective social media login page.
![368788430_1646289085861083_4169834762758091206_n](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/72150728/8c4230d8-0899-4cd3-a7c5-4c345087e841)

At this point, a user can log in to the social media platform, thus bypassing SEB's intended restrictions.

![387526737_1379375422928689_1344087292148934995_n](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/72150728/7449d257-f90e-4f8e-8d29-9f018aa43aaa)

**Version Information**
 - OS: [  Windows 11 Home Insider Preview, 22h2
 - SEB-Version [ SEB 3.5.0]

This vulnerability suggests that SEB's restriction mechanism can be bypassed by a chain of legitimate website navigations initiated from within Moodle.

**Comment by dbuechel** [comment]
You'll need to make sure that users cannot do this yourself. You can achieve this by e.g. not displaying links allowing to leave your LMS or adding URL filter rules to your exam configuration. For more information on both topics, please refer to https://safeexambrowser.org/developer/seb-integration.html resp. https://safeexambrowser.org/windows/win_usermanual_en.html#NetworkPane.
