### ISSUE TITLE
Download very slow in Mainland... Maybe is server problem

### ISSUE THREAD

**Issue by BNUZ-NFZWE** [SafeExamBrowser/seb-win-refactoring#681]
Whether it is downloaded in a browser or IDM is the same, very slow
Already tried using a vpn. It doesn't work
I asked some friends in other countries
 US, UK, KR, JP, etc... Download fast
There's nothing wrong with the local network

![image](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/147481512/45e60cba-ca63-4794-9788-0967701f2d70)(https://github.com/SafeExamBrowser/seb-win-refactoring/releases/download/v3.5.0/SEB_3.5.0.544_SetupBundle.exe)
![image](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/147481512/4612f60d-1dc2-48ca-91e4-187dda3f8c35)

**Comment by tkbstudios** [comment]
It's maybe just China scanning and logging every packet you're downloading or it's just the bandwidth from the server to your location that is slow because of the distance

**Comment by tkbstudios** [comment]
And you are downloading from githubusercontent so it's an issue you should send to github self, this doesn't look like an issue on SEB end

**Comment by BNUZ-NFZWE** [comment]
i tried download from https://safeexambrowser.org/
same, very slow, not only me 
All the students in our school are facing this problem
download link https://[nchc.dl.sourceforge.net](https://nchc.dl.sourceforge.net/project/seb/seb/SEB_3.5.0/SEB_3.5.0.544_SetupBundle.exe)/project/seb/seb/SEB_3.5.0/SEB_3.5.0.544_SetupBundle.exe

**Comment by dbuechel** [comment]
This is definitely a local or regional issue. We have two download mirrors (GitHub and SourceForge), the probability that both are down resp. not working is very low.
