### ISSUE TITLE
not able to install safe webbrowser

### ISSUE THREAD

**Issue by Bekescaba809** [SafeExamBrowser/seb-win-refactoring#687]
I am not able to install safe web broswer in windows.It gives below error.
<img width="386" alt="Screenshot 2023-10-22 184458" src="https://github.com/SafeExamBrowser/seb-win-refactoring/assets/148694840/d9fc5d06-d7a7-4eed-92c3-36206307d663">
logs:
[Safe_Exam_Browser_20231022181241.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/13063333/Safe_Exam_Browser_20231022181241.log)
can you please help

**Comment by dbuechel** [comment]
This is not an official build of Safe Exam Browser. You'll need to contact the developers of that particular version.
