### ISSUE TITLE
WARNING: Cursor configuration is compromised

### ISSUE THREAD

**Issue by RoChess** [SafeExamBrowser/seb-win-refactoring#690]
Apologies if this is due to development work in progress, as I was testing a fresh build. Test machine is running a pretty vanilla configuration, but it has some tools installed, such as Microsoft PowerToys for Windows 11.

```
# Application started at 2023-10-24 16:35:45.355
# Running on Windows 11, Microsoft Windows NT 10.0.22621.0 (x64)

Unlike official released 3.5.0, it failed with an error to check the runtime logs, which towards the end contained:

2023-10-24 16:35:48.691 [08] - INFO: Attempting to verify cursor configuration...
2023-10-24 16:35:48.693 [08] - WARNING: Cursor configuration is compromised: 'C:\Users\User\AppData\Local\Microsoft\Windows\Cursors\pin_eoa.cur'! Aborting session initialization...
2023-10-24 16:35:48.695 [08] - INFO: ### -------------------------------------- Session Start Failed -------------------------------------- ###
```

Looking at the source-code I noticed SEBWIN-714 to be the commit that adds this new check on cursor configuration.

For now I manually modified the "HKEY_CURRENT_USER\Control Panel\Cursors" keys for "Pin" and "People" to "%SystemRoot%\cursors\aero_pin.cur" and aero_people.cur respectively, and this allowed SEB to launch again.

Just that for the life of me I don't know what caused the configuration for just those two registry entries to point to 'C:\Users\User\AppData\Local\Microsoft\Windows\Cursors\pin_eoa.cur' (and person_eoa.cur) whereas all the others point to their `C:\Windows\Cursors\...` versions. They do appear to be official Microsoft cursors though.

Windows 10 machine has no `Cursors` folder available in '%AppData%\..\Local\Microsoft\Windows'

Wanted to bring this to your attention, in case it helps in defining what a `default` configuration is meant to represent.

**Comment by dbuechel** [comment]
Thanks a lot for the report, I have not been aware of this at all. I shall thus extend the verification mechanism as you suggested, as we do not want to be causing false positives like these indeed.

**Comment by dbuechel** [comment]
Thanks again for the valuable report, this is going to save us from a lot of false positives with the new cursor validation. Please do feel free to test the change in the latest beta build of version 3.6.0: https://sebdev-let.ethz.ch/api/buildjobs/l6cnw9dv1qmjxkc3/artifacts/SEB_3.6.0.607_SetupBundle.exe.

**Comment by RoChess** [comment]
Tested (with the two registry keys restored) and works now.

2023-11-07 14:30:33.200 [08] - INFO: Attempting to verify cursor configuration...
2023-11-07 14:30:33.203 [08] - INFO: Cursor configuration successfully verified.
2023-11-07 14:30:33.205 [08] - INFO: Attempting to verify ease of access configuration...
2023-11-07 14:30:33.205 [08] - INFO: Ease of access configuration successfully verified.

**Comment by dbuechel** [comment]
Excellent, thanks a lot for the feedback!
