### ISSUE TITLE
Power options can possibly dissapear after the use of SEB.

### ISSUE THREAD

**Issue by NekoJonez** [SafeExamBrowser/seb-win-refactoring#691]
I have an annoying bug report. I sometimes get complaints from the students in my school that the power options are gone after they used Safe Exam Browser and a Bookwidgets exam. 
I have the impression there is a higher chance if either:

-> The exit password is wrong and the hard reboot.
-> The internet connection got disconnected and they hard reboot.

I think that the hard reboot might be the culprint...

**Comment by dbuechel** [comment]
Yes, the hard reboot definitely is the culprit. Which version of SEB for Windows are they using?

**Comment by NekoJonez** [comment]
All are devices are connect to our Azure tennant. I have set a rule that they are upgraded to the latest Windows version. Apart from some spare devices, almost all devices are using Win 11 22H2 22621.2428 

I install SEB via Chocolatey on the devices. https://community.chocolatey.org/packages/safeexambrowser 
So, always the latest version. At the moment of writing is: 3.5.0.2023090701

Also, I have a special script that runs each wednesday at 11AM (or next time possible) to check if everything is up to date. So, if it's there is a new version of SEB -> upgrade will happen :)

**Comment by dbuechel** [comment]
Could you post the entire SEB Service log(s) of the affected client(s)? They can be found in the system profile under `AppData\Local\SafeExamBrowser`.

**Comment by NekoJonez** [comment]
Currently I have none on hand. I'll ask my co-workers to keep an eye on it too.

**Comment by danielhofer** [comment]
I could send you a bunch of logs of four computers with the problem. Can you provide me an e-mail address or so?
Thanks
Daniel

**Comment by dbuechel** [comment]
@danielhofer Please do post them here if possible.

**Comment by danielhofer** [comment]
[Logs1.zip](https://github.com/SafeExamBrowser/seb-win-refactoring/files/13297219/Logs1.zip)
[Logs2.zip](https://github.com/SafeExamBrowser/seb-win-refactoring/files/13297220/Logs2.zip)
[Logs3.zip](https://github.com/SafeExamBrowser/seb-win-refactoring/files/13297221/Logs3.zip)
[Logs4.zip](https://github.com/SafeExamBrowser/seb-win-refactoring/files/13297222/Logs4.zip)

**Comment by danielhofer** [comment]
by the way: neither deinstallation of SEB help, nor Windows Updates or `shutdown /r`. Does anybody have an idea?
I assume there is a local GPO set that won't turn back to its orginal state, but it's just a guess.

**Comment by NekoJonez** [comment]
> by the way: neither deinstallation of SEB help, nor Windows Updates or `shutdown /r`. Does anybody have an idea?
> I assume there is a local GPO set that won't turn back to its orginal state, but it's just a guess.

I tried a ton of tutorials. Usually, only a reinstall fixes it'

**Comment by dbuechel** [comment]
@danielhofer Thanks for the logs, I shall study them as soon as possible.

In general, if you are using the SEB Service component and something is not correctly restored, there is the SEB Reset Utility which is part of every SEB installation, with which you should be able to restore all changes made by the service. Please do try it out and report back here in case that neither helps.

**Comment by danielhofer** [comment]
ah, you're right. I didn't realize it. OK, I'll give it a try. Thanks!

**Comment by dbuechel** [comment]
Any updates on this?

**Comment by NekoJonez** [comment]
Sadly no. Students I ask to come dont and the problem seemed to dissapear into thin air. I will keep you posted.

**Comment by dbuechel** [comment]
Okay, thanks for the feedback. We can leave it open another week or two, after that we'd need to close it for the time being, but please do feel free to reopen it once you have new information.

**Comment by danielhofer** [comment]
Today I was able to solve the problem with the reset utility on two computers (after "shutdown /r").
On one computer the problem wasn't solved, but I had no chance to check the log because the student had to leave to the next lesson.
I'll give it a try next week.

**Comment by NekoJonez** [comment]
[Logs.zip](https://github.com/SafeExamBrowser/seb-win-refactoring/files/13476438/Logs.zip)

I have some good news. I got logs from the usage of SEB... I copied all logs since I don't know since when the power options went kaput... But, then I ran the reset utility and even when it errored out on a bit, it returned the power options. 

So, can we look at these logs to try and avoid the power options to disappear?

**Comment by dbuechel** [comment]
> But, then I ran the reset utility and even when it errored out on a bit, it returned the power options.

Excellent, that is good to know!

> So, can we look at these logs to try and avoid the power options to disappear?

We shall investigate the logs once time permits, most unfortunately, we will be busy with the release of SEB 3.6.0 and other priorities this week.

**Comment by dominique-bugmann** [comment]
Same issue, but no logs. But reset utility clear the issue. Both students say they are really sure the end the lession / exame correct. But as only 3-5 of about 300 Students has a "reboot disapear" and i'm not sure for how log they had it, i'm happy to fix it with the repair tool.
