### ISSUE TITLE
hello how i have to fix if safe exam browser its not working like starting session coming like remove hosts are clients and runtime

### ISSUE THREAD

**Issue by unknownlist66** [SafeExamBrowser/seb-win-refactoring#694]
[**IMPORTANT**]([url]([url]([url))))
Please _always_ consult the documentation first before creating a bug report!
https://safeexambrowser.org/windows/win_usermanual_en.html

**Describe the Bug**

**Steps to Reproduce**

**Expected Behavior**

**Screenshots**

**Version Information**
 - OS: [e.g. Windows 10 Professional, Version 1803]
 - SEB-Version [e.g. SEB 3.0.1]

**Additional Context**

**Comment by dbuechel** [comment]
Please fill out the issue template as it is displayed currently above and give the issue a short, descriptive name. We need to know what exactly is going wrong and when, with as much information as possible (application logs, screen shots etc.). The logs of SEB for Windows can be found under `%LocalAppData%\SafeExamBrowser\Logs`.

**Comment by unknownlist66** [comment]
Hello sir , when i login in safe exam browser  its coming like this                                                                                                                                                                                                           
 SEB failed to start a new session! Please consult the log files for more information.

C:\Users\saite\AppData\Local\SafeExam Browser\Logs\2023-10-27 23 h07m46s_Client.log

C:\Users\saite\AppData\Local\Safe Exam Browser Logs\2023-10-27_23 h07m46s_Runtime.log                                                    pls help the solution in these thank you

**Comment by dbuechel** [comment]
I'd need the log files specified above, please upload them here.

**Comment by dbuechel** [comment]
Closed due to lack of feedback.
