### ISSUE TITLE
Safe Exam Browser fail to launch with "page load error" message on Windows 11(#40939141)

### ISSUE THREAD

**Issue by Michellehdr** [SafeExamBrowser/seb-win-refactoring#697]
**IMPORTANT**
Please _always_ consult the documentation first before creating a bug report!
https://safeexambrowser.org/windows/win_usermanual_en.html

**Describe the Bug**
Safe Exam Browser fail to launch with "page load error" message on Windows 11(#40939141)

**Steps to Reproduce**
1. Deploy latest RS_PRERELEASE build
2. Perform Windows Updates and Store Updates
3. Install the application from vendor
4. Go to application file location
5. Open Configuration folder
6. Run cnfig setup
7. Select General tab
8. Paste https://s1.examonline.in/mocktest/  under Start URL
9. Click on File -->Save setting
10. Close the app
11. Launch the Application
12. Observe: Application fails to launch with page load error message

**Expected Behavior**
Application should be launch successfully without any issue

**Screenshots**
![image](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/75816577/84cc6af0-b01b-405d-a7cf-9d1bbdf9ccc7)

**Version Information**
 - OS: [Windows 11 Professional]
 - SEB-Version [Safe Exam Browser & v3.4.0.480]

**Additional Context**

**Comment by dbuechel** [comment]
This likely is a network or other issue. Can you visit the above URL in a normal browser? And does the issue persist in the latest release version (3.5.0)?

**Comment by Michellehdr** [comment]
@dbuechel the bug still repro with the latest App version: (3.5.0). Yes the above URL works fine in a normal browser.

**Comment by dbuechel** [comment]
Can you please provide the log files of the affected session? They can be found under `%LocalAppData%\SafeExamBrower\Logs`.

**Comment by dbuechel** [comment]
Terribly sorry, but without the logs and/or a reliable way to reproduce the issue, there is nothing we can do. The URL specified under step 8 leads to a network timeout in a normal browser.

**Comment by Michellehdr** [comment]
@dbuechel it is quite straight forward and easy to repro issue. Could you please try on your end? I got the error when trying to launch the App after installation.

**Comment by Michellehdr** [comment]
@dbuechel I saw the ticket is closed. Could you please reopen it?

**Comment by danschlet** [comment]
@Michellehdr Maybe the server you indicated is geo-blocked? The URL above definitely doesn't work for us (in Switzerland). 

The error message you posted clearly indicates a server certificate error.

According to ETH policy we cannot investigate issues without a working way to reproduce it and when not provided basic information like SEB log files.

**Comment by danschlet** [comment]
No, the connection to this server times out worldwide: https://check-host.net/check-http?host=https%3A%2F%2Fs1.examonline.in%2Fmocktest%2F&csrf_token=676f4999271974bfb97de77c1556cf9f843207b3

Please provide **correct** information to reproduce the issue, then we'll reopen it.

**Comment by Michellehdr** [comment]
@danschlet could you please let me know what other information needed for this bug?

**Comment by danschlet** [comment]
@Michellehdr: Please submit correct information. I'm quoting your bug report:

>8. Paste https://s1.examonline.in/mocktest/ under Start URL

**The URL https://s1.examonline.in/mocktest/ doesn't work.** Not in SEB, not in Edge, not in Internet Explorer, not in Firefox, not in Brave Browser, not in Opera, not in Safari, not in any other webbrowser!

**Just try it out yourself. Maybe it worked when you submitted your report. It doesn't work now.** 

SEB cannot load a URL which doesn't work. It's as simple as this.

**Comment by Michellehdr** [comment]
@danschlet I'm a little bit confused about your ask. Do you want me to try with the URL you shared before? But you mentioned it does not work on any browsers. What do I need to try? Could you please make it clear?

**Comment by Michellehdr** [comment]
@danschlet could you please clarify your comment above? Not quite understand what does that mean.

**Comment by danschlet** [comment]
I really don't get why you don't understand me, maybe my English is not clear.

When you reported this issue, you indicated the URL mentioned above, which doesn't work at all. Please try to open that URL in any other web browser. It doesn't work. 

So in short: We cannot reproduce any bug in SEB, because this URL you indicated doesn't work at all. The behavior in SEB with a non-working URL is as expected: It cannot load the page.

**Comment by Michellehdr** [comment]
@danschlet I checked with our tester: the url is the mock test url link we have been using for configuring the exam browser. Now the link is not working. Our tester is trying to figure out what is wrong with it. I will update the ticket once get further information from them. Thanks!
