### ISSUE TITLE
Touch input and mouse wheel stop working during exam

### ISSUE THREAD

**Issue by zznidar** [SafeExamBrowser/seb-win-refactoring#70]
**IMPORTANT**
Please _always_ consult the documentation first before creating a bug report!
https://safeexambrowser.org/windows/win_usermanual_en.html

**Describe the Bug**
When writing an exam in SEB, touch input (on a computer with touch screen) stops working if the user presses the left Alt key on the keyboard. At the same time, mouse scrolling wheel stops working as well.

**Steps to Reproduce**
~~1. Open an exam from exam.net in high-security mode with Drawing Tools enabled.
2. Observe that touch screen input works.
3. Press the (left) Alt key on the keyboard.
4. Touch screen stops being recognised. Mouse wheel stops scrolling.~~
See updated repro steps: https://github.com/SafeExamBrowser/seb-win-refactoring/issues/70#issuecomment-767112923

**Expected Behavior**
Pressing the (left) Alt key on the keyboard should not affect the input methods.

**Screenshots**
/

**Version Information**
 - OS: Windows 10 Home, Version 2004
 - SEB-Version: SEB 3.1.1.250

**Additional Context**
On some occasions, a context menu with "Move", "Size", "Minimise", "Maximise", "Close" also appears. Selecting any of enabled options just makes the issue worse: whole window starts randomly zooming in and out and dancing around when you touch the screen afterwards.

**Comment by danschlet** [comment]
For me this looks like you have a tool or driver installed which tries to display the mentioned context menu or another kind of overlay (floating) window/UI element when the left Alt key is pressed. 

SEB tries to hide any process, which attempts to display any kind of window during the exam. As far as I remember (our Windows developer can confirm that), if SEB cannot hide that process, it terminates it (this should be mentioned in the log file). If that tool/driver controls touch input and scrolling by mouse wheel, then this will stop working. Did you try if touch input and mouse wheel scrolling works again when you quit SEB or is a restart required to make it work again?

This is only a theory, but if you upload SEB log files, we might find the reason there.

**Comment by dbuechel** [comment]
According to the log, you pressed "ALT+SPACE", which is the shortcut for the default context menu of a window (as you described under additional context). Did you try to allow "ALT" resp. all key shortcuts with "ALT+..." in the configuration? I do not have a touch device at hand, but if you provide me a link where I can test an exam.net exam, I'll try to reproduce your issue in a VM with touch simulation.

**Comment by dbuechel** [comment]
Could you furthermore please verify that the issue does not happen in the CEF sample application? See https://cef-builds.spotifycdn.com/index.html#windows64

**Comment by dbuechel** [comment]
Sorry for the late response. In the meantime, I have updated the browser engine twice, and I have seen that there were some improvements regarding touch input handling. Could you please test the latest beta build of version 3.2 to see whether anything has improved?

https://sebdev-let.ethz.ch/api/buildjobs/jnorllc88f9dln3l/artifacts/SEB_3.2.0.293_SetupBundle.exe

**Comment by dbuechel** [comment]
This appears to be a framework issue. The underlying problem seems to be the ALT key, as in Windows when "a user presses the Alt key by itself [...] that moves keyboard focus to the menu bar of the application having keyboard focus, and the key is not delivered to the application. In that state, another press of the Alt key will be delivered to the application." (see https://en.wikipedia.org/wiki/Alt_key#Alt_key_pressed_alone). And with the browser engine being a child window embedded in various layers, this system command gets lost somewhere. So I'm afraid we have to live with this issue for the moment.

**Comment by zznidar** [comment]
Hey, I have tried the beta build you had linked, but unfortunately the issue persists. 

Is there any way that SEB could "Request Attention" (similar to [win.requestAttention](https://docs.nwjs.io/en/latest/References/Window/#winrequestattentionattension) in NW.js)? Just a thought, not sure if it would actually fix the problem.

**Comment by zznidar** [comment]
I did some more playing around with it. Changed the config to make the browser windowed (show the title bar, maximise, minimise etc.) and to allow the Reload (refresh page) button.

[windowed.txt](https://github.com/SafeExamBrowser/seb-win-refactoring/files/6367246/windowed.txt)

It turns out that touch only stops working inside the browser (I can still use touch to drag the window arround, to press buttons on the control bar at the bottom of the screen, to press the Menu -> Zoom/Find in page buttons and the Reload button). 

What I found is that the Reload button fixes the problem: after the page is reloaded, touch works normally (until I re-do the repro steps). Does SEB do anything special when user clicks the reload button?

**Comment by dbuechel** [comment]
No, there unfortunately isn't any way to fix this issue at the moment, I have tried various different attempts to maintain the input focus when pressing ALT. The reason why it works after reloading is that by activating the reload button, you move the input focus once again to the browser window resp. content.

**Comment by dbuechel** [comment]
I think we unfortunately won't be able to fix this issue at the moment, given that it pertains to the basic functionality the OS performs when pressing the `ALT` key. However, please do feel free to reopen the issue if you gain more insight or have an idea you'd like us to try in order to fix the problem.
