### ISSUE TITLE
random quick exit from the browser and restoration

### ISSUE THREAD

**Issue by MisterCoBen** [SafeExamBrowser/seb-win-refactoring#701]
**Describe the Bug**
While using the browser, it will randomly come back to the last scene befor I've entered the browser for max 1s and short for about 0.5s. And the action(like typing) during the short exit won't influence the browser. 

**Steps to Reproduce**
No idea, it comes randomly while using any functions form the browser. The interval between problems can be about 1-2 minutes. 

**Version Information**
 - OS: ![grafik](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/97687476/71b287e2-0bcd-4897-bc74-43546557e3b7)
 - SEB-Version: SEB 3.5.0

**Additional Context**
I've also installed NVDIA Broadcast and the security centre is also all opened. And I'm not sure if the giant modified size of vitural RAM and the opening of BitLocker will have any influence.(Just a guess, not tested)

**Comment by dbuechel** [comment]
This very much looks like an application is interfering with the lockdown induced by SEB (see e.g. #520). Can you please provide the log files of the affected session(s)? They can be found under `%LocalAppData%\SafeExamBrowser\Logs`.

**Comment by MisterCoBen** [comment]
[2023-11-03_14h18m25s_Client.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/13265962/2023-11-03_14h18m25s_Client.log)
[2023-11-03_14h18m25s_Runtime.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/13265963/2023-11-03_14h18m25s_Runtime.log)
[2023-11-03_14h18m25s_Browser.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/13265964/2023-11-03_14h18m25s_Browser.log)

**Comment by dbuechel** [comment]
Yes, there is definitely an application interfering with the lockdown of SEB. There used to be an issue with Cisco WebEx as well as Sophos anti-virus, but it may be another software in your case (e.g. a meeting or security application).

**Comment by MisterCoBen** [comment]
Do you have some useful tools to cathch the source of the trouble? Or how can I provid some more useful Infos? I've only installed the Teams as the meeting app and McAfee + the one from windows itself as security app. Although i've uninstalled McFee once before the installation of SEB, but i can still see its services behind, so I just deleted all its files through the service and the issue seems to be fixed. I'm not sure because I've forgotten about when I've deleted it completely, or I just needed to restart the PC to fix it and I've only tested it for about 3 minutes. By the way, the service name is "WebAdvisor by McAfee".

**Comment by dbuechel** [comment]
> ... I just deleted all its files through the service and the issue seems to be fixed.

Thanks a lot for the feedback. Do I understand you correctly that you think the issue has been caused by the McAfee product you were using? If so, could you please specify which exact product and version you were using?

**Comment by MisterCoBen** [comment]
I'm not sure about the version, because I've totally deleted it. But there are only 2 versions, I think 
![grafik](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/97687476/8712feed-0a31-4328-a090-96283f6f9912)
The one from me should be the latest one.

**Comment by dbuechel** [comment]
Okay, thanks for the clarification. Then we can and unfortunately must conclude that it is an interference with the kiosk mode of SEB by one of the above versions. We unfortunately cannot do much about that, the vendor of the above products would need to fix this on their side.
