### ISSUE TITLE
Resolving Triple Login Requirement with Safe Exam Browser and Moodle

### ISSUE THREAD

**Issue by dbuechel** [SafeExamBrowser/seb-win-refactoring#703]
### Discussed in https://github.com/SafeExamBrowser/seb-win-refactoring/discussions/702

<div type='discussions-op-text'>

<sup>Originally posted by **Elrashid** November  4, 2023</sup>
Hello Community,

I'm reaching out for help with an issue we're experiencing with Safe Exam Browser (SEB) integration within our Moodle setup. Our students are being asked to log in three times during the process of accessing an exam:

1. Initial Moodle Login: Students first log in to Moodle via a standard web browser.
2. Launching SEB-Win: They then click a link to launch SEB, which prompts for login credentials again.
3. SEB-Win Restart: After the initial SEB launch, SEB restarts for some reason and asks for the login details a third time.

Any advice, suggestions, or guidance on this matter would be greatly appreciated. If additional information is needed, please let me know, and I will provide it promptly.

</div>

**Comment by Elrashid** [comment]
https://github.com/SafeExamBrowser/seb-win-refactoring/discussions/833

**Comment by dbuechel** [comment]
At least the third login should become obsolete as we're now automatically overriding the required settings. The changes can be tested starting with the latest beta build of version 3.8.0: https://sebdev.ethz.ch/api/buildjobs/uhu49u589dsh8hy9/artifacts/SEB_3.8.0.690_SetupBundle.exe.
