### ISSUE TITLE
SEB & Sprint (dyslexia software)

### ISSUE THREAD

**Issue by NekoJonez** [SafeExamBrowser/seb-win-refactoring#709]
Some of our students use a software called "Sprint" to aid in their needs. 
https://www.sprintplus.be/en

Today we had a test where are students where allowed to use Sprint to open their exam. Yet, with the functionality of Sprint... They can click on "Open" to open any .pdf file, defeating part of the reason why we use Safe Exam Browser. Now, blocking .pdf files isn't the best idea since you partially cripple the program with that AND if the teacher wants to use a PDF in their exam for a reading exercise, they might not be able to open that PDF. 

Is there anything that SEB can do or is this something we need to take up with the developers of Sprint?

**Comment by dbuechel** [comment]
Yes indeed, that is something you'd need to take up with the developers of Sprint, as SEB cannot control the internal functionality of that software (or rather any third-party application, as a matter of fact).
