### ISSUE TITLE
Javascript wont run

### ISSUE THREAD

**Issue by gstyle94** [SafeExamBrowser/seb-win-refactoring#71]
Hi I've red the documentation of version 2.3.
Here is stated beneath browser settings to enable javascript.
In the new version 3.1.1. this setting is missing. 
When i start the video in the SEB it asks to reload the website and then wont play the video.

when the same page is opened in a other browser say chrome or firefox this aint a issue by playing the video.

this is played on a win10 enterprise hp notebook

**Comment by dbuechel** [comment]
How can we reproduce the issue? Do you have a link to the video which is causing the issue? Please note that proprietary video codecs are not supported in SEB 3.x, so this might be the reason why the video isn't being played.

**Comment by dbuechel** [comment]
Also, what exactly is the issue with JavaScript which you mention in the issue title?

**Comment by gstyle94** [comment]
Hi,

Thanks for your quick reply.
I use the added config file and the result is in the video.
Sadly you’ve to login to acces the video.
I’ve found this page with requirements is that helpfull?
https://handleiding.toets.nl/systeemeisen-684

thanks in advance, kind regards

[toa2.zip](https://github.com/SafeExamBrowser/seb-win-refactoring/files/5855122/toa2.zip)

**Comment by dbuechel** [comment]
Thanks for the reply and the video. Unfortunately, I'd need access to the web page with the video itself, i.e. I need to be able to reproduce the issue in order to investigate and potentially fix it...

**Comment by gstyle94** [comment]
Hi, 
you've to login to acces the video.
is it possible to share your mail adress so i can explain how to logon?

**Comment by dbuechel** [comment]
You can find my mail address via my profile or you can send me a direct message on SourceForge.

**Comment by dbuechel** [comment]
@gstyle94 Thanks, I received the credentials and I'll have a look at the issue.

**Comment by dbuechel** [comment]
Okay, the reason why the video doesn't run is because the video codec is not supported (SEB 3.x only supports open-source video codecs, proprietary codecs are not supported). Why the JavaScript alert is being shown is unclear to me, you'd ideally show the issue to the developers of your LMS, it might have something to do with the way they embed videos.

**Comment by gstyle94** [comment]
Hi, i've checked with them, they say they use e-v1.js
https://wistia.com/support/developers/e-v1
is there a way to add this in the config file?

**Comment by dbuechel** [comment]
Not in the config file, no. But you can ensure that the mentioned domains are allowed in case you're using the URL filter. Using an open-source video codec, I think the video should play without issues.
