### ISSUE TITLE
You can open the CMD While in Save Exam Browser

### ISSUE THREAD

**Issue by HennieLP** [SafeExamBrowser/seb-win-refactoring#710]
**IMPORTANT**
Please _always_ consult the documentation first before creating a bug report!
https://safeexambrowser.org/windows/win_usermanual_en.html

**Describe the Bug**
You can open the CMD While in Save Exam Browser

**Steps to Reproduce**
Replace Before hand
C:\windows\system32\Utilman.exe
With:
C:\windows\system32\cmd.exe

Open Save Exam Browser Press CTRL ALT DEL and press on the litel mann in the Right Corner 

**Expected Behavior**
Schudent Work

**Version Information**
 - OS: [Windows 11 Pro 22621.2506]
 - SEB-Version [SEB 3.5.0, 3.5.0.544]

**Comment by dbuechel** [comment]
Thanks for your report. This can be prevented by using the SEB Service component (see https://safeexambrowser.org/windows/win_usermanual_en.html#SecurityPane).
