### ISSUE TITLE
Dutch translation

### ISSUE THREAD

**Issue by NekoJonez** [SafeExamBrowser/seb-win-refactoring#713]
If I want to help translate SEB into Dutch, is translating this file enough?

https://github.com/SafeExamBrowser/seb-win-refactoring/blob/master/SafeExamBrowser.I18n/Data/en.xml

Or are there others that should be translated?

EDIT: I mainly help translating open source projects into my native language or fix issues with that translation. I'm an translation editor for WordPress for Dutch & Flemish. I'm willing to show my work if you want to see it first.

**Comment by dbuechel** [comment]
Yes exactly, that is the (one and only) file with all strings which are displayed in the user interface, so it'd be enough to translate it. We'd very much welcome your contribution!

**Comment by NekoJonez** [comment]
@dbuechel How can I test that build?

**Comment by NekoJonez** [comment]
I just tested that build and it looks fine :D 
Any idea when it shall release? @dbuechel

**Comment by dbuechel** [comment]
Excellent! We're currently performing the end testing and hope to be able to release it soon (next week or the one thereafter).
