### ISSUE TITLE
Missing user folder for up and download

### ISSUE THREAD

**Issue by Noranius** [SafeExamBrowser/seb-win-refactoring#719]
**Describe the Bug**
Only drives are displayed when files shall be uploaded or downloaded. This is problematic in our case because our pool computers only have a drive C, which is hidden. Hence, no drive is selectable for downloading/uploading files.

Hiding drives: [https://learn.microsoft.com/en-us/troubleshoot/windows-client/group-policy/using-group-policy-objects-hide-specified-drives](https://learn.microsoft.com/en-us/troubleshoot/windows-client/group-policy/using-group-policy-objects-hide-specified-drives)

**Steps to Reproduce**
1. Hide drive
2. Start SEB
3. Try downloading/uploading a file

**Expected Behavior**
Also the library of the Windows computer is shown or the home directory of the user.

**Version Information**
 - OS: Windows 11 (10.0.22621)
 - SEB 3.5.0

**Comment by dbuechel** [comment]
There is an option to use a temporary up- and download directory in the configuration tool, please do try it out and report back here.

**Comment by Noranius** [comment]
We have tried that as well. However, the temporal folder is not down if the user is allowed to select a folder and define a name for the file.

To give a bit background: the students shall draw some diagrams during the exam. Those diagrams are generated by them via a website. They can download the diagram and upload it in the respective question.

Greetings
Mathias

**Comment by dbuechel** [comment]
>[...] the temporal folder is not down if the user is allowed to select a folder and define a name for the file.

I'm afraid I don't quite understand this part; you can disable the option to select a custom download location in the configuration, or what do you mean exactly?

**Comment by dbuechel** [comment]
Any updates here?

**Comment by Noranius** [comment]
Hi,I planned to upload some screenshots. However, I had other issues to cope with. Sorry. I hope to make the screenshots until next week.Am 12/12/2023, 17:23 schrieb "Damian Büchel" ***@***.***>:

   
  Any updates here?

**Comment by dbuechel** [comment]
Closed due to lack of feedback.
