### ISSUE TITLE
Integerity Protection

### ISSUE THREAD

**Issue by Tim-Hobbes** [SafeExamBrowser/seb-win-refactoring#72]
**Is your feature request related to a problem? Please describe.**
At the moment, the virtualization protection is easily bypassed by patching the SystemComponents dll with a program like .net reflector. 

**Describe the solution you'd like**
I think the best solution would be to implement an integrity protection component, this component should not be easy to patch out. So it can be obfuscatedor written in a programming language which is not easily reversed like C or C++. To prevent the patching of the source code I think it is best to not make this code opensource. 

**Describe alternatives you've considered**
Another option is that the MD5 or SHA256 sums are included into the browser exam key. This would be quite hard to patch out because it is harder than just returning false, but it is still quite easy to patch.

**Comment by dbuechel** [comment]
We have such a binary module in our roadmap, but are currently busy with other priorities. In the end, it is theoretically impossible to completely secure a machine over which we don't have any control (i.e. a user's machine on which they have admin privileges and can thus manipulate every imaginable aspect of that system).
