### ISSUE TITLE
Add russian language to SEB

### ISSUE THREAD

**Issue by IlmirSharifullin** [SafeExamBrowser/seb-win-refactoring#720]
Our institute is going to use seb and we ran into a problem, that there is no russian in this app. Could you add it pls?
It may be just translate of all existing sentences in `SafeExamBrowser.I18n/Data/en.xml` by google translater, or smth similar to it

**Comment by danschlet** [comment]
No, but we might add Ukrainian as a language option.

**Comment by dbuechel** [comment]
We're unfortunately completely busy with other issues at the moment and furthermore lack the required language skills in our team, but it is correct that a translation of the XML file mentioned above would be sufficient to translate all text visible in the user interface. However, please do feel free to contribute a translation, then we'd happily integrate it in an upcoming release build.

**Comment by dbuechel** [comment]
You can now test the translation in the latest beta build: https://sebdev-let.ethz.ch/project/AppVeyor/seb-win-refactoring/builds/746
