### ISSUE TITLE
Block OBS by default as well, since it can capture a screen to "steal exam questions".

### ISSUE THREAD

**Issue by NekoJonez** [SafeExamBrowser/seb-win-refactoring#727]
As the title says, let's block OBS as well. I'll make a PR.

**Comment by dbuechel** [comment]
Thanks for the input, we shall definitely include this in the upcoming release version 3.6.0.

**Comment by dbuechel** [comment]
You can now test the change in the latest beta build of version 3.6.0: https://sebdev-let.ethz.ch/project/AppVeyor/seb-win-refactoring/builds/751.
