### ISSUE TITLE
using seb:// link

### ISSUE THREAD

**Issue by thomasvergouwe** [SafeExamBrowser/seb-win-refactoring#730]
**Describe the Bug**
I'd like to make it possible that students can click a URL and then SEB opens with the right configuration.
I've created a .seb config file and it works perfectly. I discovered the seb:// function, but there is very little documentation on how to use it.
I've uploaded the seb file to my onedrive to test it. I use seb://"direct link to .seb file". It opens SEB but then I get the error: the configuration resource "seb://https://..." is not supported.
The log file is attached.
[2023-11-27_12h22m50s_Runtime.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/13473530/2023-11-27_12h22m50s_Runtime.log)

**Expected Behavior**
Seb opens with the config settings I've set.

**Screenshots**
![image](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/87338734/d1be42c5-dc19-436e-ac5e-31d0635d78dd)

**Version Information**
 - OS: Windows 11 education 23H2
 - SEB-Version SEB 3.3.1

**Comment by dbuechel** [comment]
You'll have to remove the `https` part, the SEB URI scheme replaces the HTTP scheme:

`https://www.example.com/abcde...` needs to become `sebs://www.example.com/abcde...`

**Comment by thomasvergouwe** [comment]
Thank you! Then I know I'm on the right track.

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________
