### ISSUE TITLE
Trying to close Teams.exe on shared devices can cause issues when users don't sign off.

### ISSUE THREAD

**Issue by NekoJonez** [SafeExamBrowser/seb-win-refactoring#731]
[2023-11-29_11h12m10s_Client.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/13499451/2023-11-29_11h12m10s_Client.log)

We have shared devices for students who forget their own device. Now, if users don't sign off and another user signs on... SEB refuses to boot since it can't close Teams. 
Now, it tries to look for Teams in the OTHER users in their profile. Is there a way to only check if Teams is opened for the current user? 
Or does this pose a security risk? 

Or we could ammend the error if Teams can't be closed with: "If this is a shared device, please reboot the device so Teams is closed on the other logged in accounts."

**Comment by dbuechel** [comment]
That's an issue you'd need to handle on the organizational side of things. At the moment, SEB simply scans all running processes and does not distinguish under which account they're running, nor are there any plans to change that behavior in the near future.
