### ISSUE TITLE
Possible to pause audio recordings that should be unpausable

### ISSUE THREAD

**Issue by Exosploit** [SafeExamBrowser/seb-win-refactoring#736]
**Describe the Bug**
When an audio recording is not supposed to be paused, you can go to the previous page and then return back to the same page. Doing this will cause the recording to pause and you can just press play to continue the recording.

**Steps to Reproduce**
1. Go to a page which has an audio recording
2. Click on play
3. Click on previous/next page
4. Click on the previous/next button to return to the latest page
5. The audio recording will be paused (error)
7. Press play to continue

**Expected Behavior**
While the audio recording is playing, you should not be able to change page or the recording should skip to the end so you cannot continue from the same point in the recording.

**Version Information**
 - OS: Windows 11 Education
 - SEB-Version 3.5.0

**Additional Context**
This happened during our testing of the program in school.

**Comment by danschlet** [comment]
This is an issue of your exam system, report it to your exam provider. SEB is "just" a web browser. Obviously such issues have to be handled by the web developers of all the various web-based exam solutions which can be used with SEB (we only develop SEB, not such web-based exam solutions).

Btw. there are settings is SEB to prevent navigation (separate for the exam window and for additional browser windows). If your exam provider uses those settings, they may prevent this trick to pause audio.
