### ISSUE TITLE
How to read seb version at client device

### ISSUE THREAD

**Issue by kfathy-ys** [SafeExamBrowser/seb-win-refactoring#737]
I want to know seb version installed at client device

**Comment by d-damien** [comment]
Is there a list of possible user agent formats ? I have an exam software logging SEB/3.6.0 and SEB/3.3.2 (which are probably just the latest for windows and macos, so far so good), but also SEB/14968 CFNetwork. What is this one ? Something related to Apple it seems.

**Comment by danschlet** [comment]
That's no valid SEB user agent. What version produced that user agent?
