### ISSUE TITLE
Check the installed browser vesion

### ISSUE THREAD

**Issue by Muhammed-Aslan** [SafeExamBrowser/seb-win-refactoring#739]
We are developing an exam portal using .Net Core  back-end and Angular front-end  
and we would like to enforce students to use the latest version of the SafeExamBrowser during the exam.
Any Idea how to get the version of the installed Browser ?

**Comment by danschlet** [comment]
Just read our documentation:
Manual: [Browser User Agent](https://safeexambrowser.org/windows/win_usermanual_en.html#BrowserPane)
Developer information: [SEB Javascript API](https://safeexambrowser.org/windows/win_usermanual_en.html#BrowserPane)

**Comment by Muhammed-Aslan** [comment]
@danschlet  Could you please Share a correct link for the "SEB Javascript API".
thanks in advance

**Comment by danschlet** [comment]
Just do a Google search for exactly this term you wrote in brackets and you'll find it yourself.
