### ISSUE TITLE
Browser Zoom keyboard shortcut works partially. 

### ISSUE THREAD

**Issue by wgar9916** [SafeExamBrowser/seb-win-refactoring#74]
When accessing a web page via SEB, with page zoom enabled, the zoom-in 'Ctrl+' shortcut does not work correctly. Zoom out 'Ctrl-' does correctly zoom-out. It should be noted that this is when using the plus key on the number row, where it is the shift-function of the equals (=) key. 

If using a fullsize keyboard with numberpad, the numberpad plus key works correctly to zoom-in on exam content. I suspect that SEB is trying to interpret 'Ctrl=', which is not mapped as a zoom-in shortcut. This is however the behaviour on standard browsers (Chrome/FF/Edge etc), so candidates are used to this. Additionally, Ctrl-Shift-= does not work to zoom in. 

**Steps to Reproduce**

1. Configure an exam such that page zoom is enabled.
2. Launch said exam
3. Attempt to zoom in using Ctrl+ (no effect)
4. Verify zoom out works by using Ctrl- (zooms out)
5. Close exam.

**Expected Behavior**

When pressing Ctrl+, if the setting is enabled in the exam config, the page zooms in.

**Version Information**
 - OS: Windows 10 Professional Version 19014
 - SEB 3.1.1

**Additional Context**

Current workaround is to enable browser tool bar and use on-screen zoom controls.

**Comment by dbuechel** [comment]
Which keyboard layout are you using? Please note that e.g. in German, one has to use CTRL+SHIFT+1, not CTRL+1, in order to zoom in, as the + symbol is the shift function of the 1 key.

**Comment by wgar9916** [comment]
Hi @dbuechel ,

Thanks so much for your quick response.  The keyboard layout is set as ENG. I have tested, and the Ctrl-SHIFT-1 combination works to zoom in. However this is not marked on ENG layout keyboards, as Ctrl-SHIFT-1 would normally be an exclamation mark (!). 

So it seems that SEB is interpreting the keyboard shortcut as if it was from a GER keyboard layout?

Thanks.

**Comment by dbuechel** [comment]
Thanks for the info, I'll have a look at it and will come back once I know more.

**Comment by dbuechel** [comment]
Sorry for the late reply. The bug should now be fixed, you can test it for yourself in the latest beta build for version 3.2: https://sebdev-let.ethz.ch/api/buildjobs/9w68k4mn2ybhgox6/artifacts/SEB_3.2.0.294_SetupBundle.exe
