### ISSUE TITLE
Invalid Class (fatal error)

### ISSUE THREAD

**Issue by jcpanos** [SafeExamBrowser/seb-win-refactoring#746]
Hello,

I downloaded Safe Exam Browser (version 3.6.0.633) as well as the previous version to this. The same result occurred where it would install successfully and upon me launching the program the following error would pop up:

![safebrowser-error](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/153296664/9133d668-55e7-4b8d-902e-6f677641f690)

This matches past issues reported, however, none of the solutions worked for me. See this for an example: https://github.com/SafeExamBrowser/seb-win-refactoring/issues/33

I tried this procedure a few times and it still didn't fix the problem. Please note that this is a work computer and these instructions were received from my IT team. Others in my training have not had this issue.

Procedure to potentially fix WMI corruption:

-close all Apps run cmd as admin

1. Disable and stop the WMI service.
sc config winmgmt start= disabled
net stop winmgmt

2. Run the following commands.
Winmgmt /salvagerepository C:\WINDOWS\System32\wbem
Winmgmt /resetrepository C:\WINDOWS\System32\wbem

3. Re-enable the WMI service and then reboot the server to see how it goes.
sc config winmgmt start= auto

-restart PC

Any help here would be great. Thank you.

**Comment by dbuechel** [comment]
I currently have no other explanation that indeed, there is an issue with your particular system (configuration). The code in question tries to initialize the MAC address of the active network adapter: https://github.com/SafeExamBrowser/seb-win-refactoring/blob/master/SafeExamBrowser.SystemComponents/SystemInfo.cs#L244.

This should work without any issues when you're having a working network resp. internet connection, which I assume is the case on your system?

**Comment by jcpanos** [comment]
Yes, this is the case with my system. It is working with an internet connection. I've had a different, separate issue that may also be tied to this overall problem. 
I got a different computer from work to use this tool and take the exam.
Thank you.

**Comment by dbuechel** [comment]
Okay, then we'll consider the issue as done for the moment. But please do feel free to reopen it in case it should reappear.
