### ISSUE TITLE
SEB install is blocked by TotalAV

### ISSUE THREAD

**Issue by NekoJonez** [SafeExamBrowser/seb-win-refactoring#750]
When you have TotalAV is installed, and you try to install SEB, you get blocked by generic generated AV messages when the webview component is being installed.

**Comment by dbuechel** [comment]
That's an issue of TotalAV and they need to resolve it resp. fix the false-positive detection of MSFT's WebView. You might want to report it as such to TotalAV.

**Comment by NekoJonez** [comment]
Just for people who google this and find this ticket, I have submitted a report to TotalAV to fix this. Should be fixed in the near future I assume.
