### ISSUE TITLE
Make Cursor Validation Configurable

### ISSUE THREAD

**Issue by dbuechel** [SafeExamBrowser/seb-win-refactoring#755]
### Discussed in https://github.com/SafeExamBrowser/seb-win-refactoring/discussions/754

<div type='discussions-op-text'>

<sup>Originally posted by **peterbuysse** December 12, 2023</sup>
Hi
We orrganised a SEB-examen in our school today. What never happend before: a lot of students weren't able to start SEB-session. I found this message in the logs:

2023-12-11 10:40:47.713 [07] - INFO: Attempting to verify cursor configuration...
2023-12-11 10:40:47.713 [07] - WARNING: Cursor configuration is compromised: 'C:\Users\vonckxs0702\Downloads\fortnite-1\fortnite rocket launcher.cur'! Aborting session initialization...

We found that a program called 'Custom Cursor' was responable: when we removed it, SEB started!

Can we change the settings in the SEB-configuration file to ignore this error?

Thanks!</div>

**Comment by dbuechel** [comment]
We can certainly add a new configuration option.

**Comment by NekoJonez** [comment]
Related ticket: #751

**Comment by dbuechel** [comment]
There is a new configuration option which can be found in tab "Security" (enable cursor verification) and tested in the latest beta version: https://sebdev-let.ethz.ch/api/buildjobs/wxae9f4aqb6x70rh/artifacts/SEB_3.7.0.673_SetupBundle.exe.

**Comment by dbuechel** [comment]
@simonatwork FYI
