### ISSUE TITLE
FN key can cause issues - Give ability in SEB config tool to disable it.

### ISSUE THREAD

**Issue by NekoJonez** [SafeExamBrowser/seb-win-refactoring#762]
The FN key can cause issues or make it possible to abuse things. 
On newer HP laptops for example, if you press FN+F12, you can enter a macro program where you can edit something to appear or get pasted on the clipboard.
Also, I wanted today to disable some F-keys to avoid students entering airplane mode. Yet, if I disable the F-key... it doesn't work. 
At first, I thought this was a bug, but the functionality on our laptops was flipped outside of SEB. After a firmware update, it worked like normal. 

Now, I think it would be a great idea if we can disable the FN key (and FN lock if it's a separate key) so things like the two examples above can't happen.

**Comment by NekoJonez** [comment]
I did some further research and it seems like blocking the FN key is near impossible. 
It needs to be done on BIOS/EUFI level... https://support.hp.com/us-en/document/ish_5878386-5878448-16 

What do you think? Any idea's?

Otherwise, I'll just make two new tickets and look into if we can disable the button to enter airplane mode and the "HP Programmable Key" app block.

**Comment by danschlet** [comment]
Just a general remark: SEB cannot block everything, especially individual features of specific devices. It is also not feasible to develop (sorry, we can't look into HP-specific features!) and doesn't make sense. Most important is, that SEB blocks information and communication channels and ways to leak the exam. The private or isolated clipboard features prevent cheating using tools which manipulate the clipboard. 

Why do you want to block students from activating airplane mode? In most cases they won't be able to continue the exam and you can detect when they're offline either in the exam solution or with SEB Server. Then you can act on that with administrative measures.

**Comment by NekoJonez** [comment]
That's a fair remark. And I totally understand and agree with it. I was thinking/looking for a way to avoid students going into that mode since it makes a whole discussion of time loss, concentration loss etc... But, you are totally right that looking into things like this and developing stuff for this wouldn't make sense.

In any case, I have been looking further into things and:

- Lenovo has also a smartkey and you can't attach text to it.
- The HP programmable key --> if you set the clipboard policy on "SEB only" it's cheating potential is blocked. 

Unless there is something I'm overlooking, I think we can safely close this issue with the two above answers in mind.
