### ISSUE TITLE
Copy & Paste Between Browser Windows Not Working

### ISSUE THREAD

**Issue by dbuechel** [SafeExamBrowser/seb-win-refactoring#764]
### Discussed in https://github.com/SafeExamBrowser/seb-win-refactoring/discussions/763

<div type='discussions-op-text'>

<sup>Originally posted by **moehzhaw** December 14, 2023</sup>
**The following situation applies:**
- During a test, additional resources are available, e.g. access to Deepl.
- After something has been translated, the translation should be copied from Deepl and then pasted into a free text task on Moodle.
- Status for Windwos: ❌does not work with my device (Windows 11) with the latest SEB Windows version (3.6.0); it still worked with Win version 3.5.0. (What still works under Win 3.6.0: I can still copy and paste text within the Moodle test... but not across resources).
- Status with macOS: ✅ Works with the latest Mac version (3.3)
- Conclusion: Due to this difference, there is an enormous inequality in the treatment of Windows and macOS users

**My questions:**
- Do other users have the same challenge?
- Is it possible that the latest Windows version (3.6.0) prevents copy-paste even more strictly?
- If the strict handling is not intended, what could be the reason why copy-paste no longer works?
- What workaround could solve the problem?

</div>

**Comment by dbuechel** [comment]
Thanks for the report, this is indeed a bug. We'll try to fix it resp. improve the implementation so that the isolated clipboard is shared between all browser windows.

**Comment by simonatwork** [comment]
Would it be possible to be able to disable the isolated clipboard feature at all? There seems to be a checkbox in the Config Tool for disabling the private clipboard for Macintosh users, but this does not seem to affect Windows PCs.

**Comment by dbuechel** [comment]
@simonatwork Yes, you can disable it by using the clipboard policy "Allow".

**Comment by dbuechel** [comment]
@moehzhaw Could you please test the latest beta version to check whether the issue is resolved for you: https://sebdev-let.ethz.ch/api/buildjobs/8894md0ivqmjb35y/artifacts/SEB_3.7.0.671_SetupBundle.exe.

**Comment by KsseeBea** [comment]
its still the same Problem. copy and paste isn't possible...

**Comment by dbuechel** [comment]
@KsseeBea Please be specific: What are you trying to do and why do you think it isn't working resp. what are you expecting to work how?

**Comment by KsseeBea** [comment]
we try (like you in your startpost) to use a additional resource for an exam. the students should create code on a webpage and submit it via an exam.net-test.
In Version 3.3 it works properly. In Version 3.6 and Version 3.7 copying text between resources isn't possible (with the same settings like in Version 3.3 - there it works). 
It doesn't make a difference starting directly via exam.net or starting via a created config-File. In both cases: SEB 3.3 is working fine - copy and paste has no problems
SEB 3.6 and 3.7 - copy and paste isn't possible
operating systems are win 10

**Comment by moehzhaw** [comment]
From our side, I can report some progress. I tested our setting with additional ressources with
- SEB-Version Windows 3.7.0 and
- Windows 11 Enterprise and
- Moodle 4.2.6.

It results, that copy-paste between ressources is possible now... but, only once: I can copy text from a website and paste it in an essay question type. But, if I go to the next question by turning the moodle-page pasting is not possible any more with Windows (with macOS-Version 3.3 this still works).. Nevertheless, the situation has improved compared with the Windows-Version 3.6.0. Thanks for your effort!

**Comment by dbuechel** [comment]
That is better, yet not what we ultimately want. Could you please provide me access to such an exam in Moodle including step-by-step instructions so that I can attempt to debug and fix the issue?

**Comment by moehzhaw** [comment]
You're enrolled as a student to the course [E-Prüfungen mit Safe Exam Browser: Funktionskontrolle](https://moodle-exam.zhaw.ch/course/view.php?id=13437). As you can see, there are 3 demo-tests. For the copy-paste-check you can use
2. E-Demo-Test MIT Zugriff auf weitere Web-Ressourcen
or 
3. E-Demo-Test MIT Zugriff auf SWITCHdrive.

**Comment by dbuechel** [comment]
I think I was able to fix the issue, I forgot to inject already existing clipboard content on page load. Could you please retest the latest build @moehzhaw: https://sebdev-let.ethz.ch/api/buildjobs/1vs6gjahr5madjto/artifacts/SEB_3.7.0.678_SetupBundle.exe.

**Comment by moehzhaw** [comment]
There is one thing more working now: I can copy text from a website and paste it in several essay questions... So far so good. But, I do not manage to copy-paste text from a PDF-ressource at all. @dbuechel: Or do you manage? Please, try it with the "2. E-Demo-Test MIT Zugriff auf weitere Web-Ressourcen" in our "Funktionskontrolle-Kurs". In the first question, you find a PDF as a ressource. (You also find a Website as a ressource: Here copy-paste works as mentioned...)

**Comment by dbuechel** [comment]
Excellent, then that issue should also be resolved. No, copying from a PDF is for the time being not working nor can I promise that it ever will work, as PDFs are rendered by the internal PDF reader and to my knowledge there is no way to inject our isolated clipboard implemented in JavaScript into an instance of the internal PDF reader.

**Comment by dbuechel** [comment]
As a workaround, you can simply render PDFs on your end (using e.g. PDF.js), then the isolated clipboard should work as expected.

**Comment by steinhp** [comment]
> @simonatwork Yes, you can disable it by using the clipboard policy "Allow".

As we would also need do disable the C/P functionionality in the SEB: with clipboard policy you mean the windows one or is there such a policy for the SEB and when how to do?
tnx a lot!

**Comment by moehzhaw** [comment]
Hi 
With the version 3.7.0 for Windows copy-paste is possible again. Thanks for this! And yet, I would like to come back to the PDF context: In this context copy-paste is not working with 3.7.0, for exemple with [this ressource](https://www.zh.ch/content/dam/zhweb/bilder-dokumente/organisation/staatskanzlei/digitale-verwaltung-und-e-government/strategie_digitale_verwaltung.pdf).
I've just checked copy-paste from PDF to Moodle with the version 3.5.0 for Windows: This works. = Is it possible to have this implemented in the next version again?

**Comment by dbuechel** [comment]
Unfortunately not (at least for the time being), please refer to https://github.com/SafeExamBrowser/seb-win-refactoring/issues/764#issuecomment-1997174217 as to why we can't provide that functionality with the isolated clipboard.

**Comment by erik1980** [comment]
Hello,

I need your help with a couple of issues I'm facing while preparing an exam on Moodle.

One of the questions is an Essay type and requires students to open an online compiler, design a web page (HTML, CSS, and JavaScript), and then copy and paste the code into the answer area. I'm using Safe Exam Browser, and I've encountered the following issues:

1. I cannot use the Ctrl+C/Ctrl+V key combinations to copy and paste between the question window and the online compiler. Safe Exam Browser seems to block this functionality.
2. 
3. When I try to copy and paste text within the same answer area, the text gets duplicated. For example, if I copy "Hello," it pastes "HelloHello."

I'm using Moodle 4.2.3+ (Build: 20231110), Safe Exam Browser 3.7.0, and Windows 11.

Do you have any suggestions or solutions for these issues?

I appreciate any advice or recommendations you can provide. Thank you very much in advance!
