### ISSUE TITLE
Spotify keeps playing when you start SEB

### ISSUE THREAD

**Issue by NekoJonez** [SafeExamBrowser/seb-win-refactoring#766]
Today, a fellow IT admin was testing SEB and noticed that his Spotify podcast kept playing. Since, this can used for cheating, let's block Spotify by default. 
If I hear in that group that students are using other podcast apps, I'll add a PR to add those and block them as well. :)

**Comment by dbuechel** [comment]
Excellent, thanks for your contribution. I shall merge the pull requests as soon as possible.
