### ISSUE TITLE
Several apps that can be used for cheating aren't blocked from launching

### ISSUE THREAD

**Issue by NekoJonez** [SafeExamBrowser/seb-win-refactoring#769]
I have been going through several FB groups here in Belgium where fellow IT-admins complain about how SEB didn't block/close several apps that students used to cheat during this exam period and the summer exam period. I tested them and will create a PR to block/close  them.

**Comment by danschlet** [comment]
I wonder if they understand that they could themselves add those apps to the configs they use?
But your PRs to add it to the predefined prohibited processes are highly welcomed of course!
For the future we also had in mind creating a database where anybody could submit metadata for apps they consider could be used for cheating. We would then use that database to automatically compile prohibited processes for new SEB releases and add a feature to SEB Server to always fetch the latest list from that database and include it in SEB client exam settings.

**Comment by NekoJonez** [comment]
Yeah, I wondered that too reading some comments. 
I tested 7 apps today and turned out that only TWO can be abused. Creating that PR now. Both are media players and when you have an oral exam or an exam with an oral part ... You can use a headset and then you can get started and loop something. 
Yeeeet, keyboard shortcuts to pause/advance the tracks don't work which is extremely funny to me. So, if a student messes up and the examinator hears sound while it's supposed to be a silent question they are screwed.

**Comment by danschlet** [comment]
I understand that there could be some cheating with Spotify and media players, but I feel like that would only affect exams with audio/video questions, where students are allowed to use headsets. Of course someone with long hair could hide an AirPod or similar in their ear, but they could also use that with a mobile phone. So teachers should anyways always have an eye on what students stick into their ears...

**Comment by NekoJonez** [comment]
> I understand that there could be some cheating with Spotify and media players, but I feel like that would only affect exams with audio/video questions, where students are allowed to use headsets. Of course someone with long hair could hide an AirPod or similar in their ear, but they could also use that with a mobile phone. So teachers should anyways always have an eye on what students stick into their ears...

Yeah, things like that are a double-edged sword. At one hand... Why block them, since it's a minor section of possible cheating... At the other hand, that might be things that users/students are looking for to abuse? 
I once work for a government exam center and the list of things that the examiners had to check was getting so absurdly long, it's always a cat and mouse game. But the more bases that we cover, the harder we make it and more creative they have to be and at that point you'll have to ask... how well have things to go to not fail and not go into the absurd?

**Comment by dbuechel** [comment]
Thanks for your input, we shall merge the pull requests as soon as possible.
