### ISSUE TITLE
WebRTC support timeline?

### ISSUE THREAD

**Issue by ScottDellinger** [SafeExamBrowser/seb-win-refactoring#77]
I'm the CTO of an online proctoring company that is interested in recommending Safe Exam Browser to our clients, but the lack of WebRTC support is a deal breaker (as that's how we access the user's webcam and screen sharing). I understand that this may come with SEB 3.2. Can you confirm that?

Also, do you have an estimated date for SEB 3.2?

**Comment by dbuechel** [comment]
SEB 3.2 will come with remote proctoring capability with Jitisi Meet, and we might be able to integrate a simplified WebRTC support directly within SEB, as opposed to the workaround with Chrominimum. Current estimate for the release is no later than end of may 2021.

**Comment by dbuechel** [comment]
See #3 , thus I'll close this for now.

**Comment by ScottDellinger** [comment]
I have tested our product and confirmed it as working with the new beta.

Does the macOS version work with WebRTC?

**Comment by dbuechel** [comment]
As far as I know there are changes which should allow the usage of WebRTC, but you'd need to ask in the macOS repository for the details.
