### ISSUE TITLE
how can prevent students to access taskbar

### ISSUE THREAD

**Issue by mosgouda** [SafeExamBrowser/seb-win-refactoring#773]
Descriptions 
student can access device taskbar then go to device files

Steps to Reproduce
 i don't known the steps

![taskbar ](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/71437502/340e2b34-298e-4e4e-a70c-d1b81f60523b)

**Version Information**
 - OS: Windows 
 - SEB-Version: NA

we need a solution for the issue

**Comment by strau0106** [comment]
If you expect anyone to help with this issue, you will need to provide more infromation.
We would need more information such as log files and the exam configuration used.

**Comment by dbuechel** [comment]
Looks like you're using SEB without a kiosk mode, see https://safeexambrowser.org/windows/win_usermanual_en.html#SecurityPane.
