### ISSUE TITLE
SEB doesn't start - Prohibited Display Configuration

### ISSUE THREAD

**Issue by mbalous** [SafeExamBrowser/seb-win-refactoring#780]
**Describe the Bug**
Can't launch Safe Exam Browser

**Steps to Reproduce**
1. Download latest version of SEB
2. Install
3. Double click created start menu item

**Expected Behavior**
SEB launches with no error present

**Screenshots**
![Screenshot 2024-01-05 121933](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/10358985/e81f6199-af93-4307-a91f-b0d345dfe093)

**Version Information**
 - OS Version:  Windows 11 10.0.22621 N/A Build 22621
 - Safe Exam Browser, Version 3.6.0 (x64), Build 3.6.0.633

**Additional Context**
[2024-01-05_12h16m51s_Runtime.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/13841387/2024-01-05_12h16m51s_Runtime.log)
![Screenshot 2024-01-05 122505](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/10358985/70f7d942-8878-46ea-bf4b-a519fe5b59d1)

**Comment by dbuechel** [comment]
According to the log, the display verification failed:

```
2024-01-05 12:16:53.756 [08] - INFO: Validating display configuration...
2024-01-05 12:16:53.788 [08] - ERROR: [DisplayMonitor] Failed to query displays!

   Exception Message: Access denied 
   Exception Type: System.Management.ManagementException

   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__97`1.MoveNext()
   at SafeExamBrowser.Monitoring.Display.DisplayMonitor.TryLoadDisplays(IList`1& displays) in C:\Users\appveyor\projects\seb-win-refactoring-phv3mbelx16fm9ou\SafeExamBrowser.Monitoring\Display\DisplayMonitor.cs:line 169

2024-01-05 12:16:53.803 [08] - WARNING: [DisplayMonitor] Failed to validate display configuration, active configuration is not allowed.
2024-01-05 12:16:53.803 [08] - ERROR: Display configuration is not allowed!
```

Why that would be is impossible to deduce without access to the device itself. You can ignore display validation failures in the configuration itself, but please take note of the implications this has: https://safeexambrowser.org/windows/win_usermanual_en.html#SecurityPane.

**Comment by dbuechel** [comment]
Any updates here?

**Comment by mbalous** [comment]
I'm a student, not an exam configurator.

**Comment by mlohnen** [comment]
This could be because of monitoring software like Impero, which is widely used at schools for monitoring and controlling pc's remotely.
I had this and had to enable 'ignore errors validating display configuration'.

**Comment by KayhanEfe** [comment]
I have the same problem and I can't fix it. I have an exam in 3 days I need help. 

NOTE: I am not using VM.

Can someone tell me what I can do?

**Comment by dbuechel** [comment]
@KayhanEfe Please post the log files of the affected session. They can be found under `%LocalAppData%\SafeExamBrowser\Logs`.

**Comment by wibiansyaa** [comment]
[2024-04-23_17h53m46s_Runtime.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/15075710/2024-04-23_17h53m46s_Runtime.log)
please help me how fix the display configuration is not allowed.

**Comment by gads131** [comment]
> > I have the same issue i only have 1 display My pc spec :
> > 
> > * Ryzen 5 4560g
> > * MSI A320M Pro Vh plus
> > * Nvdia gtx 1050 ti
> > * Os win 11 ver 10.
> >   I plug the HDMI cable from mobo because my gpu socket is bad and using the gpu socket still wont fix
> >   I use tv for the display
> > * changing display using win + p
> > * i also tried to run the script from this thread : https://techcommunity.microsoft.com/blog/askperf/wmi-rebuilding-the-wmi-repository/373846
> > * upgrading the version, my test require 3.7 version so i tried to use 3.9 version
> > * updating the driver
> > 
> > please help i only have 1 weeks before the final test
> > [2025-04-16_17h54m36s_Runtime.log](https://github.com/user-attachments/files/19774905/2025-04-16_17h54m36s_Runtime.log)
> 
> Well, unless the geniuses behind the configurator suddenly fix it, your only real option is to sit and hope, or just buy a new laptop.
> 
> Fuck indon gov, why on earth they hire this stupid mf to config the seb.

So the issue is behind the admin who cfg the SEB it self and they have display check xD. I mean why on earth they try so bad to eliminate cheater's while they using an open source program, and people can just open the source code an reverse it 🤣

**Comment by gads131** [comment]
> > > > I have the same issue i only have 1 display My pc spec :
> > > > 
> > > > * Ryzen 5 4560g
> > > > * MSI A320M Pro Vh plus
> > > > * Nvdia gtx 1050 ti
> > > > * Os win 11 ver 10.
> > > >   I plug the HDMI cable from mobo because my gpu socket is bad and using the gpu socket still wont fix
> > > >   I use tv for the display
> > > > * changing display using win + p
> > > > * i also tried to run the script from this thread : https://techcommunity.microsoft.com/blog/askperf/wmi-rebuilding-the-wmi-repository/373846
> > > > * upgrading the version, my test require 3.7 version so i tried to use 3.9 version
> > > > * updating the driver
> > > > 
> > > > please help i only have 1 weeks before the final test
> > > > [2025-04-16_17h54m36s_Runtime.log](https://github.com/user-attachments/files/19774905/2025-04-16_17h54m36s_Runtime.log)
> > > 
> > > 
> > > Well, unless the geniuses behind the configurator suddenly fix it, your only real option is to sit and hope, or just buy a new laptop.
> > > Fuck indon gov, why on earth they hire this stupid mf to config the seb.
> > 
> > 
> > So the issue is behind the admin who cfg the SEB it self and they have display check xD. I mean why on earth they try so bad to eliminate cheater's while they using an open source program, and people can just open the source code an reverse it 🤣
> 
> Yeah, our issue is a bit different, op issue is that SEB doesn’t detect any displays, whether internal or external. But the config is alr correct, they allow 1 internal display / external display.
> 
> Meanwhile our issue is that the admin set it up to restrict external displays like monitors, allowing ONLY internal displays. This means only laptops or AIO pc can take the test. And i'm sure they wont give a f about this.
> 
> So my advice, just prepare a laptop, maybe borrow one from a friend or smth if you still want to take the test.

I see the main issue is the admin are being ret*rded xD
Thanks anyway Good luck !
