### ISSUE TITLE
Students can still cheat with custom cursors.

### ISSUE THREAD

**Issue by NekoJonez** [SafeExamBrowser/seb-win-refactoring#784]
If the student uses a program to enable a custom cursor like Custom Cursors (https://apps.microsoft.com/detail/XPFF8Q4ZP7Q321?hl=nl-nl&gl=US) and then reset HKCU:\Control Panel\Cursors to their default settings, SEB doesn't block the user.

**Comment by strau0106** [comment]
I dont entirely know how secure this check is anyways? What hinders me in putting my custom cursors in the two directories SEB counts as valid?

**Comment by dbuechel** [comment]
The current mechanism is the best we can do according to our actual state of knowledge. If you have any suggestions for improvement, please do feel free to reopen the issue and share them here.

**Comment by strau0106** [comment]
I believe the only proper option against this would be to force cursors that are shipped with SEB and validated.

**Comment by dbuechel** [comment]
Thanks for the input, yes that would be an idea but is currently impossible to realize with all the other priorities and features we have on our to do list. But we'll keep that in mind should we ever have enough free time on our hands.
