### ISSUE TITLE
Problems with freezing SEB during login prompt via Microsoft OIDC and MFA

### ISSUE THREAD

**Issue by AntonT76** [SafeExamBrowser/seb-win-refactoring#796]
Dear SEB-team,

we have been using login via Microsoft OIDC (Open ID Connect) for some time now and also use multi-factor authentication (MFA) via MS Azure.

During the login, the user will be forwarded to https://login.microsoftonline.com/....... We have also configured this web address in the whitelists of SEB. This has not been a problem with any of our previous exams. However, now we had the case with one student that the login window froze when opening the SEB (I think it might be during the login process). It was no longer possible to log in. The student then restarted SEB and the computer and also changed computers, but the problem also occurred there.

I also believe that the error message "Access to "" is not allowed according to the current configuration." occurred. Unfortunately, I can't say for sure because I wasn't on site.

We are currently checking whether it might be related to the user's Windows profile or something relateing to the MFA, but it is difficult to find out. Perhaps the SEB-Config file could not be loaded correctly because the whitelisted websites were saved there?

We are using Moodle 4.1.4+ and SEB V3.5 on Windows 10. The SEB config file is saved on the computer. If someone starts SEB, this config file will be loaded.

Attached you can find the log files from the two computers where the problem occurred as a ZIP file.
[SEB-Logfiles.zip](https://github.com/SafeExamBrowser/seb-win-refactoring/files/14112497/SEB-Logfiles.zip)
Perhaps you can help us find out what the problem is.

thanks & best regards
Anton

**Comment by dbuechel** [comment]
Thanks for the report. At first glance, there is nothing suspicious in the log files but you might find relevant information in the system event logs (Event Viewer > Windows Logs > Application). Apart from that, there's unfortunately not much we can do unless you provide a way to reliably reproduce the problem.

**Comment by AntonT76** [comment]
Dear @dbuechel 

thank you for your answer. It looks like we have found the issue but we have to test it in detail: the user uses for authentication a YubiKey (https://www.yubico.com/der-yubikey/?lang=de). It seems to be that this authentication method will not work in our SEB settings ...

Do you have any experiences by using this keys in SEB?

thanks & br, Anton

**Comment by dbuechel** [comment]
Unfortunately not, but you might be able to get to the root of the issue by contacting the support of YubiKey.

**Comment by strau0106** [comment]
@AntonT76 For a successful FIDO Identification to occur, Windows opens a Windows Hello window, which guides you through the process of inserting your Security Key and potentially entering a PIN. 
Windows puts this window in the foreground and kind of freezes everything else.
For students to be able to authenticate with hardware tokens, which you should definitely support btw, you would probably have  to just allow another the windows hello exe...
If I have time I'll test this.

**Comment by AntonT76** [comment]
Hi @strau0106

thank you very much for your advice. We also think that a special website is being accessed during the authentication process. So, we need to add this to the whitelist in SEB so that it is also permitted by SEB. But we have to test that.

However, we are still considering whether we should generally recommend students to obtain the second factor via app or SMS during exams if FIDO causes problems.

Best regards, Anton

**Comment by strau0106** [comment]
I wouldn't ever have noticed so, but it could be. I'll test that if I have some time. 

I wouldn't recommend my students a vendor locked or comparably insecure 2FA method.

**Comment by strau0106** [comment]
I tested a bit earlier today. Although one process is started, it does not open the window required. I believe there is something missing in the config for CEF which results in this...

**Comment by dbuechel** [comment]
Did you check whether a particular window or process is not being suppressed by SEB? If you think that it is an issue with the browser engine, you could verify this by using the CEF sample application and test your use case with it: https://cef-builds.spotifycdn.com/index.html.

**Comment by strau0106** [comment]
Gotta go get my windows testing device first, but will defo try.

**Comment by strau0106** [comment]
PS: I couldn't reproduce the freezing. That could be MS. I tried with the [YubiKey Demo Page](https://demo.yubico.com/webauthn-technical/registration).

**Comment by strau0106** [comment]
I‘ll record some logs and share them here, there are some processes that are being blocked.
