### ISSUE TITLE
HTML <input> list Attribute does not work in SEB

### ISSUE THREAD

**Issue by michaelhq** [SafeExamBrowser/seb-win-refactoring#802]
Hello everyone, first of all many thanks for your great work and the very good support! Thank you furthermore for always taking users' problems seriously and trying to help quickly!

Firstly, the issue described below, I couldn't find anything in the documentation, here on GitHub or on the internet that points to the issue.

**Describe the Bug**
If you have a webpage with an HTML <input> element with pre-defined values in a <datalist>, the pre-defined values were not shown as dropdown.

**Steps to Reproduce**
1. Configure SEB to open: [https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_datalist](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_datalist)
2. Start SEB
3. Click in the field behind "Choose your browser from the list:"
4. A dropdown should pop up, but it does not. An arrow down is shown, but no data list values.

**Expected Behavior**
A dropdown should pop up like in other mainly used browsers on Windows like Chrome, Firefox and Edge.

**Screenshots**
Chrome
![grafik](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/11134268/68fe318c-6378-4c2b-8f2c-5461734760ad)

Firefox
![grafik](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/11134268/1aa7b317-b455-44f2-a2bf-6c9814b5449d)

Safe Exam Browser (only an arrow is shown)
![grafik](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/11134268/e99f7b71-2001-458e-b427-a89162d0522a)

**Version Information**
 - OS: Windows 11 23HS2
 - SEB-Version 3.5 and 3.6

**Additional Information**
With SEB 3.3.2 on Mac OS this is not an issue. Everything woks as expected.

Best regards,
Michael

**Comment by dbuechel** [comment]
Thanks for the report. This issue unfortunately reproduces with the CEF Sample Application (see https://cef-builds.spotifycdn.com/index.html) and is thus an upstream issue in the browser engine (most likely CEF, potentially even Chromium). You'd need to take it up with them and open an issue in the CEF support forum or repository.
