### ISSUE TITLE
Urgent Security Issue: HDMI cables used to cheat or record exam content.

### ISSUE THREAD

**Issue by keean** [SafeExamBrowser/seb-win-refactoring#81]
Candidates can mirror the display using an HDMI cable.

To reproduce plug an HDMI cable into a second monitor.

This is already causing real-world problems with cheating. Candidates using a long cable to a second monitor in another room, or recording the second screen to leak exam content even on proctored exams. We see this as an urgent security issue that will mean cancelling exams if it cannot be resolved.

The expected behaviour is to either disable screen mirroring, or control the number of connected monitors allowed.

This affects all versions of SEB.

From what I have read on the forums, it seems to be suggested that it is not possible to do this on windows, however the WMI monitors API can show all attached monitors and whether they are active, see:

https://devblogs.microsoft.com/scripting/use-powershell-to-discover-multi-monitor-information/

**Comment by danschlet** [comment]
We're looking into it, but @dbuechel's first feedback was, that these WMI queries don't indicate if a display is internal or external. Then that API would be quite useless, as long as you could close the lid of a portable PC or deactivate the internal display by software and connect an external display, using an external video signal splitter.

Also there are still Windows laptops with VGA and other kinds of connectors for external displays, the question is if those get detected as well.

In general, it's impossible to make remote exams 100% secure (not even close) with technological means. Preventing to record exams is impossible regardless if conducted at home or in exam halls (spy cams are tiny and cheap nowadays). Good exam design together with some technological means can make remote exams better, but I guess best is to get vaccinated and postpone the most important high stakes exams until all students can take them on site again...

**Comment by keean** [comment]
I think simply counting monitors is good enough. Desktop PCs don't have internal displays. It is the mirroring of displays that we are particularly concerned with, so I think that objection to the API is not relevant. Simply a setting to limit to one monitor would deal with the screen mirroring over HDMI (or any other monitor connection type from what I can tell, so would include VGA, but even if it only detects HDMI its still better than nothing).

I agree it is impossible to achieve 100% security - and it will come down to how much risk an organisation is prepared to take. Preventing the 'easier' forms of abuse, like using an HDMI lead, is going to make it harder to cheat, and therefore more organisations will be prepared to go ahead with exams.

So even knowing about spy cameras, teams of candidates memorising questions etc, it is still worthwhile to prevent the easier methods of cheating where you can, otherwise why even bother with a lockdown browser, just construct un-googleable questions, and run the exam open book in a standard web browser.

So we think this can be easily prevented, think that limiting to a single monitor is sufficient to prevent it (the laptop camera will stop working if they close the lid on a proctored exam).

**Comment by keean** [comment]
This WMI call will tell you if a display is internal or not:

https://docs.microsoft.com/en-gb/windows/win32/wmicoreprov/wmimonitorconnectionparams?redirectedfrom=MSDN

Values are here:

https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/d3dkmdt/ne-d3dkmdt-_d3dkmdt_video_output_technology

and can have the value: D3DKMDT_VOT_INTERNAL

However, I do not think detecting this is as important as simply counting displays to prevent mirroring, because we want to allow desktop PCs as well as laptops. 

If you wanted to restrict to only internal displays, I would suggest having two controls in the exam configuration, one to restrict to a single monitor, and one to force that single monitor to be internal. We would probably not want to set the internal restriction.

**Comment by danschlet** [comment]
Thanks for the query. Some information @dbuechel looked into in the past was apparently related to display drivers and not useful for our purposes, but maybe this is some other system library.

> If you wanted to restrict to only internal displays, I would suggest having two controls in the exam configuration, one to restrict to a single monitor, and one to force that single monitor to be internal. We would probably not want to set the internal restriction.

Exactly [what the Mac version has](https://safeexambrowser.org/macosx/mac_usermanual_en.html#SecurityPane).

The other preliminary finding of @dbuechel when he looked into it a few weeks ago apparently was that on his device the queries reported a wrong number of connected displays. We will reevaluate this and will see if it works.


The remote exam discussion is probably kind of pointless, I just know that expectations vary widely. Many institutions trust solutions like Proctorio which is a browser extension and knows almost nothing about the system it is running on. Others want us to find out if several displays, keyboards and pointer devices are connected. Once again: If companies or big institutions want more elaborate features in SEB, they can contribute code or money by becoming member in the [SEB Alliance](https://safeexambrowser.org/alliance/join.html).

**Comment by keean** [comment]
Hi Daniel,

We are certainly interested in joining the SEB Alliance, and I will follow
up on that at this end.

In this case it is not us that is making controlling the HDMI mirroring a
requirement, it is one of the organisations we work with. So we need to
resolve this to carry on working with that organization. I think my point
is that the more we can do, the more organisations we can work with as we
cover off more of their particular concerns.

Cheers,
Keean.

**Comment by keean** [comment]
@dbuechel Looking at the 'wrong' number of displays, you need to test if the displays are "active" before counting... otherwise they could be displays that have at some point been connected, but are not now connected.

**Comment by danschlet** [comment]
Thanks for the update Keean!
@dbuechel is off this week, but I'll make sure we look into the code part next week. Hopefully we get the correct information we need. If we could get it to the point it works in the Mac version, it would be perfect, but you're probably right that any even partial detection would be a progress.

**Comment by dbuechel** [comment]
I have just checked the WMI commands, they seem to work, at least on my laptop. I must have checked other commands back when I was investigating this issue which were giving me wrong information. So yes, with these queries we should be able to implement a simple check of how many monitors are connected and whether they are internal or not.

**Comment by dbuechel** [comment]
I'm working on the functionality, but have just found that the following command actually does return, at least to my understanding, an invalid result on my machine:

`Get-WmiObject win32_desktopmonitor`

Returns two monitors, I'm however on a laptop and currently using only one (the internal) monitor:

```
DeviceID            : DesktopMonitor1
DisplayType         :
MonitorManufacturer : Lenovo
Name                : Wide viewing angle & High density FlexView Display 1920x1080
ScreenHeight        : 1080
ScreenWidth         : 1920

DeviceID            : DesktopMonitor2
DisplayType         :
MonitorManufacturer :
Name                : Standardmonitor
ScreenHeight        : 1440
ScreenWidth         : 2560
```

**Comment by keean** [comment]
If you cross reference that with active monitors you should find only one
is active. the other one is one that has been plugged in, its like a memory
of the last monitor that was connected, but as its not connected, it should
not be active.

**Comment by dbuechel** [comment]
Ah yes, that is correct, there is only one entry returned by `Get-CimInstance -Namespace root\wmi -ClassName WmiMonitorBasicDisplayParams`. Excellent, thanks for your input.

**Comment by keean** [comment]
@dbuechel Might be worth taking a look at this:

https://stackoverflow.com/questions/31712915/detect-identify-the-port-hdmi-other-the-monitor-is-connected-to-in-windows-7

I think it would be useful to restrict laptops to their internal display only, to prevent use of HDMI splitting devices, as on optional extra restriction on top of only one active monitor (I think this is how the Mac version works).

**Comment by dbuechel** [comment]
The latest build of the beta version now contains a basic display monitoring: https://sebdev-let.ethz.ch/api/buildjobs/364oxdyc9n9rjpg6/artifacts/SEB_3.2.0.314_SetupBundle.exe

**Comment by dbuechel** [comment]
@keean Were you able to take a look at the functionality?

**Comment by keean** [comment]
I will take a look.
