### ISSUE TITLE
Reduce verbosity level on local log files of SEB v3.1.1

### ISSUE THREAD

**Issue by GeorgBraun** [SafeExamBrowser/seb-win-refactoring#82]
Thanks for providing SEB v3.1.1

Migrating from SEB v2.4(.1) to v3.1.1 on Windows-10 20H2, we are currently running several tests. So far, everything looks quite good. Thanks for your hard and excellent work.

What we are concerned about is the verbosity level of the logging done in `%localappdata%\SafeExamBrowser\Logs\..._Browser.log`.

It seems that the full path of all connections done during a session are logged within this file, even query parameters of https-URLs.

If I remember correctly, on SEB 2.4(.1) we were able to reduce the logging verbosity down to a level where details of TLS-protected URLs did not show up in the logging. With v3.1.1, it seems that we cannot do this any longer.

We are a little concerned about this potentially becomming a security issue. Other system components (e.g. network sniffers, DSL-Routers) are usually able to see only the server host-name of a TLS/https-based connection, but no details like URL paths or query parameters. With the verbose loggin in `%localappdata%\SafeExamBrowser\Logs\..._Browser.log` much more details are accessible on user level.

Maybe, there is a setting parameter that allows us to disable or reduce the logging level? If so, my apologies that I could not find it up to now. If not, do you think it is possible to keep the details of TLS-protected connections out of the log-files?

Many thanks and best regards,
 Georg

**Comment by GeorgBraun** [comment]
Thanks for the fast and helpful answer!

If I understand you correctly, I will do the following steps to try this:

1. Safe the SEB-config-file without a start PW to get an unencrypted SEB-XML-file.
2. Insert `<key>` and `<integer>` as you suggested. In the current log files, I see `INFO:CONSOLE` entries, which I would like to avoid. Therefore, `SEBLogLevelWarning = 1` will probably be the right choice.
3. Re-read the SEB-XML-file into SEB-Config-Tool, add the start PW and safe it, to get an encrypted SEB config file.

Right?

**Comment by dbuechel** [comment]
Yes, correct, that should work.

**Comment by GeorgBraun** [comment]
It did work, thanks for your confirmation.

I've tested with `SEBLogLevelWarning = 0` and a quick test without injecting any errors to see what the minimum logging would look like. Here are my test results (if it is of any help or value):

Instead of 4 files (`..._Runtime.log`, `..._Client.log`, `..._Browser.log`, `..._Service.log`) I only got 3 files (`..._Runtime.log`, `..._Client.log`, `..._Browser.log`)  with the following contents:

* `..._Browser.log` was created, but was empty (0 bytes).
* `..._Browser.log` had only 2 entries, "# New client instance started at ..." and "# Client instance terminated at ..."
* `..._Runtime.log` startet with quite some `INFO` and `DEBUG` messages, but then became quiet after an entry "Switching from log severity 'DEBUG' to 'ERROR' for new session." The next entry was "# Application terminated at ..."

This looks perfectly right and save for us. We will execute our exams with `SEBLogLevelWarning = 0`

Many thanks and best regards,
 Georg

**Comment by GeorgBraun** [comment]
Sorry, one more thing:

Looking at an old SEB v2.4 config file, I found another entry

```xml
    <key>enableLogging</key>
    <false />
```

Within the SEB v3.1.1 config tool, it seems that the corresponding check box `checkBoxEnableLogging` contained by group box `groupBox10` is disabled as of https://github.com/SafeExamBrowser/seb-win-refactoring/blob/master/SebWindowsConfig/SebWindowsConfigForm.Designer.cs#L1446

This probably means that `<key>enableLogging</key>` is deprecated for SEB v3.1.1, right?
