### ISSUE TITLE
Crash in lockdown mode when tab-navigating over the end of the page

### ISSUE THREAD

**Issue by Stehlampe2020** [SafeExamBrowser/seb-win-refactoring#822]
**Describe the Bug**
When I'm in an exam in lockdown mode (no task bar and the window is in fullscreen) and navigate with the tab key it works fine, but when I press tab while on the last input on the page SEB freezes and then crashes. 

**Steps to Reproduce**
1. Go into a safe exam which has an input form at the end (e.g. a text where you have to enter single words into blanks)
2. Click on the last input element
3. press tab

**Expected Behavior**
Nothing should happen or the focus should roll over to the first focusable element on the page. 

**Version Information**
 - OS: Windows 11 Education Edition, Version 22H2 (OS_version 22621.2428)
 - SEB-Version 3.4.1

**Additional Context**
These are the logs from the session in question:   
* [2024-03-05_10h23m35s_Browser.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/14494112/2024-03-05_10h23m35s_Browser.log)
* [2024-03-05_10h23m35s_Client.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/14494113/2024-03-05_10h23m35s_Client.log)
* [2024-03-05_10h23m35s_Runtime.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/14494114/2024-03-05_10h23m35s_Runtime.log)
* [2024-03-05_10h23m35s_Service.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/14494116/2024-03-05_10h23m35s_Service.log)

I think the error occurs because SEB tries to focus its own task bar when tabbing over the end of the page, but in lockdown mode that doesn't exist and thus SEB crashes. Why do I think that? I started SEB manually (so it wasn't in full lockdown) and tabbing over the end of the page then focused elements in the SEB task bar.

**Comment by dbuechel** [comment]
This issue has already been fixed with version 3.5.0:

https://github.com/SafeExamBrowser/seb-win-refactoring/issues/490
https://github.com/SafeExamBrowser/seb-win-refactoring/releases/tag/v3.5.0
