### ISSUE TITLE
Problems opening SEB: You have installed Safe Exam Browser (SEB), but it isn't configured yet

### ISSUE THREAD

**Issue by AntonT76** [SafeExamBrowser/seb-win-refactoring#829]
Dear SEB Support,

We have a repeated problem with SEB during a Moodle quiz exam with 2 students out of 3

Date: 07. 03. 2024
Time: ca. 09:15

In the case of the PC LNZD2OG2PCR06 the student was unable to log into SEB, please find attached a photo of the screen message and the logfiles (ZIP File PC06 + JPG-File)

- Safe Exam Browser, Version 3.2.0 (x64), Build 3.2.0.338
- Copyright © 2021 ETH Zürich, Educational Development and Technology (LET)
- Application started at 2024-03-07 09:00:45.679
- Running on Windows 10, Microsoft Windows NT 10.0.19045.0 (x64)
- Computer 'LNZD2OG2PCR06' is a 103C_53307F HP EliteDesk HP EliteDesk 800 G4 SFF manufactured by HP
- Runtime-ID: 3b0a9066-0bb6-471f-b0ed-4c084f4fe665

The PC LNZC2OG2PCR08 produced the same problem. Please find attached the logfiles (ZIP File PC08)

- Safe Exam Browser, Version 3.2.0 (x64), Build 3.2.0.338
- Copyright © 2021 ETH Zürich, Educational Development and Technology (LET)
- Application started at 2024-03-07 09:09:54.234
- Running on Windows 10, Microsoft Windows NT 10.0.19045.0 (x64)
- Computer 'LNZD2OG2PCR08' is a 103C_53307F HP EliteDesk HP EliteDesk 800 G4 SFF manufactured by HP
- Runtime-ID: 65037e40-30a7-4c98-9b2f-d752b2680910

Only the student on the PC LNZC2OG2PCR04 was able to complete the exam, we are sending you the log files for comparison (ZIP File PC04)

- Safe Exam Browser, Version 3.2.0 (x64), Build 3.2.0.338
- Copyright © 2021 ETH Zürich, Educational Development and Technology (LET)
- Application started at 2024-03-07 09:00:45.268
- Running on Windows 10, Microsoft Windows NT 10.0.19045.0 (x64)
- Computer 'LNZD2OG2PCR04' is a 103C_53307F HP EliteDesk HP EliteDesk 800 G4 SFF manufactured by HP
- Runtime-ID: cac4f24c-4481-457a-b8e9-27314f5c4b33

[SEB-Logs_2024-03-07.zip](https://github.com/SafeExamBrowser/seb-win-refactoring/files/14635015/SEB-Logs_2024-03-07.zip)

Is it possible that there was a network problem and the config file was not loaded?
Can you find any hints to the cause of the problem?

thanks & best regards, Anton

**Comment by dbuechel** [comment]
The logs of the other two machines seem to abruptly terminate; this often indicates an issue on system side, you likely will get more information in the event logs of Windows itself.

We'd furthermore need more information about your particular use case (e.g. how you're starting SEB and when resp. how the failure occurs and what you'd be expecting instead), please refer also to the issue template for bugs here on GitHub.

Last but not least we always recommend to use the latest available release version, thus I'd recommend to update as soon as possible and check whether the issue still occurs.

**Comment by AntonT76** [comment]
Dear @dbuechel 
Thank you for your reply. I will forward your recommendation to our system administrator and hope that it will no longer occur with the update to the latest SEB version, or that the sys admins will find out the problem in the Windows event log files.
br, Anton
