### ISSUE TITLE
Screen Reader Compatibility

### ISSUE THREAD

**Issue by Rich2038** [SafeExamBrowser/seb-win-refactoring#835]
Do you have a whitelist or other means to allow screen readers to work within SEB?

We have students with vision impairment who need to use JAWS (3rd party app) or Narrator (built in to Windows) to read the screen in order to take the test.

**Comment by dbuechel** [comment]
You'd need to add the screen reader of your preference to the allowed applications in your SEB configuration: https://safeexambrowser.org/windows/win_usermanual_en.html#ApplicationsPane. Please note that kiosk mode Create New Desktop is currently not compatible with NVDA or JAWS (as is also noted in the [release notes](https://github.com/SafeExamBrowser/seb-win-refactoring/releases/tag/v3.6.0)). Further information related to accessibility can also be found in the VPAT: https://safeexambrowser.org/vpat/VPAT_WCAG_SEB_Win.pdf
