### ISSUE TITLE
Browser window not initializing

### ISSUE THREAD

**Issue by daanvy** [SafeExamBrowser/seb-win-refactoring#836]
> [!IMPORTANT]
> - Please _always_ consult the documentation first before creating a bug report: https://safeexambrowser.org/windows/win_usermanual_en.html.
> - Please _always_ attach the log file(s) of the affected session(s)! They can be found under `%LocalAppData%\SafeExamBrowser\Logs`.

**Describe the Bug**
No browser window initializing when I open the program

**Steps to Reproduce**
1. Download the source code
2. Open the source code with Visual Studio
3. Build to 64x release
4. Try to open the File
5. Window will open and will be gray, also takes away taskbar and alt-tab functionality etc.
6. No sidebar or browser shows up

**Expected Behavior**
A browser window will appear by default.

**Screenshots**
N/A

**Version Information**
 - OS: Windows 11 Pro [23H2]
 - SEB-Version Latest from source code on github here as of 27/03/2024 @ 19:37 C.E.T

**Additional Context**
Have not changed anything in the files that could break it since I have not changed anything at all.

[2024-03-27_19h29m49s_Runtime.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/14779801/2024-03-27_19h29m49s_Runtime.log)

**Comment by dbuechel** [comment]
Please post the client log file, as everything on the runtime side appears to be working as intended. Also, please do note that support for customization of SEB is reserved for members of the SEB Alliance.
