### ISSUE TITLE
SEB Freezing

### ISSUE THREAD

**Issue by Flyingfoxi** [SafeExamBrowser/seb-win-refactoring#838]
> [!IMPORTANT]
> - Please _always_ consult the documentation first before creating a bug report: https://safeexambrowser.org/windows/win_usermanual_en.html.
> - Please _always_ attach the log file(s) of the affected session(s)! They can be found under `%LocalAppData%\SafeExamBrowser\Logs`.

**Describe the Bug**
The window opens, but it stops at initializing UI.

**Steps to Reproduce**
1. Downloaded SEB 3.6.0
2. Run a Test Exam
3. It freezes, i waited around half a hour and then shut down the pc.

**Expected Behavior**
It should start quite fast as on the PC of my friends

**Version Information**
 - OS: Window 11 Enterprise
[2024-03-28_11h39m53s_Client.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/14788869/2024-03-28_11h39m53s_Client.log)
[2024-03-28_11h39m53s_Service.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/14788870/2024-03-28_11h39m53s_Service.log)
[2024-03-28_11h39m53s_Runtime.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/14788871/2024-03-28_11h39m53s_Runtime.log)
 - SEB-Version SEB 3.6

**Additional Context**
Log Files Attached

**Comment by dbuechel** [comment]
Yes, it indeed looks like SEB got stuck while initializing the keyboard layouts. Does this behavior reproduce, i.e. does SEB always get stuck at that point or can you start it normally otherwise?

Please open the Windows Event Viewer system utility and check whether there are any error or warning logs related to SEB under "Windows Logs" > "Application".

**Comment by dbuechel** [comment]
If possible a video or screen recording of how you're trying to start SEB could be helpful.

**Comment by Flyingfoxi** [comment]
I tried many times, even with different codes, when i look up in the Windows Event Logs i see many error (I copied them into a file) and i am starting the SEB from exam.net, but i can't save my screen recording because i can't exit SEB and need to completly shut down my pc.
[Logs.txt](https://github.com/SafeExamBrowser/seb-win-refactoring/files/14791922/Logs.txt)

**Comment by Flyingfoxi** [comment]
Thanks, i'll try that
