### ISSUE TITLE
Source Code anti tamper when running the application.

### ISSUE THREAD

**Issue by TheonlyJok3r** [SafeExamBrowser/seb-win-refactoring#845]
So im wondering if your guys source code can be tampered since its open cause i have some smart students in my class which know alot of programming and im thinking if you guys can flags students for that ?

**Comment by kabonKoda** [comment]
The SEB software performs an integrity check before it opens the browser .... If the code has been compromised i guess it wont run

**Comment by dbuechel** [comment]
There are various countermeasures, among them the App Signature Key, Browser Exam Key and Configuration Key. In general, we do recommend the usage of SEB Server for high-stakes exams which provides automatic integrity verification of SEB clients using the App Signature Key.
