### ISSUE TITLE
Issue I'm getting with my students when using Take a test

### ISSUE THREAD

**Issue by TheonlyJok3r** [SafeExamBrowser/seb-win-refactoring#846]
Hi so I've been experiencing this issue when my students use the feature take a test after couple minutes I get a notification saying "We have received reports of user issues with Take a Test (Windows). We recommend instead that your students use SEB - Safe Exam Browser when using high security mode on Windows computers" and I'm wondering is this normal or should I contact exact.net to take a look upon this because I don't understand what it exactly mean is it like user having issues or cheating? ![image](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/128870258/958751f1-679b-49a6-9062-3cca896c81b1)

**Comment by danschlet** [comment]
You have to ask/discuss this with your exam system provider, I guess in this case exam.net.

**Comment by dbuechel** [comment]
That is definitely something you'd need to resolve with the LMS manufacturer.
