### ISSUE TITLE
In Moodle, the cookie can have a prefix. If one is set, the session sent to SEB server is not correct.

### ISSUE THREAD

**Issue by lucaboesch** [SafeExamBrowser/seb-win-refactoring#848]
Cookies in Moodle can have customizable prefixes.
Unfortunately, in our place, one is set.
<img width="1437" alt="image" src="https://github.com/SafeExamBrowser/seb-win-refactoring/assets/377279/ca51b010-3ee6-4e98-b923-c34183d53429">
In line [416 of ResourceHandler.css](https://github.com/SafeExamBrowser/seb-win-refactoring/SafeExamBrowser.Browser)Browser\handlers\ResourceHandler.cs](https://github.com/SafeExamBrowser/seb-win-refactoring/blob/d9662ec31e3c0b32e75e7eccd84a7a11b35f0b43/SafeExamBrowser.Browser/Handlers/ResourceHandler.cs#L416) the message.Headers.Add command hardcodedly does transmit 
`"MoodleSession="`
which omits that prefix, if set.
That leads to the UserId not being set, which results in a not finished handshake.

**Comment by danschlet** [comment]
But does Moodle transmit the prefix to the browser? Is that in an other header field than "MoodleSession"? 

If the SEB browser doesn't receive the prefix, then this would need to be fixed in the SEB Server, not the SEB clients.

**Comment by lucaboesch** [comment]
In the above setting "MoodleSession" then becomes "MoodleSessionbfh2" and that is what is expected back.
IMHO this should be resolvable in Safe Exam Browser client.

**Comment by lucaboesch** [comment]
(just noticed that technically, this is a "suffix", not a "prefix" 😂

**Comment by lucaboesch** [comment]
No idea whether in the 2020ies years this is still an issue but I reckon with ancient browsers and technologies what was stated here was true and useful:

> 
This setting customises the name of the cookie used for Moodle sessions. This is optional, and only useful to avoid cookies being confused when there is more than one copy of Moodle running within the same web site.

**Comment by dbuechel** [comment]
Thanks for the report! @anhefti, @danschlet and myself will have a look at it and try to fix that for version 3.8.0.

**Comment by dbuechel** [comment]
The issue should be fixed and can be tested in the latest beta build of version 3.8.0: http://sebdev-let.ethz.ch/api/buildjobs/036aec708vk2x1i4/artifacts/SEB_3.8.0.684_SetupBundle.exe.

**Comment by lucaboesch** [comment]
Yes, it does, @dbuechel see https://github.com/moodle/moodle/blob/b798633ae074eddd581724d0c5b1cdba01b9d909/lib/classes/session/manager.php#L335

**Comment by dbuechel** [comment]
Perfect, thanks, then the fix should work as it is currently implemented.

**Comment by lucaboesch** [comment]
@danschlet do you want me to open the same issue on https://github.com/SafeExamBrowser/seb-mac ?
Additionally, over there, if I am not mistaken, you do not check for /mod/quiz/accessrule/sebserver/classes/external/user.php and stick merely to /theme/boost_ethz/sebuser.php.

**Comment by lucaboesch** [comment]
https://github.com/SafeExamBrowser/seb-mac/issues/396 created.

**Comment by lucaboesch** [comment]
> The issue should be fixed and can be tested in the latest beta build of version 3.8.0: http://sebdev-let.ethz.ch/api/buildjobs/036aec708vk2x1i4/artifacts/SEB_3.8.0.684_SetupBundle.exe.

I can see the fix working fine in 3.8.0BETA.
Thanks!

**Comment by dbuechel** [comment]
Excellent! Then we'll release the fix as is with version 3.8.0.
