### ISSUE TITLE
Periodic reload + kiosk message window on LMS page

### ISSUE THREAD

**Issue by acamacho-unige** [SafeExamBrowser/seb-win-refactoring#849]
**Describe the Bug**
When doing a BYOD mock exam, we had 3 Windows 11 computers that showed a strange behaviour.
After launching SEB (3.7.0), which uses a ConfigureClient configuration specifying the start_url, students can login without any problem on Moodle LMS.
Then, on LMS homepage, those 3 students had Safe Exam Browser acting weirdly :

1. LMS page was showing without problem
2. LMS page disappears, and at center of screen we see SEB window with message "Loading kiosk mode" (or something like that).
3. LMS page appears again, and no other problem can be observed.
4. After 30 seconds aprox. this behaviour restarts ... and we have this loop every 30 seconds.

When rebooting computers, issue seems to disapear (or to happen only once, and not in a loop every 30 seconds).

**Steps to Reproduce**
1. ConfigureClient with a SEB config
2. Start SEB
3. Login on LMS (students did not yet go to a course > quiz > StartExam configuration)

**Expected Behavior**
We expected SEB to not have this behaviour, like on other Windows 10 computers and MacOS ones.

**Screenshots**
_The IT team could not grab a screenshot or logs. **We will do our maximum to reproduce the problem and get those logs and screenshot.**_

**Version Information**
 - OS: Windows 11, current-version of 17.04.2024 (no updates avalaible)
 - SEB-Version: 3.7.0

**Comment by dbuechel** [comment]
Thanks for the detailed report, that is indeed strange (and unintended) behavior. That sounds like something (be it the system or third-party software) interfering with the kiosk mode induced by SEB. If so, that would indeed be logged in the runtime logs, which I shall analyze once they're made available.
