### ISSUE TITLE
Unmute sound after starting SEB

### ISSUE THREAD

**Issue by galfisk** [SafeExamBrowser/seb-win-refactoring#850]
**Is your feature request related to a problem? Please describe.**
Many students have their notebook audio muted by default. Once they start SEB, they can no longer unmute the sound, because the hotkeys no longer work, and there is no unmute feature inside SEB.

**Describe the solution you'd like**
I'd like for an unmute button inside SEB, an automatic unmuting (either always, or when opening any test with any audio feature enabled), or a button for manual unmuting.

**Describe alternatives you've considered**
Asking every test conductor to ask every student to unmute their audio before starting the test only works if the message reaches every conductor and student every time, which it doesn't.

**Additional context**
We use HP laptops, which have hotkey software which SEB seems to disable. Fn+F5 should unmute our laptops, but doesn't once the test has started.

**Comment by dbuechel** [comment]
This functionality should already work as is, see the "Audio Control" section under tab "User Interface" in the configuration tool: https://safeexambrowser.org/windows/win_usermanual_en.html#AppearancePane.
