### ISSUE TITLE
SEB - Office Programms - EntraID(AzureAD) 2FA

### ISSUE THREAD

**Issue by supajo** [SafeExamBrowser/seb-win-refactoring#858]
Hello, 

We have the situation that in our SEB Environment, users must authenticate in our Office program's against EntraID (AzureAD) for the license, even though we are using M365 SharedDevice Licenses. 

Since the Digital Markets Act is active since 01.03.2024, SSO into our Office program's don't work anymore because a popup opens in the background. Here a screenshot as example how it should be
![1-seb](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/29715436/c73c9642-31e8-4119-8c4a-e4c7166e4760)
I must be able to click "Weiter" to accomplish the login

Here is how it looks like in a SEB Session:
![3b7bf6b6-accf-418c-88a8-19c961c42206](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/29715436/452203a5-af64-4861-8eed-c1c2e7272592) 
The popup from the first screenshot never opens / is opened in background.

A few months ago we created a rule to exlude certain devices from 2FA because we already had this issue but now there is no workaround anymore.

The popup from the screenshot is created by the following program (UWA App)
![image](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/29715436/8fab2fbf-c560-48df-8a86-1bdd2910735b)

Whitelisting of Microsoft.AAD.BrokerPlugin.exe sadly doesnt help, the popup opens still in background.

Any help is welcomed.

OS: Windows 10, 22H2
SEB Version: 3.7.0

**Comment by dbuechel** [comment]
Thanks for your report. UWP applications are most unfortunately incompatible with both of SEB's kiosk modes, thus I'm afraid there is no solution to your issue for the time being.

The underlying reason is that UWP applications apparently need Windows Explorer in order to work correctly, but SEB does and cannot allow that in both kiosk modes.

**Comment by supajo** [comment]
Just for information for anybody who runs into the same problem.
There is a possibility to use M365 Device Licenses (at no costs, order at your reseller)
https://learn.microsoft.com/en-us/deployoffice/device-based-licensing

Now our workaround is working again.

**Comment by dbuechel** [comment]
Great, that is good to know and may help other users, thanks for the update!
