### ISSUE TITLE
Prohibited Display Configuration

### ISSUE THREAD

**Issue by xavierose** [SafeExamBrowser/seb-win-refactoring#859]
I Cannot log in to my exam things, i already checklist the setting in SEB configuration due to display error checking, for the SEB only it works, but when i click from my work test web, the error checking persist. here i drop the screenshot of the error and my log file. Please Help if there any answer about this issu
![Error SEB](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/168051730/0e17bddd-15cd-4603-ac3d-396001fa12af)
[2024-04-25_09h41m35s_Runtime.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/15103301/2024-04-25_09h41m35s_Runtime.log)

**Comment by dbuechel** [comment]
This has been discussed at length in other issues and discussions. Please search GitHub accordingly and try the solution attempts provided there; normally, it comes down to missing Windows Updates, outdated drivers or a corrupted system configuration.
