### ISSUE TITLE
SEB Failed to Launch

### ISSUE THREAD

**Issue by Rional31** [SafeExamBrowser/seb-win-refactoring#864]
[2024-04-25_16h12m31s_Client.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/15107396/2024-04-25_16h12m31s_Client.log)
[2024-04-25_16h12m31s_Runtime.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/15107397/2024-04-25_16h12m31s_Runtime.log)

why SEB can't launch with these logs?
![image](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/168079943/0d973885-9203-4ffc-b189-02c858df63bf)

**Comment by dbuechel** [comment]
Please note that we don't support Windows 7 anymore. Apart from that, use the setup bundle (.exe) for installation as is mentioned prominently in the release notes, or then install all the required runtime dependencies (in this case the VC++ Redistributable) manually.

**Comment by dbuechel** [comment]
See https://github.com/cefsharp/CefSharp/discussions/4336.

**Comment by Rional31** [comment]
I already install various version of VCC++ redistributable, but it still failed to work. what should I do then?
is there any version of SEB that only work in Windows 7?

**Comment by dbuechel** [comment]
In order to use the latest release versions, you'll need to upgrade to Windows 10 or 11. Older SEB versions may still run under Windows 7, but they are not supported by us anymore and we furthermore strongly advise against using them.
