### ISSUE TITLE
Cant choose organisation when starting SEB - Blank White Window

### ISSUE THREAD

**Issue by EnKoppTe2** [SafeExamBrowser/seb-win-refactoring#868]
Logs
[2024-04-26_08h34m51s_Browser.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/15126463/2024-04-26_08h34m51s_Browser.log)
[2024-04-26_08h34m51s_Client.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/15126464/2024-04-26_08h34m51s_Client.log)
[2024-04-26_08h34m51s_Runtime.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/15126465/2024-04-26_08h34m51s_Runtime.log)
[2024-04-26_08h34m51s_Service.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/15126466/2024-04-26_08h34m51s_Service.log)

**Describe the Bug**
When the student starts the test, Safe Exam Browser starts with no issue. When the browser is fully started there should be a box where the students can log in to their microsoft accounts. On some PCs it works flawlessly (we've tried on a admin pc and "local" pc not connected to and AD domain) and on some the box is just white and will not load. 
Ive tried to reinstall SEB a couple of times, tested different verions (3.4.6 upto 3.7) with the same issue. 

**Steps to Reproduce**
1. Go to [skolverket](https://www.skolverket.se/skolutveckling/digitala-nationella-prov/logga-in-i-provplattformen/logga-in-med-safe-exam-browser)
2. Click on sebs://www.skolverket.se/download/18.51c904b718e5404561cce/1710861162726/vt24_fed.seb
3. SEB starts up and should get a login window but its just White. 

**Expected Behavior**
A window where the student can log in.

**Screenshots**
![IMG_20240426_084045782](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/146131121/3ff4673c-298a-43b9-bb3b-23e429630d08)

**Version Information**
Windows 10 Education 22H2
 - SEB-Version 3.6 and 3.7

**Comment by dbuechel** [comment]
I can't quite reproduce the issue; what institution would I need to select in order to reach that page, or is it the institution selection itself which does not load?

There is one entry in the browser log which could indicate a network or server issue:

`[0426/083545.771:INFO:CONSOLE(1)] "Uncaught Error: Window did not load after 5000ms", source: https://ds.fidus.skolverket.se/vendors~cta~ds~index_d1d4484af119508118b5.js (1)`

**Comment by EnKoppTe2** [comment]
Hi. I just came back from a couple of days of work since I made this post. I found the issue earlier today. In one of the logs it says it doesn't have permission to download a font due to restrictions. 

It seems that Skolverket (swedish school org) have made a test with a hardcoded font from Adobe that it tries to download through a javascript. According to our IT Admin we have a restriction policy in Intune that blocks javascript to download anything. When we disabled that policy it works fine. 

You can close this issue :) Thanks!

**Comment by dbuechel** [comment]
Excellent, that is great to know and thank you as well for the update.
