### ISSUE TITLE
cant detect droidcam

### ISSUE THREAD

**Issue by nickokiller2** [SafeExamBrowser/seb-win-refactoring#870]
i use seb 3.7 cant detect droid cam when another app can detect and i miss my exam for looking a job. i use pc not a laptop because my laptop broke i dont know if seb cant detect droidcam because not everyone have a webcam not everyone need just for a 1 used, so i have optional for use droidcam with my phone to be a webcam.

**Comment by dbuechel** [comment]
SEB does not directly access webcams, that is then a feature of the web application / LMS you were using and you'd need to contact its manufacturer.

**Comment by nickokiller2** [comment]
oh i see, thankyou for your explanation.
