### ISSUE TITLE
SEB Initializing Kiosk Mode keep flashing when in the browser.

### ISSUE THREAD

**Issue by tepid-milk** [SafeExamBrowser/seb-win-refactoring#871]
I am required to use Safe Exam Browser for an upcoming examination, I have purchased a new laptop and installed SEB, I was also provided a configuration file that I 'Open With' Safe Exam Browser, everything opens correctly and looks okay until after a minute, then every minute or so after that SEB exits kiosk mode and appears with the loading kiosk window to then return to where I left off in the browser.

[2024-04-30_12h41m18s_Browser.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/15158469/2024-04-30_12h41m18s_Browser.log)
[2024-04-30_12h41m18s_Client.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/15158470/2024-04-30_12h41m18s_Client.log)
[2024-04-30_12h41m18s_Runtime.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/15158471/2024-04-30_12h41m18s_Runtime.log)
[2024-04-30_12h41m18s_Service.log](https://github.com/SafeExamBrowser/seb-win-refactoring/files/15158472/2024-04-30_12h41m18s_Service.log)

1. Right click on configuration file (.seb)
2. Receive pop up that configuration is successful - select no when asked if I want to quit
3. SEB opens up to the correct white listed page
4. After a short time my screen flashes with the previously stated issue.

The correct applications and page open according to the configuration but very soon after the below image flashes and continues to every 90 seconds

![SEBissue](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/168509482/5247c91d-d097-4c2f-865f-f9f2f667fd25)

 - OS: Windows 11 Home
 - SEB-Version 3.4.1

Please note that all users are using SEB version 3.4.1 but I am the only one with this issue

**Comment by dbuechel** [comment]
Some third-party application is interfering with the kiosk mode induced by SEB:

```
2024-04-30 12:42:29.163 [08] - WARNING: [DesktopMonitor] Detected desktop switch to 'Default' [3864], trying to reactivate 'YdclcYmxATYZxoG' [108]...
```

We had the same reports with Cisco WebEx as well as ESET Anti-Virus, thus you'd need to investigate which application it is and then ideally report your findings here, so that it may help other users encountering the same issue.

As a side note, we always strongly recommend updating to the latest official release version, first and foremost due to security updates and bug fixes.

**Comment by Choopx** [comment]
Same situation and same problem with me. New laptop, updated version of the browser, SEB 3.7, I am the only one with this issue.

**Comment by nabilarosa** [comment]
I am using SEB 3.7.0 on my Windows 11 Home, and currently having the same problem. I have no applications opened or antivirus installed, except the default windows security. I already reinstalled the SEB and still facing the same issue. Please help me solve this. Thank you!

**Comment by dbuechel** [comment]
@Choopx @nabilarosa Did you rule out that none of the applications mentioned under https://github.com/SafeExamBrowser/seb-win-refactoring/issues/871#issuecomment-2085732244 as well as the linked issue interfere with SEB?

It is highly unlikely that there is another cause for this problem than a third-party application interfering with the kiosk mode induced by SEB, as already stated above.

**Comment by ThomasL-AP** [comment]
One of our students is having the same issue. 
[logs s152966-1.zip](https://github.com/user-attachments/files/15738383/logs.s152966-1.zip)
She can finish her exam but this is annoying for her.
Below a video of the pop-up during a "test" exam. This happens indeed about every minute. 
https://github.com/SafeExamBrowser/seb-win-refactoring/assets/156918144/62730a7a-3c41-4f71-a533-54f53512d602

I will look into what other software on her machine could cause this.

**Comment by Ne0sky** [comment]
was any solution found for this ?

**Comment by ThomasL-AP** [comment]
I'm not sure if I ever saw the student in question back at my desk. But I'm pretty sure the solution is to check the system tray or other apps running in the background.

**Comment by lifeunexpected** [comment]
Hey we just experienced the same problem and it was releated to a program called "win usb display" in the list of applications installed on the PC.

Two students had the same problem and they had bought a usb to HDMI dongle to get picture from the PC to the TV and that device asked them to install Win USB Display software that caused the problem with flickering when running SEB

![image](https://github.com/user-attachments/assets/da071b69-f64f-47e6-83b6-7f606ee29f31)

**Comment by dbuechel** [comment]
Thanks a lot for the information @lifeunexpected, this certainly will help other users facing the same issue. It is a bit strange that this third-party application interferes with the kiosk mode of SEB by re-activating the standard desktop (it should just simply capture the currently active desktop); if you're so inclined, it certainly would be good to make the manufacturer aware of the issue.

**Comment by ThomasL-AP** [comment]
[Flashing seb.zip](https://github.com/user-attachments/files/19538309/Flashing.seb.zip)

Still having this issue. I'm not sure which log to look at.

Comparing Client and runtime logs I see this happening 3 times, almost at fixed intervals of exactly one minute.
**Client**:
> 2025-03-31 17:44:30.177 [19] - DEBUG: [ApplicationMonitor] Window has changed from '' (1049920) to 'Aanmelden bij uw account' (329178).
**Runtime**:
>2025-03-31 17:44:30.145 [07] - WARNING: [DesktopMonitor] Detected desktop switch to 'Default' [3036], trying to reactivate 'GQSykvrJNcUREoOO' [6487]...

**Comment by dbuechel** [comment]
@ThomasL-AP You'll need to identify the third-party application / driver which is interfering with the kiosk mode. The logs themselves most likely cannot show anything other than the above entries, as the third-party application simply is reactivating the default desktop.

**Comment by TomJampen** [comment]
We have just identified one more application responsible for switching desktops:

**OMEN Gaming Hub** (or more precisely the process `OmenCommandCenterBackground.exe`)

Unfortunately, this is HP software often preinstalled in HP devices. Uninstalling OMEN Gaming Hub resolved the issue for severeal students in our institution.

**Comment by ThomasL-AP** [comment]
I can confirm HP Omen Gaming Hub was in one of my cases probably the cause. 
(I also updated a graphic card driver but I have no reason to think this was the cause.)

**Comment by adrianwhatwedo** [comment]
Is there a offical list of known or reported Apps/Driver that lead to this issue? 
@dbuechel Would you be intressted in these reportings or are they not of any help for you?

**Comment by Karelbe** [comment]
We have also some reports and not always have a solution but:

- mcAfee has been a problem (removing are disabling it resolved it)
- Windows updates pending also triggered this pop-up
