### ISSUE TITLE
Trouble installing 3.1.1.250

### ISSUE THREAD

**Issue by Grogera** [SafeExamBrowser/seb-win-refactoring#88]
I have been trying to install the latest version on a couple of computers. 
So far three of them have encountered this: 
"The feature you are trying to use is on a network resource that is unavailable. Click OK to try again or enter an alternate path to a folder containing the installation package 'SafeExamBrowser.msi' in the box below."

I have tried searching for the msi but cannot find it. I have the installer bundle in a folder called temp directly on C:.
I have made sure to run windows update and also tried running the linked installers. Also made sure I start the installation as admin.

**Comment by dbuechel** [comment]
There most likely is an issue on your system, it might be that Windows Installer can have an inconsistent state which needs correction. Either way, if you need the MSI setups for SEB 3.1.1, you can find them here:

MSI for SEB 3.1.1 (x86): https://sebdev-let.ethz.ch/project/AppVeyor/seb-win-refactoring/builds/280/job/rfmwpuo4hdx9u2si/artifacts
MSI for SEB 3.1.1 (x64): https://sebdev-let.ethz.ch/project/AppVeyor/seb-win-refactoring/builds/280/job/3pv4craowibjxry0/artifacts

**Comment by Grogera** [comment]
Thanks, gonna give them a try.
