### ISSUE TITLE
Unable to configure mock test URL

### ISSUE THREAD

**Issue by ChanderSreeram** [SafeExamBrowser/seb-win-refactoring#881]
I am from Compatibility test team at Microsoft. Our team is responsible for overseeing the compatibility to ensure all existing applications and end-user scenarios continue to function with the latest Windows Updates. Currently, we are looking for your support on Safe Exam Browser application which is failing to launch with an error. This issue is currently impacting our validation, can you please let us know if there is any known workaround or any contact to follow up and get this issue resolved for our compat validation.

I can share the mock exam URL which was shared earlier to enable the validation at our end. I am logging a issue here as i couldn't find the direct contact to reach out. Please route me or mail me in case any further details are required(v-nsree@microsoft.com)

We appreciate your support.

![SafeExamBrowser](https://github.com/SafeExamBrowser/SafeExamBrowser-Website/assets/167824748/44a2cc4e-5925-49cb-8c13-b34d38cba1d5)

Thanks,
Chander

**Comment by dbuechel** [comment]
Please post the log files of the affected session(s). They can be found under `%LocalAppData%\SafeExamBrowser\Logs`.

**Comment by dbuechel** [comment]
Or it could be an issue with the local clock settings of your Windows installation. Please verify that it is correct and up to date.

**Comment by ChanderSreeram** [comment]
> Please post the log files of the affected session(s). They can be found under `%LocalAppData%\SafeExamBrowser\Logs`.
Confirmed the issue today and ensured that the local clock settings are correct, yet the error persists. This problem occurs upon launching after updating the mock test URL (https://s1.examonline.in/mocktest/) in the SEB configuration tool. Kindly assist in verifying if this URL is still active or help us provide a new one for our validation.

**Comment by ChanderSreeram** [comment]
@dbuechel  I have attached the logs and share the requested information. Please review when you get a chance. We are eager to resume the validation runs on Safe Exam browser.

**Comment by dbuechel** [comment]
The logs do support the assumption that there is a network or related issue on your system(s):

```
2024-05-17 14:24:57.753 [25] - WARNING: [Browser Window #1] Request failed: ERR_CONNECTION_TIMED_OUT (-118, main request).
2024-05-17 14:25:30.574 [25] - WARNING: [Browser Window #1] Request failed: ERR_CONNECTION_TIMED_OUT (-118, main request).
2024-05-17 14:24:57.753 [25] - WARNING: [Browser Window #1] Request failed: ERR_CONNECTION_TIMED_OUT (-118, main request).
2024-05-17 14:25:30.574 [25] - WARNING: [Browser Window #1] Request failed: ERR_CONNECTION_TIMED_OUT (-118, main request).
```

**Comment by ChanderSreeram** [comment]
@dbuechel  We verified the issue across multiple systems using different network environments and this seems to be an issue with the mock URL link we are using (https://s1.examonline.in/mocktest/). Could you please help us with a different URL to try on our end and resume our testing process on SEB. 

Thank you!

**Comment by dbuechel** [comment]
Just use any actually existing URL, e.g. [https://www.duckduckgo.com](https://www.duckduckgo.com).

**Comment by ChanderSreeram** [comment]
@dbuechel  Thanks for the link. We have checked the provided URL, and while it launches successfully, we are unable to take the mock test. Could you please provide a URL that allows us to take a mock test so we can fully evaluate the application's functionalities. Thank you.

**Comment by dbuechel** [comment]
To which mock test are you referring? We have a few demo configurations under [https://safeexambrowser.org/testing/](https://safeexambrowser.org/testing/) (quit password, if required: `quit`).

**Comment by ChanderSreeram** [comment]
@dbuechel We have tried to use the demo links which was shared earlier(https://safeexambrowser.org/testing/) and observed invalid login error. Could you please let us know if there are any other specific login details. (username & password as quite is not working)

![image](https://github.com/user-attachments/assets/e7a2460a-5c75-40da-a47c-6b33df48515f)
![SafeExamBrowser_Invalidlogin](https://github.com/user-attachments/assets/e2d26c5b-1e80-4d53-9f44-5da6f11a73d4)

**Comment by dbuechel** [comment]
As per information on the demo Moodle:

> This is a Moodle demo site for Safe Exam Browser (SEB). You can try out some simple demonstration exams secured by SEB. There are several demo user accounts, randomly choose one of those. The password for all of these users is "demo"
> 
> seb1, seb2, seb3, seb4, seb5, seb6, seb7, seb8, seb9, seb10

**Comment by ChanderSreeram** [comment]
Thank you, @dbuechel , for sharing the demo URL and the details. We’ve reviewed the link and incorporated it into our validation process. However, there are a few functionalities we couldn’t verify due to the demo’s limitations. Could you please provide us with a dedicated URL that would allow us to fully evaluate the application, including all planned functionalities, as part of the Windows compatibility effort? Below are the functionalities currently blocked from validation.

	mock test
	next previous questions
	section/legends/summary
	send messages to any other system while giving assessment
	work with basic functionalities while giving assessment
	submit exam

**Comment by dbuechel** [comment]
Moodle is not part of Safe Exam Browser, it in this here case merely serves as an example use case for an exam. You can find all the relevant information about SEB's functionalities in the user manual: https://safeexambrowser.org/windows/win_usermanual_en.html. From there, you can simply create a SEB configuration file, configure the functionalities you'd like to test and then start SEB with it.

**Comment by ChanderSreeram** [comment]
@dbuechel We have created a SEB configuration and successfully able to launch the exam using the demo credentials. This allowed us to review previously tested exams without any issues. However, we attempted to take a new exam using the provided link below, we've encountered the following issues. Please let us know if there is any way to verify the reconfiguration or we can drop this functionality if this is not a critical check based on your suggestion.

[https://safeexambrowser.org/testing/](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsafeexambrowser.org%2Ftesting%2F&data=05%7C02%7Cv-nsree%40microsoft.com%7C7eaf045712e54ae71a0808dd0980b709%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638677170642552348%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=GeVKfsXvMT%2B8LlRG8mcuCVlEdM%2Bdwra%2BtFYjR3JMM28%3D&reserved=0), 

1) A pop-up message appeared stating "Reconfiguration denied" and "You are not allowed to reconfigure SEB."
2) Additionally, when opening the demo link [https://safeexambrowser.org/testing/](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsafeexambrowser.org%2Ftesting%2F&data=05%7C02%7Cv-nsree%40microsoft.com%7C7eaf045712e54ae71a0808dd0980b709%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638677170642566102%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=3imhm2jYIGC7JAIymk6amogMBdLOvWs8PMWU2kFWU8E%3D&reserved=0), in screen it is indicating, "You must use an approved version of Safe Exam Browser to attempt this quiz."

**Comment by ChanderSreeram** [comment]
@dbuechel since the primary functionality of the application is to take the exam and get the results, we would like to understand if there is any feasibility to replicate the same in our testing. Currently with the link which is provided earlier, we are only able to review the exams that were previously attempted and we are unable to take a new test. Please let us know if there is any other source or suggestion to enable this in our testing.

**Comment by dbuechel** [comment]
That is a configuration issue of Moodle (i.e. allowing multiple or clearing previous attempts). If you'd need that, you could set up your own Moodle installation and is it for testing.
