### ISSUE TITLE
Blacklisting non-vm computer as vm

### ISSUE THREAD

**Issue by pinkestflamingo** [SafeExamBrowser/seb-win-refactoring#886]
Enabling the following options on your Windows computer will create the disk 'PROD_VIRTUAL_DISK' which is blacklisted by SEB:
- Windows Subsystem for Linux
- Windows Sandbox

This caused me to get flagged each and every exam for 8+ months and I had to attach a debugger to SEB to understand where it is flagging me.
Filtering for "PROD_VIRTUAL_DISK" is the most stupid thing I've seen to detect virtual environments.

It is embarrassing that having a virtual disk is a detection vector. Step up your game. EMBARRASSING!

**Comment by danschlet** [comment]
@pinkestflamingo Please mind your language. We don't tolerate verbal abuse (this is not Twitter -> X).

**Comment by dbuechel** [comment]
You are very correct indeed! I doubt that we have a logic error there, I vaguely remember introducing the whitelist which then has been verified by our internal testing.

Do you happen to have the capacity and time to debug the issue and verify that it can't be `PROD_VIRTUAL_DISK` triggering the detection?

**Comment by dbuechel** [comment]
Thanks, but this then should clarify that the VM detection actually was not triggered because there is a virtual disk installed on a physical machine.
