### ISSUE TITLE
Copy-Paste Issues with Safe Exam Browser 3.7.0

### ISSUE THREAD

**Issue by erik1980** [SafeExamBrowser/seb-win-refactoring#890]
### Describe the Bug
I'm experiencing two major issues while using Safe Exam Browser (SEB) for an essay-type question in a Moodle exam:

1- Copy-Paste Functionality Blocked: SEB is blocking the ability to copy and paste text between the exam question window and an external online compiler. This issue specifically arises when students are required to design a web page (using HTML, CSS, and JavaScript) in the online compiler and then copy-paste the code into the answer area within the exam.

2- Text Duplication on Copy-Paste: When attempting to copy and paste text within the same answer area, the text gets duplicated. For example, if the text "Hello" is copied, it pastes as "HelloHello" instead of just "Hello". 

These issues are severely hindering the ability of students to effectively complete the essay-type question, as they cannot transfer their work from the online compiler to the answer area, and any attempt to copy-paste within the answer area results in text duplication.

### Steps to Reproduce
1. Open Safe Exam Browser for a Moodle exam.
2. Navigate to an essay-type question that requires opening an online compiler and copying code into the answer area.
3. Try to copy-paste text from the online compiler to the answer area using Ctrl+C/Ctrl+V.
4. The copy-paste functionality is blocked, and the text cannot be transferred.
5. Try to copy-paste text within the same answer area.
6. The text gets duplicated (e.g., "Hello" becomes "HelloHello").

### Expected Behavior
The expected behavior is to be able to copy-paste text freely between the online compiler and the answer area, as well as within the answer area itself, without any duplication or blocking of functionality.

### Screenshots
First issue
![image](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/33292301/55c3fa12-cded-4adf-a2ce-9d5d6ba2d181)

Second issue
![WhatsApp Image 2024-05-26 at 16 47 23_21ac87aa](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/33292301/1cf55824-9546-4b99-9250-ce7e3ef6a877)

### Version Information

- OS: Windows 11 Version 23H2
- SEB-Version: Safe Exam Browser 3.7.0
- Moodle Version: 4.2.3+ (Build: 20231110)

### Additional Context
This issue is specific to an essay-type question in a Moodle exam that requires students to design a web page using HTML, CSS, and JavaScript in an online compiler and then copy-paste the code into the answer area. The inability to copy-paste or use keyboard shortcuts hinders the students' ability to complete the question effectively.

**Comment by erik1980** [comment]
I tried it on macOS and it works, but not on Windows 11.

**Comment by dbuechel** [comment]
If you want to be able to use the system clipboard instead of the isolated clipboard only working within the browser application of SEB, then you can set the respective clipboard policy in the configuration (see Security > Clipboard Policy > Allow).

Regarding the duplicated content pasting: Does that occur everywhere resp. in all types of inputs (e.g. search engine input or default textbox) or only inside Moodle resp. even only in an essay question type?

**Comment by erik1980** [comment]
The first issue is already resolved. 
Regarding the second issue, I tried others in other parts of the browser and in other types of questions and it worked perfectly. Apparently it's only in essay type questions. The problem disappears with the .seb configuration file that resolved the first issue.

**Comment by dbuechel** [comment]
Then I assume that the essay type has a custom handler for copying and pasting. That isn't something we can change and would need to be changed resp. made configurable in Moodle itself.
