### ISSUE TITLE
intallation stuck on WebView2 Runtime installation

### ISSUE THREAD

**Issue by finete** [SafeExamBrowser/seb-win-refactoring#893]
**Describe the Bug**
I am trying to install the following SEB: https://github.com/SafeExamBrowser/seb-win-refactoring/releases/download/3.3.1/SEB_3.3.1.388_SetupBundle.exe

however the installation is stuck on the installation of the WebView2 Runtime even though I already have the runtime installed.

I have tried to follow the steps [here](https://sourceforge.net/p/seb/discussion/844844/thread/afb87c42fc/) to no avail as well.

**Steps to Reproduce**
1. install WebView2 Runtime
2. try to install SEB_3.3.1.388_SetupBundle.exe
3. get stuck

**Expected Behavior**
the program to be installed

**Screenshots**
![image](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/34818222/b1135cb6-70db-4c47-955d-be784f0985fa)

**Version Information**
 - OS: windows11 22H2
 - SEB-Version SEB_3.3.1.388

**Comment by dbuechel** [comment]
SEB 3.3.1 is not officially supported anymore; if possible, please use the latest official version (currently SEB 3.7.0). In case you specifically need 3.3.1, install all the required runtime dependencies as specified in the release notes here on GitHub and then install the respective MSI setup (not the setup bundle).
