### ISSUE TITLE
Need help building

### ISSUE THREAD

**Issue by M4THYOU** [SafeExamBrowser/seb-win-refactoring#9]
I'm trying to build this project in Visual Studio, but it is not working. I'm finding it unclear on how to do so. Is there a specific version I need to have installed? And how do I use the SetupBundle to get the prerequisites installed?

**Comment by M4THYOU** [comment]
I am now building it with Visual Studio 2019. When I try building the solution, I get just this error:

`The command "robocopy "C:\Users\Matthew\source\repos\seb-win-refactoring\SafeExamBrowser.Browser\bin\x64\Debug" "C:\Users\Matthew\source\repos\seb-win-refactoring\SafeExamBrowser.Client\bin\x64\Debug" /e /np
if %ERRORLEVEL% geq 8 exit 1
robocopy "C:\Users\Matthew\source\repos\seb-win-refactoring\SafeExamBrowser.Client\bin\x64\Debug" "C:\Users\Matthew\source\repos\seb-win-refactoring\SafeExamBrowser.Runtime\bin\x64\Debug" /e /np
if %ERRORLEVEL% geq 8 exit 1
exit 0" exited with code 1.	SafeExamBrowser.Client`		

Any idea why this Robocopy error happens?

**Comment by danschlet** [comment]
Please note that for consulting by the SEB developer about building customized versions of Safe Exam Browser, a Platinum Membership in the [SEB Consortium](https://safeexambrowser.org/consortium/members.html) is required.
