### ISSUE TITLE
SEB for ChromeOS ?

### ISSUE THREAD

**Issue by wolfravenous** [SafeExamBrowser/seb-win-refactoring#902]
I currently work for a small private college, so our IT budget is very streamlined compared to larger state-funded schools.  That being said, we have chosen to utilize Moodle for our LMS and offer the instructors the use of SEB to assist with quiz/testing security.

We have recently partnered with multiple high schools to offer Dual Enrollment courses.  We have discovered that many of the partner schools issue the students Chromebooks, of course running ChromeOS.

I was just wondering if there were any plans to incorporate ChromeOS into the SEB development paradigm.    I understand ChromeOS is a tiny percentage of the overall OS landscape; however, based on our interactions with our partner schools, it seems as if almost all of that usage exists in the high school educational setting.  

Could you please let me know if there are any plans for SEB development on ChromeOS in the near future?

**Comment by danschlet** [comment]
This is a question of financing. We would need some new members contributing to the [SEB Alliance](https://safeexambrowser.org/alliance/fees.html) to be able to fund one permanent developer to do the initial development and then maintenance and improvements of a ChromeOS SEB version. We had some entities being interested in the past, but unfortunately no one was willing to contribute financially.

**Comment by wolfravenous** [comment]
Daniel, thanks for the prompt reply.  I also appreciate your explanation of the issue.

Best
Steve

**Comment by wolfravenous** [comment]
Hi Daniel,
I have been thinking more about this issue, and I know that Google supports a wide range of initiatives.  I was thinking I might be able to connect with the right person at Google to present the idea of providing funding to the SEB group specifically for ChromeOS development. This would lead to the development of SEB for ChromeOS, a move that would greatly benefit numerous school systems worldwide that rely on Moodle and Chromebooks.  This seems like a win-win-win for both Google and their ChromeOS platform and Moodle users who want to leverage SEB on inexpensive Chromebooks and The SEB Alliance in their ability to provide an even wider offering of compatibility.  Just curious what your thoughts would be on the idea.  I don't know the policy of SEB Alliance or if you would be able to even accept funding from an entity like Google.  Could you please let me know before I take more action on the idea?  Thanks.
