### ISSUE TITLE
Where is the Linux version ?

### ISSUE THREAD

**Issue by EBiForE** [SafeExamBrowser/seb-win-refactoring#91]
A public OpenSource software dedicated to a study course must guarantee equal study opportunities, until there is a Linux version or one that works with wine, this right will not be guaranteed.

**Comment by danschlet** [comment]
Very simple: Someone has to pay for it. Our software if free to use, but its development, maintenance and support costs money. We need at least one dedicated permanent developer to cover a new OS platform.

If enough institutions or companies, which require a Linux version, contribute funding by becoming member of the [SEB Alliance](https://safeexambrowser.org/alliance), then there will be a Linux version. If not, there won't be any.

**Comment by wiltaylor** [comment]
You do realise by not supporting linux you are just encouraging people to bypass your protection and implement a fix themselves.  All this nonsense about money is very short sighted and foolish.

**Comment by danschlet** [comment]
WE DON'T HAVE DEVELOPERS TO DEVELOP A LINUX VERSION. SOMEONE NEEDS TO PAY SALARIES! ARE YOU WORKING FOR FREE???
