### ISSUE TITLE
Downloading functionality Windows 11

### ISSUE THREAD

**Issue by jellevyncke** [SafeExamBrowser/seb-win-refactoring#916]
**Describe the Bug**
When downloading a file through SEB (on a windows 11 machine). It shows the "download not allowed" alert even though the configuration says downloading is allowed. It looks like an original config not having something (null value) for "choose download / upload directory" makes SEB think "download is not allowed" when it should be allowed if "use temporary download / upload directory" has been checked.

I added a screenshot below. Config 1 does work, config 2 does not. Config 1 is a duplicate I made of config 2. The only thing I changed was first checking the "allow the user to select custom download / upload directory", then adding a directory in the "choose download / upload directory" field. Then unchecking the "allow user to select custom download / upload directory".

As you can see in both configs no other thing has been changed. Users where reporting that downloading files they need for examination did not longer work. They used config 2. Now using config 1 they report downloading works again.

**Steps to Reproduce**
Hard to reproduce. There are no actual steps but using the config file that no longer works and having the one that works.

**Expected Behavior**
If "allow downloading files" is checked it should always allow downloading when "use temporary download / upload directory" is checked even when "choose download / upload directory" has not been choosen.

**Screenshots**
![image](https://github.com/SafeExamBrowser/seb-win-refactoring/assets/39987849/0dce1810-8763-4f86-97be-c17917cf1886)

**Version Information**
 - OS: Windows 11, 22H2, 22621.3737
 - SEB-Version 3.7.0 (x64), Build 3.7.0.682

**Comment by dbuechel** [comment]
Thanks for the report. We introduced new and separate settings for down- and uploading with version 3.7.0 but decided to keep backward compatibility to the old combined setting. Most unfortunately, a bug was introduced in the processing logic of the new and old settings which may very well be why you're experience the problem.

We shall notify you once the issue has been fixed and can be tested in a development build.

**Comment by dbuechel** [comment]
Please try the latest development build of version 3.8.0 to verify whether it works there as you would expect: https://sebdev.ethz.ch/api/buildjobs/gngcllm720wn910h/artifacts/SEB_3.8.0.718_SetupBundle.exe.

**Comment by 20250304000000** [comment]
Hello,

I'm experiencing a similar issue to with the SEB Configuration File that enables file downloads and uploads—it doesn't seem to be working. Here are my system details:
Operating System: Windows 10 Pro 64-bit, release 22H2
SEB Version: 3.8.0

I've also provided a link where you can review all the configurations I've applied.

[](https://liuc-my.sharepoint.com/:w:/g/personal/sgenone_liuc_it/EWrgaOf6AfVBvzQOpHzrg3AB7QWyV1MRED8mIz4q1iS-SA?e=fmHYP9](https://github.com/SafeExamBrowser/seb-win-refactoring/issues/)

Could you please assist me with this issue?

Thank you.
Sara
