### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by Pk2911** [SafeExamBrowser/seb-win-refactoring#927]
Hey I'm not able to find the logic/source code of/to the methods, `TryReadSessionCache`, `TryWriteSessionCache`, `TryVerifyCodeSignature ` and `TryVerifySessionIntegrity` and the files seb_x64.dll  and seb_x86.dll. Could you please show me where it is

**Comment by dbuechel** [comment]
Why resp. what would you need them for?

**Comment by strau0106** [comment]
If you are at it, I'd also take a copy 😛
