### ISSUE TITLE
Microsoft Teams Application screen share is not allowing inside SEB.

### ISSUE THREAD

**Issue by Shubhadaelumina** [SafeExamBrowser/seb-win-refactoring#932]
> [!IMPORTANT]
> - Please _always_ consult the documentation first before creating a bug report: https://safeexambrowser.org/windows/win_usermanual_en.html.
> - Please _always_ attach the log file(s) of the affected session(s)! They can be found under `%LocalAppData%\SafeExamBrowser\Logs`.

**Describe the Bug**
The Microsoft Teams application is allowed in the SEB application configuration. The Screen share functionality of Teams applications is not allowing in the SEB.

**Steps to Reproduce**
1. Go to SEB configuration
2. Click on Applications and select Prohibited Applications. MS.Teams.exe and Teams.exe are allowed.
3. Save the Configuration changes.
4. Schedule a meeting in Microsoft Teams, start Screen sharing and Launch the SEB launch file.

**Expected Behavior**
The Screenshare must continue even after Launching the SEB and taking the exam.

But the Screenshare is getting blocked after launching the SEB, but the meeting is running in the background.

**Version Information**
 - OS: [Windows 10 Pro, Version 1803]
 - SEB-Version [SEB 3.7.0]

**Comment by dbuechel** [comment]
You'll also need to allow Teams as a permitted application, otherwise it won't be allowed resp. still be suppressed if activated (see https://safeexambrowser.org/windows/win_usermanual_en.html#ApplicationsPane). You most likely also need to start Teams after SEB has been initialized. If that still doesn't work, make sure you're using kiosk mode Disable Explorer Shell instead of Create New Desktop.

**Comment by Shubhadaelumina** [comment]
Hi we enabled the Teams applications same as Zoom. In Zoom we can use the Screen share functionality before and after the SEB is launched. Same configuration we are expecting for Teams application. We have allowed the Teams application.

**Comment by dbuechel** [comment]
If you've correctly enabled Teams (i.e. added it as a permitted application as well as deactivated its entry under the prohibited applications), then try using the other kiosk mode as already mentioned above.

**Comment by Shubhadaelumina** [comment]
Ok thanks for the information. Can you update us with Executable name and Title for the Teams application? So that we could provide the permission for the Teams application.
