### ISSUE TITLE
Subject: Restricting access to the Word application to a specific folder in SEB 

### ISSUE THREAD

**Issue by Michael284713** [SafeExamBrowser/seb-win-refactoring#936]
Hello, I'm writing to ask for help using the Safe Exam Browser application. We've set up a test in Moodle, where the student has to hand in a Word file at the end. We have authorized the Word application in the ".seb" configuration file. However, we have encountered a problem: when the student opens Word in SEB, he has access to the entire Windows Explorer. We'd like to limit this access to a specific folder. For example, we'd like all shared drives and the entire C drive to be blocked, except for the download folder. For technical reasons, we'd like to avoid using a virtual desktop infrastructure (VDI). It's not a viable solution for us. Is it still possible to implement this configuration? If so, could you guide us through the necessary steps? Thank you very much for your help. Best regards,

**Version Information**
 - OS: Win10-22h2 / Win11-23h2
 - SEB-Version v3.7.0 - BUILD 3.7.0.682

**Comment by dbuechel** [comment]
This is unfortunately not possible, as we cannot restrict or interfere with the internal functionality of third-party applications (see also https://safeexambrowser.org/windows/win_usermanual_en.html#ApplicationsPane). As a workaround, you could use an online editor (e.g Office Online) in conjunction with the network filter component of SEB as well as restricted file system access with a temporary download directory.
