### ISSUE TITLE
Issue with 'decodeAudioData' on BaseAudioContext in SEB 3.7.0.682

### ISSUE THREAD

**Issue by SalamShahid** [SafeExamBrowser/seb-win-refactoring#937]
Hello,

I am a developer currently working on a web application designed for conducting tests. Our application utilizes the audio context to play audio, and it functions correctly on a standard browser environment (Chrome 126.0.6478.127 64-bit). However, when running the application on Safe Exam Browser (SEB 3.7.0.682), I encounter the following error:

**DOMException: Failed to execute 'decodeAudioData' on 'BaseAudioContext': Unable to decode audio data.**

This error is triggered by the following function in our code:

    const response = await firstValueFrom(this.resourceService.getResource(url));

    const arrayBuffer = await response.arrayBuffer();

    const audioCtx = new (window.AudioContext)();

    this.currentAudioBuffer = await audioCtx.decodeAudioData(arrayBuffer);

    this.setupAudioNode();

**Screenshots**
<img width="1066" alt="Screenshot 2024-07-15 at 8 26 35 AM" src="https://github.com/user-attachments/assets/d6e33af3-4e67-41da-9369-c27387be2338">

Not marked errors were caused by the first error.

**Version Information**
 - Device: [Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz 4.00 GHz 16GB RAM]
 - OS: [Windows 10 Enterprise, Version 22H2]
 - SEB-Version [SEB 3.7.0.682]

**Attachments**
 - Log files: [Logs.zip](https://github.com/user-attachments/files/16229780/Logs.zip)
 - Sample audio file: [F965C-P1-intro.mp3.zip](https://github.com/user-attachments/files/16229784/F965C-P1-intro.mp3.zip)

I would appreciate any guidance or support in resolving this issue.

Please let me know if you need any further information or clarification.

Thank you for your assistance.

Best regards,
Salam Shahid Abbas

**Comment by dbuechel** [comment]
This is most definitely an upstream issue with the browser engine. Please try to reproduce the issue with the CEF sample application: https://cef-builds.spotifycdn.com/index.html. If it reproduces with the sample application, then it's an issue with CEF (Chromium Embedded Framework) and you'd need to report it there; if not, then it's an issue with CefSharp (C# wrapper for CEF) and you'd need to report it there respectively.

**Comment by dbuechel** [comment]
Please do note that proprietary audio and video codecs are not supported, in case you're using such.
