### ISSUE TITLE
Students being able to open different websites, while being in a test

### ISSUE THREAD

**Issue by SSIvanov19** [SafeExamBrowser/seb-win-refactoring#939]
> [!IMPORTANT]
> - Please _always_ consult the documentation first before creating a bug report: https://safeexambrowser.org/windows/win_usermanual_en.html.
> - Please _always_ attach the log file(s) of the affected session(s)! They can be found under `%LocalAppData%\SafeExamBrowser\Logs`.

**Describe the Bug**
We use Moodle as our LMS and authenticate students via OpenID Connect with Microsoft 365 Integration. However, we’ve encountered an issue: When a test is opened from an SEB configuration (.seb) file, during the authentication process, users can open the Microsoft website from the link to terms and conditions. This opens a new tab where they can navigate to other websites (such as bing.com or google.com) while still in the test.

**Steps to Reproduce**
1. Download an SEB configuration file for any test in Moodle using OpenID Connect with Microsoft 365 Integration.
2. While authenticating with your O365 account, click on the link to open terms and conditions or privacy policy. A new window opens with the relevant page.
3. From this new window, users can navigate to other websites.
4. After logging in and continuing to moodle, they have unrestricted internet access while taking the test in SEB.

**Expected Behavior**
The new window should be closed automatically, or the test session should be terminated to prevent unauthorized internet access.

**Version Information**
 - OS: Tested on various versions, including Windows 11 23H2 and Windows 10 22H2.
 - SEB-Version: SEB 3.7.1.104

**Additional Context**

- The issue is only applicable when accessing the test from the .seb file.
- If students access the test through the “Launch Safe Exam Browser” button in Moodle, the issue does not occur.
- Although we’ve hidden the button to download the configuration from the test page, it can still be downloaded from the URL: /mod/quiz/accessrule/seb/config.php?cmid=<id of the test> 

Here are the logs from my latest session:
[2024-07-17_12h34m10s_Client.log](https://github.com/user-attachments/files/16263421/2024-07-17_12h34m10s_Client.log)
[2024-07-17_12h34m10s_Browser.log](https://github.com/user-attachments/files/16263422/2024-07-17_12h34m10s_Browser.log)
[2024-07-17_12h34m10s_Runtime.log](https://github.com/user-attachments/files/16263423/2024-07-17_12h34m10s_Runtime.log)
[2024-07-17_12h34m10s_Service.log](https://github.com/user-attachments/files/16263424/2024-07-17_12h34m10s_Service.log)

**Comment by dbuechel** [comment]
You can disable the opening of new browser windows, see https://safeexambrowser.org/windows/win_usermanual_en.html#BrowserPane > Links requesting to be opened in a new browser window. Additionally or as an alternative, you can also enable the network filter: https://safeexambrowser.org/windows/win_usermanual_en.html#NetworkPane.
