### ISSUE TITLE
ARM (aarch64) Windows Builds

### ISSUE THREAD

**Issue by DennisTHCR** [SafeExamBrowser/seb-win-refactoring#941]
**Is your feature request related to a problem? Please describe.**
Whilst x86-64 emulation works on Windows on ARM devices, the performance just isn't great.

**Describe the solution you'd like**
Either native ARM builds, or compilation instructions would solve the problem, I believe.

**Describe alternatives you've considered**
I've tried compiling the project myself, however I just couldn't get it to work, as I am not very familiar with C# / Visual Studio

**Additional context**
Especially with the new Qualcomm Snapdragon X Laptop processors releasing, more people (especially students) will probably use ARM based systems (me included, hence the issue), due to their better efficiency, and therefore extended battery life. The performance is bearable, however I believe compiling to another architecture shouldn't be an issue, considering cross compilation is pretty widely supported nowadays, and it would be appreciated :)

**Comment by dbuechel** [comment]
We're currently looking into the topic and according to our current state of knowledge, SEB appears to work just fine on the emulation layer.

A native ARM build is for the time being most likely not going to happen, due to various factors (runtime dependencies, native code parts, other priorities and feature requests).

**Comment by dbuechel** [comment]
As mentioned in #1024: For those experiencing performance issues with (the 64-bit build of) SEB on ARM, you can workaround the problem by simply installing the 32-bit (x86) build of Safe Exam Browser for the time being.
