### ISSUE TITLE
SEB_3.7.1.704_SetupBundle.exe won't install  

### ISSUE THREAD

**Issue by leon-alpay** [SafeExamBrowser/seb-win-refactoring#945]
After agreeing to the terms and conditions the setup fails and shows following message: 
![2024-08-06 15_47_13-Safe Exam Browser Installation](https://github.com/user-attachments/assets/07304c87-3ce2-4a45-b634-d91a27ecc54f)
I manually installed the .Net Framework Runtime 4.8 and 4.8.1 as well as the VC++ 2015-2019 Redistributable but it's not working.

[Safe_Exam_Browser_20240805140713.log](https://github.com/user-attachments/files/16511130/Safe_Exam_Browser_20240805140713.log)

**Comment by dbuechel** [comment]
It seems that the WebView2 runtime dependency (`MicrosoftEdgeWebview2Setup.exe`) is causing issues. Please try to install it manually and then retry installing SEB.
