### ISSUE TITLE
Error trying to open exam on 2 displays

### ISSUE THREAD

**Issue by cnm-michael** [SafeExamBrowser/seb-win-refactoring#95]
**Describe the Bug**
Opening .seb file with version 3.2.0 on windows computer with 2 screens produces an error:

Opening same .seb file with version 3.2.0 on windows computer with 2 screens does not have any error.

**Steps to Reproduce**
1. Windows Computer
2. 2 or more displays connected
3. Version 3.2.0 installed

**Expected Behavior**
It works

**Screenshots**
![Screenshot 2021-06-10 at 11 42 56](https://user-images.githubusercontent.com/52914933/121511866-01cd7a00-c9e1-11eb-8f6e-30447454d5b0.png)

**Version Information**
 - OS: Windows 10 Professional
 - SEB-Version 3.2.0

**Additional Context**

**Comment by dbuechel** [comment]
SEB 3.2.0 introduces a new feature for display monitoring. The default configuration only allows that there is one display connected, but this may be changed under tab "Security" in the configuration tool.

**Comment by cnm-michael** [comment]
Thank you Damian!
