### ISSUE TITLE
Update Installer

### ISSUE THREAD

**Issue by leumas700** [SafeExamBrowser/seb-win-refactoring#951]
**Is your feature request related to a problem? Please describe.**
We have alot of students who face bugs that already have been fixed. The problem for them is there is no way on knowing that SEB released an update. You can only check the current version via SEB Reset Utility but not update it. 

**Describe the solution you'd like**
SEB needs an update feature so users always use the current version and don't run into already fixed issues and bugs.
This could be a warning when starting SEB that there is a newer version or an additional setting in the SEB Reset Utility like "Check for updates".

**Describe alternatives you've considered**
Normally applications have a feature (Button) like "Search for updates" or it does it automatically on startup.

**Additional context**
I'm happy to answer questions if there are any.

**Comment by dbuechel** [comment]
A warning or hint would likely be possible. An auto-update mechanism on the other hand is for the time being not feasible and furthermore comes with other implications (e.g. failures due to BEK resp. ASK and/or version verification for a particular exam).

**Comment by leumas700** [comment]
A warning / hint would definitely already help a lot!

**Comment by danschlet** [comment]
One issue though is that SEB for privacy and scalability reasons (we have now dozens if not hundreds of millions users) is explicitly designed to **not contact any centralized server or cloud service**. A check for existing updates would require that.

Also for sure we won't add some update background service which would check for SEB updates without SEB being started. So if students wouldn't start SEB before an exam, they would find out only when the exam starts that they need to download a newer version.

A custom exam system integration could check which SEB version is used and refuse students to connect with an old version (or direct them to the download of the latest version).

**Comment by dbuechel** [comment]
@danschlet You're right, I forgot about that. A hack could be to check the available versions on e.g. GitHub, but that wouldn't be a clean solution (and likely will also cause issues). Thus, the only proper solution would be for your LMS to query the SEB version and then act accordingly.
