### ISSUE TITLE
Consistency in "minimal macOS version"-setting between Windows and mac

### ISSUE THREAD

**Issue by Spruce8913** [SafeExamBrowser/seb-win-refactoring#952]
**Is your feature request related to a problem? Please describe.**
The digital question platform we use with SEB, has some advanced javascript needs, which is why we want a quite high 'minimal' macOS version. Currently, you can select up to macOS 12 in Windows installation of SEB (which is where I prepare the settings .seb file that gets distributed to students through the question platform), which is fine.

However, I fear that in the future macOS 12 won't be enough and I see that in [SEB 3.3.3 for Mac](https://github.com/SafeExamBrowser/seb-mac/releases) the maximal ‘minimal macOS version’ is already macOS 14.

**Describe the solution you'd like**
Would it be possible to increase the options for the 'minimal macOS version'-setting in the Windows version as well? Our university is using Windows on all work-pc's, so there's otherwise no way for me to create a functional .seb file with for example minimal macOS 13 enforced.

**Comment by dbuechel** [comment]
That is certainly possible, we even already do have an internal work item related to updating the macOS-specific settings in the Windows configuration tool.

**Comment by dbuechel** [comment]
See also #527.

**Comment by Spruce8913** [comment]
Thank you!
