### ISSUE TITLE
SEB setup failed/ not installing

### ISSUE THREAD

**Issue by MelusiZondi** [SafeExamBrowser/seb-win-refactoring#957]
> [!IMPORTANT]
> - Please _always_ consult the documentation first before creating a bug report: https://safeexambrowser.org/windows/win_usermanual_en.html.
> - Please _always_ attach the log file(s) of the affected session(s)! They can be found under `%LocalAppData%\SafeExamBrowser\Logs`.

**Describe the Bug**

**Steps to Reproduce**

**Expected Behavior**

**Screenshots**

**Version Information**
 - OS: [e.g. Windows 10 Professional, Version 1803]
 - SEB-Version [e.g. SEB 3.0.1]

**Additional Context**
One or more issues caused the setup to fail. In some cases, the .NET Framework or the VC++
Redistribute fail to install due to insuffient disk space or network issues.

0x800713ec - Asia

**Comment by dbuechel** [comment]
What exactly is failing and which error message is displayed? Please also do provide the log file of the installer.

**Comment by MelusiZondi** [comment]
Hi Damian,

Please see screenshots below from various student showing the error they are experiencing. I will try to get ahold students that experienced this error to ask for the log file for the installer.

[cid:3f00898a-dc8f-4f0c-af7b-85e8da2dc082]





Regards

________________________________

**Comment by MelusiZondi** [comment]
![image](https://github.com/user-attachments/assets/9eebc582-e62a-4fc1-9690-272a6278c1f9)

**Comment by MelusiZondi** [comment]
Please see error message below received from several of our students;-

**Setup Failed

One or more issues caused the setup to fail. In some cases, the .NET Framework or the VC++
Redistributable fail to install due to insufficient disk space (at least 4.5 GB required) or network
issues. Please fix the issues (e.g. manually install the .NET Framework Runtime 4.8 from https:/
[/dotnet.microsoft.com/download](https://url.za.m.mimecastprotect.com/s/CTZtC58EwDhwy7LfzfMuzxCZ9) or the VC++ 2015-2019 Redistributable from https://
[support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)](https://url.za.m.mimecastprotect.com/s/v9x4C667xEcZRvYH6hPuX5WL0?domain=support.microsoft.com) and
then retry setup. For more information see the log file.

0x80072efe - Unspecified error**

**Comment by dbuechel** [comment]
Again, please provide the log file of the installer as previously mentioned. You can do so by clicking the link "log file" on the error page of the installer as shown above.

**Comment by MelusiZondi** [comment]
[Safe_Exam_Browser_20240830121903.log](https://github.com/user-attachments/files/16815863/Safe_Exam_Browser_20240830121903.log)

**Comment by MelusiZondi** [comment]
Kindy see log file above

**Comment by MelusiZondi** [comment]
Hi Danial,

Kindly find attached log file as per your request.

Regards

________________________________

**Comment by dbuechel** [comment]
The error is caused by the WebView2 runtime dependency:

```
[153C:2B24][2024-08-30T12:20:04]i301: Applying execute package: MicrosoftEdgeWebview2Setup.exe, action: Install, path: C:\ProgramData\Package Cache\B600AA26D1CDED59760304C6D77F4FF75722EABD\MicrosoftEdgeWebview2Setup.exe, arguments: '"C:\ProgramData\Package Cache\B600AA26D1CDED59760304C6D77F4FF75722EABD\MicrosoftEdgeWebview2Setup.exe" /silent /install'
[153C:2B24][2024-08-30T12:20:24]e000: Error 0x80072efe: Process returned error: 0x80072efe
[153C:2B24][2024-08-30T12:20:24]e000: Error 0x80072efe: Failed to execute EXE package.
```

Please try to download and install it manually (see https://go.microsoft.com/fwlink/p/?LinkId=2124703), then retry installing SEB.
