### ISSUE TITLE
I can't find the linux version

### ISSUE THREAD

**Issue by wemiprog** [SafeExamBrowser/seb-win-refactoring#96]
Where can I find the linux version?
I have a problem when I have a exam and can't use my notebook only because I don't want to gift my data to microsoft or apple!

**Comment by danschlet** [comment]
There is no Linux version because no one until now offered to pay for an additional  developer who would be needed to develop, maintain and support a version for another operating system. 

Ask your examiner to provide you an evil OS notebook.
