### ISSUE TITLE
Add ARM compatibility 

### ISSUE THREAD

**Issue by 0roshi47** [SafeExamBrowser/seb-win-refactoring#964]
I tried to start the Safe Exam Browser on my ARM windows laptop, but it just won't boot
I don't know if it is possible to add this feature, but it would help many people in my situation I believe

**Comment by dbuechel** [comment]
According to our internal testing, SEB works just fine on ARM devices (see also #941). Could you please share the error message (with a screenshot) and log files?

**Comment by 0roshi47** [comment]
![image](https://github.com/user-attachments/assets/05fc3b05-b550-4189-816c-7905f40b55c6)
[2024-09-06_11h10m10s_Client.log](https://github.com/user-attachments/files/16905664/2024-09-06_11h10m10s_Client.log)
[2024-09-06_11h10m10s_Runtime.log](https://github.com/user-attachments/files/16905665/2024-09-06_11h10m10s_Runtime.log)

Here are the info i have

**Comment by dbuechel** [comment]
As the logs reveal, SEB is working perfectly fine on ARM, i.e. this issue is completely unrelated to the computing platform. Quite to the contrary, you'll simply need to ensure that you grant SEB the location permission in the system configuration (as is already explained in #928).
