### ISSUE TITLE
Install Fails

### ISSUE THREAD

**Issue by Reynbow** [SafeExamBrowser/seb-win-refactoring#967]
**Describe the Bug**
Fails to install

**Steps to Reproduce**
1. Run installer

**Expected Behavior**
Should install

**Screenshots**
![image](https://github.com/user-attachments/assets/8f02ee97-0fa9-452d-8d05-62cb7e60019a)

**Version Information**
 - OS: Win10
 - SEB-Version 3.7.1

**Additional Context**
have installed all the pre-reqs manually as per: https://github.com/SafeExamBrowser/seb-win-refactoring/releases/tag/v3.7.1

log attached also: 

[Safe_Exam_Browser_20240909175332.txt](https://github.com/user-attachments/files/16927280/Safe_Exam_Browser_20240909175332.txt)

**Comment by dbuechel** [comment]
Please restart your machine and retry installing the setup bundle. Should that still fail with the same error, try to download the respective MSI setup (linked here on GitHub under releases) and make sure that all runtime dependencies are installed correctly.
