### ISSUE TITLE
Safe Exam Browser Client terminating

### ISSUE THREAD

**Issue by hopferm** [SafeExamBrowser/seb-win-refactoring#970]
We've got new computers (Lenovo ThinkCentre M70q G3) which have LAN and WLAN.
Installation of SEB - no problem.

When starting SafeExamBrowser, it just crashes at the end of the initialisation.
We installed SEB_3.7.1.704_SetupBundle.exe and the newest VC++Redist 14.40.33810
User is Administrator on the computer

From the info, I found in the log-files I deactivated the WLAN and the WiFi-adpater,
but it made no difference.

Any idea?

Many thanx, Marcus

Here the corresponding part of the client-log file:

----------------------------------------------------------------------------------------------------------

2024-09-12 08:21:21.973 [01] - ERROR: Caught unexpected exception while performing operation 'LazyInitializationOperation'!

   Exception Message: Access denied
   Exception Type: System.ComponentModel.Win32Exception

   bei SimpleWifi.Win32.WlanClient..ctor()
   bei SimpleWifi.Wifi..ctor()
   bei SafeExamBrowser.SystemComponents.Network.NetworkAdapter.Initialize() in C:\Users\appveyor\projects\seb-win-refactoring-mltg1wfbmuoivnbc\SafeExamBrowser.SystemComponents\Network\NetworkAdapter.cs:Zeile 92.
   bei SafeExamBrowser.Client.Operations.ShellOperation.InitializeSystemComponents() in C:\Users\appveyor\projects\seb-win-refactoring-mltg1wfbmuoivnbc\SafeExamBrowser.Client\Operations\ShellOperation.cs:Zeile 230.
   bei SafeExamBrowser.Client.Operations.ShellOperation.Perform() in C:\Users\appveyor\projects\seb-win-refactoring-mltg1wfbmuoivnbc\SafeExamBrowser.Client\Operations\ShellOperation.cs:Zeile 85.
   bei SafeExamBrowser.Core.OperationModel.OperationSequence.Perform() in C:\Users\appveyor\projects\seb-win-refactoring-mltg1wfbmuoivnbc\SafeExamBrowser.Core\OperationModel\OperationSequence.cs:Zeile 108.

2024-09-12 08:21:21.975 [01] - INFO: Terminating shell...

-------------------------------------------------------------------------------------------------------------------

**Comment by dbuechel** [comment]
Please refer to #928.

**Comment by hopferm** [comment]
Thanx a lot - this worked for me.   Sorry - didn't find #928 ´cause was fixed on WiFi problem...
