### ISSUE TITLE
Message "The browser application has detected a closed URL. Do you want to terminate SEB now?" but only hard shutdown is possible

### ISSUE THREAD

**Issue by WDMIL27** [SafeExamBrowser/seb-win-refactoring#975]
One of my students gets this message when she finishes her exercises:

It says (in Dutch): "The browser application has detected a closed URL. Do you want to terminate SEB now?" But the Yes and No buttons don't work, nor is anything else on her screen. The only thing she can do, is to use a hard shutdown. 

(We are using SEB in combination with bookwidgets, a tool for online exercises in educational context.)

Any suggestions on what we can try? Thanks!

![image](https://github.com/user-attachments/assets/23dd46ae-d42c-4a3a-95de-0887221d96be)

**Comment by dbuechel** [comment]
Please provide the application logs of the affected session(s). They can be found under `%LocalAppData%\SafeExamBrowser\Logs`.

**Comment by wxnnvs** [comment]
@WDMIL27 do what @dbuechel says
If it doesnt work try just hitting enter
