### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by mamie77** [SafeExamBrowser/seb-win-refactoring#985]
> [!IMPORTANT]
> - Please _always_ consult the documentation first before creating a bug report: https://safeexambrowser.org/windows/win_usermanual_en.html.
> - Please _always_ attach the log file(s) of the affected session(s)! They can be found under `%LocalAppData%\SafeExamBrowser\Logs`.

**Describe the Bug**

**Steps to Reproduce**

**Expected Behavior**

**Screenshots**

**Version Information**
 - OS: [e.g. Windows 8 Professional, Version 1803]
 - SEB-Version [e.g. SEB 3.7.1]

**Additional Context**

**Comment by mamie77** [comment]
![Skärmbild (5)](https://github.com/user-attachments/assets/a4385ecf-46b7-4e85-868e-6a6fb9043f93)
![Skärmbild (6)](https://github.com/user-attachments/assets/6e8e6485-3519-4fcc-9854-99935f16a189)
![Skärmbild (9)](https://github.com/user-attachments/assets/e60d8143-2ea1-4a80-8e6a-8c1ff07ce3b5)
![Skärmbild (11)](https://github.com/user-attachments/assets/16cf454b-be32-46ce-bd5b-06eed2383310)
![Skärmbild (10)](https://github.com/user-attachments/assets/12fcffc8-8505-4ca7-9cf7-d1fe26abacb3)

**Comment by dbuechel** [comment]
Windows 8.x is not officially supported anymore.
