### ISSUE TITLE
Windows 24H2 update says SEB should be uninstalled before upgrading

### ISSUE THREAD

**Issue by NekoJonez** [SafeExamBrowser/seb-win-refactoring#988]
We are updating our devices to 24H2 and we get this:

![IMG-20241004-WA0000](https://github.com/user-attachments/assets/73c525e7-32b9-45a2-8c62-f9b291779f51)

Now, we installed Safe Exam Browser via Chocolatey and pushing it via Intune (Endpoint).

**Comment by dbuechel** [comment]
Could you please translate the entire message of the Windows update dialog?

**Comment by NekoJonez** [comment]
Behind the Windows 11 upgrade dialogue, you notice that it's updating PowerShell and updating to Windows 24H2. The usual Windows UI in the update settings.

Then the blue title says: "Let's check what needs to happen first". 
Underneath: "Process the following points if you want to continue with the installation and your Windows settings, and you want to keep personal files and apps."
"Why did I see this?"

"Safe Exam Browser (Wu Offer Block) - Manual removal"
"Remove this app now since it's no comptabile with Windows 11".

**Comment by MikuAuahDark** [comment]
From https://learn.microsoft.com/en-us/windows/release-health/status-windows-11-24h2#234msgdesc

> After installing Windows 11, version 24H2, you will experience issues while opening the [Safe Exam Browser](https://safeexambrowser.org/) app if you are running **version 3.7 or lower versions of this application**.

For anyone who got that window telling to uninstall SEB: Close the setup window, which then the IA will tell you something's wrong. Update SEB to 3.8.0+ before trying again. Once you updated SEB, retry updating again and it should allow you to continue upgrading.

**Comment by NekoJonez** [comment]
A potential bug this is creating @dbuechel, is that I have seen on some of my spare laptops that students use... That SEB v3.7.0 gets installed AND 3.8.0 ... And for some bizar reason, there is a chance v3.7.0 gets launched and shits the bed trying to close processes that aren't even running. 
We can solve it by removing both versions and installing it clean. But, this might be an unrelated issue since we push SEB via Microsoft Intune

**Comment by MikuAuahDark** [comment]
> This is absolutely new to me and I have not the slightest idea why SEB version 3.7.x or lower would be incompatible with Windows 11 24H2...

It looks like related to #935. App needs to request permission for certain APIs in 24H2.

**Comment by dbuechel** [comment]
> It looks like related to https://github.com/SafeExamBrowser/seb-win-refactoring/issues/935. App needs to request permission for certain APIs in 24H2.

Thanks for the hint @MikuAuahDark! I think that must be the issue then, but as already stated in the linked issue, the API permission request is already implemented in version 3.8.0. I also fail to understand why the new permission handling for the location API makes the entirety of Safe Exam Browser for Windows "incompatible" according to M$FT, but I reckon they have their reasons...

**Comment by dbuechel** [comment]
> That SEB v3.7.0 gets installed AND 3.8.0 ... And for some bizar reason, there is a chance v3.7.0 gets launched and shits the bed trying to close processes that aren't even running.

That's really almost not possible, as all SEB for Windows (at least the 3.x versions) declare the exact same product code for installation. SEB for Windows is furthermore installed at the exact same file system location for all 3.x versions, so it is physically impossible to have two (standard and official) SEB release versions installed in parallel.

**Comment by NekoJonez** [comment]
@dbuechel This issue is still present. Maybe we should reopen this ticket?

**Comment by dbuechel** [comment]
If you're referring to older versions (than SEB 3.8.0): We won't update them, you'll need to use the latest release version in order to comply with the new operating system requirements.

**Comment by LucasNiesen** [comment]
> > That SEB v3.7.0 gets installed AND 3.8.0 ... And for some bizar reason, there is a chance v3.7.0 gets launched and shits the bed trying to close processes that aren't even running.
> 
> That's really almost not possible, as all SEB for Windows (at least the 3.x versions) declare the exact same product code for installation. SEB for Windows is furthermore installed at the exact same file system location for all 3.x versions, so it is physically impossible to have two (standard and official) SEB release versions installed in parallel.

When i get the product code of  "SEB_3.8.0.742_x64_Setup.msi" I get this A51B2608-FCDD-435F-AF31-DA5549727C38 but when I do it for "SEB_3.7.0.682_x64_Setup.msi" I get this 40017F46-C514-4E1F-BCB5-FC42A31EDBFF

**Comment by dbuechel** [comment]
Well, at least on our end the upgrade codes have not changed, see https://github.com/SafeExamBrowser/seb-win-refactoring/blob/master/SetupBundle/Bundle.wxs#L6 and https://github.com/SafeExamBrowser/seb-win-refactoring/blob/master/Setup/Product.wxs#L4. So this might be an issue with the underlying Windows Installer or Windows itself, although I highly doubt that.
