### ISSUE TITLE
"seb is running..."  keeps constantly popping up in the foreground

### ISSUE THREAD

**Issue by MarcoPasta** [SafeExamBrowser/seb-win-refactoring#993]
> [!IMPORTANT]
> - Please _always_ consult the documentation first before creating a bug report: https://safeexambrowser.org/windows/win_usermanual_en.html.
> - Please _always_ attach the log file(s) of the affected session(s)! They can be found under `%LocalAppData%\SafeExamBrowser\Logs`.

**Describe the Bug**
When starting, the application is constantly popping up the window thats states "seb is running...". This behavior starts when the application is started ( i will provide videos to this).

**Steps to Reproduce**
1. Start the application
2. Accept message to close applications (it starts "blinking" here)

**Expected Behavior**
As seen on a Mac, the application was not blinking. 

**Screenshots**
https://drive.google.com/file/d/13cDwUrVPtQ3j9QFiHHWdFLlFhzii0hhE/view?usp=sharing
https://drive.google.com/file/d/1pie0XJ9ReR6QGzip4rRGSL6iYmyTR8-r/view?usp=sharing

**Logs**
[2024-10-12_14h06m34s_Browser.log](https://github.com/user-attachments/files/17350171/2024-10-12_14h06m34s_Browser.log)
[2024-10-12_14h06m34s_Client.log](https://github.com/user-attachments/files/17350172/2024-10-12_14h06m34s_Client.log)
[2024-10-12_14h06m34s_Runtime.log](https://github.com/user-attachments/files/17350173/2024-10-12_14h06m34s_Runtime.log)

**Version Information**
 - OS: Windows 11 Pro, 23H2, 22631.4317
 - SEB-Version: 3.8.1 for Windows

**Additional Context**
The problem did not happen on my side but its happening to my cousin and i am trying to help him. :)

**Comment by RoChess** [comment]
@MarcoPasta the runtime log shows everything going correct for your cousin, until kiosk mode is activated, and a random desktop is created. At that moment the blinking starts with OS switching back to default desktop, and SEB trying to reactivate the kiosk-screen.

Does your cousin have a GPU driver or OS setting/app active to mess with virtual desktops?

Try adjusting SEB config to not use kiosk mode and test again. That will at least narrow the issue down and make it easier for developers, although they probably already know what's happening 😁

**Comment by dbuechel** [comment]
There are various issues resp. discussions here on GitHub related to the problem; in most cases, it is a third-party application interfering with SEB (according to my recollection ESET AntiVirus as well as Cisco WebEx). Please make sure resp. locate the application interfering and terminate and/or uninstall it.
