### ISSUE TITLE
SEB se termine pendant l'examen

### ISSUE THREAD

**Issue by ChristopheKilchoer** [SafeExamBrowser/seb-win-refactoring#997]
[2024-10-14_15h35m04s_Browser.log](https://github.com/user-attachments/files/17377394/2024-10-14_15h35m04s_Browser.log)
[2024-10-14_15h35m04s_Client.log](https://github.com/user-attachments/files/17377396/2024-10-14_15h35m04s_Client.log)
[2024-10-14_15h35m04s_Runtime.log](https://github.com/user-attachments/files/17377397/2024-10-14_15h35m04s_Runtime.log)
> [!IMPORTANT]
> - Please _always_ consult the documentation first before creating a bug report: https://safeexambrowser.org/windows/win_usermanual_en.html.
> - Please _always_ attach the log file(s) of the affected session(s)! They can be found under `%LocalAppData%\SafeExamBrowser\Logs`.

**Describe the Bug**
Bonjour, message d'erreur qui apparait au milieu du test SEB : "

**Steps to Reproduce**
1. ouverture du fichier .seb
2. démarrage du test
3. à la fin du test revoir les questions en cliquant sur le numéro de la question
4. l'examen bug et il se termine!
5. un message est affiché "Une erreur irrémédiable s'est produite ! .."

**Expected Behavior**
Résolution de ce problème..

**Screenshots**
Voir le screeshot
<img width="596" alt="Screenshot" src="https://github.com/user-attachments/assets/ce619d89-43d0-4f77-9cd5-30c8478d5b49">

**Version Information**
 - OS: Windows 10 (10.0.19045)
 - SEB-Version 3.6.0.633

**Additional Context**

**Comment by RoChess** [comment]
@ChristopheKilchoer update first to 3.8.0 and test to see if the issue has already been fixed.

https://github.com/SafeExamBrowser/seb-win-refactoring/tags

**Comment by dbuechel** [comment]
And please provide the log files of the affected session(s) in case it still happens with the latest release version (currently 3.8.0).

**Comment by ChristopheKilchoer** [comment]
La version 3.8.0 a réglé mon problème!
Un grand merci!
Belle journée et cordiales salutations.

**Comment by ChristopheKilchoer** [comment]
La version 3.8.0 a réglé mon problème!
Un grand merci!
Belle journée et cordiales salutations.
