### ISSUE TITLE
SEB 3.8.0. does not start

### ISSUE THREAD

**Issue by heinzkrebs** [SafeExamBrowser/seb-win-refactoring#998]
dear all,

i have one student, which has a similar problem to issue #966, seb does not start but returns an error message (see below). the version 3.8.0 did not create a logfile, but the version 3.7.1 behaves similar and returns a logfile (see also below)

he told me his computer is running
Edition     Windows 10 Home
Version     22H2
Installiert am    ‎12.‎06.‎2023
Betriebssystembuild     19045.4894
Leistung    Windows Feature Experience Pack 1000.19060.1000.0
his system is update, he only misses the last cumulative update

any suggestions?????

error message:
> Fatal Error
> X
> Ungültige Klasse
> bei System.Management.ManagementException.ThrowWith Extended Info(ManagementStatus errorCode) bei System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext( bei System.Linq.Enumerable.<Castiterator>d_97'1.MoveNext()
> bei System.Linq.Enumerable.First[Source] (IEnumerable`1 source)
> bei SafeExamBrowser.System Components.Systeminfo.InitializeMacAddress() in C:\Users\appveyor\projects\seb-win-refactoring-t7rrnbsqeloke9rp\Safe ExamBrowser.System Components\Systeminfo.cs:Zeile 244. bei SafeExamBrowser.System Components.Systeminfo..ctor(Registry registry) in C:\Users\appveyor\projects\seb-win-refactoring-t7rrnbsqeloke9rp\Safe Exam Browser.System Components\Systeminfo.cs:Zeile 45. bei SafeExamBrowser.Runtime.CompositionRoot.BuildObjectGraph(Action shutdown)
> bei SafeExamBrowser.Runtime.App.OnStartup(StartupEventArgs e)
> bei System.Windows.Application.<.ctor>b__1_0(Object unused)
> bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
> bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) System.Windows.Threading.DispatcherOperation.Invokelmpl()
> bei
> bei MS.Internal.CulturePreserving ExecutionContext.CallbackWrapper(Object obj)
> bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
> bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
> bei MS.Internal.CulturePreserving ExecutionContext.Run(CulturePreserving ExecutionContext executionContext, ContextCallback callback, Object state) bei System.Windows.Threading.DispatcherOperation.Invoke(
> bei System.Windows.Threading.Dispatcher.ProcessQueue()
> bei System.Windows.Threading. Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr IParam, Boolean& handled)
> bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr IParam, Boolean& handled)
> bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
> bei System.Windows.Threading. ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
> bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) bei System.Windows.Threading.Dispatcher.Legacylnvokelmpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs) bei MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr IParam)
> bei MS.Win32.UnsafeNativeMethods. DispatchMessage(MSG& msg)
> bei System.Windows.Threading. Dispatcher.PushFramelmpl(DispatcherFrame frame)
> bei System.Windows.Application.RunDispatcher(Object ignore)
> bei System.Windows.Application.RunInternal(Window window)
> bei SafeExamBrowser.Runtime.App.StartApplication
> bei SafeExamBrowser.Runtime.App.Main()

logfile:

> ﻿# Application started at 2024-10-11 13:00:26.725
> 
> 2024-10-11 13:00:26.745 [01] - INFO: There is currently no other instance running.
> 2024-10-11 13:00:26.747 [01] - INFO: User 'DESKTOP-XXXXX\YYYY' is running the application with administrator privileges.
> 2024-10-11 13:00:26.747 [01] - INFO: SEB is currently not running.
> 2024-10-11 13:00:59.416 [01] - ERROR: [UserInfo] Failed to get SID via 'NtAccount' for user name 'AAAAA'!
> 
>    Exception Message: Manche oder alle Identitätsverweise konnten nicht übersetzt werden.
>    Exception Type: System.Security.Principal.IdentityNotMappedException
> 
>    bei System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, Boolean forceSuccess)
>    bei System.Security.Principal.NTAccount.Translate(Type targetType)
>    bei SafeExamBrowser.SystemComponents.UserInfo.NtAccount(String userName) in C:\Users\appveyor\projects\seb-win-refactoring-t7rrnbsqeloke9rp\SafeExamBrowser.SystemComponents\UserInfo.cs:Zeile 82.
>    bei SafeExamBrowser.SystemComponents.UserInfo.TryGetSidForUser(String userName, String& sid) in C:\Users\appveyor\projects\seb-win-refactoring-t7rrnbsqeloke9rp\SafeExamBrowser.SystemComponents\UserInfo.cs:Zeile 50.
> 
> 2024-10-11 13:00:59.516 [01] - WARNING: [UserInfo] Retrieved invalid SID '' via 'Wmi' for user name 'AAAAA'!
> 2024-10-11 13:00:59.517 [01] - ERROR: [UserInfo] All attempts to retrieve SID for user name 'AAAAA' failed!

**Comment by dbuechel** [comment]
This issue has been discussed before and the resolution should remain the same: This WMI class should exist on a normal system - if not, the WMI repository or even system configuration is likely corrupted and must be repaired.
